OMNEST NEDXML: NEDTypeInfo2::NEDElementMap Class Reference
NEDTypeInfo2::NEDElementMap Class Reference
#include <nedtypeinfo2.h>
Public Member Functions
bool contains (const std::string &key) const
NEDElement * get (const std::string &key) const
void put (const std::string &key, NEDElement *node)
int size () const
const std::string & key (int i) const
NEDElement * value (int i) const
void putAll (const NEDElementMap &map)
Member Function Documentation
bool NEDTypeInfo2::NEDElementMap::contains (const std::string & key) const [inline]
NEDElement* NEDTypeInfo2::NEDElementMap::get (const std::string & key) const [inline]
void NEDTypeInfo2::NEDElementMap::put (const std::string & key, NEDElement * node) [inline]
int NEDTypeInfo2::NEDElementMap::size () const [inline]
Referenced by putAll().
const std::string& NEDTypeInfo2::NEDElementMap::key (int i) const [inline]
Referenced by putAll().
NEDElement* NEDTypeInfo2::NEDElementMap::value (int i) const [inline]
Referenced by putAll().
void NEDTypeInfo2::NEDElementMap::putAll (const NEDElementMap & map) [inline]
References key(), size(), and value().
The documentation for this class was generated from the following file:
nedtypeinfo2.h