OMNeT++ Simulation Library: cEqdHistogramBase Class Reference
cEqdHistogramBase Class Reference
[Statistical data collection]
#include <chistogram.h>
Detailed Description
Base class for equal cell size histograms.
Public Member Functions
Constructors, destructor, assignment.
cEqdHistogramBase (const cEqdHistogramBase &r)
cEqdHistogramBase (const char *name=NULL, int numcells=-1)
cEqdHistogramBase & operator= (const cEqdHistogramBase &res)
Redefined cObject member functions.
virtual void parsimPack (cCommBuffer *buffer)
virtual void parsimUnpack (cCommBuffer *buffer)
Redefined member functions from cStatistic and its subclasses.
virtual double getBasepoint (int k) const
virtual double getCellValue (int k) const
virtual double getPDF (double x) const
virtual double getCDF (double x) const
virtual void saveToFile (FILE *) const
virtual void loadFromFile (FILE *)
Cell size.
virtual void setCellSize (double d)
virtual double getCellSize () const
Protected Member Functions
virtual void collectTransformed (double value)
virtual void setupRange ()
Constructor & Destructor Documentation
cEqdHistogramBase::cEqdHistogramBase (const cEqdHistogramBase & r) [inline]
Copy constructor.
References cNamedObject::getName(), cHistogramBase::operator=(), and cNamedObject::setName().
cEqdHistogramBase::cEqdHistogramBase (const char * name = NULL, int numcells = -1) [explicit]
Constructor.
Member Function Documentation
cEqdHistogramBase& cEqdHistogramBase::operator= (const cEqdHistogramBase & res)
Assignment operator.
The name member doesn't get copied; see cNamedObject's operator=() for more details.
Referenced by cDoubleHistogram::cDoubleHistogram(), and cLongHistogram::cLongHistogram().
virtual void cEqdHistogramBase::parsimPack (cCommBuffer * buffer) [virtual]
Serializes the object into an MPI send buffer.
Used by the simulation kernel for parallel execution. See cObject for more details.
Reimplemented from cHistogramBase.
virtual void cEqdHistogramBase::parsimUnpack (cCommBuffer * buffer) [virtual]
Deserializes the object from an MPI receive buffer Used by the simulation kernel for parallel execution.
See cObject for more details.
Reimplemented from cHistogramBase.
virtual void cEqdHistogramBase::collectTransformed (double value) [protected, virtual]
Called internally by collect(), this method collects a value after the histogram has been transformed.
Implements cDensityEstBase.
virtual void cEqdHistogramBase::setupRange () [protected, virtual]
Called internally by transform(), this method should determine and set up the histogram range.
It also calculates the cell size.
Reimplemented from cDensityEstBase.
Reimplemented in cLongHistogram, and cDoubleHistogram.
virtual double cEqdHistogramBase::getBasepoint (int k) const [virtual]
Returns the kth cell boundary.
Implements cDensityEstBase.
virtual double cEqdHistogramBase::getCellValue (int k) const [virtual]
Returns the number of observations that fell into the kth histogram cell.
Implements cDensityEstBase.
virtual double cEqdHistogramBase::getPDF (double x) const [virtual]
Returns the value of the Probability Density Function at a given x.
Implements cDensityEstBase.
virtual double cEqdHistogramBase::getCDF (double x) const [virtual]
Returns the value of the Cumulated Density Function at a given x.
Implements cDensityEstBase.
virtual void cEqdHistogramBase::saveToFile (FILE *) const [virtual]
Writes the contents of the object into a text file.
Reimplemented from cHistogramBase.
virtual void cEqdHistogramBase::loadFromFile (FILE *) [virtual]
Reads the object data from a file, in the format written out by saveToFile().
Reimplemented from cHistogramBase.
virtual void cEqdHistogramBase::setCellSize (double d) [virtual]
Sets the cell size.
Cannot be called when the cells have been set up already.
virtual double cEqdHistogramBase::getCellSize () const [inline, virtual]
Returns the cell size, or 0 when unknow (i.e.
the cells have not been set up yet, and setCellSize() has not been called).
The documentation for this class was generated from the following file:
chistogram.h