MiXiM: BaseArp Class Reference
BaseArp Class Reference
[netwLayer - network layer modules, baseModules - base module classes of MiXiM]
A class to convert integer layer addresses.
#include <BaseArp.h>
Inherits BaseModule.
Public Member Functions
virtual void initialize (int stage)
Basic initialization for all modules.
virtual void handleMessage (cMessage *)
should not be called, instead direct calls to the radio methods should be used.
int getMacAddr (const int netwAddr)
returns a L2 address to a given L3 address
int getNetwAddr (const int macAddr)
returns a L3 address to a given L2 address
int myMacAddr (cModule *mac)
Returns the L2 address for the passed mac.
int myNetwAddr (cModule *netw)
Returns the L3 address for the passed net.
Private Attributes
bool coreDebug
Detailed Description
A class to convert integer layer addresses.
This class takes the network layer id as the network layer address and the mac layer id as the mac layer address
ARP implementations are divers, it does not make sense to start from a common class. Their main purpose is to translate layer 2 into layer 3 addresses. However, these addresses can be very different. Here, simple integers are sufficient, but for hardware-in-the-loop simulations more complex ones are appropriate.
In contrast to this ARP, others may want to cache entries. This adds another set of basic operations that may or may not make sense for ARPs.
Author:
Daniel Willkomm
Definition at line 47 of file BaseArp.h.
Member Function Documentation
int BaseArp::getMacAddr (const int netwAddr)
returns a L2 address to a given L3 address
Definition at line 32 of file BaseArp.cc.
References coreEV, and BaseModule::debug.
Referenced by BaseNetwLayer::encapsMsg().
{
    if(debug) {
        Enter_Method("getMacAddr(%d)",netwAddr);
    } else {
        Enter_Method_Silent();
    }
    coreEV << "for host[" << simulation.getModule( netwAddr )->getParentModule()->getIndex()
       << "]: netwAddr " << netwAddr << "; MAC address "
       << simulation.getModule( netwAddr )->getParentModule()->getSubmodule( "nic" )->getId() <<endl;
    return simulation.getModule(netwAddr)->getParentModule()->getSubmodule("nic")->getId();
}
int BaseArp::getNetwAddr (const int macAddr)
returns a L3 address to a given L2 address
Definition at line 45 of file BaseArp.cc.
References coreDebug, and coreEV.
{
    if(coreDebug) {
        Enter_Method("getNetwAddr(%d)",macAddr);
    } else {
        Enter_Method_Silent();
    }
    coreEV << "for host[" << simulation.getModule( macAddr )->getParentModule()->getIndex()
       << "]: macAddr " << macAddr << "; netw address "
       << simulation.getModule( macAddr )->getParentModule()->getSubmodule("nic")->getId() <<endl;
    return simulation.getModule(macAddr)->getParentModule()->getSubmodule("netw")->getId();
}
virtual void BaseArp::handleMessage (cMessage *) [inline, virtual]
should not be called, instead direct calls to the radio methods should be used.
Definition at line 58 of file BaseArp.h.
{
        error("ARP module cannot receive messages!");
    };
void BaseArp::initialize (int stage) [virtual]
Basic initialization for all modules.
Subscription to Blackboard should be in stage==0, and firing notifications in stage==1 or later.
NOTE: You have to call this in the initialize() function of the inherited class!
Reimplemented from BaseModule.
Definition at line 24 of file BaseArp.cc.
References coreDebug.
{
    BaseModule::initialize(stage);
    if(stage==0) {
        hasPar("coreDebug") ? coreDebug = par("coreDebug").boolValue() : coreDebug = false;
  }
}
int BaseArp::myMacAddr (cModule * mac)
Returns the L2 address for the passed mac.
Definition at line 62 of file BaseArp.cc.
Referenced by Define_Module(), and Mac80211::initialize().
{
    return (mac->getParentModule())->getId();
}
int BaseArp::myNetwAddr (cModule * netw)
Returns the L3 address for the passed net.
Definition at line 58 of file BaseArp.cc.
Referenced by BaseNetwLayer::initialize().
{
    return netw->getId();
}
Member Data Documentation
bool BaseArp::coreDebug [private]
Definition at line 50 of file BaseArp.h.
Referenced by getNetwAddr(), and initialize().
The documentation for this class was generated from the following files:
base/modules/BaseArp.h
base/modules/BaseArp.cc