MiXiM: LinearMobility Class Reference
LinearMobility Class Reference
[mobility - modules handling the mobility of the hosts]
Linear movement model. See NED file for more info.
#include <LinearMobility.h>
Inherits BaseMobility.
Public Member Functions
virtual void initialize (int)
Initializes mobility model parameters.
Protected Member Functions
virtual void makeMove ()
Move the host.
virtual void fixIfHostGetsOutside ()
Should be redefined in subclasses.
Protected Attributes
double angle
angle of linear motion
double acceleration
acceleration of linear motion
Coord stepTarget
always stores the last step for position display update
Detailed Description
Linear movement model. See NED file for more info.
Author:
Emin Ilker Cetinbas
Definition at line 32 of file LinearMobility.h.
Member Function Documentation
void LinearMobility::fixIfHostGetsOutside () [protected, virtual]
Should be redefined in subclasses.
Should invoke handleIfOutside() and pass the references to the parameters to be modified.
Additional action after border handling (such as choosing a new target position if the BorderPolicy is PLACERANDOMLY) should be implemented here.
See also:
HandleIfOutside
Reimplemented from BaseMobility.
Definition at line 46 of file LinearMobility.cc.
References angle, BaseMobility::handleIfOutside(), stepTarget, and BaseMobility::WRAP.
Referenced by makeMove().
{
    Coord dummy;
    handleIfOutside(WRAP, stepTarget, dummy, dummy, angle);
}
void LinearMobility::initialize (int stage) [virtual]
Initializes mobility model parameters.
Reimplemented from BaseMobility.
Definition at line 27 of file LinearMobility.cc.
References acceleration, angle, BaseMobility::move, Move::speed, Move::startPos, and stepTarget.
{
    BaseMobility::initialize(stage);
    EV << "initializing LinearMobility stage " << stage << endl;
    if (stage == 0){
        move.speed = par("speed");
        acceleration = par("acceleration");
        angle = par("angle");
        angle = fmod(angle,360);
    }
    else if(stage == 1){
  stepTarget = move.startPos;
    }
}
void LinearMobility::makeMove () [protected, virtual]
Move the host.
Move the host if the destination is not reached yet. Otherwise calculate a new random position
Reimplemented from BaseMobility.
Definition at line 57 of file LinearMobility.cc.
References acceleration, angle, fixIfHostGetsOutside(), Coord::getX(), Coord::getY(), Coord::info(), Move::info(), BaseMobility::move, Move::setDirection(), Coord::setX(), Coord::setY(), Move::speed, Move::startPos, Move::startTime, stepTarget, and BaseMobility::updateInterval.
{
    EV << "start makeMove " << move.info() << endl;
    move.startPos = stepTarget;
    move.startTime = simTime();
    stepTarget.setX(move.startPos.getX() + move.speed * cos(PI * angle / 180) * updateInterval.dbl());
    stepTarget.setY(move.startPos.getY() + move.speed * sin(PI * angle / 180) * updateInterval.dbl());
    move.setDirection(stepTarget);
    EV << "new stepTarget: " << stepTarget.info() << endl;
    // accelerate
    move.speed += acceleration * updateInterval.dbl();
    fixIfHostGetsOutside();
}
Member Data Documentation
double LinearMobility::acceleration [protected]
acceleration of linear motion
Definition at line 36 of file LinearMobility.h.
Referenced by initialize(), and makeMove().
double LinearMobility::angle [protected]
angle of linear motion
Definition at line 35 of file LinearMobility.h.
Referenced by fixIfHostGetsOutside(), initialize(), and makeMove().
Coord LinearMobility::stepTarget [protected]
always stores the last step for position display update
Definition at line 39 of file LinearMobility.h.
Referenced by fixIfHostGetsOutside(), initialize(), and makeMove().
The documentation for this class was generated from the following files:
modules/mobility/LinearMobility.h
modules/mobility/LinearMobility.cc