MiXiM: DimensionSet Class Reference
DimensionSet Class Reference
[mapping - classes representing mathematical mappings]
Represents a set of dimensions which is used to define over which dimensions a mapping is defined (the domain of the mapping).
#include <MappingBase.h>
Public Member Functions
DimensionSet ()
Default constructor creates an empty DimensionSet.
DimensionSet (const Dimension &d)
Creates a new DimensionSet with the passed Dimension as initial Dimension.
DimensionSet (const Dimension &d1, const Dimension &d2)
Creates a new DimensionSet with the passed Dimensions as initial Dimensions (convenience method).
DimensionSet (const Dimension &d1, const Dimension &d2, const Dimension &d3)
Creates a new DimensionSet with the passed Dimensions as initial Dimensions (convenience method).
bool isSubSet (const DimensionSet &other) const
Returns true if the passed DimensionSet is a subset of this DimensionSet.
bool isRealSubSet (const DimensionSet &other) const
Returns true if the passed DimensionSet is a real subset of this DimensionSet.
void addDimension (const Dimension &d)
Adds the passed dimension to the DimensionSet.
bool hasDimension (const Dimension &d) const
Returns true if the passed Dimension is inside this DimensionSet.
bool operator== (const DimensionSet &o)
Returns true if the dimensions of both sets are equal.
Static Public Attributes
static const DimensionSet timeDomain
Shortcut to a DimensionSet which only contains time.
static const DimensionSet timeFreqDomain
Shortcut to a DimensionSet which contains time and frequency.
Detailed Description
Represents a set of dimensions which is used to define over which dimensions a mapping is defined (the domain of the mapping).
This class actually public extends from std::set<Dimension>. So any method provided by std::set can be also used.
The dimensions are stored ordered by their ids.
Note: Unlike Arguments and Mappings, a DimensionSet does not contain "time" as dimension per default. You'll have to add it like any other dimension.
Author:
Karl Wessel
Definition at line 159 of file MappingBase.h.
Constructor & Destructor Documentation
DimensionSet::DimensionSet () [inline]
Default constructor creates an empty DimensionSet.
Definition at line 170 of file MappingBase.h.
{}
DimensionSet::DimensionSet (const Dimension & d) [inline]
Creates a new DimensionSet with the passed Dimension as initial Dimension.
Definition at line 176 of file MappingBase.h.
{
    this->insert(d);
  }
DimensionSet::DimensionSet (const Dimension & d1, const Dimension & d2) [inline]
Creates a new DimensionSet with the passed Dimensions as initial Dimensions (convenience method).
Definition at line 183 of file MappingBase.h.
{
    this->insert(d1);
    this->insert(d2);
  }
DimensionSet::DimensionSet (const Dimension & d1, const Dimension & d2, const Dimension & d3) [inline]
Creates a new DimensionSet with the passed Dimensions as initial Dimensions (convenience method).
Definition at line 191 of file MappingBase.h.
{
    this->insert(d1);
    this->insert(d2);
    this->insert(d3);
  }
Member Function Documentation
void DimensionSet::addDimension (const Dimension & d) [inline]
Adds the passed dimension to the DimensionSet.
Definition at line 231 of file MappingBase.h.
Referenced by Argument::getDimensions(), and SimpleMacLayer::initialize().
{
    this->insert(d);
  }
bool DimensionSet::hasDimension (const Dimension & d) const [inline]
Returns true if the passed Dimension is inside this DimensionSet.
Definition at line 238 of file MappingBase.h.
Referenced by ConstMapping::ConstMapping(), MappingUtils::createMapping(), and SimplePathlossModel::filterSignal().
{
    return this->count(d) > 0;
  }
bool DimensionSet::isRealSubSet (const DimensionSet & other) const [inline]
Returns true if the passed DimensionSet is a real subset of this DimensionSet.
A DimensionSet is a real subset of this DimensionSet if every Dimension of the passed DimensionSet is defined in this DimensionSet and there is at least one Dimensions in this set which isn't in the other set.
Definition at line 221 of file MappingBase.h.
{
    if(this->size() <= other.size())
      return false;
    return std::includes(this->begin(), this->end(), other.begin(), other.end());
  }
bool DimensionSet::isSubSet (const DimensionSet & other) const [inline]
Returns true if the passed DimensionSet is a subset of this DimensionSet.
A DimensionSet is a subset of this DimensionSet if every Dimension of the passed DimensionSet is defined in this DimensionSet.
Definition at line 205 of file MappingBase.h.
Referenced by MappingUtils::findMax(), MappingUtils::findMin(), and SimpleConstMappingIterator::SimpleConstMappingIterator().
{
    if(this->size() < other.size())
      return false;
    return std::includes(this->begin(), this->end(), other.begin(), other.end());
  }
bool DimensionSet::operator== (const DimensionSet & o) [inline]
Returns true if the dimensions of both sets are equal.
Definition at line 245 of file MappingBase.h.
{
    if(size() != o.size())
      return false;
    return std::equal(begin(), end(), o.begin());
  }
Member Data Documentation
const DimensionSet DimensionSet::timeDomain [static]
Shortcut to a DimensionSet which only contains time.
Definition at line 162 of file MappingBase.h.
Referenced by BaseDecider::calculateRSSIMapping(), BaseMacLayer::createConstantMapping(), Mac80211::createSignal(), SimplePathlossModel::filterSignal(), and BasePhyLayer::initialize().
const DimensionSet DimensionSet::timeFreqDomain [static]
Shortcut to a DimensionSet which contains time and frequency.
Definition at line 165 of file MappingBase.h.
Referenced by Decider80211::calcChannelSenseRSSI(), Decider80211::checkIfSignalOk(), BaseMacLayer::createSingleFrequencyMapping(), SimplePathlossModel::filterSignal(), and Decider80211::processNewSignal().
The documentation for this class was generated from the following files:
base/phyLayer/MappingBase.h
base/phyLayer/MappingBase.cc