MiXiM: DeciderToPhyInterface Class Reference
DeciderToPhyInterface Class Reference
[decider - decider modules]
This class is the interface for a Decider to the BasePhyLayer.
#include <DeciderToPhyInterface.h>
Inherited by BasePhyLayer.
Public Types
typedef std::vector< AirFrame * > AirFrameVector
Public Member Functions
virtual ~DeciderToPhyInterface ()
virtual void getChannelInfo (simtime_t from, simtime_t to, AirFrameVector &out)=0
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
virtual ConstMapping * getThermalNoise (simtime_t from, simtime_t to)=0
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
virtual void sendControlMsg (cMessage *msg)=0
Called by the Decider to send a control message to the MACLayer.
virtual void sendUp (AirFrame *packet, DeciderResult *result)=0
Called to send an AirFrame with DeciderResult to the MACLayer.
virtual simtime_t getSimTime ()=0
Returns the current simulation time.
virtual void cancelScheduledMessage (cMessage *msg)=0
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
virtual void drawCurrent (double amount, int activity)=0
Enables the Decider to draw Power from the phy layers power accounts.
Detailed Description
This class is the interface for a Decider to the BasePhyLayer.
The Decider can do the following things using it:
get the current simulation time
get the list of AirFrames that intersect with a specific time interval (to calculate SNR)
tell the BasePhyLayer to hand an AirFrame up to the MACLayer
tell the BasePhyLayer to send a control message to the MACLayer (to answer a ChannelSenseRequest)
Definition at line 34 of file DeciderToPhyInterface.h.
Member Typedef Documentation
typedef std::vector<AirFrame*> DeciderToPhyInterface::AirFrameVector
Definition at line 37 of file DeciderToPhyInterface.h.
Constructor & Destructor Documentation
virtual DeciderToPhyInterface::~DeciderToPhyInterface () [inline, virtual]
Definition at line 39 of file DeciderToPhyInterface.h.
{}
Member Function Documentation
virtual void DeciderToPhyInterface::cancelScheduledMessage (cMessage * msg) [pure virtual]
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
Used by the Decider if it has to handle an AirFrame or an control message earlier than it has returned to the PhyLayer the last time the Decider handled that message.
Implemented in BasePhyLayer.
Referenced by BaseDecider::setChannelIdleStatus().
virtual void DeciderToPhyInterface::drawCurrent (double amount, int activity) [pure virtual]
Enables the Decider to draw Power from the phy layers power accounts.
Does nothing if no Battery module in simulation is present.
Implemented in BasePhyLayer.
Referenced by Decider80211Battery::setChannelIdleStatus().
virtual void DeciderToPhyInterface::getChannelInfo (simtime_t from, simtime_t to, AirFrameVector & out) [pure virtual]
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
Implemented in BasePhyLayer.
Referenced by BaseDecider::calculateRSSIMapping().
virtual simtime_t DeciderToPhyInterface::getSimTime () [pure virtual]
Returns the current simulation time.
Implemented in BasePhyLayer.
Referenced by Decider80211::calcChannelSenseRSSI(), BaseDecider::calcChannelSenseRSSI(), BaseDecider::canAnswerCSR(), BaseDecider::getChannelState(), and BaseDecider::handleNewSenseRequest().
virtual ConstMapping* DeciderToPhyInterface::getThermalNoise (simtime_t from, simtime_t to) [pure virtual]
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
The implementing class of this method keeps ownership of the Mapping.
Implemented in BasePhyLayer.
Referenced by BaseDecider::calculateRSSIMapping().
virtual void DeciderToPhyInterface::sendControlMsg (cMessage * msg) [pure virtual]
Called by the Decider to send a control message to the MACLayer.
This function can be used to answer a ChannelSenseRequest to the MACLayer
Implemented in BasePhyLayer.
Referenced by BaseDecider::answerCSR(), and Decider80211::processSignalEnd().
virtual void DeciderToPhyInterface::sendUp (AirFrame * packet, DeciderResult * result) [pure virtual]
Called to send an AirFrame with DeciderResult to the MACLayer.
When a packet is completely received and not noise, the Decider call this function to send the packet together with the corresponding DeciderResult up to MACLayer
Implemented in BasePhyLayer.
Referenced by ThresholdDecider::handleSignalOver(), SNRThresholdDecider::processSignalEnd(), Decider80211::processSignalEnd(), and BaseDecider::processSignalEnd().
The documentation for this class was generated from the following file:
base/phyLayer/DeciderToPhyInterface.h