MiXiM: Linear< Key, V, Pair, InputIterator > Class Template Reference
Linear< Key, V, Pair, InputIterator > Class Template Reference
[mappingDetails - mostly internal mapping classes]
Given two iterators defining a range of key-value-pairs this class provides linear interpolation of the value at an arbitrary key-position.
#include <Interpolation.h>
Public Types
typedef Interpolated< V > interpolated
Public Member Functions
Linear ()
Linear (V oorv)
void setOutOfRangeVal (V oorv)
interpolated operator() (const InputIterator &first, const InputIterator &last, const Key &pos) const
interpolated operator() (const InputIterator &first, const InputIterator &last, const Key &pos, InputIterator upperBound) const
Static Public Member Functions
static double linearInterpolation (const Key &t, const Key &t0, const Key &t1, const V &v0, const V &v1)
Protected Attributes
PairLess< Pair, Key > comp
bool continueOutOfRange
V outOfRangeVal
Detailed Description
template<class Key, class V, class Pair, class InputIterator>
class Linear< Key, V, Pair, InputIterator >
Given two iterators defining a range of key-value-pairs this class provides linear interpolation of the value at an arbitrary key-position.
Author:
Karl Wessel
Definition at line 223 of file Interpolation.h.
Member Typedef Documentation
template<class Key , class V , class Pair , class InputIterator > typedef Interpolated<V> Linear< Key, V, Pair, InputIterator >::interpolated
Definition at line 225 of file Interpolation.h.
Constructor & Destructor Documentation
template<class Key , class V , class Pair , class InputIterator > Linear< Key, V, Pair, InputIterator >::Linear () [inline]
Definition at line 232 of file Interpolation.h.
          :
    continueOutOfRange(true) {}
template<class Key , class V , class Pair , class InputIterator > Linear< Key, V, Pair, InputIterator >::Linear (V oorv) [inline]
Definition at line 235 of file Interpolation.h.
                :
    continueOutOfRange(false), outOfRangeVal(oorv) {}
Member Function Documentation
template<class Key , class V , class Pair , class InputIterator > static double Linear< Key, V, Pair, InputIterator >::linearInterpolation (const Key & t, const Key & t0, const Key & t1, const V & v0, const V & v1) [inline, static]
Definition at line 242 of file Interpolation.h.
Referenced by Linear< Key, V, Pair, InputIterator >::operator()().
{
    return v0 + (v1 - v0) * (double)((t - t0) / (t1 - t0));
  }
template<class Key , class V , class Pair , class InputIterator > interpolated Linear< Key, V, Pair, InputIterator >::operator() (const InputIterator & first, const InputIterator & last, const Key & pos, InputIterator upperBound) const [inline]
Definition at line 257 of file Interpolation.h.
References Linear< Key, V, Pair, InputIterator >::continueOutOfRange, Linear< Key, V, Pair, InputIterator >::linearInterpolation(), and Linear< Key, V, Pair, InputIterator >::outOfRangeVal.
{
    if(first == last){
      if(continueOutOfRange)
        return interpolated(V());
      else
        return interpolated(outOfRangeVal);
    }
    if(upperBound == first){
      if(continueOutOfRange)
        return interpolated(upperBound->second);
      else
        return interpolated(outOfRangeVal);
    }
    InputIterator right = upperBound;
    InputIterator left = --upperBound;
    if(left->first == pos)
      return interpolated(left->second, false);
    if(right == last){
      if(continueOutOfRange)
        return interpolated(left->second);
      else
        return interpolated(outOfRangeVal);
    }
    return interpolated(linearInterpolation(pos, left->first, right->first, left->second, right->second));
  }
template<class Key , class V , class Pair , class InputIterator > interpolated Linear< Key, V, Pair, InputIterator >::operator() (const InputIterator & first, const InputIterator & last, const Key & pos) const [inline]
Definition at line 248 of file Interpolation.h.
References Linear< Key, V, Pair, InputIterator >::comp.
Referenced by Linear< double, Mapping *, std::map< double, Mapping * >::value_type, std::map< double, Mapping * >::const_iterator >::operator()().
{
    InputIterator right = std::upper_bound(first, last, pos, comp);
    return operator()(first, last, pos, right);
  }
template<class Key , class V , class Pair , class InputIterator > void Linear< Key, V, Pair, InputIterator >::setOutOfRangeVal (V oorv) [inline]
Definition at line 238 of file Interpolation.h.
References Linear< Key, V, Pair, InputIterator >::outOfRangeVal.
{
    outOfRangeVal = oorv;
  }
Member Data Documentation
template<class Key , class V , class Pair , class InputIterator > PairLess<Pair, Key> Linear< Key, V, Pair, InputIterator >::comp [protected]
Definition at line 228 of file Interpolation.h.
Referenced by Linear< Key, V, Pair, InputIterator >::operator()().
template<class Key , class V , class Pair , class InputIterator > bool Linear< Key, V, Pair, InputIterator >::continueOutOfRange [protected]
Definition at line 229 of file Interpolation.h.
Referenced by Linear< Key, V, Pair, InputIterator >::operator()().
template<class Key , class V , class Pair , class InputIterator > V Linear< Key, V, Pair, InputIterator >::outOfRangeVal [protected]
Definition at line 230 of file Interpolation.h.
Referenced by Linear< Key, V, Pair, InputIterator >::operator()(), and Linear< Key, V, Pair, InputIterator >::setOutOfRangeVal().
The documentation for this class was generated from the following file:
base/phyLayer/Interpolation.h