MiXiM: ConstSpeedMobility Class Reference
ConstSpeedMobility Class Reference
[mobility - modules handling the mobility of the hosts]
Controls all movement related things of a host.
#include <ConstSpeedMobility.h>
Inherits BaseMobility.
Public Member Functions
virtual void initialize (int)
Initializes mobility model parameters.
Protected Member Functions
virtual void setTargetPosition ()
Calculate the target position to move to.
virtual void makeMove ()
Move the host.
Protected Attributes
Coord targetPos
Coord stepTarget
Coord stepSize
parameters to handle the movement of the host
int numSteps
Total number of steps.
int step
Number of steps already moved.
Detailed Description
Controls all movement related things of a host.
Parameters to be specified in omnetpp.ini
vHost : Speed of a host [m/s]
updateInterval : Time interval to update the hosts position
x, y : Starting position of the host, -1 = random
Author:
Steffen Sroka, Marc Loebbers, Daniel Willkomm
See also:
ConnectionManager
Definition at line 39 of file ConstSpeedMobility.h.
Member Function Documentation
void ConstSpeedMobility::initialize (int stage) [virtual]
Initializes mobility model parameters.
Reads the updateInterval and the velocity
If the host is not stationary it calculates a random position and schedules a timer to trigger the first movement
Reimplemented from BaseMobility.
Definition at line 35 of file ConstSpeedMobility.cc.
References Move::info(), BaseMobility::move, numSteps, Move::speed, Move::startPos, step, stepSize, and stepTarget.
{
    BaseMobility::initialize(stage);
    if (stage == 0) {
        move.speed = par("speed").doubleValue();
        if(move.speed <= 0)
      move.speed = 0;
  numSteps = 0;
  step = -1;
  stepSize = Coord(0,0,0);
        EV << "Initialize: move speed: " << move.speed << " (" << par("speed").doubleValue() << ")"
           << " pos: " << move.info() << endl;
    }
    else if( stage == 1 ){
  stepTarget = move.startPos;
    }
}
void ConstSpeedMobility::makeMove () [protected, virtual]
Move the host.
Move the host if the destination is not reached yet. Otherwise calculate a new random position
Reimplemented from BaseMobility.
Definition at line 97 of file ConstSpeedMobility.cc.
References Move::info(), Coord::info(), BaseMobility::move, numSteps, setTargetPosition(), Move::startPos, Move::startTime, step, stepSize, and stepTarget.
{
    // increment number of steps
    step++;
    if( step == numSteps ){
  // last step
  //stepSize.x =
  // step forward
  move.startPos = stepTarget;
  move.startTime = simTime();
  EV << "stepping forward. step #=" << step
     << " startPos: " << move.startPos.info() << endl;
  // get new target position
  EV << "destination reached.\n"
     << move.info() << endl;
  setTargetPosition();
    }
    else if( step < numSteps ){
  // step forward
  move.startPos = stepTarget;
  stepTarget += stepSize;
  move.startTime = simTime();
  EV << "stepping forward. step #=" << step
     << " startPos: " << move.startPos.info() << endl;
    }
    else{
  error("step cannot be bigger than numSteps");
    }
    //    fixIfHostGetsOutside();
}
void ConstSpeedMobility::setTargetPosition () [protected, virtual]
Calculate the target position to move to.
Calculate a new random position and the number of steps the host needs to reach this position
Definition at line 62 of file ConstSpeedMobility.cc.
References Coord::distance(), BaseMobility::getRandomPosition(), Coord::info(), Move::info(), BaseMobility::move, numSteps, FWMath::round(), Move::setDirection(), Move::speed, Move::startPos, step, stepSize, stepTarget, targetPos, and BaseMobility::updateInterval.
Referenced by makeMove().
{
    EV << "start setTargetPosistion: " << move.info() << endl;
    do{
  targetPos = getRandomPosition();
  double distance = move.startPos.distance(targetPos);
  simtime_t totalTime = distance / move.speed;
  numSteps = FWMath::round(totalTime / updateInterval);
  EV << "new targetPos: " << targetPos.info() << " distance=" << distance
     << " totalTime=" << totalTime << " numSteps=" << numSteps << endl;
    }
    while( numSteps == 0 );
    stepSize = targetPos - move.startPos;
    stepSize = stepSize / numSteps;
    stepTarget = move.startPos + stepSize;
    EV << "stepSize: " << stepSize.info() << " target: " << (stepSize*numSteps).info() << endl;
    step = 0;
    move.setDirection(targetPos);
    EV << "end setTargetPosistion: " << move.info() << endl;
}
Member Data Documentation
int ConstSpeedMobility::numSteps [protected]
Total number of steps.
Definition at line 47 of file ConstSpeedMobility.h.
Referenced by initialize(), makeMove(), and setTargetPosition().
int ConstSpeedMobility::step [protected]
Number of steps already moved.
Definition at line 49 of file ConstSpeedMobility.h.
Referenced by initialize(), makeMove(), and setTargetPosition().
Coord ConstSpeedMobility::stepSize [protected]
parameters to handle the movement of the host
Size of a step
Definition at line 45 of file ConstSpeedMobility.h.
Referenced by initialize(), makeMove(), and setTargetPosition().
Coord ConstSpeedMobility::stepTarget [protected]
Definition at line 53 of file ConstSpeedMobility.h.
Referenced by initialize(), makeMove(), and setTargetPosition().
Coord ConstSpeedMobility::targetPos [protected]
Definition at line 52 of file ConstSpeedMobility.h.
Referenced by setTargetPosition().
The documentation for this class was generated from the following files:
modules/mobility/ConstSpeedMobility.h
modules/mobility/ConstSpeedMobility.cc