MiXiM: BaseWorldUtility Class Reference
BaseWorldUtility Class Reference
[baseModules - base module classes of MiXiM]
Provides information and utility methods for the whole simulation.
#include <BaseWorldUtility.h>
Public Member Functions
void initialize (int stage)
virtual int numInitStages () const
const Coord * getPgs ()
Returns the playgroundSize.
bool useTorus ()
Returns true if our playground represents a torus (borders are connected).
Coord getRandomPosition ()
bool use2D ()
Returns true if the world is 2-dimensional.
long getUniqueAirFrameId ()
Returns an Id for an AirFrame, at the moment simply an incremented long-value.
Static Public Attributes
static const double speedOfLight = 299792458.0
Speed of light.
Protected Attributes
Coord playgroundSize
Size of the area the nodes are in (in meters).
bool useTorusFlag
Should the playground be treatend as a torus?
bool use2DFlag
Should the world be 2-dimensional?
long airFrameId
Provides a unique number for AirFrames per simulation.
Detailed Description
Provides information and utility methods for the whole simulation.
Definition at line 32 of file BaseWorldUtility.h.
Member Function Documentation
const Coord* BaseWorldUtility::getPgs () [inline]
Returns the playgroundSize.
Definition at line 56 of file BaseWorldUtility.h.
References playgroundSize.
Referenced by BaseMobility::initialize(), BaseConnectionManager::initialize(), PhyLayer::initializeSimplePathlossModel(), BaseMobility::playgroundSizeX(), BaseMobility::playgroundSizeY(), and BaseMobility::playgroundSizeZ().
{
        return &playgroundSize;
    };
Coord BaseWorldUtility::getRandomPosition ()
Definition at line 49 of file BaseWorldUtility.cc.
References Coord::getX(), Coord::getY(), Coord::getZ(), playgroundSize, and use2DFlag.
Referenced by BaseMobility::getRandomPosition(), BaseMobility::initialize(), and BaseMobility::placeRandomlyIfOutside().
{
    if (use2DFlag) {
        return Coord(uniform(0, playgroundSize.getX()),
                     uniform(0, playgroundSize.getY()));
    } else {
        return Coord(uniform(0, playgroundSize.getX()),
                     uniform(0, playgroundSize.getY()),
                     uniform(0, playgroundSize.getZ()));
    }
}
long BaseWorldUtility::getUniqueAirFrameId () [inline]
Returns an Id for an AirFrame, at the moment simply an incremented long-value.
Definition at line 75 of file BaseWorldUtility.h.
References airFrameId.
Referenced by BasePhyLayer::encapsMsg().
{
      // if counter has done one complete cycle and will be set to a value it already had
      if (airFrameId == -1){
        // print a warning
        ev << "WARNING: AirFrameId-Counter has done one complete cycle."
        << " AirFrameIds are repeating now and may not be unique anymore." << endl;
      }
      return airFrameId++;
    }
void BaseWorldUtility::initialize (int stage)
Definition at line 30 of file BaseWorldUtility.cc.
References airFrameId, playgroundSize, use2DFlag, and useTorusFlag.
{
  if (stage == 0) {
        use2DFlag = par("use2D");
        if (use2DFlag) {
            playgroundSize = Coord(par("playgroundSizeX"),
                                   par("playgroundSizeY"));
        } else {
            playgroundSize = Coord(par("playgroundSizeX"),
                                   par("playgroundSizeY"),
                                   par("playgroundSizeZ"));
        }
    useTorusFlag = par("useTorus");
    airFrameId = 0;
  }
}
virtual int BaseWorldUtility::numInitStages () const [inline, virtual]
Definition at line 51 of file BaseWorldUtility.h.
{
    return 2;
  }
bool BaseWorldUtility::use2D () [inline]
Returns true if the world is 2-dimensional.
Definition at line 72 of file BaseWorldUtility.h.
References use2DFlag.
Referenced by BaseMobility::checkIfOutside(), BaseMobility::goToBorder(), and BaseMobility::initialize().
{ return use2DFlag; }
bool BaseWorldUtility::useTorus () [inline]
Returns true if our playground represents a torus (borders are connected).
Definition at line 61 of file BaseWorldUtility.h.
References useTorusFlag.
Referenced by BaseConnectionManager::initialize(), and PhyLayer::initializeSimplePathlossModel().
                   {
      return useTorusFlag;
    };
Member Data Documentation
long BaseWorldUtility::airFrameId [protected]
Provides a unique number for AirFrames per simulation.
Definition at line 45 of file BaseWorldUtility.h.
Referenced by getUniqueAirFrameId(), and initialize().
Coord BaseWorldUtility::playgroundSize [protected]
Size of the area the nodes are in (in meters).
Definition at line 36 of file BaseWorldUtility.h.
Referenced by getPgs(), getRandomPosition(), and initialize().
const double BaseWorldUtility::speedOfLight = 299792458.0 [static]
Speed of light.
Definition at line 69 of file BaseWorldUtility.h.
Referenced by ConnectionManager::calcInterfDist(), SimplePathlossModel::calcPathloss(), ChannelAccess::calculatePropagationDelay(), SimplePathlossModel::filterSignal(), SimplePathlossConstMapping::getValue(), and JakesFadingMapping::getValue().
bool BaseWorldUtility::use2DFlag [protected]
Should the world be 2-dimensional?
Definition at line 42 of file BaseWorldUtility.h.
Referenced by getRandomPosition(), initialize(), and use2D().
bool BaseWorldUtility::useTorusFlag [protected]
Should the playground be treatend as a torus?
Definition at line 39 of file BaseWorldUtility.h.
Referenced by initialize(), and useTorus().
The documentation for this class was generated from the following files:
base/modules/BaseWorldUtility.h
base/modules/BaseWorldUtility.cc