MiXiM: BaseDecider Class Reference
BaseDecider Class Reference
[decider - decider modules, baseModules - base module classes of MiXiM]
Provides some base functionality for most common deciders.
#include <BaseDecider.h>
Inherits Decider.
Inherited by Decider80211, and SNRThresholdDecider.
Public Member Functions
BaseDecider (DeciderToPhyInterface *phy, double sensitivity, int myIndex, bool debug)
virtual ~BaseDecider ()
virtual simtime_t processSignal (AirFrame *frame)
Processes an AirFrame given by the PhyLayer.
virtual ChannelState getChannelState ()
A function that returns information about the channel state.
virtual simtime_t handleChannelSenseRequest (ChannelSenseRequest *request)
This function is called by the PhyLayer to hand over a ChannelSenseRequest.
Protected Types
enum SignalState { NEW, EXPECT_HEADER, EXPECT_END }
typedef std::pair< AirFrame
*, int > ReceivedSignal
Pair of a AirFrame and the state it is in.
typedef std::pair
< ChannelSenseRequest
*, simtime_t > CSRInfo
Pair of a ChannelSenseRequest and the simtime it started.
Protected Member Functions
virtual simtime_t processNewSignal (AirFrame *frame)
Processes a new Signal. Returns the time it wants to handle the signal again.
virtual simtime_t processSignalHeader (AirFrame *frame)
Processes the end of the header of a received Signal.
virtual simtime_t processSignalEnd (AirFrame *frame)
Processes the end of a received Signal.
virtual simtime_t processUnknownSignal (AirFrame *frame)
Processes any Signal for which no state could be found. (is an error case).
virtual int getSignalState (AirFrame *frame)
Returns the SignalState for the passed AirFrame.
virtual simtime_t handleNewSenseRequest (ChannelSenseRequest *request)
Handles a new incoming ChannelSenseRequest and returns the next (or latest) time to handle the request again.
virtual void handleSenseRequestTimeout (CSRInfo &requestInfo)
Handles the timeout of a ChannelSenseRequest by calculating the ChannelState and returning the request to the mac layer.
virtual void setChannelIdleStatus (bool isIdle)
Changes the "isIdle"-status to the passed value.
virtual bool canAnswerCSR (const CSRInfo &requestInfo)
Returns true if the ChannelSenseRequest of the passed CSRInfo can be answered (e.g. because channel state changed or timeout is reached).
virtual double calcChannelSenseRSSI (CSRInfo &requestInfo)
Calculates the RSSI value for the passed ChannelSenseRequest.
virtual void answerCSR (CSRInfo &requestInfo)
Answers the ChannelSenseRequest (CSR) from the passed CSRInfo.
virtual Mapping * calculateSnrMapping (AirFrame *frame)
Calculates a SNR-Mapping for a Signal.
virtual Mapping * calculateRSSIMapping (simtime_t start, simtime_t end, AirFrame *exclude=0)
Calculates a RSSI-Mapping (or Noise-Strength-Mapping) for a Signal.
Protected Attributes
double sensitivity
sensitivity value for receiving an AirFrame
ReceivedSignal currentSignal
pointer to the currently received AirFrame
bool isChannelIdle
Stores the idle state of the channel.
CSRInfo currentChannelSenseRequest
pointer to the currently running ChannelSenseRequest and its start-time
int myIndex
index for this Decider-instance given by Phy-Layer (mostly Host-index) default-value for myIndex is -1, i.e. no parameter passed to constructor-call
bool debug
toggles display of debugging messages
Detailed Description
Provides some base functionality for most common deciders.
Forwards the AirFrame from "processSignal" to "processNewSignal", "processSignalHeader" or "processSignalEnd" depending on the state for that AirFrame returned by "getSignalState".
Provides answering of ChannelSenseRequests (instantaneous and over time).
Subclasses should define when they consider the channel as idle by calling "setChannelIdleStatus" because BaseDecider uses that to answer ChannelSenseRequests.
If a subclassing Decider only tries to receive one signal at a time it can use BaseDeciders "currentSignal" member which is a pair of the signal to receive and the state for that signal. The state is then used by BaseDeciders "getSignalState" to decide to which "process***" method to forward the signal. If a subclassing Decider needs states for more than one Signal it has to store these states by itself and should probably override the "getSignalState" method.
Definition at line 40 of file BaseDecider.h.
Member Typedef Documentation
typedef std::pair<ChannelSenseRequest*, simtime_t> BaseDecider::CSRInfo [protected]
Pair of a ChannelSenseRequest and the simtime it started.
Definition at line 61 of file BaseDecider.h.
typedef std::pair<AirFrame*, int> BaseDecider::ReceivedSignal [protected]
Pair of a AirFrame and the state it is in.
Definition at line 52 of file BaseDecider.h.
Member Enumeration Documentation
enum BaseDecider::SignalState [protected]
Enumerator:
NEW
EXPECT_HEADER Signal is received the first time.
EXPECT_END Waiting for the header of the signal.
Definition at line 42 of file BaseDecider.h.
                  {
    NEW,
    EXPECT_HEADER,
    EXPECT_END,
  };
Constructor & Destructor Documentation
BaseDecider::BaseDecider (DeciderToPhyInterface * phy, double sensitivity, int myIndex, bool debug) [inline]
Definition at line 74 of file BaseDecider.h.
References currentChannelSenseRequest, currentSignal, and NEW.
                                                                                      :
    Decider(phy),
    sensitivity(sensitivity),
    isChannelIdle(true),
    myIndex(myIndex),
    debug(debug)
  {
    currentSignal.first = 0;
    currentSignal.second = NEW;
    currentChannelSenseRequest = std::pair<ChannelSenseRequest*, simtime_t>(0, -1);
  }
virtual BaseDecider::~BaseDecider () [inline, virtual]
Definition at line 86 of file BaseDecider.h.
{}
Member Function Documentation
void BaseDecider::answerCSR (CSRInfo & requestInfo) [protected, virtual]
Answers the ChannelSenseRequest (CSR) from the passed CSRInfo.
Calculates the rssi value and the channel idle state and sends the CSR together with the result back to the mac layer.
Definition at line 182 of file BaseDecider.cc.
References calcChannelSenseRSSI(), isChannelIdle, Decider::phy, and DeciderToPhyInterface::sendControlMsg().
Referenced by handleNewSenseRequest(), handleSenseRequestTimeout(), and setChannelIdleStatus().
{
  double rssiValue = calcChannelSenseRSSI(requestInfo);
  //"findMax()" returns "-DBL_MAX" on empty mappings
  if (rssiValue < 0)
    rssiValue = 0;
  // put the sensing-result to the request and
  // send it to the Mac-Layer as Control-message (via Interface)
  requestInfo.first->setResult( ChannelState(isChannelIdle, rssiValue) );
  phy->sendControlMsg(requestInfo.first);
  requestInfo.first = 0;
}
double BaseDecider::calcChannelSenseRSSI (CSRInfo & requestInfo) [protected, virtual]
Calculates the RSSI value for the passed ChannelSenseRequest.
This method is called by BaseDecider when it answers a ChannelSenseRequest and can be overridden by sub classing Deciders.
Default implementation gets start of the request from the passed CSRInfo and end of the request from the current simulation time (because the request is answered now) and returns the maximum RSSI value inside that maximum.
Reimplemented in Decider80211.
Definition at line 168 of file BaseDecider.cc.
References calculateRSSIMapping(), MappingUtils::findMax(), DeciderToPhyInterface::getSimTime(), and Decider::phy.
Referenced by answerCSR().
{
  simtime_t start = requestInfo.second;
  simtime_t end = phy->getSimTime();
  Mapping* rssiMap = calculateRSSIMapping(start, end);
  // the sensed RSSI-value is the maximum value between (and including) the interval-borders
  double rssi = MappingUtils::findMax(*rssiMap, Argument(start), Argument(end));
  delete rssiMap;
  return rssi;
}
Mapping * BaseDecider::calculateRSSIMapping (simtime_t start, simtime_t end, AirFrame * exclude = 0) [protected, virtual]
Calculates a RSSI-Mapping (or Noise-Strength-Mapping) for a Signal.
This method can be used to calculate a RSSI-Mapping in case the parameter exclude is omitted OR to calculate a Noise-Strength-Mapping in case the AirFrame of the received Signal is passed as parameter exclude.
Definition at line 220 of file BaseDecider.cc.
References MappingUtils::add(), MappingUtils::createMapping(), debugEV, DeciderToPhyInterface::getChannelInfo(), Signal::getReceivingPower(), Signal::getSignalLength(), Signal::getSignalStart(), DeciderToPhyInterface::getThermalNoise(), Decider::phy, and DimensionSet::timeDomain.
Referenced by Decider80211::calcChannelSenseRSSI(), calcChannelSenseRSSI(), calculateSnrMapping(), and getChannelState().
{
  if(exclude)
    debugEV << "Creating RSSI map excluding AirFrame with id " << exclude->getId() << endl;
  else
    debugEV << "Creating RSSI map." << endl;
  AirFrameVector airFrames;
  // collect all AirFrames that intersect with [start, end]
  phy->getChannelInfo(start, end, airFrames);
  //TODO: create a "MappingUtils:createMappingFrom()"-method and use it here instead
  //of abusing the add method
  // create an empty mapping
  Mapping* resultMap = MappingUtils::createMapping(0.0, DimensionSet::timeDomain);
  //add thermal noise
  ConstMapping* thermalNoise = phy->getThermalNoise(start, end);
  if(thermalNoise) {
    Mapping* tmp = resultMap;
    resultMap = MappingUtils::add(*resultMap, *thermalNoise);
    delete tmp;
  }
  // otherwise, iterate over all AirFrames (except exclude)
  // and sum up their receiving-power-mappings
  AirFrameVector::iterator it;
  for (it = airFrames.begin(); it != airFrames.end(); it++)
  {
    // the vector should not contain pointers to 0
    assert (*it != 0);
    // if iterator points to exclude (that includes the default-case 'exclude == 0')
    // then skip this AirFrame
    if ( *it == exclude ) continue;
    // otherwise get the Signal and its receiving-power-mapping
    Signal& signal = (*it)->getSignal();
    // backup pointer to result map
    // Mapping* resultMapOld = resultMap;
    // TODO1.1: for testing purposes, for now we don't specify an interval
    // and add the Signal's receiving-power-mapping to resultMap in [start, end],
    // the operation Mapping::add returns a pointer to a new Mapping
    ConstMapping* recvPowerMap = signal.getReceivingPower();
    assert(recvPowerMap);
    // Mapping* resultMapNew = Mapping::add( *(signal.getReceivingPower()), *resultMap, start, end );
    debugEV << "Adding mapping of Airframe with ID " << (*it)->getId()
        << ". Starts at " << signal.getSignalStart()
        << " and ends at " << signal.getSignalStart() + signal.getSignalLength() << endl;
    Mapping* resultMapNew = MappingUtils::add( *recvPowerMap, *resultMap, 0.0 );
    // discard old mapping
    delete resultMap;
    resultMap = resultMapNew;
    resultMapNew = 0;
  }
  return resultMap;
}
Mapping * BaseDecider::calculateSnrMapping (AirFrame * frame) [protected, virtual]
Calculates a SNR-Mapping for a Signal.
A Noise-Strength-Mapping is calculated (by using the "calculateRSSIMapping()"-method) for the time-interval of the Signal and the Signal-Strength-Mapping is divided by the Noise-Strength-Mapping.
Note: 'divided' means here the special element-wise operation on mappings.
Definition at line 198 of file BaseDecider.cc.
References calculateRSSIMapping(), MappingUtils::divide(), Signal::getReceivingPower(), Signal::getSignalLength(), and Signal::getSignalStart().
Referenced by SNRThresholdDecider::processSignalEnd(), and Decider80211::processSignalEnd().
{
  /* calculate Noise-Strength-Mapping */
  Signal& signal = frame->getSignal();
  simtime_t start = signal.getSignalStart();
  simtime_t end = start + signal.getSignalLength();
  Mapping* noiseMap = calculateRSSIMapping(start, end, frame);
  assert(noiseMap);
  ConstMapping* recvPowerMap = signal.getReceivingPower();
  assert(recvPowerMap);
  //TODO: handle noise of zero (must not devide with zero!)
  Mapping* snrMap = MappingUtils::divide( *recvPowerMap, *noiseMap, 0.0 );
  delete noiseMap;
  noiseMap = 0;
  return snrMap;
}
bool BaseDecider::canAnswerCSR (const CSRInfo & requestInfo) [protected, virtual]
Returns true if the ChannelSenseRequest of the passed CSRInfo can be answered (e.g. because channel state changed or timeout is reached).
Definition at line 146 of file BaseDecider.cc.
References DeciderToPhyInterface::getSimTime(), isChannelIdle, and Decider::phy.
Referenced by handleNewSenseRequest(), and setChannelIdleStatus().
{
  if(requestInfo.first == 0)
    return false;
  bool modeFulfilled = false;
  switch(requestInfo.first->getSenseMode())
  {
  case UNTIL_IDLE:
    modeFulfilled = isChannelIdle;
    break;
  case UNTIL_BUSY:
    modeFulfilled = !isChannelIdle;
    break;
  }
  return modeFulfilled                  //CSR mode is fulfilled
       || (phy->getSimTime() ==   requestInfo.second  //or timeout is reached
                    + requestInfo.first->getSenseTimeout());
}
ChannelState BaseDecider::getChannelState () [virtual]
A function that returns information about the channel state.
It is an alternative for the MACLayer in order to obtain information immediately (in contrast to sending a ChannelSenseRequest, i.e. sending a cMessage over the OMNeT-control-channel)
Reimplemented from Decider.
Definition at line 72 of file BaseDecider.cc.
References calculateRSSIMapping(), DeciderToPhyInterface::getSimTime(), ConstMapping::getValue(), isChannelIdle, and Decider::phy.
{
  simtime_t now = phy->getSimTime();
  Mapping* rssiMap = calculateRSSIMapping(now, now);
  double rssiValue = rssiMap->getValue(Argument(now));
  delete rssiMap;
  rssiMap = 0;
  return ChannelState(isChannelIdle, rssiValue);
}
int BaseDecider::getSignalState (AirFrame * frame) [protected, virtual]
Returns the SignalState for the passed AirFrame.
The default implementation checks if the passed AirFrame is the "currentSignal" and returns its state or if not "NEW".
Definition at line 129 of file BaseDecider.cc.
References currentSignal, and NEW.
Referenced by processSignal().
{
  if(frame == currentSignal.first)
    return currentSignal.second;
  return NEW;
}
simtime_t BaseDecider::handleChannelSenseRequest (ChannelSenseRequest * request) [virtual]
This function is called by the PhyLayer to hand over a ChannelSenseRequest.
The MACLayer is able to send a ChannelSenseRequest to the PhyLayer that calls this function with it and is returned a time point when to re-call this function with the specific ChannelSenseRequest.
The Decider puts the result (ChannelState) to the ChannelSenseRequest and "answers" by calling the "sendControlMsg"-function on the DeciderToPhyInterface, i.e. telling the PhyLayer to send it back.
Reimplemented from Decider.
Definition at line 86 of file BaseDecider.cc.
References currentChannelSenseRequest, handleNewSenseRequest(), handleSenseRequestTimeout(), and Decider::notAgain.
{
  assert(request);
  if (currentChannelSenseRequest.first == 0)
  {
    return handleNewSenseRequest(request);
  }
  if (currentChannelSenseRequest.first != request) {
    opp_error("Got a new ChannelSenseRequest while already handling another one!");
    return notAgain;
  }
  handleSenseRequestTimeout(currentChannelSenseRequest);
  // say that we don't want to have it again
  return notAgain;
}
simtime_t BaseDecider::handleNewSenseRequest (ChannelSenseRequest * request) [protected, virtual]
Handles a new incoming ChannelSenseRequest and returns the next (or latest) time to handle the request again.
Definition at line 106 of file BaseDecider.cc.
References answerCSR(), canAnswerCSR(), currentChannelSenseRequest, DeciderToPhyInterface::getSimTime(), Decider::notAgain, and Decider::phy.
Referenced by handleChannelSenseRequest().
{
  // no request handled at the moment, handling the new one
  simtime_t now = phy->getSimTime();
  // saving the pointer to the request and its start-time (now)
  currentChannelSenseRequest.first = request;
  currentChannelSenseRequest.second = now;
  //check if we can already answer the request
  if(canAnswerCSR(currentChannelSenseRequest))
  {
    answerCSR(currentChannelSenseRequest);
    return notAgain;
  }
  return ( now + request->getSenseTimeout() );
}
void BaseDecider::handleSenseRequestTimeout (CSRInfo & requestInfo) [protected, virtual]
Handles the timeout of a ChannelSenseRequest by calculating the ChannelState and returning the request to the mac layer.
Definition at line 125 of file BaseDecider.cc.
References answerCSR().
Referenced by handleChannelSenseRequest().
{
  answerCSR(requestInfo);
}
simtime_t BaseDecider::processNewSignal (AirFrame * frame) [protected, virtual]
Processes a new Signal. Returns the time it wants to handle the signal again.
Default implementation checks if the signals receiving power is above the sensitivity of the radio and we are not already trying to receive another AirFrame. If thats the case it waits for the end of the signal.
Reimplemented in Decider80211.
Definition at line 27 of file BaseDecider.cc.
References currentSignal, debugEV, EXPECT_END, Signal::getReceivingPower(), Signal::getSignalLength(), Signal::getSignalStart(), Decider::notAgain, sensitivity, and setChannelIdleStatus().
Referenced by processSignal().
{
  if(currentSignal.first != 0) {
    debugEV << "Already receiving another AirFrame!" << endl;
    return notAgain;
  }
  // get the receiving power of the Signal at start-time
  Signal& signal = frame->getSignal();
  double recvPower = signal.getReceivingPower()->getValue(Argument(signal.getSignalStart()));
  // check whether signal is strong enough to receive
  if ( recvPower < sensitivity )
  {
    debugEV << "Signal is to weak (" << recvPower << " < " << sensitivity
        << ") -> do not receive." << endl;
    // Signal too weak, we can't receive it, tell PhyLayer that we don't want it again
    return notAgain;
  }
  // Signal is strong enough, receive this Signal and schedule it
  debugEV << "Signal is strong enough (" << recvPower << " > " << sensitivity
      << ") -> Trying to receive AirFrame." << endl;
  currentSignal.first = frame;
  currentSignal.second = EXPECT_END;
  //channel turned busy
  setChannelIdleStatus(false);
  return ( signal.getSignalStart() + signal.getSignalLength() );
}
simtime_t BaseDecider::processSignal (AirFrame * frame) [virtual]
Processes an AirFrame given by the PhyLayer.
Returns the time point when the decider wants to be given the AirFrame again.
Reimplemented from Decider.
Definition at line 10 of file BaseDecider.cc.
References debugEV, EXPECT_END, EXPECT_HEADER, getSignalState(), NEW, processNewSignal(), processSignalEnd(), processSignalHeader(), and processUnknownSignal().
{
  assert(frame);
  debugEV << "Processing AirFrame..." << endl;
  switch(getSignalState(frame)) {
  case NEW:
    return processNewSignal(frame);
  case EXPECT_HEADER:
    return processSignalHeader(frame);
  case EXPECT_END:
    return processSignalEnd(frame);
  default:
    return processUnknownSignal(frame);
  }
}
simtime_t BaseDecider::processSignalEnd (AirFrame * frame) [protected, virtual]
Processes the end of a received Signal.
Returns the time it wants to handle the signal again (most probably notAgain).
Default implementation just decides every signal as correct and passes it to the upper layer.
Reimplemented in Decider80211, and SNRThresholdDecider.
Definition at line 59 of file BaseDecider.cc.
References currentSignal, Decider::notAgain, Decider::phy, DeciderToPhyInterface::sendUp(), and setChannelIdleStatus().
Referenced by processSignal().
{
  EV << "packet was received correctly, it is now handed to upper layer...\n";
  phy->sendUp(frame, new DeciderResult(true));
  // we have processed this AirFrame and we prepare to receive the next one
  currentSignal.first = 0;
  //channel is idle now
  setChannelIdleStatus(true);
  return notAgain;
}
virtual simtime_t BaseDecider::processSignalHeader (AirFrame * frame) [inline, protected, virtual]
Processes the end of the header of a received Signal.
Returns the time it wants to handle the signal again.
Default implementation does not handle signal headers.
Definition at line 138 of file BaseDecider.h.
References Decider::notAgain.
Referenced by processSignal().
{
    opp_error("BaseDecider does not handle Signal headers!");
    return notAgain;
  }
virtual simtime_t BaseDecider::processUnknownSignal (AirFrame * frame) [inline, protected, virtual]
Processes any Signal for which no state could be found. (is an error case).
Definition at line 158 of file BaseDecider.h.
References Decider::notAgain.
Referenced by processSignal().
{
    opp_error("Unknown state for the AirFrame with ID %d", frame->getId());
    return notAgain;
  }
void BaseDecider::setChannelIdleStatus (bool isIdle) [protected, virtual]
Changes the "isIdle"-status to the passed value.
This method further checks if there are any ChannelSenseRequests which can be answered because of the idle state changed.
Reimplemented in Decider80211Battery.
Definition at line 136 of file BaseDecider.cc.
References answerCSR(), canAnswerCSR(), DeciderToPhyInterface::cancelScheduledMessage(), currentChannelSenseRequest, isChannelIdle, and Decider::phy.
Referenced by Decider80211::processNewSignal(), processNewSignal(), SNRThresholdDecider::processSignalEnd(), Decider80211::processSignalEnd(), and processSignalEnd().
{
  isChannelIdle = isIdle;
  //check if there is an ChannelSenseRequest we can answer now
  if(canAnswerCSR(currentChannelSenseRequest)){
    phy->cancelScheduledMessage(currentChannelSenseRequest.first);
    answerCSR(currentChannelSenseRequest);
  }
}
Member Data Documentation
CSRInfo BaseDecider::currentChannelSenseRequest [protected]
pointer to the currently running ChannelSenseRequest and its start-time
Definition at line 64 of file BaseDecider.h.
Referenced by BaseDecider(), handleChannelSenseRequest(), handleNewSenseRequest(), and setChannelIdleStatus().
ReceivedSignal BaseDecider::currentSignal [protected]
pointer to the currently received AirFrame
Definition at line 55 of file BaseDecider.h.
Referenced by BaseDecider(), getSignalState(), Decider80211::processNewSignal(), processNewSignal(), SNRThresholdDecider::processSignalEnd(), Decider80211::processSignalEnd(), and processSignalEnd().
bool BaseDecider::debug [protected]
toggles display of debugging messages
Definition at line 71 of file BaseDecider.h.
Referenced by SNRThresholdDecider::checkIfAboveThreshold().
bool BaseDecider::isChannelIdle [protected]
Stores the idle state of the channel.
Definition at line 58 of file BaseDecider.h.
Referenced by answerCSR(), canAnswerCSR(), getChannelState(), and setChannelIdleStatus().
int BaseDecider::myIndex [protected]
index for this Decider-instance given by Phy-Layer (mostly Host-index) default-value for myIndex is -1, i.e. no parameter passed to constructor-call
Definition at line 68 of file BaseDecider.h.
double BaseDecider::sensitivity [protected]
sensitivity value for receiving an AirFrame
Definition at line 49 of file BaseDecider.h.
Referenced by Decider80211::processNewSignal(), and processNewSignal().
The documentation for this class was generated from the following files:
base/phyLayer/BaseDecider.h
base/phyLayer/BaseDecider.cc