MiXiM: BonnMotionMobility Class Reference
BonnMotionMobility Class Reference
[mobility - modules handling the mobility of the hosts]
Uses the BonnMotion native file format. See NED file for more info.
#include <BonnMotionMobility.h>
Inherits LineSegmentsMobilityBase.
Public Member Functions
~BonnMotionMobility ()
virtual void initialize (int)
Initializes mobility model parameters.
Protected Member Functions
virtual void setTargetPosition ()
Overridden from LineSegmentsMobilityBase.
virtual void fixIfHostGetsOutside ()
Overridden from LineSegmentsMobilityBase.
Protected Attributes
const BonnMotionFile::Line * vecp
unsigned vecpos
Detailed Description
Uses the BonnMotion native file format. See NED file for more info.
Author:
Andras Varga
Definition at line 32 of file BonnMotionMobility.h.
Constructor & Destructor Documentation
BonnMotionMobility::~BonnMotionMobility ()
Definition at line 67 of file BonnMotionMobility.cc.
References BonnMotionFileCache::deleteInstance().
{
    BonnMotionFileCache::deleteInstance();
}
Member Function Documentation
void BonnMotionMobility::fixIfHostGetsOutside () [protected, virtual]
Overridden from LineSegmentsMobilityBase.
Reimplemented from BaseMobility.
Definition at line 91 of file BonnMotionMobility.cc.
References BaseMobility::handleIfOutside(), BaseMobility::RAISEERROR, and LineSegmentsMobilityBase::stepTarget.
{
    Coord dummy;
    double dum;
    handleIfOutside( RAISEERROR, stepTarget, dummy, dummy, dum );
}
void BonnMotionMobility::initialize (int stage) [virtual]
Initializes mobility model parameters.
Reimplemented from BaseMobility.
Definition at line 27 of file BonnMotionMobility.cc.
References BonnMotionFileCache::getFile(), BonnMotionFileCache::getInstance(), BonnMotionFile::getLine(), Coord::info(), BaseMobility::move, Coord::setX(), Coord::setY(), Move::speed, Move::startPos, Move::startTime, LineSegmentsMobilityBase::targetPos, LineSegmentsMobilityBase::targetTime, vecp, and vecpos.
{
    LineSegmentsMobilityBase::initialize(stage);
    EV << "initializing BonnMotionMobility stage " << stage << endl;
    if(stage == 0)
    {
        int nodeId = par("nodeId");
        if (nodeId == -1)
            nodeId = getParentModule()->getIndex();
        const char *fname = par("traceFile");
        const BonnMotionFile *bmFile = BonnMotionFileCache::getInstance()->getFile(fname);
        vecp = bmFile->getLine(nodeId);
        if (!vecp)
            error("invalid nodeId %d -- no such line in file '%s'", nodeId, fname);
        vecpos = 0;
        // obtain initial position
        const BonnMotionFile::Line& vec = *vecp;
        if (vec.size()>=3){
            move.startPos.setX(vec[1]);
            move.startPos.setY(vec[2]);
      move.startTime = vec[0];
      //vecpos += 3;
            targetPos = move.startPos;
      targetTime = simTime();
      //stepTarget = move.startPos;
      //dummy value; speed not used in BonnMotion
      move.speed = 1;
      EV << "start pos: t=" << move.startTime << move.startPos.info() << endl;
        }
    }
}
void BonnMotionMobility::setTargetPosition () [protected, virtual]
Overridden from LineSegmentsMobilityBase.
Implements LineSegmentsMobilityBase.
Definition at line 72 of file BonnMotionMobility.cc.
References Coord::info(), BaseMobility::move, Coord::setX(), Coord::setY(), Move::speed, LineSegmentsMobilityBase::targetPos, LineSegmentsMobilityBase::targetTime, vecp, and vecpos.
{
    const BonnMotionFile::Line& vec = *vecp;
    if (vecpos+2 >= vec.size())
    {
  move.speed = 0;
  EV << "host is stationary now!!!\n";
        return;
    }
    targetTime = vec[vecpos];
    targetPos.setX(vec[vecpos+1]);
    targetPos.setY(vec[vecpos+2]);
    vecpos += 3;
    EV << "TARGET: t=" << targetTime << targetPos.info() << "\n";
}
Member Data Documentation
const BonnMotionFile::Line* BonnMotionMobility::vecp [protected]
Definition at line 36 of file BonnMotionMobility.h.
Referenced by initialize(), and setTargetPosition().
unsigned BonnMotionMobility::vecpos [protected]
Definition at line 37 of file BonnMotionMobility.h.
Referenced by initialize(), and setTargetPosition().
The documentation for this class was generated from the following files:
modules/mobility/BonnMotionMobility.h
modules/mobility/BonnMotionMobility.cc