MiXiM: BaseDelayedIterator< Base, Iterator > Class Template Reference
BaseDelayedIterator< Base, Iterator > Class Template Reference
[mappingDetails - mostly internal mapping classes]
Common base for a Const- and NonConst-Iterator for a DelayedMapping.
#include <MappingUtils.h>
Public Member Functions
BaseDelayedIterator (Iterator *it, simtime_t delay)
virtual ~BaseDelayedIterator ()
virtual const Argument & getNextPosition () const
virtual void jumpTo (const Argument &pos)
virtual void jumpToBegin ()
virtual void iterateTo (const Argument &pos)
virtual void next ()
virtual const Argument & getPosition () const
Protected Member Functions
Argument undelayPosition (const Argument &pos) const
Argument delayPosition (const Argument &pos) const
void updatePosition ()
Protected Attributes
simtime_t delay
Argument position
Argument nextPosition
Detailed Description
template<class Base, class Iterator>
class BaseDelayedIterator< Base, Iterator >
Common base for a Const- and NonConst-Iterator for a DelayedMapping.
See also:
BaseDelayedMapping
Author:
Karl Wessel
Definition at line 2054 of file MappingUtils.h.
Constructor & Destructor Documentation
template<class Base , class Iterator > BaseDelayedIterator< Base, Iterator >::BaseDelayedIterator (Iterator * it, simtime_t delay) [inline]
Definition at line 2079 of file MappingUtils.h.
References BaseDelayedIterator< Base, Iterator >::updatePosition().
                                                    :
    Base(it), delay(delay) {
    updatePosition();
  }
template<class Base , class Iterator > virtual BaseDelayedIterator< Base, Iterator >::~BaseDelayedIterator () [inline, virtual]
Definition at line 2085 of file MappingUtils.h.
{}
Member Function Documentation
template<class Base , class Iterator > Argument BaseDelayedIterator< Base, Iterator >::delayPosition (const Argument & pos) const [inline, protected]
Definition at line 2067 of file MappingUtils.h.
References BaseDelayedIterator< Base, Iterator >::delay, Argument::getTime(), and Argument::setTime().
Referenced by BaseDelayedIterator< Base, Iterator >::updatePosition().
{
    Argument res(pos);
      res.setTime(res.getTime() + delay);
      return res;
  }
template<class Base , class Iterator > virtual const Argument& BaseDelayedIterator< Base, Iterator >::getNextPosition () const [inline, virtual]
Definition at line 2087 of file MappingUtils.h.
References BaseDelayedIterator< Base, Iterator >::nextPosition.
{ return nextPosition; }
template<class Base , class Iterator > virtual const Argument& BaseDelayedIterator< Base, Iterator >::getPosition () const [inline, virtual]
Definition at line 2109 of file MappingUtils.h.
References BaseDelayedIterator< Base, Iterator >::position.
{
    return position;
  }
template<class Base , class Iterator > virtual void BaseDelayedIterator< Base, Iterator >::iterateTo (const Argument & pos) [inline, virtual]
Definition at line 2099 of file MappingUtils.h.
References BaseDelayedIterator< Base, Iterator >::undelayPosition(), and BaseDelayedIterator< Base, Iterator >::updatePosition().
{
    this->origIterator->iterateTo(undelayPosition(pos));
    updatePosition();
  }
template<class Base , class Iterator > virtual void BaseDelayedIterator< Base, Iterator >::jumpTo (const Argument & pos) [inline, virtual]
Definition at line 2089 of file MappingUtils.h.
References BaseDelayedIterator< Base, Iterator >::undelayPosition(), and BaseDelayedIterator< Base, Iterator >::updatePosition().
{
    this->origIterator->jumpTo(undelayPosition(pos));
    updatePosition();
  }
template<class Base , class Iterator > virtual void BaseDelayedIterator< Base, Iterator >::jumpToBegin () [inline, virtual]
Definition at line 2094 of file MappingUtils.h.
References BaseDelayedIterator< Base, Iterator >::updatePosition().
{
    this->origIterator->jumpToBegin();
    updatePosition();
  }
template<class Base , class Iterator > virtual void BaseDelayedIterator< Base, Iterator >::next () [inline, virtual]
Definition at line 2104 of file MappingUtils.h.
References BaseDelayedIterator< Base, Iterator >::updatePosition().
                      {
    this->origIterator->next();
    updatePosition();
  }
template<class Base , class Iterator > Argument BaseDelayedIterator< Base, Iterator >::undelayPosition (const Argument & pos) const [inline, protected]
Definition at line 2061 of file MappingUtils.h.
References BaseDelayedIterator< Base, Iterator >::delay, Argument::getTime(), and Argument::setTime().
Referenced by BaseDelayedIterator< Base, Iterator >::iterateTo(), and BaseDelayedIterator< Base, Iterator >::jumpTo().
{
    Argument res(pos);
    res.setTime(res.getTime() - delay);
    return res;
  }
template<class Base , class Iterator > void BaseDelayedIterator< Base, Iterator >::updatePosition () [inline, protected]
Definition at line 2073 of file MappingUtils.h.
References BaseDelayedIterator< Base, Iterator >::delayPosition(), BaseDelayedIterator< Base, Iterator >::nextPosition, and BaseDelayedIterator< Base, Iterator >::position.
Referenced by BaseDelayedIterator< Base, Iterator >::BaseDelayedIterator(), BaseDelayedIterator< Base, Iterator >::iterateTo(), BaseDelayedIterator< Base, Iterator >::jumpTo(), BaseDelayedIterator< Base, Iterator >::jumpToBegin(), and BaseDelayedIterator< Base, Iterator >::next().
{
    nextPosition = delayPosition(this->origIterator->getNextPosition());
    position = delayPosition(this->origIterator->getPosition());
  }
Member Data Documentation
template<class Base , class Iterator > simtime_t BaseDelayedIterator< Base, Iterator >::delay [protected]
Definition at line 2056 of file MappingUtils.h.
Referenced by BaseDelayedIterator< Base, Iterator >::delayPosition(), and BaseDelayedIterator< Base, Iterator >::undelayPosition().
template<class Base , class Iterator > Argument BaseDelayedIterator< Base, Iterator >::nextPosition [protected]
Definition at line 2059 of file MappingUtils.h.
Referenced by BaseDelayedIterator< Base, Iterator >::getNextPosition(), and BaseDelayedIterator< Base, Iterator >::updatePosition().
template<class Base , class Iterator > Argument BaseDelayedIterator< Base, Iterator >::position [protected]
Definition at line 2058 of file MappingUtils.h.
Referenced by BaseDelayedIterator< Base, Iterator >::getPosition(), and BaseDelayedIterator< Base, Iterator >::updatePosition().
The documentation for this class was generated from the following file:
base/phyLayer/MappingUtils.h