MiXiM: ANSimMobility Class Reference
ANSimMobility Class Reference
[mobility - modules handling the mobility of the hosts]
Uses the <position_change> elements of the ANSim tool's trace file. See NED file for more info.
#include <ANSimMobility.h>
Inherits LineSegmentsMobilityBase.
Public Member Functions
virtual void initialize (int)
Initializes mobility model parameters.
Protected Member Functions
virtual void setTargetPosition ()
Overridden from LineSegmentsMobilityBase.
void extractDataFrom (cXMLElement *node)
Utility: extract data from given <position_update> element.
virtual void fixIfHostGetsOutside ()
Overridden from LineSegmentsMobilityBase.
Protected Attributes
int nodeId
we'll have to compare this to the <node_id> elements
cXMLElement * nextPosChange
points to the next <position_change> element
Detailed Description
Uses the <position_change> elements of the ANSim tool's trace file. See NED file for more info.
Author:
Andras Varga
Definition at line 32 of file ANSimMobility.h.
Member Function Documentation
void ANSimMobility::extractDataFrom (cXMLElement * node) [protected]
Utility: extract data from given <position_update> element.
Definition at line 96 of file ANSimMobility.cc.
References firstChildWithTag(), Coord::setX(), Coord::setY(), LineSegmentsMobilityBase::targetPos, and LineSegmentsMobilityBase::targetTime.
Referenced by setTargetPosition().
{
    // extract data from <position_update> element
    //const char *startTimeStr = firstChildWithTag(node, "start_time")->getNodeValue();
    const char *endTimeStr = firstChildWithTag(node, "end_time")->getNodeValue();
    cXMLElement *destElem = firstChildWithTag(node, "destination");
    const char *xStr = firstChildWithTag(destElem, "xpos")->getNodeValue();
    const char *yStr = firstChildWithTag(destElem, "ypos")->getNodeValue();
    if (!endTimeStr || !xStr || !yStr)
        error("no content in <end_time>, <destination>/<xpos> or <ypos> element at %s", node->getSourceLocation());
    targetTime = atof(endTimeStr);
    targetPos.setX(atof(xStr));
    targetPos.setY(atof(yStr));
}
void ANSimMobility::fixIfHostGetsOutside () [protected, virtual]
Overridden from LineSegmentsMobilityBase.
Reimplemented from BaseMobility.
Definition at line 113 of file ANSimMobility.cc.
References BaseMobility::handleIfOutside(), BaseMobility::RAISEERROR, and LineSegmentsMobilityBase::stepTarget.
{
    Coord dummy;
    double dum;
    handleIfOutside( RAISEERROR, stepTarget, dummy, dummy, dum );
}
void ANSimMobility::initialize (int stage) [virtual]
Initializes mobility model parameters.
Reimplemented from BaseMobility.
Definition at line 37 of file ANSimMobility.cc.
References BaseMobility::move, nextPosChange, nodeId, setTargetPosition(), Move::speed, Move::startPos, LineSegmentsMobilityBase::stepTarget, LineSegmentsMobilityBase::targetPos, and LineSegmentsMobilityBase::targetTime.
{
    LineSegmentsMobilityBase::initialize(stage);
    EV << "initializing ANSimMobility stage " << stage << endl;
    if (stage == 0)
    {
        nodeId = par("nodeId");
        if (nodeId == -1)
            nodeId = getParentModule()->getIndex();
        // get script: param should point to <simulation> element
        cXMLElement *rootElem = par("ansimTrace");
        if (strcmp(rootElem->getTagName(),"simulation")!=0)
            error("ansimTrace: <simulation> is expected as root element not <%s> at %s",
                  rootElem->getTagName(), rootElem->getSourceLocation());
        nextPosChange = rootElem->getElementByPath("mobility/position_change");
        if (!nextPosChange)
            error("element doesn't have <mobility> child or <position_change> grandchild at %s",
                  rootElem->getSourceLocation());
        // set initial position;
        setTargetPosition();
        move.startPos = targetPos;
  stepTarget = move.startPos;
  targetTime = simTime();
  // dummy value; speed not used in ansim
  move.speed = 1;
    }
}
void ANSimMobility::setTargetPosition () [protected, virtual]
Overridden from LineSegmentsMobilityBase.
Implements LineSegmentsMobilityBase.
Definition at line 72 of file ANSimMobility.cc.
References extractDataFrom(), firstChildWithTag(), BaseMobility::move, nextPosChange, nodeId, and Move::speed.
Referenced by initialize().
{
    // find next <position_update> element with matching <node_id> tag (current one also OK)
    while (nextPosChange)
    {
        const char *nodeIdStr = firstChildWithTag(nextPosChange, "node_id")->getNodeValue();
        if (nodeIdStr && atoi(nodeIdStr)==nodeId)
            break;
        nextPosChange = nextPosChange->getNextSibling();
    }
    if (!nextPosChange)
    {
        move.speed = 0;
        return;
    }
    // extract data from it
    extractDataFrom(nextPosChange);
    // skip this one
    nextPosChange = nextPosChange->getNextSibling();
}
Member Data Documentation
cXMLElement* ANSimMobility::nextPosChange [protected]
points to the next <position_change> element
Definition at line 39 of file ANSimMobility.h.
Referenced by initialize(), and setTargetPosition().
int ANSimMobility::nodeId [protected]
we'll have to compare this to the <node_id> elements
Definition at line 36 of file ANSimMobility.h.
Referenced by initialize(), and setTargetPosition().
The documentation for this class was generated from the following files:
modules/mobility/ANSimMobility.h
modules/mobility/ANSimMobility.cc