MiXiM: LogNormalShadowing Class Reference
LogNormalShadowing Class Reference
[analogueModels - AnalogueModel implementations]
Channel state implementing log-normal shadowing.
#include <LogNormalShadowing.h>
Inherits AnalogueModel.
Public Member Functions
LogNormalShadowing (double mean, double stdDev, simtime_t interval)
virtual ~LogNormalShadowing ()
virtual void filterSignal (Signal &s)
Calculates shadowing loss based on a normal gaussian function.
Protected Member Functions
double randomLogNormalGain () const
Returns a random log normal distributed gain factor.
Protected Attributes
double mean
Mean of the random attenuation in dB.
double stdDev
Standart deviation of the random attenuation in dB.
simtime_t interval
The interval to set attenuation entries in.
Static Protected Attributes
static DimensionSet dimensions
The dimensions of this analogue model.
Detailed Description
Channel state implementing log-normal shadowing.
Author:
Hermann S. Lichte, Karl Wessel (port for MiXiM)
Date:
2007-08-15
Definition at line 28 of file LogNormalShadowing.h.
Constructor & Destructor Documentation
LogNormalShadowing::LogNormalShadowing (double mean, double stdDev, simtime_t interval)
Definition at line 20 of file LogNormalShadowing.cc.
                                                                                    :
  mean(mean), stdDev(stdDev), interval(interval)
{ }
LogNormalShadowing::~LogNormalShadowing () [virtual]
Definition at line 24 of file LogNormalShadowing.cc.
{}
Member Function Documentation
void LogNormalShadowing::filterSignal (Signal & s) [virtual]
Calculates shadowing loss based on a normal gaussian function.
Implements AnalogueModel.
Definition at line 30 of file LogNormalShadowing.cc.
References Signal::addAttenuation(), Mapping::appendValue(), MappingUtils::createMapping(), dimensions, Signal::getSignalLength(), Signal::getSignalStart(), interval, Mapping::LINEAR, randomLogNormalGain(), and Argument::setTime().
{
  simtime_t start = s.getSignalStart();
  simtime_t end = start + s.getSignalLength();
  Mapping* att = MappingUtils::createMapping(dimensions, Mapping::LINEAR);
  Argument pos;
  for(simtime_t t = start; t <= end; t += interval)
  {
    pos.setTime(t);
    att->appendValue(pos, randomLogNormalGain());
  }
  s.addAttenuation(att);
}
double LogNormalShadowing::randomLogNormalGain () const [protected]
Returns a random log normal distributed gain factor.
The gain factor is below 1.0 so its an actual attenuation.
Definition at line 26 of file LogNormalShadowing.cc.
References FWMath::dBm2mW(), mean, and stdDev.
Referenced by filterSignal().
{
  return FWMath::dBm2mW(-1.0 * normal(mean, stdDev));
}
Member Data Documentation
DimensionSet LogNormalShadowing::dimensions [static, protected]
The dimensions of this analogue model.
Definition at line 31 of file LogNormalShadowing.h.
Referenced by filterSignal().
simtime_t LogNormalShadowing::interval [protected]
The interval to set attenuation entries in.
Definition at line 40 of file LogNormalShadowing.h.
Referenced by filterSignal().
double LogNormalShadowing::mean [protected]
Mean of the random attenuation in dB.
Definition at line 34 of file LogNormalShadowing.h.
Referenced by randomLogNormalGain().
double LogNormalShadowing::stdDev [protected]
Standart deviation of the random attenuation in dB.
Definition at line 37 of file LogNormalShadowing.h.
Referenced by randomLogNormalGain().
The documentation for this class was generated from the following files:
modules/analogueModel/LogNormalShadowing.h
modules/analogueModel/LogNormalShadowing.cc