MiXiM: ConstantSimpleConstMapping Class Reference
ConstantSimpleConstMapping Class Reference
[mapping - classes representing mathematical mappings]
Represents a constant mathematical mapping (f(x) = c).
#include <MappingUtils.h>
Inherits SimpleConstMapping.
Public Member Functions
ConstantSimpleConstMapping (const DimensionSet &dims, double val)
ConstantSimpleConstMapping (const DimensionSet &dims, const Argument &key, double val)
virtual double getValue (const Argument &pos) const
Returns the value of the mapping at the passed position.
double getValue () const
Returns the value of this constant mapping.
void setValue (double val)
Sets the value of this constant mapping.
ConstMapping * constClone () const
creates a clone of this mapping.
Protected Attributes
double value
Detailed Description
Represents a constant mathematical mapping (f(x) = c).
Returns the same value for every point in any dimension.
Author:
Karl Wessel
Definition at line 783 of file MappingUtils.h.
Constructor & Destructor Documentation
ConstantSimpleConstMapping::ConstantSimpleConstMapping (const DimensionSet & dims, double val) [inline]
Definition at line 788 of file MappingUtils.h.
Referenced by constClone().
                                                                  :
    SimpleConstMapping(dims), value(val) {}
ConstantSimpleConstMapping::ConstantSimpleConstMapping (const DimensionSet & dims, const Argument & key, double val) [inline]
Definition at line 791 of file MappingUtils.h.
                            :
    SimpleConstMapping(dims, key), value(val) {}
Member Function Documentation
ConstMapping* ConstantSimpleConstMapping::constClone () const [inline, virtual]
creates a clone of this mapping.
This method has to be implemented by every subclass.
Implements SimpleConstMapping.
Definition at line 812 of file MappingUtils.h.
References ConstantSimpleConstMapping(), ConstMapping::dimensions, and value.
{
    return new ConstantSimpleConstMapping(dimensions, value);
  }
double ConstantSimpleConstMapping::getValue () const [inline]
Returns the value of this constant mapping.
Definition at line 803 of file MappingUtils.h.
References value.
{
    return value;
  }
virtual double ConstantSimpleConstMapping::getValue (const Argument & pos) const [inline, virtual]
Returns the value of the mapping at the passed position.
This method has to be implemented by every subclass and should only have constant complexity.
Implements SimpleConstMapping.
Definition at line 796 of file MappingUtils.h.
References value.
Referenced by MultiDimMapping< Linear >::MultiDimMapping(), and MultiDimMapping< Linear >::operator=().
{
    return value;
  }
void ConstantSimpleConstMapping::setValue (double val) [inline]
Sets the value of this constant mapping.
Definition at line 810 of file MappingUtils.h.
References value.
{ value = val; }
Member Data Documentation
double ConstantSimpleConstMapping::value [protected]
Definition at line 785 of file MappingUtils.h.
Referenced by constClone(), getValue(), and setValue().
The documentation for this class was generated from the following file:
base/phyLayer/MappingUtils.h