MiXiM: HostState Class Reference
HostState Class Reference
[Power consumption - Classes using/defining power consumption, BaseUtility - blackboard related stuff]
HostState is published by the battery to announce host failure.
#include <HostState.h>
Inherits BBItem.
Public Types
enum States {
ACTIVE, FAILED, BROKEN, SLEEP,
OFF
}
Public Member Functions
virtual BBItem * parentObject () const
HostState (States state=ACTIVE)
States get () const
Returns the host state.
void set (States s)
Sets the host state.
std::string info () const
Private Attributes
States state
Detailed Description
HostState is published by the battery to announce host failure.
HostState information is published by the Battery to announce Host failure due to battery depletion. (Default state is ON, OFF is not used; existing modules basically ignore everything but FAIL.)
All modules that generate messages and collect statistics should subscribe to this notification. Should eventually be generalized to handle more general HostState (e.g. stochastic failure, restart).
Definition at line 34 of file HostState.h.
Member Enumeration Documentation
enum HostState::States
Enumerator:
ACTIVE
FAILED Host is active and fully working
BROKEN Host is not active because of some failure but might able to be restarted
SLEEP Host is not active because of some failure and won't be able to be restarted
OFF Host is not active (sleeping) Host is not active (shut down)
Definition at line 39 of file HostState.h.
        {
          ACTIVE,
          FAILED,
          BROKEN,
          SLEEP,
          OFF
        };
Constructor & Destructor Documentation
HostState::HostState (States state = ACTIVE) [inline]
Definition at line 56 of file HostState.h.
                                  :
    state(state)
  {}
Member Function Documentation
States HostState::get () const [inline]
Returns the host state.
Definition at line 61 of file HostState.h.
References state.
Referenced by PhyLayerBattery::handleAirFrame(), PhyLayerBattery::handleHostState(), BurstApplLayerBattery::handleHostState(), BaseModule::handleHostState(), and PhyLayerBattery::handleUpperMessage().
{ return state; }
std::string HostState::info () const [inline]
Definition at line 65 of file HostState.h.
References ACTIVE, BROKEN, FAILED, OFF, SLEEP, and state.
Referenced by BaseUtility::receiveBBItem().
{
    std::ostringstream ost;
    switch(state) {
    case ACTIVE:
      ost << "ACTIVE";
      break;
    case FAILED:
      ost << "FAILED";
      break;
    case BROKEN:
      ost << "BROKEN";
      break;
    case SLEEP:
      ost << "SLEEP";
      break;
    case OFF:
      ost << "OFF";
      break;
    default:
      ost << "Unknown";
      break;
    }
    return ost.str();
  }
virtual BBItem* HostState::parentObject () const [inline, virtual]
Reimplemented from BBItem.
Definition at line 36 of file HostState.h.
:
    enum States
void HostState::set (States s) [inline]
Sets the host state.
Definition at line 63 of file HostState.h.
References state.
Referenced by SimpleBattery::deductAndCheck(), SimpleBattery::initialize(), and BaseUtility::initialize().
{ state = s; }
Member Data Documentation
States HostState::state [private]
Definition at line 53 of file HostState.h.
Referenced by get(), info(), and set().
The documentation for this class was generated from the following file:
base/utils/HostState.h