MiXiM: BaseMacLayer Class Reference
BaseMacLayer Class Reference
[macLayer - MAC layer modules, baseModules - base module classes of MiXiM]
A very simple MAC module template which provides de- and encapsulation of messages using the standard addresses and MacControlInfo of MiXiM. It also provides basic handling of lower layer messages.
#include <BaseMacLayer.h>
Inherits BaseLayer.
Inherited by CSMAMacLayer, and Mac80211.
Public Types
enum BaseMacMessageKinds { LAST_BASE_MAC_MESSAGE_KIND = 23000 }
enum BaseMacControlKinds { TX_OVER = 23500, PACKET_DROPPED, LAST_BASE_MAC_CONTROL_KIND }
Public Member Functions
virtual void initialize (int)
Initialization of the module and some variables.
Protected Member Functions
virtual void handleUpperMsg (cMessage *msg)
Handle messages comming from the network layer.
virtual void handleLowerMsg (cMessage *msg)
virtual void handleSelfMsg (cMessage *msg)
Handle self messages such as timer...
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from upper layer.
virtual cPacket * decapsMsg (MacPkt *)
decapsulate the network message from the MacPkt
virtual MacPkt * encapsMsg (cPacket *)
Encapsulate the NetwPkt into an MacPkt.
virtual Signal * createSignal (simtime_t start, simtime_t length, double power, double bitrate)
Creates a simple Signal defined over time with the passed parameters.
Mapping * createConstantMapping (simtime_t start, simtime_t end, double value)
Creates a simple Mapping with a constant curve progression at the passed value.
ConstMapping * createSingleFrequencyMapping (simtime_t start, simtime_t end, double centerFreq, double bandWith, double value)
Creates a Mapping defined over time and frequency with constant power in a certain frequency band.
Protected Attributes
MacToPhyInterface * phy
Handler to the physical layer.
int headerLength
Length of the MacPkt header.
int myMacAddr
MAC address (simply module id).
bool coreDebug
debug this core module?
Detailed Description
A very simple MAC module template which provides de- and encapsulation of messages using the standard addresses and MacControlInfo of MiXiM. It also provides basic handling of lower layer messages.
Author:
Daniel Willkomm, Karl Wessel
Definition at line 41 of file BaseMacLayer.h.
Member Enumeration Documentation
enum BaseMacLayer::BaseMacControlKinds
Enumerator:
TX_OVER Indicates the end of a transmission
PACKET_DROPPED Tells the netw layer that a packet to be sent has been dropped.
LAST_BASE_MAC_CONTROL_KIND Stores the id on which classes extending BaseMac should continue their own control kinds.
Definition at line 49 of file BaseMacLayer.h.
{
    TX_OVER = 23500,
    PACKET_DROPPED,
    LAST_BASE_MAC_CONTROL_KIND,
  };
enum BaseMacLayer::BaseMacMessageKinds
Enumerator:
LAST_BASE_MAC_MESSAGE_KIND Stores the id on which classes extending BaseMac should continue their own message kinds.
Definition at line 44 of file BaseMacLayer.h.
{
    LAST_BASE_MAC_MESSAGE_KIND = 23000,
  };
Member Function Documentation
Mapping * BaseMacLayer::createConstantMapping (simtime_t start, simtime_t end, double value) [protected]
Creates a simple Mapping with a constant curve progression at the passed value.
Used by "createSignal" to create the power and bitrate mapping.
Definition at line 169 of file BaseMacLayer.cc.
References MappingUtils::createMapping(), Mapping::LINEAR, Mapping::setValue(), and DimensionSet::timeDomain.
Referenced by createSignal().
{
  //create mapping over time
  Mapping* m = MappingUtils::createMapping(0.0, DimensionSet::timeDomain, Mapping::LINEAR);
  //set position Argument
  Argument startPos(start);
  //set mapping at position
  m->setValue(startPos, value);
  //set position Argument
  Argument endPos(end);
  //set mapping at position
  m->setValue(endPos, value);
  return m;
}
Signal * BaseMacLayer::createSignal (simtime_t start, simtime_t length, double power, double bitrate) [protected, virtual]
Creates a simple Signal defined over time with the passed parameters.
Convenience method to be able to create the appropriate Signal for the MacToPhyControlInfo without needing to care about creating Mappings.
Reimplemented in Mac80211.
Definition at line 152 of file BaseMacLayer.cc.
References createConstantMapping(), Signal::setBitrate(), and Signal::setTransmissionPower().
Referenced by CSMAMacLayer::encapsMsg().
{
  simtime_t end = start + length;
  //create signal with start at current simtime and passed length
  Signal* s = new Signal(start, length);
  //create and set tx power mapping
  Mapping* txPowerMapping = createConstantMapping(start, end, power);
  s->setTransmissionPower(txPowerMapping);
  //create and set bitrate mapping
  Mapping* bitrateMapping = createConstantMapping(start, end, bitrate);
  s->setBitrate(bitrateMapping);
  return s;
}
ConstMapping * BaseMacLayer::createSingleFrequencyMapping (simtime_t start, simtime_t end, double centerFreq, double bandWith, double value) [protected]
Creates a Mapping defined over time and frequency with constant power in a certain frequency band.
Definition at line 189 of file BaseMacLayer.cc.
References MappingUtils::createMapping(), Dimension::frequency_static(), Mapping::LINEAR, Argument::setArgValue(), Argument::setTime(), Mapping::setValue(), and DimensionSet::timeFreqDomain.
Referenced by Mac80211::createSignal().
{
  Mapping* res = MappingUtils::createMapping(0.0, DimensionSet::timeFreqDomain, Mapping::LINEAR);
  Argument pos(DimensionSet::timeFreqDomain);
  pos.setArgValue(Dimension::frequency_static(), centerFreq - halfBandwidth);
  pos.setTime(start);
  res->setValue(pos, value);
  pos.setTime(end);
  res->setValue(pos, value);
  pos.setArgValue(Dimension::frequency_static(), centerFreq + halfBandwidth);
  res->setValue(pos, value);
  pos.setTime(start);
  res->setValue(pos, value);
  return res;
}
cPacket * BaseMacLayer::decapsMsg (MacPkt * msg) [protected, virtual]
decapsulate the network message from the MacPkt
Decapsulates the network packet from the received MacPkt
Definition at line 55 of file BaseMacLayer.cc.
References coreEV.
Referenced by CSMAMacLayer::handleLowerMsg(), and handleLowerMsg().
{
    cPacket *m = msg->decapsulate();
    m->setControlInfo(new MacControlInfo(msg->getSrcAddr()));
    // delete the macPkt
    delete msg;
    coreEV << " message decapsulated " << endl;
    return m;
}
MacPkt * BaseMacLayer::encapsMsg (cPacket * netwPkt) [protected, virtual]
Encapsulate the NetwPkt into an MacPkt.
Encapsulates the received NetwPkt into a MacPkt and set all needed header fields.
Reimplemented in CSMAMacLayer, and Mac80211.
Definition at line 70 of file BaseMacLayer.cc.
References coreEV, MacControlInfo::getNextHopMac(), headerLength, and myMacAddr.
Referenced by handleUpperMsg().
{
    MacPkt *pkt = new MacPkt(netwPkt->getName(), netwPkt->getKind());
    pkt->setBitLength(headerLength);
    // copy dest address from the Control Info attached to the network
    // message by the network layer
    MacControlInfo* cInfo = static_cast<MacControlInfo*>(netwPkt->removeControlInfo());
    coreEV <<"CInfo removed, mac addr="<< cInfo->getNextHopMac()<<endl;
    pkt->setDestAddr(cInfo->getNextHopMac());
    //delete the control info
    delete cInfo;
    //set the src address to own mac address (nic module getId())
    pkt->setSrcAddr(myMacAddr);
    //encapsulate the network packet
    pkt->encapsulate(netwPkt);
    coreEV <<"pkt encapsulated\n";
    return pkt;
}
void BaseMacLayer::handleLowerControl (cMessage * msg) [protected, virtual]
Handle control messages from lower layer.
Implements BaseLayer.
Reimplemented in CSMAMacLayer, and Mac80211.
Definition at line 137 of file BaseMacLayer.cc.
References coreEV, BaseLayer::sendControlUp(), TX_OVER, and MacToPhyInterface::TX_OVER.
{
  switch (msg->getKind())
  {
    case MacToPhyInterface::TX_OVER:
      msg->setKind(TX_OVER);
      sendControlUp(msg);
      break;
    default:
      coreEV << "BaseMacLayer does not handle control messages of this type (name was "<<msg->getName()<<")\n";
      delete msg;
      break;
  }
}
void BaseMacLayer::handleLowerMsg (cMessage * msg) [protected, virtual]
If message arrives from lower layer, check whether it is for us. Send it up if yes.
This basic implementation just forwards all message that are broadcast (destAddr = L2BROADCAST) or destined for this node (destAddr = nic module getId()) to the network layer
See also:
sendUp
Implements BaseLayer.
Reimplemented in CSMAMacLayer, and Mac80211.
Definition at line 116 of file BaseMacLayer.cc.
References coreEV, decapsMsg(), L2BROADCAST, myMacAddr, and BaseLayer::sendUp().
{
    MacPkt *mac = static_cast<MacPkt *>(msg);
    int dest = mac->getDestAddr();
    int src = mac->getSrcAddr();
    //only foward to upper layer if message is for me or broadcast
    if((dest == myMacAddr) || (dest == L2BROADCAST)) {
    coreEV << "message with mac addr " << src
         << " for me (dest=" << dest
         << ") -> forward packet to upper layer\n";
    sendUp(decapsMsg(mac));
    }
    else{
    coreEV << "message with mac addr " << src
         << " not for me (dest=" << dest
         << ") -> delete (my MAC="<<myMacAddr<<")\n";
    delete mac;
    }
}
virtual void BaseMacLayer::handleSelfMsg (cMessage * msg) [inline, protected, virtual]
Handle self messages such as timer...
Implements BaseLayer.
Reimplemented in CSMAMacLayer, and Mac80211.
Definition at line 102 of file BaseMacLayer.h.
{
  error("BaseMacLayer does not handle self messages");
    };
virtual void BaseMacLayer::handleUpperControl (cMessage * msg) [inline, protected, virtual]
Handle control messages from upper layer.
Implements BaseLayer.
Definition at line 107 of file BaseMacLayer.h.
{
  error("BaseMacLayer does not handle control messages from upper layers");
    };
void BaseMacLayer::handleUpperMsg (cMessage * mac) [protected, virtual]
Handle messages comming from the network layer.
Here is the place to implement a real medium access functionality.
If message arrives from upper layer, make a MAC packet from it (encapsMsg) and send it down (sendDown).
See also:
encapsMsg, sendDown
Redefine this function if you want to process messages from upper layers before they are send to lower layers.
To forward the message to lower layers after processing it please use sendDown. It will take care of anything needed
Implements BaseLayer.
Reimplemented in CSMAMacLayer, and Mac80211.
Definition at line 102 of file BaseMacLayer.cc.
References encapsMsg(), and BaseLayer::sendDown().
{
  assert(dynamic_cast<cPacket*>(mac));
    sendDown(encapsMsg(static_cast<cPacket*>(mac)));
}
void BaseMacLayer::initialize (int stage) [virtual]
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Reimplemented from BaseLayer.
Reimplemented in CSMAMacLayer, and Mac80211.
Definition at line 36 of file BaseMacLayer.cc.
References coreDebug, headerLength, myMacAddr, and phy.
Referenced by Define_Module().
{
    BaseLayer::initialize(stage);
    if(stage==0) {
      // get handle to phy layer
        phy = FindModule<MacToPhyInterface*>::findSubModule(getParentModule());
        headerLength= par("headerLength");
        // The nic id is used as MAC address
        myMacAddr = getParentModule()->getId();
        hasPar("coreDebug") ? coreDebug = par("coreDebug").boolValue() : coreDebug = false;
    }
}
Member Data Documentation
bool BaseMacLayer::coreDebug [protected]
debug this core module?
Definition at line 74 of file BaseMacLayer.h.
Referenced by initialize().
int BaseMacLayer::headerLength [protected]
Length of the MacPkt header.
Definition at line 66 of file BaseMacLayer.h.
Referenced by encapsMsg(), and initialize().
int BaseMacLayer::myMacAddr [protected]
MAC address (simply module id).
Reimplemented in Mac80211.
Definition at line 71 of file BaseMacLayer.h.
Referenced by encapsMsg(), CSMAMacLayer::handleLowerMsg(), handleLowerMsg(), and initialize().
MacToPhyInterface* BaseMacLayer::phy [protected]
Handler to the physical layer.
Definition at line 61 of file BaseMacLayer.h.
Referenced by Mac80211::beginNewCycle(), Mac80211::handleEndContentionTimer(), Mac80211::handleEndSifsTimer(), Mac80211::handleLowerControl(), CSMAMacLayer::handleLowerControl(), Mac80211::handleLowerMsg(), CSMAMacLayer::handleSelfMsg(), initialize(), and CSMAMacLayer::scheduleBackoff().
The documentation for this class was generated from the following files:
base/modules/BaseMacLayer.h
base/modules/BaseMacLayer.cc