MiXiM: MassMobility Class Reference
MassMobility Class Reference
[mobility - modules handling the mobility of the hosts]
Models the mobility of with mass, making random motions. See NED file for more info.
#include <MassMobility.h>
Inherits BaseMobility.
Public Types
enum MassMobilityMsgKinds { MK_CHANGE_DIR = BaseMobility::LAST_BASE_MOBILITY_KIND, LAST_MASS_MOBILITY_KIND }
The kind field of messages.
Public Member Functions
virtual void initialize (int)
Initializes mobility model parameters.
Protected Member Functions
virtual void handleSelfMsg (cMessage *msg)
Called upon arrival of a self messages.
virtual void makeMove ()
Move the host.
virtual void fixIfHostGetsOutside ()
Should be redefined in subclasses.
Protected Attributes
cPar * changeInterval
cPar * changeAngleBy
double currentSpeed
speed of the host
double currentAngle
angle of linear motion
Coord step
calculated from speed, angle and updateInterval
Coord targetPos
Detailed Description
Models the mobility of with mass, making random motions. See NED file for more info.
Author:
Emin Ilker Cetinbas, Andras Varga
Definition at line 36 of file MassMobility.h.
Member Enumeration Documentation
enum MassMobility::MassMobilityMsgKinds
The kind field of messages.
that are used internally by this class have one of these values
Enumerator:
MK_CHANGE_DIR
LAST_MASS_MOBILITY_KIND
Definition at line 56 of file MassMobility.h.
{
  MK_CHANGE_DIR = BaseMobility::LAST_BASE_MOBILITY_KIND,
  LAST_MASS_MOBILITY_KIND
    };
Member Function Documentation
void MassMobility::fixIfHostGetsOutside () [protected, virtual]
Should be redefined in subclasses.
Should invoke handleIfOutside() and pass the references to the parameters to be modified.
Additional action after border handling (such as choosing a new target position if the BorderPolicy is PLACERANDOMLY) should be implemented here.
See also:
HandleIfOutside
Reimplemented from BaseMobility.
Definition at line 109 of file MassMobility.cc.
References currentAngle, BaseMobility::handleIfOutside(), BaseMobility::REFLECT, step, and targetPos.
Referenced by makeMove().
{
    Coord dummy;
    handleIfOutside( REFLECT, targetPos, dummy, step, currentAngle );
}
void MassMobility::handleSelfMsg (cMessage * msg) [protected, virtual]
Called upon arrival of a self messages.
The only self message possible is to indicate a new movement.
Reimplemented from BaseMobility.
Definition at line 70 of file MassMobility.cc.
References changeAngleBy, changeInterval, currentAngle, MK_CHANGE_DIR, BaseMobility::move, BaseMobility::MOVE_HOST, Move::setDirection(), Coord::setX(), Coord::setY(), Move::speed, Move::startPos, step, and BaseMobility::updateInterval.
{
    Coord dummy;
    switch (msg->getKind()){
    case MOVE_HOST:
  BaseMobility::handleSelfMsg( msg );
  break;
    case MK_CHANGE_DIR:
  currentAngle += changeAngleBy->doubleValue();
  step.setX(move.speed * cos(PI * currentAngle / 180) * updateInterval.dbl());
  step.setY(move.speed * sin(PI * currentAngle / 180) * updateInterval.dbl());
  move.setDirection(move.startPos+step);
  scheduleAt(simTime() + changeInterval->doubleValue(), msg);
  break;
    default:
  opp_error("Unknown self message kind in MassMobility class");
  break;
    }
}
void MassMobility::initialize (int stage) [virtual]
Initializes mobility model parameters.
Reads the updateInterval and the velocity
If the host is not stationary it calculates a random position and schedules a timer to trigger the first movement
Reimplemented from BaseMobility.
Definition at line 36 of file MassMobility.cc.
References changeAngleBy, changeInterval, currentAngle, MK_CHANGE_DIR, BaseMobility::move, Move::setDirection(), Coord::setX(), Coord::setY(), Move::speed, Move::startPos, Move::startTime, step, targetPos, and BaseMobility::updateInterval.
{
    BaseMobility::initialize(stage);
    EV << "initializing MassMobility stage " << stage << endl;
    if (stage == 0)
    {
        changeInterval = &par("changeInterval");
        changeAngleBy = &par("changeAngleBy");
        // initial speed and angle
        move.speed = par("speed");
        currentAngle = uniform(0, 360);
        step.setX(move.speed * cos(PI * currentAngle / 180) * updateInterval.dbl());
        step.setY(move.speed * sin(PI * currentAngle / 180) * updateInterval.dbl());
    }
    else if( stage == 1 ){
  // start moving: set direction and start time
  move.setDirection(move.startPos+step);
  move.startTime = simTime();
  targetPos = move.startPos;
  scheduleAt(simTime() + uniform(0, changeInterval->doubleValue()), new cMessage("turn", MK_CHANGE_DIR));
    }
}
void MassMobility::makeMove () [protected, virtual]
Move the host.
Move the host if the destination is not reached yet. Otherwise calculate a new random position
Reimplemented from BaseMobility.
Definition at line 99 of file MassMobility.cc.
References fixIfHostGetsOutside(), BaseMobility::move, Move::startPos, Move::startTime, step, and targetPos.
{
    move.startPos = targetPos;
    targetPos += step;
    move.startTime = simTime();
   // do something if we reach the wall
    fixIfHostGetsOutside();
}
Member Data Documentation
cPar* MassMobility::changeAngleBy [protected]
Definition at line 41 of file MassMobility.h.
Referenced by handleSelfMsg(), and initialize().
cPar* MassMobility::changeInterval [protected]
Definition at line 40 of file MassMobility.h.
Referenced by handleSelfMsg(), and initialize().
double MassMobility::currentAngle [protected]
angle of linear motion
Definition at line 45 of file MassMobility.h.
Referenced by fixIfHostGetsOutside(), handleSelfMsg(), and initialize().
double MassMobility::currentSpeed [protected]
speed of the host
Definition at line 44 of file MassMobility.h.
Coord MassMobility::step [protected]
calculated from speed, angle and updateInterval
Definition at line 46 of file MassMobility.h.
Referenced by fixIfHostGetsOutside(), handleSelfMsg(), initialize(), and makeMove().
Coord MassMobility::targetPos [protected]
Definition at line 48 of file MassMobility.h.
Referenced by fixIfHostGetsOutside(), initialize(), and makeMove().
The documentation for this class was generated from the following files:
modules/mobility/MassMobility.h
modules/mobility/MassMobility.cc