MiXiM: FrameTimer Class Reference
FrameTimer Class Reference
#include <FrameTimer.h>
Public Member Functions
virtual ~FrameTimer ()
virtual void init (BaseModule *parent)
void setFrameTimer (unsigned int index, double period)
unsigned int setFrameTimer (double period)
void cancelFrameTimer (unsigned int index)
virtual void handleFrameTimer (unsigned int index)=0
Protected Attributes
FrameTimerGenerator * tg
BaseModule * owner
Friends
class FrameTimerGenerator
Detailed Description
Definition at line 15 of file FrameTimer.h.
Constructor & Destructor Documentation
virtual FrameTimer::~FrameTimer () [inline, virtual]
Definition at line 22 of file FrameTimer.h.
References tg.
{delete tg;}
Member Function Documentation
void FrameTimer::cancelFrameTimer (unsigned int index) [inline]
Definition at line 26 of file FrameTimer.h.
References FrameTimerGenerator::cancelFrameTimer(), and tg.
{tg->cancelFrameTimer(index);}
virtual void FrameTimer::handleFrameTimer (unsigned int index) [pure virtual]
Referenced by FrameTimerGenerator::handleMessage().
void FrameTimer::init (BaseModule * parent) [virtual]
Definition at line 3 of file FrameTimer.cc.
References FrameTimerGenerator::init(), owner, and tg.
{
  owner = parent;
  tg = dynamic_cast<FrameTimerGenerator*>(cModuleType::get("FrameTimerGenerator")->createScheduleInit("generator",owner));
  tg->init(this);
}
unsigned int FrameTimer::setFrameTimer (double period) [inline]
Definition at line 25 of file FrameTimer.h.
References FrameTimerGenerator::setFrameTimer(), and tg.
{return tg->setFrameTimer(period);}
void FrameTimer::setFrameTimer (unsigned int index, double period) [inline]
Definition at line 24 of file FrameTimer.h.
References FrameTimerGenerator::setFrameTimer(), and tg.
{tg->setFrameTimer(index,period);}
Friends And Related Function Documentation
friend class FrameTimerGenerator [friend]
Definition at line 17 of file FrameTimer.h.
Member Data Documentation
BaseModule* FrameTimer::owner [protected]
Definition at line 20 of file FrameTimer.h.
Referenced by FrameTimerGenerator::init(), and init().
FrameTimerGenerator* FrameTimer::tg [protected]
Definition at line 19 of file FrameTimer.h.
Referenced by cancelFrameTimer(), init(), setFrameTimer(), and ~FrameTimer().
The documentation for this class was generated from the following files:
base/timers/FrameTimer.h
base/timers/FrameTimer.cc