MiXiM: DelayedMapping Class Reference
DelayedMapping Class Reference
[mappingDetails - mostly internal mapping classes]
Moves another Mapping in its time dimension.
#include <MappingUtils.h>
Inherits BaseDelayedMapping< Mapping >.
Public Member Functions
DelayedMapping (Mapping *mapping, simtime_t delay)
virtual ~DelayedMapping ()
virtual void setValue (const Argument &pos, double value)
Changes the value of the Mapping at the specified position.
virtual Mapping * clone () const
Returns a deep copy of this Mapping.
virtual MappingIterator * createIterator ()
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change it.
virtual MappingIterator * createIterator (const Argument &pos)
Returns a pointer of a new Iterator which is able to iterate over the function and can change it.
Detailed Description
Moves another Mapping in its time dimension.
See propagation delay effect of the signal for an example how to use this mapping.
Author:
Karl Wessel
Definition at line 2216 of file MappingUtils.h.
Constructor & Destructor Documentation
DelayedMapping::DelayedMapping (Mapping * mapping, simtime_t delay) [inline]
Definition at line 2218 of file MappingUtils.h.
Referenced by clone().
                                                   :
    BaseDelayedMapping<Mapping>(mapping, delay) {}
virtual DelayedMapping::~DelayedMapping () [inline, virtual]
Definition at line 2221 of file MappingUtils.h.
{}
Member Function Documentation
virtual Mapping* DelayedMapping::clone () const [inline, virtual]
Returns a deep copy of this Mapping.
Implements Mapping.
Definition at line 2227 of file MappingUtils.h.
References Mapping::clone(), BaseDelayedMapping< Mapping >::delay, DelayedMapping(), and BaseDelayedMapping< Mapping >::mapping.
{
    return new DelayedMapping(mapping->clone(), delay);
  }
virtual MappingIterator* DelayedMapping::createIterator (const Argument & pos) [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the function and can change it.
The iterator starts at the passed position.
Implements Mapping.
Definition at line 2235 of file MappingUtils.h.
References Mapping::createIterator(), BaseDelayedMapping< Mapping >::delay, BaseDelayedMapping< Mapping >::delayPosition(), and BaseDelayedMapping< Mapping >::mapping.
{
    return new DelayedMappingIterator(mapping->createIterator(delayPosition(pos)), delay);
  }
virtual MappingIterator* DelayedMapping::createIterator () [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change it.
Implements Mapping.
Definition at line 2231 of file MappingUtils.h.
References Mapping::createIterator(), BaseDelayedMapping< Mapping >::delay, and BaseDelayedMapping< Mapping >::mapping.
{
    return new DelayedMappingIterator(mapping->createIterator(), delay);
  }
virtual void DelayedMapping::setValue (const Argument & pos, double value) [inline, virtual]
Changes the value of the Mapping at the specified position.
The complexity of this method depends on the implementation.
Implements Mapping.
Definition at line 2223 of file MappingUtils.h.
References BaseDelayedMapping< Mapping >::delayPosition(), BaseDelayedMapping< Mapping >::mapping, and Mapping::setValue().
{
    mapping->setValue(delayPosition(pos), value);
  }
The documentation for this class was generated from the following file:
base/phyLayer/MappingUtils.h