MiXiM: CircleMobility Class Reference
CircleMobility Class Reference
[mobility - modules handling the mobility of the hosts]
Circle movement model. See NED file for more info.
#include <CircleMobility.h>
Inherits BaseMobility.
Public Member Functions
virtual void initialize (int)
Initializes mobility model parameters.
Protected Member Functions
virtual void makeMove ()
Move the host.
virtual void fixIfHostGetsOutside ()
Should be redefined in subclasses.
Protected Attributes
Coord center
double r
double omega
angular velocity [rad/s], derived from speed and radius
double angle
direction from the centre of the circle
Coord targetPos
Target position for the host.
Detailed Description
Circle movement model. See NED file for more info.
Author:
Andras Varga
Definition at line 32 of file CircleMobility.h.
Member Function Documentation
void CircleMobility::fixIfHostGetsOutside () [protected, virtual]
Should be redefined in subclasses.
Should invoke handleIfOutside() and pass the references to the parameters to be modified.
Additional action after border handling (such as choosing a new target position if the BorderPolicy is PLACERANDOMLY) should be implemented here.
See also:
HandleIfOutside
Reimplemented from BaseMobility.
Definition at line 69 of file CircleMobility.cc.
References center, BaseMobility::handleIfOutside(), targetPos, and BaseMobility::WRAP.
Referenced by makeMove().
{
    Coord dummy;
    double dum;
    handleIfOutside( WRAP, targetPos, center, dummy, dum);
}
void CircleMobility::initialize (int stage) [virtual]
Initializes mobility model parameters.
Reimplemented from BaseMobility.
Definition at line 27 of file CircleMobility.cc.
References angle, center, Coord::getX(), Coord::getY(), BaseMobility::move, omega, r, Coord::setX(), Coord::setY(), Move::speed, Move::startPos, and targetPos.
{
    BaseMobility::initialize(stage);
    EV << "initializing CircleMobility stage " << stage << endl;
    if (stage == 0)
    {
        // read parameters
        center.setX(par("cx"));
        center.setY(par("cy"));
        r = par("r");
        ASSERT(r>0);
        angle = par("startAngle").doubleValue()/180.0*PI;
        move.speed = par("speed");
        omega = move.speed/r;
        // calculate initial position
        move.startPos.setX(center.getX() + r * cos(angle));
        move.startPos.setY(center.getY() + r * sin(angle));
  targetPos = move.startPos;
    }
}
void CircleMobility::makeMove () [protected, virtual]
Move the host.
Reimplemented from BaseMobility.
Definition at line 55 of file CircleMobility.cc.
References angle, center, fixIfHostGetsOutside(), Coord::getX(), Coord::getY(), BaseMobility::move, omega, r, Move::setDirection(), Coord::setX(), Coord::setY(), Move::startPos, Move::startTime, targetPos, and BaseMobility::updateInterval.
{
    move.startPos = targetPos;
    angle += omega * updateInterval.dbl();
    targetPos.setX(center.getX() + r * cos(angle));
    targetPos.setY(center.getY() + r * sin(angle));
    move.setDirection(targetPos);
    move.startTime = simTime();
    fixIfHostGetsOutside();
}
Member Data Documentation
double CircleMobility::angle [protected]
direction from the centre of the circle
Definition at line 41 of file CircleMobility.h.
Referenced by initialize(), and makeMove().
Coord CircleMobility::center [protected]
Definition at line 36 of file CircleMobility.h.
Referenced by fixIfHostGetsOutside(), initialize(), and makeMove().
double CircleMobility::omega [protected]
angular velocity [rad/s], derived from speed and radius
Definition at line 38 of file CircleMobility.h.
Referenced by initialize(), and makeMove().
double CircleMobility::r [protected]
Definition at line 37 of file CircleMobility.h.
Referenced by initialize(), and makeMove().
Coord CircleMobility::targetPos [protected]
Target position for the host.
Definition at line 44 of file CircleMobility.h.
Referenced by fixIfHostGetsOutside(), initialize(), and makeMove().
The documentation for this class was generated from the following files:
modules/mobility/CircleMobility.h
modules/mobility/CircleMobility.cc