MiXiM: MacControlInfo Class Reference
MacControlInfo Class Reference
[baseUtils - utitities for base MiXiM, macLayer - MAC layer modules, netwLayer - network layer modules, utils - utiltity classes]
Control info to pass next hop L2 addr from netw to MAC layer.
#include <MacControlInfo.h>
Public Member Functions
MacControlInfo (const int addr)
Default constructor.
virtual ~MacControlInfo ()
Destructor.
virtual const int getNextHopMac ()
Getter method.
virtual void setNextHopMac (const int addr)
Setter method.
Protected Attributes
int nextHopMac
netw address of the sending or receiving node
Detailed Description
Control info to pass next hop L2 addr from netw to MAC layer.
Control Info to pass interface information from the network to the MAC layer Currently the only information necessary is the MAC address of the next hop, which has to be determined by ARP or some similar mechanism
Author:
Daniel Willkomm
Definition at line 41 of file MacControlInfo.h.
Constructor & Destructor Documentation
MacControlInfo::MacControlInfo (const int addr) [inline]
Default constructor.
Definition at line 49 of file MacControlInfo.h.
: nextHopMac(addr) {};
virtual MacControlInfo::~MacControlInfo () [inline, virtual]
Destructor.
Definition at line 51 of file MacControlInfo.h.
{};
Member Function Documentation
virtual const int MacControlInfo::getNextHopMac () [inline, virtual]
Getter method.
Definition at line 54 of file MacControlInfo.h.
References nextHopMac.
Referenced by Mac80211::encapsMsg(), BaseMacLayer::encapsMsg(), and SimpleNetwLayer::handleHelloWorld().
{
  return nextHopMac;
    };
virtual void MacControlInfo::setNextHopMac (const int addr) [inline, virtual]
Setter method.
Definition at line 59 of file MacControlInfo.h.
References nextHopMac.
{
  nextHopMac = addr;
    };
Member Data Documentation
int MacControlInfo::nextHopMac [protected]
netw address of the sending or receiving node
Definition at line 45 of file MacControlInfo.h.
Referenced by getNextHopMac(), and setNextHopMac().
The documentation for this class was generated from the following file:
base/utils/MacControlInfo.h