MiXiM: Coord Class Reference
Coord Class Reference
[baseUtils - utitities for base MiXiM, utils - utiltity classes]
Class for storing host positions.
#include <Coord.h>
Public Member Functions
Coord (bool use2D=false)
Coord (double x, double y, double z)
Coord (double x, double y)
Coord (const Coord &pos)
Coord (const Coord *pos)
std::string info () const
Coord operator*= (double f)
Coord operator/= (double f)
Coord operator+= (const Coord &a)
Coord operator= (const Coord &a)
Coord operator-= (const Coord &a)
double distance (const Coord &a) const
double sqrdist (const Coord &a) const
double sqrTorusDist (const Coord &b, const Coord &playgroundSize) const
double squareLength () const
double length () const
double getX () const
void setX (double x)
double getY () const
void setY (double y)
double getZ () const
void setZ (double z)
bool isValid () const
bool is2D () const
bool is3D () const
bool isInRectangle (const Coord &upperLeftCorner, const Coord &lowerRightCorner) const
Coord min (const Coord &a)
Coord max (const Coord &a)
Static Public Attributes
static const double UNDEFINED = 0.0
Protected Attributes
double x
x and y coordinates of the position
double y
double z
bool use2DFlag
Friends
Coord operator+ (const Coord &a, const Coord &b)
Coord operator- (const Coord &a, const Coord &b)
Coord operator* (const Coord &a, double f)
Coord operator/ (const Coord &a, double f)
bool operator== (const Coord &a, const Coord &b)
bool operator!= (const Coord &a, const Coord &b)
bool operator> (const Coord &a, const Coord &b)
bool operator< (const Coord &a, const Coord &b)
Detailed Description
Class for storing host positions.
Class for a storing a position / vector. Some comparison and basic arithmetic operators on Coord structures are implemented.
Note: This class can work 2-dimensional or 3-dimensional. The dimension of a Coord can only be set at construction time. The only way to change it afterwards is by assigning Coord a new value with the overloaded "="-operator. So every time you create a new Coord variable you should make sure to use the proper constructor. Since most time you won't have own constructors in Omnet-modules every member variable of type Coord becomes 3D at the beginning (because the default-constructor creates a 3D-Coord). In this case you should give it the right dimension by assigning them a new value in the "initialize()"-Method by a line like this:
coordMember = Coord(x, y); <- 2D coordMember = Coord(x, y, z); <- 3D
See the constructors for more details.
Most methods of Coord does not check for dimension compatibility. For example the overloaded "+"-operator does not check if both Coord are of the same dimension. The user has to assure the proper use of this methods!
Author:
Christian Frank
Definition at line 61 of file Coord.h.
Constructor & Destructor Documentation
Coord::Coord (bool use2D = false) [inline]
Initialize a 3d (default) or 2d coordinate with the origin
Definition at line 78 of file Coord.h.
References UNDEFINED, and z.
        :x(0.0), y(0.0), use2DFlag(use2D)
    {
        if (use2D) {
            z = UNDEFINED;
        } else {
            z = 0.0;
        }
    }
Coord::Coord (double x, double y, double z) [inline]
Initializes 3D coordinate.
Definition at line 90 of file Coord.h.
        : x(x), y(y), z(z) , use2DFlag(false) {}
Coord::Coord (double x, double y) [inline]
Initializes 2D coordinate.
Definition at line 94 of file Coord.h.
        : x(x), y(y), z(UNDEFINED) , use2DFlag(true) {}
Coord::Coord (const Coord & pos) [inline]
Initializes coordinate from other coordinate.
Definition at line 99 of file Coord.h.
        : cObject(pos), x(pos.x), y(pos.y), z(pos.z), use2DFlag(pos.use2DFlag) {}
Coord::Coord (const Coord * pos) [inline]
Initializes coordinate from other coordinate.
Definition at line 103 of file Coord.h.
        : cObject(*pos), x(pos->x), y(pos->y), z(pos->z), use2DFlag(pos->use2DFlag) {}
Member Function Documentation
double Coord::distance (const Coord & a) const [inline]
Returns the distance to Coord a. Does not check for dimension compatibility!
Definition at line 230 of file Coord.h.
References length().
Referenced by LineSegmentsMobilityBase::beginNextMove(), ChannelAccess::calculatePropagationDelay(), TurtleMobility::executeStatement(), BaseMobility::handleIfOutside(), Move::setDirection(), and ConstSpeedMobility::setTargetPosition().
{
        Coord dist=*this-a;
        return dist.length();
    }
double Coord::getX () const [inline]
Getter for the x coordinate
Definition at line 270 of file Coord.h.
References x.
Referenced by BaseMobility::checkIfOutside(), TurtleMobility::executeStatement(), BaseWorldUtility::getRandomPosition(), BaseMobility::goToBorder(), BaseConnectionManager::BaseConnectionManager::GridCoord::GridCoord(), CircleMobility::initialize(), BaseConnectionManager::initialize(), LinearMobility::makeMove(), CircleMobility::makeMove(), BaseMobility::playgroundSizeX(), BaseMobility::reflectCoordinate(), BaseMobility::reflectIfOutside(), BaseMobility::updatePosition(), and BaseMobility::wrapIfOutside().
{ return x; }
double Coord::getY () const [inline]
Getter for the y coordinate
Definition at line 280 of file Coord.h.
References y.
Referenced by BaseMobility::checkIfOutside(), TurtleMobility::executeStatement(), BaseWorldUtility::getRandomPosition(), BaseMobility::goToBorder(), BaseConnectionManager::BaseConnectionManager::GridCoord::GridCoord(), CircleMobility::initialize(), BaseConnectionManager::initialize(), LinearMobility::makeMove(), CircleMobility::makeMove(), BaseMobility::playgroundSizeY(), BaseMobility::reflectCoordinate(), BaseMobility::reflectIfOutside(), BaseMobility::updatePosition(), and BaseMobility::wrapIfOutside().
{ return y; }
double Coord::getZ () const [inline]
Getter for the z coordinate.
This method should return Coord::UNDEFINED if this is a two-dimensional coordinate. If not, the proper function of the Coord-methods can't be assured.
Definition at line 295 of file Coord.h.
References z.
Referenced by BaseMobility::checkIfOutside(), BaseWorldUtility::getRandomPosition(), BaseMobility::goToBorder(), BaseConnectionManager::BaseConnectionManager::GridCoord::GridCoord(), BaseConnectionManager::initialize(), BaseMobility::playgroundSizeZ(), BaseMobility::reflectCoordinate(), BaseMobility::reflectIfOutside(), and BaseMobility::wrapIfOutside().
{ return z; }
std::string Coord::info () const [inline]
Returns a string with the value of the coordinate.
Definition at line 107 of file Coord.h.
References use2DFlag, x, y, and z.
Referenced by LineSegmentsMobilityBase::beginNextMove(), BaseMobility::checkIfOutside(), TurtleMobility::fixIfHostGetsOutside(), BaseMobility::goToBorder(), BaseMobility::handleBorderMsg(), BaseMobility::handleIfOutside(), Move::info(), BonnMotionMobility::initialize(), BaseMobility::initialize(), LinearMobility::makeMove(), ConstSpeedMobility::makeMove(), ConstSpeedMobility::setTargetPosition(), and BonnMotionMobility::setTargetPosition().
{
        std::stringstream os;
        if (use2DFlag) {
            os << "(" << x << "," << y << ")";
        } else {
            os << "(" << x << "," << y << "," << z << ")";
        }
        return os.str();
    }
bool Coord::is2D () const [inline]
Returns true if this coordinate is two-dimensional
Definition at line 322 of file Coord.h.
References use2DFlag.
Referenced by BaseConnectionManager::BaseConnectionManager::GridCoord::GridCoord().
{ return use2DFlag; }
bool Coord::is3D () const [inline]
Returns true if this coordinate is three-dimensional
Definition at line 327 of file Coord.h.
References use2DFlag.
Referenced by max(), and min().
{ return !use2DFlag; }
bool Coord::isInRectangle (const Coord & upperLeftCorner, const Coord & lowerRightCorner) const [inline]
Checks if this coordinate is inside a specified rectangle.
Does not check for dimension compatibility!
Parameters:
upperLeftCorner The upper left corner of the rectangle.
lowerRightCorner the lower right corner of the rectangle.
Definition at line 337 of file Coord.h.
References use2DFlag, x, y, and z.
Referenced by BaseMobility::initialize().
{
        return  x >= upperLeftCorner.x && x <= lowerRightCorner.x &&
                y >= upperLeftCorner.y && y <= lowerRightCorner.y &&
                (use2DFlag || (z >= upperLeftCorner.z && z <= lowerRightCorner.z));
    }
bool Coord::isValid () const [inline]
Returns true if this coordinate is valid. Valid means this Coord is 3-dimensional or this Coord is 2-Dimensional and the z-value i equal to Coord::UNDEFINED.
Definition at line 315 of file Coord.h.
References UNDEFINED, use2DFlag, and z.
{
        return (z == UNDEFINED) || !use2DFlag;
    }
double Coord::length () const [inline]
Returns the length of this coords position vector
Definition at line 262 of file Coord.h.
References squareLength().
Referenced by distance(), and BaseMobility::handleIfOutside().
    {
        return sqrt(squareLength());
    }
Coord Coord::max (const Coord & a) [inline]
Returns the maximal coordinates.
Definition at line 358 of file Coord.h.
References is3D(), setX(), setY(), setZ(), x, y, and z.
{
        Coord tmp = *this;
  tmp.setX(this->x > a.x ? this->x : a.x);
  tmp.setY(this->y > a.y ? this->y : a.y);
  if (tmp.is3D())
    tmp.setZ(this->z > a.z ? this->z : a.z);
        return tmp;
    }
Coord Coord::min (const Coord & a) [inline]
Returns the minimal coordinates.
Definition at line 346 of file Coord.h.
References is3D(), setX(), setY(), setZ(), x, y, and z.
{
        Coord tmp = *this;
  tmp.setX(this->x < a.x ? this->x : a.x);
  tmp.setY(this->y < a.y ? this->y : a.y);
  if (tmp.is3D())
    tmp.setZ(this->z < a.z ? this->z : a.z);
        return tmp;
    }
Coord Coord::operator*= (double f) [inline]
Multiplies a coordinate vector by a real number.
Definition at line 154 of file Coord.h.
References x, y, and z.
{
        x *= f;
        y *= f;
        z *= f;
        return *this;
    }
Coord Coord::operator+= (const Coord & a) [inline]
Adds coordinate vector b to a. Does not check for dimension compatibility!
Definition at line 175 of file Coord.h.
References x, y, and z.
{
        x += a.x;
        y += a.y;
        z += a.z;
        return *this;
    }
Coord Coord::operator-= (const Coord & a) [inline]
Subtracts coordinate vector b from a. Does not check for dimension compatibility!
Definition at line 198 of file Coord.h.
References x, y, and z.
{
        x -= a.x;
        y -= a.y;
        z -= a.z;
        return *this;
    }
Coord Coord::operator/= (double f) [inline]
Divides a coordinate vector by a real number.
Definition at line 164 of file Coord.h.
References x, y, and z.
{
        x /= f;
        y /= f;
        z /= f;
        return *this;
    }
Coord Coord::operator= (const Coord & a) [inline]
Assigns a this. This operator can change the dimension of the coordinate.
Definition at line 186 of file Coord.h.
References use2DFlag, x, y, and z.
{
        x = a.x;
        y = a.y;
        z = a.z;
        use2DFlag = a.use2DFlag;
        return *this;
    }
void Coord::setX (double x) [inline]
Setter for the x coordinate
Definition at line 275 of file Coord.h.
Referenced by LineSegmentsMobilityBase::beginNextMove(), TractorMobility::calculateXY(), RectangleMobility::calculateXY(), BaseMobility::checkIfOutside(), TurtleMobility::executeStatement(), ANSimMobility::extractDataFrom(), BaseMobility::goToBorder(), MassMobility::handleSelfMsg(), MassMobility::initialize(), CircleMobility::initialize(), BonnMotionMobility::initialize(), LinearMobility::makeMove(), CircleMobility::makeMove(), max(), min(), BaseMobility::reflectCoordinate(), BaseMobility::reflectIfOutside(), BonnMotionMobility::setTargetPosition(), and BaseMobility::wrapIfOutside().
{this->x = x;}
void Coord::setY (double y) [inline]
Setter for the y coordinate
Definition at line 285 of file Coord.h.
Referenced by LineSegmentsMobilityBase::beginNextMove(), TractorMobility::calculateXY(), RectangleMobility::calculateXY(), BaseMobility::checkIfOutside(), TurtleMobility::executeStatement(), ANSimMobility::extractDataFrom(), BaseMobility::goToBorder(), MassMobility::handleSelfMsg(), MassMobility::initialize(), CircleMobility::initialize(), BonnMotionMobility::initialize(), LinearMobility::makeMove(), CircleMobility::makeMove(), max(), min(), BaseMobility::reflectCoordinate(), BaseMobility::reflectIfOutside(), BonnMotionMobility::setTargetPosition(), and BaseMobility::wrapIfOutside().
{this->y = y;}
void Coord::setZ (double z) [inline]
Setter for the z coordinate.
This method does not check its dimension! So never call it if you are working with two-dimensional coordinates! A 2D-Coord looses its functionality if the z-value becomes another value than Coord::UNDEFINED
Definition at line 307 of file Coord.h.
Referenced by BaseMobility::checkIfOutside(), BaseMobility::goToBorder(), max(), min(), BaseMobility::reflectCoordinate(), BaseMobility::reflectIfOutside(), and BaseMobility::wrapIfOutside().
{this->z = z;}
double Coord::sqrdist (const Coord & a) const [inline]
Returns distance^2 to Coord a (omits square root). Does not check for dimension compatibility!
Definition at line 239 of file Coord.h.
References squareLength().
Referenced by SimplePathlossModel::calcPathloss(), SimplePathlossModel::filterSignal(), and BaseConnectionManager::updateNicConnections().
{
        Coord dist=*this-a;
        return dist.squareLength();
    }
double Coord::sqrTorusDist (const Coord & b, const Coord & playgroundSize) const
Returns the squared distance on a torus to Coord a (omits square root).
Does not check for dimension compatibility!
Definition at line 11 of file Coord.cc.
References x, y, and z.
Referenced by SimplePathlossModel::calcPathloss(), SimplePathlossModel::filterSignal(), and BaseConnectionManager::updateNicConnections().
{
    double xDist = fabs(x - b.x);
    double yDist = fabs(y - b.y);
    double zDist = fabs(z - b.z);
    /*
     * on a torus the end and the begin of the axes are connected so you
     * get a circle. On a circle the distance between two points can't be greater
     * than half of the circumference.
     * If the normal distance between two points on one axis is bigger than
     * half of the playground there must be a "shorter way" over the playground
     * border on this axis
     */
    if(xDist * 2.0 > playgroundSize.x)
    {
        xDist = playgroundSize.x - xDist;
    }
    //same for y- and z-coordinate
    if(yDist * 2.0 > playgroundSize.y)
    {
      yDist = playgroundSize.y - yDist;
    }
    if(zDist * 2.0 > playgroundSize.z)
    {
      zDist = playgroundSize.z - zDist;
    }
    return xDist * xDist + yDist * yDist + zDist * zDist;
}
double Coord::squareLength () const [inline]
Returns the square of the length of this coords position vector
Definition at line 254 of file Coord.h.
References x, y, and z.
Referenced by length(), and sqrdist().
    {
        return x * x + y * y + z * z;
    }
Friends And Related Function Documentation
bool operator!= (const Coord & a, const Coord & b) [friend]
Tests whether two coordinate vectors are not equal. Negation of the operator==.
Does not check for dimension compatibility!
Definition at line 222 of file Coord.h.
{
        return !(a==b);
    }
Coord operator* (const Coord & a, double f) [friend]
Multiplies a coordinate vector by a real number.
Definition at line 138 of file Coord.h.
{
    Coord tmp = a;
    tmp *= f;
        return tmp;
    }
Coord operator+ (const Coord & a, const Coord & b) [friend]
Adds two coordinate vectors. Does not check for dimension compatibility!
Definition at line 121 of file Coord.h.
{
        Coord tmp = a;
        tmp += b;
        return tmp;
    }
Coord operator- (const Coord & a, const Coord & b) [friend]
Subtracts two coordinate vectors. Does not check for dimension compatibility!
Definition at line 131 of file Coord.h.
{
        Coord tmp = a;
        tmp -= b;
        return tmp;
    }
Coord operator/ (const Coord & a, double f) [friend]
Divides a coordinate vector by a real number.
Definition at line 145 of file Coord.h.
{
    Coord tmp = a;
    tmp /= f;
        return tmp;
    }
bool operator< (const Coord & a, const Coord & b) [friend]
Tests whether this coordinate vector is strictly smaller than another coordinate vector.
Definition at line 381 of file Coord.h.
{
  return (a.x < b.x &&
    a.y < b.y &&
    (a.is3D() ? a.z < b.z : true));
    }
bool operator== (const Coord & a, const Coord & b) [friend]
Tests whether two coordinate vectors are equal. Because coordinates are of type double, this is done through the FWMath::close function.
Does not check for dimension compatibility!
Definition at line 212 of file Coord.h.
{
        return FWMath::close(a.x, b.x) && FWMath::close(a.y, b.y) && FWMath::close(a.z, b.z);
    }
bool operator> (const Coord & a, const Coord & b) [friend]
Tests whether this coordinate vector is strictly larger than another coordinate vector.
Definition at line 371 of file Coord.h.
{
  return (a.x > b.x &&
    a.y > b.y &&
    (a.is3D() ? a.z > b.z : true));
    }
Member Data Documentation
const double Coord::UNDEFINED = 0.0 [static]
Definition at line 64 of file Coord.h.
Referenced by Coord(), and isValid().
bool Coord::use2DFlag [protected]
Definition at line 70 of file Coord.h.
Referenced by info(), is2D(), is3D(), isInRectangle(), isValid(), and operator=().
double Coord::x [protected]
x and y coordinates of the position
Definition at line 68 of file Coord.h.
Referenced by getX(), info(), isInRectangle(), max(), min(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), sqrTorusDist(), and squareLength().
double Coord::y [protected]
Definition at line 68 of file Coord.h.
Referenced by getY(), info(), isInRectangle(), max(), min(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), sqrTorusDist(), and squareLength().
double Coord::z [protected]
Definition at line 68 of file Coord.h.
Referenced by Coord(), getZ(), info(), isInRectangle(), isValid(), max(), min(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), sqrTorusDist(), and squareLength().
The documentation for this class was generated from the following files:
base/utils/Coord.h
base/utils/Coord.cc