MiXiM: ChannelInfo Class Reference
ChannelInfo Class Reference
[phyLayer - physical layer modules]
This class is used by the BasePhyLayer to keep track of the AirFrames on the channel.
#include <ChannelInfo.h>
Classes
class BaseIntersectionIterator
Iterator for every intersection of a specific interval in a AirFrameMatrix.
class IntersectionIterator
Public Types
typedef std::vector< AirFrame * > AirFrameVector
Public Member Functions
void addAirFrame (AirFrame *a, simtime_t startTime)
Tells the ChannelInfo that an AirFrame has started.
simtime_t removeAirFrame (AirFrame *a)
Tells the ChannelInfo that an AirFrame is over.
void getAirFrames (simtime_t from, simtime_t to, AirFrameVector &out) const
Fills the passed AirFrameVector reference with the AirFrames which intersect with the given time interval.
simtime_t getEarliestInfoPoint ()
Returns the current time-point from that information concerning AirFrames is needed to be stored.
Protected Types
typedef std::pair< simtime_t,
AirFrame * > AirFrameTimePair
typedef std::list
< AirFrameTimePair > AirFrameTimeList
typedef std::map< simtime_t,
AirFrameTimeList > AirFrameMatrix
typedef
BaseIntersectionIterator
< const AirFrameMatrix,
AirFrameMatrix::const_iterator,
AirFrameTimeList::const_iterator > ConstIntersectionIterator
typedef std::map< AirFrame
*, simtime_t > AirFrameStartMap
Protected Member Functions
void getIntersections (const AirFrameMatrix &airFrames, simtime_t from, simtime_t to, AirFrameVector &outVector) const
Returns every AirFrame of an AirFrameMatrix which intersect with a given interval.
bool isIntersecting (const AirFrameMatrix &airFrames, simtime_t from, simtime_t to) const
Returns true if there is at least one AirFrame in the passed AirFrameMatrix which intersect with the given interval.
void addToInactives (AirFrame *a, simtime_t startTime, simtime_t endTime)
Moves an previously active AirFrame to the inactives.
void deleteAirFrame (AirFrameMatrix &airFrames, AirFrame *a, simtime_t startTime, simtime_t endTime)
Protected Attributes
AirFrameMatrix activeAirFrames
Stores the currently active AirFrames.
AirFrameMatrix inactiveAirFrames
Stores inactive AirFrames.
AirFrameStartMap airFrameStarts
Stores the start time of every AirFrame.
simtime_t earliestInfoPoint
Stores the earliest time-point we need to keep information for.
Detailed Description
This class is used by the BasePhyLayer to keep track of the AirFrames on the channel.
ChannelInfo is able to return every AirFrame which intersects with a specified interval. This is mainly used to get the noise for a received signal.
ChannelInfo is a passive class meaning the user has to tell it when a new AirFrame starts and an existing ends.
Once an AirFrame has been added to the ChannelInfo the ChannelInfo holds the ownership of this AirFrame even if the AirFrame is removed again from the ChannelInfo. This is necessary because the ChannelInfo has to be able to store also the AirFrames which are over but still intersect with an currently running AirFrame.
Note: ChannelInfo assumes that the AirFrames are added and removed chronologically. This means every time you add an AirFrame with a specific start time ChannelInfo assumes that start time as the current time and assumes that every following action happens after that moment. The same goes for "removeAirFrame". When removing an AirFrames, ChannelInfo assumes the start time plus the duration of the AirFrame as the current time. This also affects "getAirFrames" in the way that you may only ask for intervals which lie before the "current time" of ChannelInfo.
Definition at line 41 of file ChannelInfo.h.
Member Typedef Documentation
typedef std::map<simtime_t, AirFrameTimeList > ChannelInfo::AirFrameMatrix [protected]
The AirFrames are stored in a Matrix with start- and end time as dimensions.
Definition at line 52 of file ChannelInfo.h.
typedef std::map<AirFrame*, simtime_t> ChannelInfo::AirFrameStartMap [protected]
Definition at line 177 of file ChannelInfo.h.
typedef std::list<AirFrameTimePair> ChannelInfo::AirFrameTimeList [protected]
Definition at line 47 of file ChannelInfo.h.
typedef std::pair<simtime_t, AirFrame*> ChannelInfo::AirFrameTimePair [protected]
Definition at line 46 of file ChannelInfo.h.
typedef std::vector<AirFrame*> ChannelInfo::AirFrameVector
Definition at line 191 of file ChannelInfo.h.
typedef BaseIntersectionIterator<const AirFrameMatrix, AirFrameMatrix::const_iterator, AirFrameTimeList::const_iterator> ChannelInfo::ConstIntersectionIterator [protected]
Definition at line 120 of file ChannelInfo.h.
Member Function Documentation
void ChannelInfo::addAirFrame (AirFrame * a, simtime_t startTime)
Tells the ChannelInfo that an AirFrame has started.
From this point ChannelInfo gets the ownership of the AirFrame.
parameter startTime holds the time the receiving of the AirFrame has started in seconds.
Definition at line 6 of file ChannelInfo.cc.
References activeAirFrames, and airFrameStarts.
Referenced by BasePhyLayer::handleAirFrameStartReceive().
{
  //calculate endTime of AirFrame
  simtime_t endTime = startTime + a->getDuration();
  //add AirFrame to active AirFrames
  activeAirFrames[endTime].push_back(AirFrameTimePair(startTime, a));
  //add to start time map
  airFrameStarts[a] = startTime;
}
void ChannelInfo::addToInactives (AirFrame * a, simtime_t startTime, simtime_t endTime) [protected]
Moves an previously active AirFrame to the inactives.
This methods checks if there are some inactive AirFrames which can be deleted because the AirFrame to inactivate was the last one they intersected with. It also checks if the AirFrame do inactivate still intersect with at least one active AirFrame before it is moved to inactived AirFrames.
Definition at line 92 of file ChannelInfo.cc.
References activeAirFrames, airFrameStarts, ChannelInfo::ChannelInfo::IntersectionIterator::eraseAirFrame(), inactiveAirFrames, isIntersecting(), and ChannelInfo::ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >::next().
Referenced by removeAirFrame().
{
  //At first, check if some inactives can be removed because the
  //AirFrame to deactivate was the last one they intersected
  //with.
  //get through inactive AirFrame which intersected with the
  //AirFrame to deactivate (only these AirFrames could be
  //possibly deleted
  IntersectionIterator inactiveIntersectIt(&inactiveAirFrames, startTime, endTime);
  AirFrame* inactiveIntersect = inactiveIntersectIt.next();
  while(inactiveIntersect != 0) {
    simtime_t currentStart = airFrameStarts[inactiveIntersect];
    simtime_t currentEnd = currentStart + inactiveIntersect->getDuration();
    //std::cerr << "Found intersecting with to inactive " << currentStart << std::endl;
    //check if this AirFrame still intersects with at least one active AirFrame
    if(!isIntersecting(activeAirFrames, currentStart, currentEnd)) {
      inactiveIntersectIt.eraseAirFrame();
      //std::cerr << "Doesn't intersect with any active frame anymore -> delete" << std::endl;
      airFrameStarts.erase(inactiveIntersect);
      delete inactiveIntersect;
      inactiveIntersect = 0;
    }
    inactiveIntersect = inactiveIntersectIt.next();
  }
  //at last check if the AirFrame to deactivate still intersects with
  //at least one active AirFrame. If so, add it to the inactive list.
  if(isIntersecting(activeAirFrames, startTime, endTime)) {
    //std::cerr << "Removed AirFrame still intersects with at least one active." << std::endl;
    inactiveAirFrames[endTime].push_back(AirFrameTimePair(startTime, a));
  } else {
    //std::cerr << "Removed AirFrame can be removed." << std::endl;
    airFrameStarts.erase(a);
    delete a;
  }
}
void ChannelInfo::deleteAirFrame (AirFrameMatrix & airFrames, AirFrame * a, simtime_t startTime, simtime_t endTime) [protected]
Definition at line 70 of file ChannelInfo.cc.
Referenced by removeAirFrame().
{
  AirFrameMatrix::iterator listIt = airFrames.find(endTime);
  AirFrameTimeList* list = &listIt->second;
  for(AirFrameTimeList::iterator it = list->begin();
       it != list->end(); it++) {
    if(it->second == a) {
      it = list->erase(it);
      //std::cerr << "Erased AirFrame with start " << startTime << std::endl;
      if(list->empty()) {
        airFrames.erase(listIt);
        //std::cerr << "Was last one in list." << std::endl;
      }
      return;
    }
  }
  assert(false);
}
void ChannelInfo::getAirFrames (simtime_t from, simtime_t to, AirFrameVector & out) const
Fills the passed AirFrameVector reference with the AirFrames which intersect with the given time interval.
Note: Completeness of the list of AirFrames for specific interval can only be assured if start and end point of the interval lies inside the duration of at least one currently active AirFrame. An AirFrame is called active if it has been added but not yet removed from ChannelInfo.
Definition at line 159 of file ChannelInfo.cc.
References activeAirFrames, getIntersections(), and inactiveAirFrames.
Referenced by BasePhyLayer::getChannelInfo().
{
  //check for intersecting inactive AirFrames
  getIntersections(inactiveAirFrames, from, to, out);
  //check for intersecting active AirFrames
  getIntersections(activeAirFrames, from, to, out);
}
simtime_t ChannelInfo::getEarliestInfoPoint () [inline]
Returns the current time-point from that information concerning AirFrames is needed to be stored.
Definition at line 274 of file ChannelInfo.h.
References earliestInfoPoint.
Referenced by BasePhyLayer::handleAirFrameEndReceive().
  {
    return earliestInfoPoint;
  }
void ChannelInfo::getIntersections (const AirFrameMatrix & airFrames, simtime_t from, simtime_t to, AirFrameVector & outVector) const [protected]
Returns every AirFrame of an AirFrameMatrix which intersect with a given interval.
The intersecting AirFrames are stored in the AirFrameVector reference passed as parameter.
Definition at line 146 of file ChannelInfo.cc.
References ChannelInfo::ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >::next().
Referenced by getAirFrames().
{
  ConstIntersectionIterator it(&airFrames, from, to);
  AirFrame* intersect = it.next();
  while(intersect != 0) {
    outVector.push_back(intersect);
    intersect = it.next();
  }
}
bool ChannelInfo::isIntersecting (const AirFrameMatrix & airFrames, simtime_t from, simtime_t to) const [protected]
Returns true if there is at least one AirFrame in the passed AirFrameMatrix which intersect with the given interval.
Definition at line 139 of file ChannelInfo.cc.
References ChannelInfo::ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >::next().
Referenced by addToInactives().
{
  ConstIntersectionIterator it(&airFrames, from, to);
  return (it.next() != 0);
}
simtime_t ChannelInfo::removeAirFrame (AirFrame * a)
Tells the ChannelInfo that an AirFrame is over.
This does not mean that in looses ownership of the AirFrame.
Returns:
The current time-point from that information concerning AirFrames is needed to be stored.
Definition at line 18 of file ChannelInfo.cc.
References activeAirFrames, addToInactives(), airFrameStarts, deleteAirFrame(), and earliestInfoPoint.
Referenced by BasePhyLayer::handleAirFrameEndReceive().
{
  //get start of AirFrame
  simtime_t startTime = airFrameStarts[a];
  //calculate end time
  simtime_t endTime = startTime + a->getDuration();
  //remove this AirFrame from active AirFrames
  deleteAirFrame(activeAirFrames, a, startTime, endTime);
  //add to inactive AirFrames
  addToInactives(a, startTime, endTime);
  /*
   * Now check, whether the earliest time-point we need to store information for
   * might have moved on in time, since an AirFrame has been deleted.
   *
   * TODO: check for a more efficient way to find out that earliest time-point
   */
  // make a variable for the earliest-start-time of all remaining AirFrames
  simtime_t earliestStart = 0;
  AirFrameStartMap::const_iterator it = airFrameStarts.begin();
  // if there is an entry for an AirFrame
  if (it != airFrameStarts.end())
  {
    // store the start-time of the first entry as earliestStart so far
    earliestStart = (*it).second;
    // go through all other start-time-points
    for (; it != airFrameStarts.end(); ++it)
    {
      // and check if an earlier start-time was found,
      // if so, replace earliestStart with it
      if( (*it).second < earliestStart )
        earliestStart = (*it).second;
    }
    // check if the current earliest-start-time is later than the stored
    // value so far, if so, replace the earliestInfoPoint
    if ( earliestStart > earliestInfoPoint )
      earliestInfoPoint = earliestStart;
  }
  //std::cerr << "remove";
  return earliestInfoPoint;
}
Member Data Documentation
AirFrameMatrix ChannelInfo::activeAirFrames [protected]
Stores the currently active AirFrames.
This means every AirFrame which was added but not yet removed.
Definition at line 167 of file ChannelInfo.h.
Referenced by addAirFrame(), addToInactives(), getAirFrames(), and removeAirFrame().
AirFrameStartMap ChannelInfo::airFrameStarts [protected]
Stores the start time of every AirFrame.
Definition at line 182 of file ChannelInfo.h.
Referenced by addAirFrame(), addToInactives(), and removeAirFrame().
simtime_t ChannelInfo::earliestInfoPoint [protected]
Stores the earliest time-point we need to keep information for.
Definition at line 187 of file ChannelInfo.h.
Referenced by getEarliestInfoPoint(), and removeAirFrame().
AirFrameMatrix ChannelInfo::inactiveAirFrames [protected]
Stores inactive AirFrames.
This means every AirFrame which has been already removed but still is needed because it intersect with one or more active AirFrames.
Definition at line 175 of file ChannelInfo.h.
Referenced by addToInactives(), and getAirFrames().
The documentation for this class was generated from the following files:
base/phyLayer/ChannelInfo.h
base/phyLayer/ChannelInfo.cc