MiXiM: BasePhyLayer Class Reference
BasePhyLayer Class Reference
[phyLayer - physical layer modules, baseModules - base module classes of MiXiM]
The BasePhyLayer represents the physical layer of a nic.
#include <BasePhyLayer.h>
Inherits ChannelAccess, DeciderToPhyInterface, and MacToPhyInterface.
Inherited by PhyLayer.
Public Member Functions
BasePhyLayer ()
virtual ~BasePhyLayer ()
virtual int getRadioState ()
Returns the current state the radio is in.
virtual simtime_t setRadioState (int rs)
Tells the BasePhyLayer to switch to the specified radio state.
virtual ChannelState getChannelState ()
Returns the current state of the channel.
virtual void getChannelInfo (simtime_t from, simtime_t to, AirFrameVector &out)
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
virtual ConstMapping * getThermalNoise (simtime_t from, simtime_t to)
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
virtual void sendControlMsg (cMessage *msg)
Called by the Decider to send a control message to the MACLayer.
virtual void sendUp (AirFrame *packet, DeciderResult *result)
Called to send an AirFrame with DeciderResult to the MACLayer.
virtual simtime_t getSimTime ()
Returns the current simulation time.
virtual void cancelScheduledMessage (cMessage *msg)
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
virtual void drawCurrent (double amount, int activity)
Does nothing. For an actual power supporting phy see "PhyLayerBattery".
Protected Types
enum AirFrameStates { START_RECEIVE = 1, RECEIVING, END_RECEIVE }
typedef std::vector
< AnalogueModel * > AnalogueModelList
Used to store the AnalogueModels to be used as filters.
typedef std::map< std::string,
cMsgPar > ParameterMap
Used at initialisation to pass the parameters to the AnalogueModel and Decider.
Protected Member Functions
virtual void initialize (int stage)
OMNeT++ initialization function. Read simple parameters. Read and parse xml file for decider and analogue models configuration.
virtual void handleMessage (cMessage *msg)
OMNeT++ handle message function.
virtual AnalogueModel * getAnalogueModelFromName (std::string name, ParameterMap &params)
Creates and returns an instance of the AnalogueModel with the specified name.
virtual Decider * getDeciderFromName (std::string name, ParameterMap &params)
Creates and returns an instance of the Decider with the specified name.
virtual void handleAirFrame (cMessage *msg)
Handles messages received from the channel (probably AirFrames).
virtual void handleUpperMessage (cMessage *msg)
Handles messages received from the upper layer through the data gate.
virtual void handleUpperControlMessage (cMessage *msg)
Handles messages received from the upper layer through the control gate.
virtual void handleSelfMessage (cMessage *msg)
Handles self scheduled messages.
virtual void handleChannelSenseRequest (cMessage *msg)
Handles reception of a ChannelSenseRequest by forwarding it to the decider and scheduling it to the point in time returned by the decider.
void handleAirFrameFirstReceive (AirFrame *msg)
Handles incoming AirFrames with the state FIRST_RECEIVE.
void handleAirFrameStartReceive (AirFrame *msg)
Handles incoming AirFrames with the state START_RECEIVE.
void handleAirFrameReceiving (AirFrame *msg)
Handles incoming AirFrames with the state RECEIVING.
void handleAirFrameEndReceive (AirFrame *msg)
Handles incoming AirFrames with the state END_RECEIVE.
void sendControlMessageUp (cMessage *msg)
Sends the passed control message to the upper layer.
void sendMacPktUp (cMessage *pkt)
Sends the passed MacPkt to the upper layer.
void sendMessageDown (AirFrame *pkt)
Sends the passed AirFrame to the channel.
void sendSelfMessage (cMessage *msg, simtime_t time)
Schedule self message to passed point in time.
AirFrame * encapsMsg (cPacket *msg)
This function encapsulates messages from the upper layer into an AirFrame and sets all necessary attributes.
void filterSignal (Signal &s)
Filters the passed Signal by every registered AnalogueModel.
void finishRadioSwitching ()
Called the moment the simulated switching process of the Radio is finished.
Protected Attributes
ConstantSimpleConstMapping * thermalNoise
Defines the strength of the thermal noise.
double maxTXPower
The maximum transmission power a message can be send with.
double sensitivity
The sensitivity describes the minimum strength a signal must have to be received.
ChannelInfo channelInfo
Channel info keeps track of received AirFrames and provides information about currently active AirFrames at the channel.
Radio * radio
The state machine storing the current radio state (TX, RX, SLEEP).
Decider * decider
Pointer to the decider module.
AnalogueModelList analogueModels
List of the analogue models to use.
int upperGateIn
The id of the in-data gate from the Mac layer.
int upperGateOut
The id of the out-data gate to the Mac layer.
int upperControlOut
The id of the out-control gate to the Mac layer.
int upperControlIn
The id of the in-control gate from the Mac layer.
cMessage * radioSwitchingOverTimer
Self message scheduled to the point in time when the switching process of the radio is over.
cMessage * txOverTimer
Self message scheduled to the point in time when the transmission of an AirFrame is over.
int headerLength
Stores the length of the phy header in bits.
BaseWorldUtility * world
Private Member Functions
void getParametersFromXML (cXMLElement *xmlData, ParameterMap &outputMap)
Utility function. Reads the parameters of a XML element and stores them in the passed ParameterMap reference.
void initializeAnalogueModels (cXMLElement *xmlConfig)
Initializes the AnalogueModels with the data from the passed XML-config data.
void initializeDecider (cXMLElement *xmlConfig)
Initializes the Decider with the data from the passed XML-config data.
template<class T >
T readPar (const char *parName, const T defaultValue)
Reads and returns the parameter with the passed name.
Detailed Description
The BasePhyLayer represents the physical layer of a nic.
The BasePhyLayer is directly connected to the mac layer via OMNeT channels and is able to send messages to other physical layers through sub-classing from ChannelAcces.
The BasePhyLayer encapsulates two sub modules. The AnalogueModels, which are responsible for simulating the attenuation of received signals and the Decider which provides the main functionality of the physical layer like signal classification (noise or not noise) and demodulation (calculating transmission errors).
The BasePhyLayer itself is responsible for the OMNeT depended parts of the physical layer which are the following:
Module initialization:
read ned-parameters and initialize module, Decider and AnalogueModels.
Message handling:
receive messages from mac layer and hand them to the Decider or directly send them to the channel
receive AirFrames from the channel, hand them to the AnalogueModels for filtering, simulate delay and transmission duration, hand it to the Decider for evaluation and send received packets to the mac layer
keep track of currently active AirFrames on the channel (see ChannelInfo)
The actual evaluation of incoming signals is done by the Decider.
base class ChannelAccess:
provides access to the channel via the ConnectionManager
base class DeciderToPhyInterface:
interface for the Decider
base class MacToPhyInterface:
interface for the Mac
Definition at line 68 of file BasePhyLayer.h.
Member Typedef Documentation
typedef std::vector<AnalogueModel*> BasePhyLayer::AnalogueModelList [protected]
Used to store the AnalogueModels to be used as filters.
Definition at line 96 of file BasePhyLayer.h.
typedef std::map<std::string, cMsgPar> BasePhyLayer::ParameterMap [protected]
Used at initialisation to pass the parameters to the AnalogueModel and Decider.
Definition at line 105 of file BasePhyLayer.h.
Member Enumeration Documentation
enum BasePhyLayer::AirFrameStates [protected]
Enumerator:
START_RECEIVE Start of actual receiving process of the AirFrame.
RECEIVING AirFrame is being received.
END_RECEIVE Receiving process over.
Definition at line 128 of file BasePhyLayer.h.
                      {
    START_RECEIVE = 1,
    RECEIVING,
    END_RECEIVE
  };
Constructor & Destructor Documentation
BasePhyLayer::BasePhyLayer ()
Definition at line 15 of file BasePhyLayer.cc.
                          :
  thermalNoise(0),
  radio(0),
  decider(0),
  radioSwitchingOverTimer(0),
  txOverTimer(0),
  world(0)
{}
BasePhyLayer::~BasePhyLayer () [virtual]
Free the pointer to the decider and the AnalogueModels and the Radio.
Definition at line 592 of file BasePhyLayer.cc.
References analogueModels, decider, Radio::getAnalogueModel(), radio, radioSwitchingOverTimer, thermalNoise, and txOverTimer.
{
  //free timer messages
  //TOPROFILE: check BasePhy destruction for memory leaks
  if(txOverTimer) {
        if(txOverTimer->isScheduled())
            cancelEvent(txOverTimer);
    delete txOverTimer;
  }
  if(radioSwitchingOverTimer) {
        if(radioSwitchingOverTimer->isScheduled())
            cancelEvent(radioSwitchingOverTimer);
    delete radioSwitchingOverTimer;
  }
  //free thermal noise mapping
  if(thermalNoise) {
    delete thermalNoise;
  }
  //free Decider
  if(decider != 0) {
    delete decider;
  }
  /*
   * get a pointer to the radios RSAM again to avoid deleting it,
   * it is not created by calling new (BasePhyLayer is not the owner)!
   */
  AnalogueModel* rsamPointer = radio->getAnalogueModel();
  //free AnalogueModels
  for(AnalogueModelList::iterator it = analogueModels.begin();
    it != analogueModels.end(); it++) {
    AnalogueModel* tmp = *it;
    // do not delete the RSAM, it's not allocated by new!
    if (tmp == rsamPointer)
    {
      rsamPointer = 0;
      continue;
    }
    if(tmp != 0) {
      delete tmp;
    }
  }
  // free radio
  if(radio != 0)
  {
    delete radio;
  }
}
Member Function Documentation
void BasePhyLayer::cancelScheduledMessage (cMessage * msg) [virtual]
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
Used by the Decider if it has to handle an AirFrame or an control message earlier than it has returned to the PhyLayer the last time the Decider handled that message.
Implements DeciderToPhyInterface.
Definition at line 734 of file BasePhyLayer.cc.
{
  if(msg->isScheduled()){
    cancelEvent(msg);
  } else {
    EV << "Warning: Decider wanted to cancel a scheduled message but message"
       << " wasn't actually scheduled. Message is: " << msg << endl;
  }
}
void BasePhyLayer::drawCurrent (double amount, int activity) [virtual]
Does nothing. For an actual power supporting phy see "PhyLayerBattery".
Implements DeciderToPhyInterface.
Definition at line 743 of file BasePhyLayer.cc.
Referenced by PhyLayerBattery::handleSelfMessage(), PhyLayerBattery::handleUpperMessage(), and PhyLayerBattery::initialize().
{
  BatteryAccess::drawCurrent(amount, activity);
}
AirFrame * BasePhyLayer::encapsMsg (cPacket * msg) [protected]
This function encapsulates messages from the upper layer into an AirFrame and sets all necessary attributes.
Definition at line 448 of file BasePhyLayer.cc.
References MacToPhyInterface::AIR_FRAME, Signal::getSignalLength(), BaseWorldUtility::getUniqueAirFrameId(), headerLength, ChannelAccess::move, MacToPhyControlInfo::retrieveSignal(), Signal::setMove(), and world.
Referenced by handleUpperMessage().
{
  // the cMessage passed must be a MacPacket... but no cast needed here
  // MacPkt* pkt = static_cast<MacPkt*>(msg);
  // ...and must always have a ControlInfo attached (contains Signal)
  cObject* ctrlInfo = macPkt->removeControlInfo();
  assert(ctrlInfo);
  MacToPhyControlInfo* macToPhyCI = static_cast<MacToPhyControlInfo*>(ctrlInfo);
  // Retrieve the pointer to the Signal-instance from the ControlInfo-instance.
  // We are now the new owner of this instance.
  Signal* s = macToPhyCI->retrieveSignal();
  // delete the Control info
  delete macToPhyCI;
  macToPhyCI = 0;
  ctrlInfo = 0;
  // make sure we really obtained a pointer to an instance
  assert(s);
  // put host move pattern to Signal
  s->setMove(move);
  // create the new AirFrame
  AirFrame* frame = new AirFrame(0, AIR_FRAME);
  // set the members
  assert(s->getSignalLength() > 0);
  frame->setDuration(s->getSignalLength());
  // copy the signal into the AirFrame
  frame->setSignal(*s);
  frame->setBitLength(headerLength);
  // pointer and Signal not needed anymore
  delete s;
  s = 0;
  frame->setId(world->getUniqueAirFrameId());
  frame->encapsulate(macPkt);
  // --- from here on, the AirFrame is the owner of the MacPacket ---
  macPkt = 0;
  EV <<"AirFrame encapsulated, length: " << frame->getBitLength() << "\n";
  return frame;
}
void BasePhyLayer::filterSignal (Signal & s) [protected]
Filters the passed Signal by every registered AnalogueModel.
Definition at line 581 of file BasePhyLayer.cc.
References analogueModels, and AnalogueModel::filterSignal().
Referenced by handleAirFrameStartReceive().
{
  for(AnalogueModelList::const_iterator it = analogueModels.begin();
    it != analogueModels.end(); it++) {
    AnalogueModel* tmp = *it;
    tmp->filterSignal(s);
  }
}
void BasePhyLayer::finishRadioSwitching () [protected]
Called the moment the simulated switching process of the Radio is finished.
The Radio is set the new RadioState and the MAC Layer is sent a confirmation message.
Definition at line 657 of file BasePhyLayer.cc.
References Radio::endSwitch(), radio, MacToPhyInterface::RADIO_SWITCHING_OVER, and sendControlMsg().
Referenced by handleSelfMessage(), and setRadioState().
{
  radio->endSwitch(simTime());
  sendControlMsg(new cMessage("Radio switching over", RADIO_SWITCHING_OVER));
}
AnalogueModel * BasePhyLayer::getAnalogueModelFromName (std::string name, ParameterMap & params) [protected, virtual]
Creates and returns an instance of the AnalogueModel with the specified name.
The returned AnalogueModel has to be generated with the "new" command. The BasePhyLayer keeps the ownership of the returned AnalogueModel.
This method is used by the BasePhyLayer during initialisation to load the AnalogueModels which has been specified in the ned file.
This method has to be overridden if you want to be able to load your own AnalogueModels.
Reimplemented in SamplePhyLayer, and PhyLayer.
Definition at line 278 of file BasePhyLayer.cc.
References Radio::getAnalogueModel(), and radio.
Referenced by initializeAnalogueModels().
{
  // add default analogue models here
  // case "RSAM", pointer is valid as long as the radio exists
  if (name == "RadioStateAnalogueModel")
  {
    return radio->getAnalogueModel();
  }
  return 0;
}
void BasePhyLayer::getChannelInfo (simtime_t from, simtime_t to, AirFrameVector & out) [virtual]
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
Implements DeciderToPhyInterface.
Definition at line 699 of file BasePhyLayer.cc.
References channelInfo, and ChannelInfo::getAirFrames().
{
  channelInfo.getAirFrames(from, to, out);
}
ChannelState BasePhyLayer::getChannelState () [virtual]
Returns the current state of the channel.
See ChannelState for details.
Implements MacToPhyInterface.
Definition at line 691 of file BasePhyLayer.cc.
References decider, and Decider::getChannelState().
{
  Enter_Method_Silent();
  assert(decider);
  return decider->getChannelState();
}
Decider * BasePhyLayer::getDeciderFromName (std::string name, ParameterMap & params) [protected, virtual]
Creates and returns an instance of the Decider with the specified name.
The returned Decider has to be generated with the "new" command. The BasePhyLayer keeps the ownership of the returned Decider.
This method is used by the BasePhyLayer during initialisation to load the Decider which has been specified in the ned file.
This method has to be overridden if you want to be able to load your own Decider.
Reimplemented in SamplePhyLayer, PhyLayer, and PhyLayerBattery.
Definition at line 205 of file BasePhyLayer.cc.
Referenced by initializeDecider().
{
  return 0;
}
void BasePhyLayer::getParametersFromXML (cXMLElement * xmlData, ParameterMap & outputMap) [private]
Utility function. Reads the parameters of a XML element and stores them in the passed ParameterMap reference.
Definition at line 117 of file BasePhyLayer.cc.
Referenced by initializeAnalogueModels(), and initializeDecider().
{
  cXMLElementList parameters = xmlData->getElementsByTagName("Parameter");
  for(cXMLElementList::const_iterator it = parameters.begin();
    it != parameters.end(); it++) {
    const char* name = (*it)->getAttribute("name");
    const char* type = (*it)->getAttribute("type");
    const char* value = (*it)->getAttribute("value");
    if(name == 0 || type == 0 || value == 0) {
      ev << "Invalid parameter, could not find name, type or value." << endl;
      continue;
    }
    std::string sType = type;   //needed for easier comparision
    std::string sValue = value; //needed for easier comparision
    cMsgPar param(name);
    //parse type of parameter and set value
    if (sType == "bool") {
      param.setBoolValue(sValue == "true" || sValue == "1");
    } else if (sType == "double") {
      param.setDoubleValue(strtod(value, 0));
    } else if (sType == "string") {
      param.setStringValue(value);
    } else if (sType == "long") {
      param.setLongValue(strtol(value, 0, 0));
    } else {
      ev << "Unknown parameter type: \"" << sType << "\"" << endl;
      continue;
    }
    //add parameter to output map
    outputMap[name] = param;
  }
}
int BasePhyLayer::getRadioState () [virtual]
Returns the current state the radio is in.
See RadioState for possible values.
This method is mainly used by the mac layer.
Implements MacToPhyInterface.
Definition at line 651 of file BasePhyLayer.cc.
References Radio::getCurrentState(), and radio.
{
  Enter_Method_Silent();
  assert(radio);
  return radio->getCurrentState();
}
simtime_t BasePhyLayer::getSimTime () [virtual]
Returns the current simulation time.
Implements DeciderToPhyInterface.
Definition at line 729 of file BasePhyLayer.cc.
{
  return simTime();
}
ConstMapping * BasePhyLayer::getThermalNoise (simtime_t from, simtime_t to) [virtual]
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
The implementing class of this method keeps ownership of the Mapping.
This implementation returns a constant mapping with the value of the "thermalNoise" module parameter
Override this method if you want to define a more complex thermal noise.
Implements DeciderToPhyInterface.
Definition at line 703 of file BasePhyLayer.cc.
References SimpleConstMapping::initializeArguments(), and thermalNoise.
{
  if(thermalNoise)
    thermalNoise->initializeArguments(Argument(from));
  return thermalNoise;
}
void BasePhyLayer::handleAirFrame (cMessage * msg) [protected, virtual]
Handles messages received from the channel (probably AirFrames).
Reimplemented in PhyLayerBattery.
Definition at line 320 of file BasePhyLayer.cc.
References END_RECEIVE, handleAirFrameEndReceive(), handleAirFrameReceiving(), handleAirFrameStartReceive(), RECEIVING, and START_RECEIVE.
Referenced by handleMessage(), and handleSelfMessage().
{
  AirFrame* frame = static_cast<AirFrame*>(msg);
  switch(frame->getState()) {
  case START_RECEIVE:
    handleAirFrameStartReceive(frame);
    break;
  case RECEIVING: {
    handleAirFrameReceiving(frame);
    break;
  }
  case END_RECEIVE:
    handleAirFrameEndReceive(frame);
    break;
  default:
    opp_error( "Unknown AirFrame state: %s", frame->getState());
    break;
  }
}
void BasePhyLayer::handleAirFrameEndReceive (AirFrame * msg) [protected]
Handles incoming AirFrames with the state END_RECEIVE.
Definition at line 404 of file BasePhyLayer.cc.
References channelInfo, Radio::cleanAnalogueModelUntil(), coreEV, ChannelInfo::getEarliestInfoPoint(), radio, and ChannelInfo::removeAirFrame().
Referenced by handleAirFrame(), and handleAirFrameReceiving().
{
  coreEV << "End of Airframe with ID " << frame->getId() << "." << endl;
  channelInfo.removeAirFrame(frame);
  /* clean information in the radio until earliest time-point
  *  of information in the ChannelInfo,
  *  since this time-point might have changed due to removal of
  *  the AirFrame
  */
  radio->cleanAnalogueModelUntil(channelInfo.getEarliestInfoPoint());
}
void BasePhyLayer::handleAirFrameFirstReceive (AirFrame * msg) [protected]
Handles incoming AirFrames with the state FIRST_RECEIVE.
void BasePhyLayer::handleAirFrameReceiving (AirFrame * msg) [protected]
Handles incoming AirFrames with the state RECEIVING.
Definition at line 373 of file BasePhyLayer.cc.
References coreEV, decider, END_RECEIVE, Signal::getSignalLength(), Signal::getSignalStart(), handleAirFrameEndReceive(), Decider::processSignal(), and sendSelfMessage().
Referenced by handleAirFrame(), and handleAirFrameStartReceive().
{
  Signal& signal = frame->getSignal();
  simtime_t nextHandleTime = decider->processSignal(frame);
  assert(signal.getSignalLength() == frame->getDuration());
  simtime_t signalEndTime = signal.getSignalStart() + frame->getDuration();
  //check if this is the end of the receiving process
  if(simTime() >= signalEndTime) {
    frame->setState(END_RECEIVE);
    handleAirFrameEndReceive(frame);
    return;
  }
  //smaller zero means don't give it to me again
  if(nextHandleTime < 0) {
    nextHandleTime = signalEndTime;
    frame->setState(END_RECEIVE);
  //invalid point in time
  } else if(nextHandleTime < simTime() || nextHandleTime > signalEndTime) {
    opp_error("Invalid next handle time returned by Decider. Expected a value between current simulation time (%.2f) and end of signal (%.2f) but got %.2f",
                SIMTIME_DBL(simTime()), SIMTIME_DBL(signalEndTime), SIMTIME_DBL(nextHandleTime));
  }
  coreEV << "Handed AirFrame with ID " << frame->getId() << " to Decider. Next handling in " << nextHandleTime - simTime() << "s." << endl;
  sendSelfMessage(frame, nextHandleTime);
}
void BasePhyLayer::handleAirFrameStartReceive (AirFrame * msg) [protected]
Handles incoming AirFrames with the state START_RECEIVE.
Definition at line 343 of file BasePhyLayer.cc.
References ChannelInfo::addAirFrame(), channelInfo, coreEV, decider, END_RECEIVE, filterSignal(), Signal::getSignalStart(), handleAirFrameReceiving(), RECEIVING, sendSelfMessage(), Signal::setPropagationDelay(), and ChannelAccess::usePropagationDelay.
Referenced by handleAirFrame().
{
  coreEV << "Received new AirFrame with ID " << frame->getId() << " from channel" << endl;
  channelInfo.addAirFrame(frame, simTime());
  if(usePropagationDelay) {
    Signal& s = frame->getSignal();
    simtime_t delay = simTime() - s.getSignalStart();
    s.setPropagationDelay(delay);
  }
  assert(frame->getSignal().getSignalStart() == simTime());
  filterSignal(frame->getSignal());
  if(decider) {
    frame->setState(RECEIVING);
    //pass the AirFrame the first time to the Decider
    handleAirFrameReceiving(frame);
  //if no decider is defined we will schedule the message directly to its end
  } else {
    Signal& signal = frame->getSignal();
    simtime_t signalEndTime = signal.getSignalStart() + frame->getDuration();
    frame->setState(END_RECEIVE);
    sendSelfMessage(frame, signalEndTime);
  }
}
void BasePhyLayer::handleChannelSenseRequest (cMessage * msg) [protected, virtual]
Handles reception of a ChannelSenseRequest by forwarding it to the decider and scheduling it to the point in time returned by the decider.
Definition at line 499 of file BasePhyLayer.cc.
References decider, Decider::handleChannelSenseRequest(), and sendSelfMessage().
Referenced by handleSelfMessage(), and handleUpperControlMessage().
{
  ChannelSenseRequest* senseReq = static_cast<ChannelSenseRequest*>(msg);
  simtime_t nextHandleTime = decider->handleChannelSenseRequest(senseReq);
  if(nextHandleTime >= simTime()) { //schedule request for next handling
    sendSelfMessage(msg, nextHandleTime);
  } else if(nextHandleTime >= 0.0){
    opp_error("Next handle time of ChannelSenseRequest returned by the Decider is smaller then current simulation time: %.2f",
        SIMTIME_DBL(nextHandleTime));
  }
  // else, i.e. nextHandleTime < 0.0, the Decider doesn't want to handle
  // the request again
}
void BasePhyLayer::handleMessage (cMessage * msg) [protected, virtual]
OMNeT++ handle message function.
Classify and forward message to subroutines.
AirFrames from channel
self scheduled AirFrames
MacPackets from MAC layer
ControllMesasges from MAC layer
self messages like TX_OVER and RADIO_SWITCHED
Reimplemented in SamplePhyLayer.
Definition at line 295 of file BasePhyLayer.cc.
References MacToPhyInterface::AIR_FRAME, handleAirFrame(), handleSelfMessage(), handleUpperControlMessage(), handleUpperMessage(), upperControlIn, and upperGateIn.
{
  //self messages
  if(msg->isSelfMessage()) {
    handleSelfMessage(msg);
  //MacPkts <- MacToPhyControlInfo
  } else if(msg->getArrivalGateId() == upperGateIn) {
    handleUpperMessage(msg);
  //controlmessages
  } else if(msg->getArrivalGateId() == upperControlIn) {
    handleUpperControlMessage(msg);
  //AirFrames
  } else if(msg->getKind() == AIR_FRAME){
    handleAirFrame(msg);
  //unknown message
  } else {
    ev << "Unknown message received." << endl;
    delete msg;
  }
}
void BasePhyLayer::handleSelfMessage (cMessage * msg) [protected, virtual]
Handles self scheduled messages.
Reimplemented in PhyLayerBattery.
Definition at line 528 of file BasePhyLayer.cc.
References MacToPhyInterface::AIR_FRAME, MacToPhyInterface::CHANNEL_SENSE_REQUEST, finishRadioSwitching(), handleAirFrame(), handleChannelSenseRequest(), MacToPhyInterface::RADIO_SWITCHING_OVER, radioSwitchingOverTimer, sendControlMsg(), MacToPhyInterface::TX_OVER, and txOverTimer.
Referenced by handleMessage().
{
  switch(msg->getKind()) {
  //transmission over
  case TX_OVER:
    assert(msg == txOverTimer);
    sendControlMsg(new cMessage("Transmission over", TX_OVER));
    break;
  //radio switch over
  case RADIO_SWITCHING_OVER:
    assert(msg == radioSwitchingOverTimer);
    finishRadioSwitching();
    break;
  //AirFrame
  case AIR_FRAME:
    handleAirFrame(msg);
    break;
  //ChannelSenseRequest
  case CHANNEL_SENSE_REQUEST:
    handleChannelSenseRequest(msg);
    break;
  default:
    break;
  }
}
void BasePhyLayer::handleUpperControlMessage (cMessage * msg) [protected, virtual]
Handles messages received from the upper layer through the control gate.
Definition at line 516 of file BasePhyLayer.cc.
References MacToPhyInterface::CHANNEL_SENSE_REQUEST, and handleChannelSenseRequest().
Referenced by handleMessage().
{
  switch(msg->getKind()) {
  case CHANNEL_SENSE_REQUEST:
    handleChannelSenseRequest(msg);
    break;
  default:
    ev << "Received unknown control message from upper layer!" << endl;
    break;
  }
}
void BasePhyLayer::handleUpperMessage (cMessage * msg) [protected, virtual]
Handles messages received from the upper layer through the data gate.
Reimplemented in PhyLayerBattery.
Definition at line 417 of file BasePhyLayer.cc.
References encapsMsg(), Radio::getCurrentState(), radio, sendMessageDown(), sendSelfMessage(), Radio::TX, and txOverTimer.
Referenced by handleMessage().
{
  // check if Radio is in TX state
  if (radio->getCurrentState() != Radio::TX)
  {
        delete msg;
        msg = 0;
    opp_error("Error: message for sending received, but radio not in state TX");
  }
  // check if not already sending
  if(txOverTimer->isScheduled())
  {
        delete msg;
        msg = 0;
    opp_error("Error: message for sending received, but radio already sending");
  }
  // build the AirFrame to send
  assert(dynamic_cast<cPacket*>(msg) != 0);
  AirFrame* frame = encapsMsg(static_cast<cPacket*>(msg));
  // make sure there is no self message of kind TX_OVER scheduled
  // and schedule the actual one
  assert (!txOverTimer->isScheduled());
  sendSelfMessage(txOverTimer, simTime() + frame->getDuration());
  sendMessageDown(frame);
}
void BasePhyLayer::initialize (int stage) [protected, virtual]
OMNeT++ initialization function. Read simple parameters. Read and parse xml file for decider and analogue models configuration.
Reimplemented from ChannelAccess.
Reimplemented in SamplePhyLayer, and PhyLayerBattery.
Definition at line 31 of file BasePhyLayer.cc.
References FWMath::dBm2mW(), headerLength, initializeAnalogueModels(), initializeDecider(), maxTXPower, radio, MacToPhyInterface::RADIO_SWITCHING_OVER, radioSwitchingOverTimer, readPar(), Radio::RX, sensitivity, Radio::setSwitchTime(), Radio::SLEEP, thermalNoise, DimensionSet::timeDomain, Radio::TX, MacToPhyInterface::TX_OVER, txOverTimer, upperControlIn, upperControlOut, upperGateIn, upperGateOut, and world.
{
  ChannelAccess::initialize(stage);
  if (stage == 0) {
    // if using sendDirect, make sure that messages arrive without delay
    gate("radioIn")->setDeliverOnReceptionStart(true);
    //get gate ids
    upperGateIn = findGate("upperGateIn");
        upperGateOut = findGate("upperGateOut");
        upperControlOut = findGate("upperControlOut");
        upperControlIn = findGate("upperControlIn");
    //read simple ned-parameters
    //  - initialize basic parameters
        if(readPar("useThermalNoise", false)) {
      double thermalNoiseVal = FWMath::dBm2mW(readPar("thermalNoise", -999.0));
      thermalNoise = new ConstantSimpleConstMapping(DimensionSet::timeDomain,
                              thermalNoiseVal);
    } else {
      thermalNoise = 0;
    }
        headerLength = readPar("headerLength", 0);
    sensitivity = readPar("sensitivity", 0.0);
    sensitivity = FWMath::dBm2mW(sensitivity);
    maxTXPower = readPar("maxTXPower", 1.0);
    //  - initialize radio
    int initialRadioState = readPar("initalRadioState", (int) Radio::RX);
    double radioMinAtt = readPar("radioMinAtt", 1.0);
    double radioMaxAtt = readPar("radioMaxAtt", 0.0);
    radio = new Radio(initialRadioState, radioMinAtt, radioMaxAtt);
    //  - switch times to TX
    simtime_t rxToTX = readPar("timeRXToTX", 0.0);
    simtime_t sleepToTX = readPar("timeSleepToTX", 0.0);
    //if no RX to TX defined asume same time as sleep to TX
    radio->setSwitchTime(Radio::RX, Radio::TX, readPar("timeRXToTX", sleepToTX));
    //if no sleep to TX defined asume same time as RX to TX
    radio->setSwitchTime(Radio::SLEEP, Radio::TX, readPar("timeSleepToTX", rxToTX));
    //    - switch times to RX
    simtime_t txToRX = readPar("timeTXToRX", 0.0);
    simtime_t sleepToRX = readPar("timeSleepToRX", 0.0);
    //if no TX to RX defined asume same time as sleep to RX
    radio->setSwitchTime(Radio::TX, Radio::RX, readPar("timeTXToRX", sleepToRX));
    //if no sleep to RX defined asume same time as TX to RX
    radio->setSwitchTime(Radio::SLEEP, Radio::RX, readPar("timeSleepToRX", txToRX));
    //    - switch times to sleep
    simtime_t txToSleep = readPar("timeTXToSleep", 0.0);
    simtime_t rxToSleep = readPar("timeRXToSleep", 0.0);
    //if no TX to sleep defined asume same time as RX to sleep
    radio->setSwitchTime(Radio::TX, Radio::SLEEP, readPar("timeTXToSleep", rxToSleep));
    //if no RX to sleep defined asume same time as TX to sleep
    radio->setSwitchTime(Radio::RX, Radio::SLEEP, readPar("timeRXToSleep", txToSleep));
    // get pointer to the world module
    world = FindModule<BaseWorldUtility*>::findGlobalModule();
        if (world == NULL)
            throw cRuntimeError("Could not find BaseWorldUtility module");
  } else if (stage == 1){
    //read complex(xml) ned-parameters
    //  - analogue model parameters
    initializeAnalogueModels(readPar("analogueModels", (cXMLElement*)0));
    //  - decider parameters
    initializeDecider(readPar("decider", (cXMLElement*)0));
    //initialise timer messages
    radioSwitchingOverTimer = new cMessage("radio switching over", RADIO_SWITCHING_OVER);
    txOverTimer = new cMessage("transmission over", TX_OVER);
  }
}
void BasePhyLayer::initializeAnalogueModels (cXMLElement * xmlConfig) [private]
Initializes the AnalogueModels with the data from the passed XML-config data.
Definition at line 213 of file BasePhyLayer.cc.
References analogueModels, coreEV, getAnalogueModelFromName(), and getParametersFromXML().
Referenced by initialize().
{
  /*
  * first of all, attach the AnalogueModel that represents the RadioState
  * to the AnalogueModelList as first element.
  */
  std::string s("RadioStateAnalogueModel");
  ParameterMap p;
  AnalogueModel* newAnalogueModel = getAnalogueModelFromName(s, p);
  if(newAnalogueModel == 0)
  {
    opp_warning("Could not find an analogue model with the name \"%s\".", s.c_str());
  }
  analogueModels.push_back(newAnalogueModel);
  if(xmlConfig == 0) {
    opp_warning("No analogue models configuration file specified.");
    return;
  }
  cXMLElementList analogueModelList = xmlConfig->getElementsByTagName("AnalogueModel");
  if(analogueModelList.empty()) {
    opp_warning("No analogue models configuration found in configuration file.");
    return;
  }
  // iterate over all AnalogueModel-entries, get a new AnalogueModel instance and add
  // it to analogueModels
  for(cXMLElementList::const_iterator it = analogueModelList.begin();
    it != analogueModelList.end(); it++) {
    cXMLElement* analogueModelData = *it;
    const char* name = analogueModelData->getAttribute("type");
    if(name == 0) {
      opp_warning("Could not read name of analogue model.");
      continue;
    }
    ParameterMap params;
    getParametersFromXML(analogueModelData, params);
    AnalogueModel* newAnalogueModel = getAnalogueModelFromName(name, params);
    if(newAnalogueModel == 0) {
      opp_warning("Could not find an analogue model with the name \"%s\".", name);
      continue;
    }
    // attach the new AnalogueModel to the AnalogueModelList
    analogueModels.push_back(newAnalogueModel);
    coreEV << "AnalogueModel \"" << name << "\" loaded." << endl;
  } // end iterator loop
}
void BasePhyLayer::initializeDecider (cXMLElement * xmlConfig) [private]
Initializes the Decider with the data from the passed XML-config data.
Definition at line 162 of file BasePhyLayer.cc.
References coreEV, decider, getDeciderFromName(), and getParametersFromXML().
Referenced by initialize().
{
  decider = 0;
  if(xmlConfig == 0) {
    opp_error("No decider configuration file specified.");
    return;
  }
  cXMLElementList deciderList = xmlConfig->getElementsByTagName("Decider");
  if(deciderList.empty()) {
    opp_error("No decider configuration found in configuration file.");
    return;
  }
  if(deciderList.size() > 1) {
    opp_error("More than one decider configuration found in configuration file.");
    return;
  }
  cXMLElement* deciderData = deciderList.front();
  const char* name = deciderData->getAttribute("type");
  if(name == 0) {
    opp_error("Could not read type of decider from configuration file.");
    return;
  }
  ParameterMap params;
  getParametersFromXML(deciderData, params);
  decider = getDeciderFromName(name, params);
  if(decider == 0) {
    opp_error("Could not find a decider with the name \"%s\".", name);
    return;
  }
  coreEV << "Decider \"" << name << "\" loaded." << endl;
}
template<class T > T BasePhyLayer::readPar (const char * parName, const T defaultValue) [inline, private]
Reads and returns the parameter with the passed name.
If the parameter couldn't be found the value of defaultValue is returned.
Parameters:
parName - the name of the ned-parameter
defaultValue - the value to be returned if the parameter couldn't be found
Definition at line 24 of file BasePhyLayer.cc.
Referenced by initialize().
{
  if(hasPar(parName))
    return par(parName);
  else
    return defaultValue;
}
void BasePhyLayer::sendControlMessageUp (cMessage * msg) [protected]
Sends the passed control message to the upper layer.
Definition at line 560 of file BasePhyLayer.cc.
References upperControlOut.
Referenced by sendControlMsg().
{
  send(msg, upperControlOut);
}
void BasePhyLayer::sendControlMsg (cMessage * msg) [virtual]
Called by the Decider to send a control message to the MACLayer.
This function can be used to answer a ChannelSenseRequest to the MACLayer
Implements DeciderToPhyInterface.
Definition at line 710 of file BasePhyLayer.cc.
References sendControlMessageUp().
Referenced by finishRadioSwitching(), and handleSelfMessage().
{
  sendControlMessageUp(msg);
}
void BasePhyLayer::sendMacPktUp (cMessage * pkt) [protected]
Sends the passed MacPkt to the upper layer.
Definition at line 564 of file BasePhyLayer.cc.
References upperGateOut.
Referenced by sendUp().
{
  send(pkt, upperGateOut);
}
void BasePhyLayer::sendMessageDown (AirFrame * pkt) [protected]
Sends the passed AirFrame to the channel.
Definition at line 568 of file BasePhyLayer.cc.
References ChannelAccess::sendToChannel().
Referenced by handleUpperMessage().
{
  sendToChannel(msg);
}
void BasePhyLayer::sendSelfMessage (cMessage * msg, simtime_t time) [protected]
Schedule self message to passed point in time.
Definition at line 573 of file BasePhyLayer.cc.
Referenced by handleAirFrameReceiving(), handleAirFrameStartReceive(), handleChannelSenseRequest(), handleUpperMessage(), and setRadioState().
{
  //TODO: maybe delete this method because it doesn't makes much sense,
  //    or change it to "scheduleIn(msg, timeDelta)" which schedules
  //    a message to +timeDelta from current time
  scheduleAt(time, msg);
}
void BasePhyLayer::sendUp (AirFrame * packet, DeciderResult * result) [virtual]
Called to send an AirFrame with DeciderResult to the MACLayer.
When a packet is completely received and not noise, the Decider call this function to send the packet together with the corresponding DeciderResult up to MACLayer
Implements DeciderToPhyInterface.
Definition at line 714 of file BasePhyLayer.cc.
References coreEV, and sendMacPktUp().
{
  coreEV << "Decapsulating MacPacket from Airframe with ID " << frame->getId() << " and sending it up to MAC." << endl;
  cMessage* packet = frame->decapsulate();
  assert(packet);
  PhyToMacControlInfo* ctrlInfo = new PhyToMacControlInfo(result);
  packet->setControlInfo(ctrlInfo);
  sendMacPktUp(packet);
}
simtime_t BasePhyLayer::setRadioState (int rs) [virtual]
Tells the BasePhyLayer to switch to the specified radio state.
The switching process can take some time depending on the specified switching times in the ned file.
Returns:
-1: Error code if the Radio is currently switching else: switching time from the current RadioState to the new RadioState
Implements MacToPhyInterface.
Definition at line 663 of file BasePhyLayer.cc.
References finishRadioSwitching(), radio, radioSwitchingOverTimer, sendSelfMessage(), Radio::switchTo(), and txOverTimer.
{
  Enter_Method_Silent();
  assert(radio);
  if(txOverTimer->isScheduled()) {
    opp_warning("Switched radio while sending an AirFrame. The effects this would have on the transmission are not simulated by the BasePhyLayer!");
  }
  simtime_t switchTime = radio->switchTo(rs, simTime());
  //invalid switch time, we are probably already switching
  if(switchTime < 0)
    return switchTime;
  // if switching is done in exactly zero-time no extra self-message is scheduled
  if (switchTime == 0.0)
  {
    // TODO: in case of zero-time-switch, send no control-message to mac!
    // maybe call a method finishRadioSwitchingSilent()
    finishRadioSwitching();
  } else
  {
    sendSelfMessage(radioSwitchingOverTimer, simTime() + switchTime);
  }
  return switchTime;
}
Member Data Documentation
AnalogueModelList BasePhyLayer::analogueModels [protected]
List of the analogue models to use.
Definition at line 99 of file BasePhyLayer.h.
Referenced by filterSignal(), initializeAnalogueModels(), and ~BasePhyLayer().
ChannelInfo BasePhyLayer::channelInfo [protected]
Channel info keeps track of received AirFrames and provides information about currently active AirFrames at the channel.
Definition at line 87 of file BasePhyLayer.h.
Referenced by getChannelInfo(), handleAirFrameEndReceive(), and handleAirFrameStartReceive().
Decider* BasePhyLayer::decider [protected]
Pointer to the decider module.
Definition at line 93 of file BasePhyLayer.h.
Referenced by getChannelState(), handleAirFrameReceiving(), handleAirFrameStartReceive(), handleChannelSenseRequest(), initializeDecider(), and ~BasePhyLayer().
int BasePhyLayer::headerLength [protected]
Stores the length of the phy header in bits.
Definition at line 138 of file BasePhyLayer.h.
Referenced by encapsMsg(), and initialize().
double BasePhyLayer::maxTXPower [protected]
The maximum transmission power a message can be send with.
Definition at line 78 of file BasePhyLayer.h.
Referenced by initialize().
Radio* BasePhyLayer::radio [protected]
The state machine storing the current radio state (TX, RX, SLEEP).
Definition at line 90 of file BasePhyLayer.h.
Referenced by finishRadioSwitching(), getAnalogueModelFromName(), getRadioState(), handleAirFrameEndReceive(), handleUpperMessage(), initialize(), setRadioState(), and ~BasePhyLayer().
cMessage* BasePhyLayer::radioSwitchingOverTimer [protected]
Self message scheduled to the point in time when the switching process of the radio is over.
Definition at line 120 of file BasePhyLayer.h.
Referenced by handleSelfMessage(), initialize(), setRadioState(), and ~BasePhyLayer().
double BasePhyLayer::sensitivity [protected]
The sensitivity describes the minimum strength a signal must have to be received.
Definition at line 81 of file BasePhyLayer.h.
Referenced by initialize(), PhyLayer::initializeDecider80211(), PhyLayerBattery::initializeDecider80211Battery(), and PhyLayer::initializeSNRThresholdDecider().
ConstantSimpleConstMapping* BasePhyLayer::thermalNoise [protected]
Defines the strength of the thermal noise.
Definition at line 75 of file BasePhyLayer.h.
Referenced by getThermalNoise(), initialize(), and ~BasePhyLayer().
cMessage* BasePhyLayer::txOverTimer [protected]
Self message scheduled to the point in time when the transmission of an AirFrame is over.
Definition at line 126 of file BasePhyLayer.h.
Referenced by handleSelfMessage(), handleUpperMessage(), initialize(), setRadioState(), and ~BasePhyLayer().
int BasePhyLayer::upperControlIn [protected]
The id of the in-control gate from the Mac layer.
Definition at line 114 of file BasePhyLayer.h.
Referenced by handleMessage(), and initialize().
int BasePhyLayer::upperControlOut [protected]
The id of the out-control gate to the Mac layer.
Definition at line 112 of file BasePhyLayer.h.
Referenced by initialize(), and sendControlMessageUp().
int BasePhyLayer::upperGateIn [protected]
The id of the in-data gate from the Mac layer.
Definition at line 108 of file BasePhyLayer.h.
Referenced by handleMessage(), and initialize().
int BasePhyLayer::upperGateOut [protected]
The id of the out-data gate to the Mac layer.
Definition at line 110 of file BasePhyLayer.h.
Referenced by initialize(), and sendMacPktUp().
BaseWorldUtility* BasePhyLayer::world [protected]
Reimplemented from ChannelAccess.
Definition at line 141 of file BasePhyLayer.h.
Referenced by encapsMsg(), initialize(), and PhyLayer::initializeSimplePathlossModel().
The documentation for this class was generated from the following files:
base/phyLayer/BasePhyLayer.h
base/phyLayer/BasePhyLayer.cc