MiXiM: FWMath Class Reference
FWMath Class Reference
[baseUtils - utitities for base MiXiM, utils - utiltity classes]
Support functions for mathematical operations.
#include <FWMath.h>
Static Public Member Functions
static double mod (double dividend, double divisor)
static double div (double dividend, double divisor)
static bool close (double one, double two)
static int stepfunction (double i)
static int sign (double i)
static int round (double d)
static double floorToZero (double d)
static double max (double a, double b)
static double min (double a, double b)
static double dBm2mW (double dBm)
static double mW2dBm (double mW)
Convert an mW value to dBm.
static double torDist (double x1, double x2, double y1, double y2)
static double erfc (double x)
Complementary error function.
Detailed Description
Support functions for mathematical operations.
This class contains all kind of mathematical support functions
Author:
Christian Frank
Definition at line 75 of file FWMath.h.
Member Function Documentation
static bool FWMath::close (double one, double two) [inline, static]
Tests whether two doubles are close enough to be declared equal.
Returns:
true if parameters are at most epsilon apart, false otherwise
Definition at line 102 of file FWMath.h.
References EPSILON.
Referenced by Move::getPositionAt(), and stepfunction().
{
        return fabs(one-two)<EPSILON;
    }
static double FWMath::dBm2mW (double dBm) [inline, static]
convert a dBm value into milli Watt
Definition at line 141 of file FWMath.h.
Referenced by Mac80211::initialize(), BasePhyLayer::initialize(), and LogNormalShadowing::randomLogNormalGain().
{
        return pow(10.0, dBm/10.0);
    }
static double FWMath::div (double dividend, double divisor) [inline, static]
Returns the result of a whole-numbered division.
Definition at line 90 of file FWMath.h.
{
        double i;
        double f;
        f=modf(dividend/divisor, &i);
        return i;
    }
static double FWMath::erfc (double x) [inline, static]
Complementary error function.
Definition at line 162 of file FWMath.h.
{
    double t, u, y;
    if (x <= -6.0)
      return 2.0;
    if (x >= 6.0)
      return 0.0;
    t = 3.97886080735226 / (fabs(x) + 3.97886080735226);
    u = t - 0.5;
    y = (((((((((0.00127109764952614092 * u + 1.19314022838340944e-4) * u -
      0.003963850973605135) * u - 8.70779635317295828e-4) * u +
      0.00773672528313526668) * u + 0.00383335126264887303) * u -
      0.0127223813782122755) * u - 0.0133823644533460069) * u +
      0.0161315329733252248) * u + 0.0390976845588484035) * u +
      0.00249367200053503304;
    y = ((((((((((((y * u - 0.0838864557023001992) * u -
      0.119463959964325415) * u + 0.0166207924969367356) * u +
      0.357524274449531043) * u + 0.805276408752910567) * u +
      1.18902982909273333) * u + 1.37040217682338167) * u +
      1.31314653831023098) * u + 1.07925515155856677) * u +
      0.774368199119538609) * u + 0.490165080585318424) * u +
      0.275374741597376782) * t * exp(-x * x);
    return x < 0.0 ? 2.0 - y : y;
  }
static double FWMath::floorToZero (double d) [inline, static]
Returns:
the to the nearest integer towards zero rounded parameter as double
Definition at line 126 of file FWMath.h.
Referenced by TractorMobility::calculateXY().
{ return (d >= 0.0)? floor(d) : ceil(d); }
static double FWMath::max (double a, double b) [inline, static]
Returns:
greater of the given parameters
Definition at line 131 of file FWMath.h.
Referenced by BaseConnectionManager::initialize().
{ return (a<b)? b : a; }
static double FWMath::min (double a, double b) [inline, static]
Returns:
smaller of the given parameters
Definition at line 136 of file FWMath.h.
{ return (a>b)? b : a; }
static double FWMath::mod (double dividend, double divisor) [inline, static]
Returns the rest of a whole-numbered division.
Definition at line 82 of file FWMath.h.
{
        double i;
        return modf(dividend/divisor, &i)*divisor;
    }
static double FWMath::mW2dBm (double mW) [inline, static]
Convert an mW value to dBm.
Definition at line 148 of file FWMath.h.
Referenced by ConstMapping::print().
{ return (10 * log10(mW)); }
static int FWMath::round (double d) [inline, static]
Returns:
integer that corresponds to rounded double parameter
Definition at line 121 of file FWMath.h.
Referenced by SimpleBattery::finish(), ConstSpeedMobility::setTargetPosition(), and BaseMobility::updatePosition().
{ return (int)(ceil(d-0.5)); }
static int FWMath::sign (double i) [inline, static]
Returns:
1 if parameter greater or equal zero, -1 otherwise
Definition at line 116 of file FWMath.h.
{ return (i>=0)? 1 : -1; };
static int FWMath::stepfunction (double i) [inline, static]
Returns:
0 if i is close to 0, 1 if i is positive greater epsilon, -1 if it is negative smaller epsilon.
Definition at line 110 of file FWMath.h.
References close(), and EPSILON.
{ return (i>EPSILON) ? 1 : close(i,0) ? 0 :-1; };
static double FWMath::torDist (double x1, double x2, double y1, double y2) [inline, static]
helper function, returns squared euclidean distance makes code less messy
Definition at line 154 of file FWMath.h.
{
        return (x1-x2) * (x1-x2) + (y1-y2) * (y1-y2);
    }
The documentation for this class was generated from the following file:
base/utils/FWMath.h