MiXiM: BaseLayer Class Reference
BaseLayer Class Reference
[baseModules - base module classes of MiXiM]
A very simple layer template.
#include <BaseLayer.h>
Inherits BatteryAccess.
Inherited by BaseApplLayer, BaseMacLayer, and BaseNetwLayer.
Public Member Functions
virtual void initialize (int)
Initialization of the module and some variables.
virtual void handleMessage (cMessage *)
Called every time a message arrives.
virtual void finish ()
virtual ~BaseLayer ()
Protected Member Functions
Handle Messages
Functions to be redefined by the programmer
These are the functions provided to add own functionality to your modules. These functions are called whenever a blackboard message, a self message or a data message from the upper or lower layer arrives respectively.
virtual void handleSelfMsg (cMessage *msg)=0
Handle self messages such as timer...
virtual void handleUpperMsg (cMessage *msg)=0
Handle messages from upper layer.
virtual void handleLowerMsg (cMessage *msg)=0
Handle messages from lower layer.
virtual void handleLowerControl (cMessage *msg)=0
Handle control messages from lower layer.
virtual void handleUpperControl (cMessage *msg)=0
Handle control messages from upper layer.
Convenience Functions
Functions for convenience - NOT to be modified
These are functions taking care of message encapsulation and message sending. Normally you should not need to alter these.
All these functions assume that YOU do all the necessary handling of control information etc. before you use them.
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Attributes
bool doStats
int catPassedMsg
PassedMessage * passedMsg
int hostId
The hosts id.
int upperGateIn
gate id
int upperGateOut
int lowerGateIn
int lowerGateOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Detailed Description
A very simple layer template.
This module provides basic abstractions that ease development of a network or MAC layer.
Author:
Andreas Koepke
Definition at line 38 of file BaseLayer.h.
Constructor & Destructor Documentation
BaseLayer::~BaseLayer () [virtual]
Definition at line 143 of file BaseLayer.cc.
References doStats, and passedMsg.
{
    if (doStats) {
        delete passedMsg;
    }
}
Member Function Documentation
void BaseLayer::finish () [virtual]
Reimplemented in TestApplLayer, BurstApplLayerBattery, CSMAMacLayer, and Mac80211.
Definition at line 139 of file BaseLayer.cc.
                       {
}
virtual void BaseLayer::handleLowerControl (cMessage * msg) [protected, pure virtual]
Handle control messages from lower layer.
Implemented in BaseApplLayer, BaseMacLayer, BaseNetwLayer, CSMAMacLayer, and Mac80211.
Referenced by handleMessage().
virtual void BaseLayer::handleLowerMsg (cMessage * msg) [protected, pure virtual]
Handle messages from lower layer.
Implemented in BaseApplLayer, BaseMacLayer, BaseNetwLayer, TestApplLayer, BurstApplLayerBattery, CSMAMacLayer, and Mac80211.
Referenced by handleMessage().
void BaseLayer::handleMessage (cMessage * msg) [virtual]
Called every time a message arrives.
The basic handle message function.
Depending on the gate a message arrives handleMessage just calls different handle*Msg functions to further process the message.
You should not make any changes in this function but implement all your functionality into the handle*Msg functions called from here.
See also:
handleUpperMsg, handleLowerMsg, handleSelfMsg
Definition at line 73 of file BaseLayer.cc.
References handleLowerControl(), handleLowerMsg(), handleSelfMsg(), handleUpperControl(), handleUpperMsg(), PassedMessage::INCOMING, PassedMessage::LOWER_CONTROL, PassedMessage::LOWER_DATA, lowerControlIn, lowerGateIn, recordPacket(), PassedMessage::UPPER_CONTROL, PassedMessage::UPPER_DATA, upperControlIn, and upperGateIn.
{
    if (msg->isSelfMessage()){
        handleSelfMsg(msg);
    } else if(msg->getArrivalGateId()==upperGateIn) {
        recordPacket(PassedMessage::INCOMING,PassedMessage::UPPER_DATA,msg);
        handleUpperMsg(msg);
    } else if(msg->getArrivalGateId()==upperControlIn) {
        recordPacket(PassedMessage::INCOMING,PassedMessage::UPPER_CONTROL,msg);
        handleUpperControl(msg);
    } else if(msg->getArrivalGateId()==lowerControlIn){
        recordPacket(PassedMessage::INCOMING,PassedMessage::LOWER_CONTROL,msg);
        handleLowerControl(msg);
    } else if(msg->getArrivalGateId()==lowerGateIn) {
        recordPacket(PassedMessage::INCOMING,PassedMessage::LOWER_DATA,msg);
        handleLowerMsg(msg);
    }
    else if(msg->getArrivalGateId()==-1) {
        /* Classes extending this class may not use all the gates, f.e.
         * BaseApplLayer has no upper gates. In this case all upper gate-
         * handles are initialized to -1. When getArrivalGateId() equals -1,
         * it would be wrong to forward the message to one of these gates,
         * as they actually don't exist, so raise an error instead.
         */
        opp_error("No self message and no gateID?? Check configuration.");
    } else {
        /* msg->getArrivalGateId() should be valid, but it isn't recognized
         * here. This could signal the case that this class is extended
         * with extra gates, but handleMessage() isn't overridden to
         * check for the new gate(s).
         */
        opp_error("Unknown gateID?? Check configuration or override handleMessage().");
    }
}
virtual void BaseLayer::handleSelfMsg (cMessage * msg) [protected, pure virtual]
Handle self messages such as timer...
Implemented in BaseApplLayer, BaseMacLayer, BaseNetwLayer, TestApplLayer, BurstApplLayer, BurstApplLayerBattery, CSMAMacLayer, and Mac80211.
Referenced by handleMessage().
virtual void BaseLayer::handleUpperControl (cMessage * msg) [protected, pure virtual]
Handle control messages from upper layer.
Implemented in BaseApplLayer, BaseMacLayer, and BaseNetwLayer.
Referenced by handleMessage().
virtual void BaseLayer::handleUpperMsg (cMessage * msg) [protected, pure virtual]
Handle messages from upper layer.
This function is pure virtual here, because there is no reasonable guess what to do with it by default.
Implemented in BaseApplLayer, BaseMacLayer, BaseNetwLayer, CSMAMacLayer, and Mac80211.
Referenced by handleMessage().
void BaseLayer::initialize (int stage) [virtual]
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseModule. This module takes care of the gate initialization.
Reimplemented from BaseModule.
Reimplemented in BaseApplLayer, BaseMacLayer, BaseNetwLayer, TestApplLayer, BurstApplLayer, BurstApplLayerBattery, CSMAMacLayer, and Mac80211.
Definition at line 36 of file BaseLayer.cc.
References catPassedMsg, doStats, BaseModule::findHost(), PassedMessage::fromModule, BaseUtility::getCategory(), hostId, lowerControlIn, lowerControlOut, lowerGateIn, lowerGateOut, passedMsg, upperControlIn, upperControlOut, upperGateIn, upperGateOut, and BaseModule::utility.
{
  BatteryAccess::initialize(stage);
    if(stage==0){
        if (hasPar("stats") && par("stats").boolValue()) {
            doStats = true;
            passedMsg = new PassedMessage();
            catPassedMsg = utility->getCategory(passedMsg);
            passedMsg->fromModule = getId();
            hostId = findHost()->getId();
        }
        else {
            doStats = false;
        }
        upperGateIn  = findGate("upperGateIn");
        upperGateOut = findGate("upperGateOut");
        lowerGateIn  = findGate("lowerGateIn");
        lowerGateOut = findGate("lowerGateOut");
        upperControlIn  = findGate("upperControlIn");
        upperControlOut = findGate("upperControlOut");
        lowerControlIn  = findGate("lowerControlIn");
        lowerControlOut = findGate("lowerControlOut");
    }
}
void BaseLayer::recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage * m) [protected]
Definition at line 128 of file BaseLayer.cc.
References catPassedMsg, PassedMessage::direction, doStats, PassedMessage::gateType, hostId, PassedMessage::kind, PassedMessage::name, passedMsg, BaseUtility::publishBBItem(), and BaseModule::utility.
Referenced by handleMessage(), sendControlDown(), sendControlUp(), BaseApplLayer::sendDelayedDown(), sendDown(), and sendUp().
{
    if (!doStats) return;
    passedMsg->direction = dir;
    passedMsg->gateType = gate;
    passedMsg->kind = msg->getKind();
    passedMsg->name = msg->getName();
    utility->publishBBItem(catPassedMsg, passedMsg, hostId);
}
void BaseLayer::sendControlDown (cMessage * msg) [protected]
Sends a control message to a lower layer.
Definition at line 123 of file BaseLayer.cc.
References PassedMessage::LOWER_CONTROL, lowerControlOut, PassedMessage::OUTGOING, and recordPacket().
Referenced by Mac80211::handleCTSframe(), Mac80211::handleDATAframe(), Mac80211::handleRTSframe(), and Mac80211::senseChannelWhileIdle().
{
    recordPacket(PassedMessage::OUTGOING,PassedMessage::LOWER_CONTROL,msg);
    send(msg, lowerControlOut);
}
void BaseLayer::sendControlUp (cMessage * msg) [protected]
Sends a control message to an upper layer.
Definition at line 118 of file BaseLayer.cc.
References PassedMessage::OUTGOING, recordPacket(), PassedMessage::UPPER_CONTROL, and upperControlOut.
Referenced by BaseMacLayer::handleLowerControl(), Mac80211::handleUpperMsg(), CSMAMacLayer::handleUpperMsg(), CSMAMacLayer::scheduleBackoff(), and Mac80211::testMaxAttempts().
{
    recordPacket(PassedMessage::OUTGOING,PassedMessage::UPPER_CONTROL,msg);
    send(msg, upperControlOut);
}
void BaseLayer::sendDown (cMessage * msg) [protected]
Sends a message to the lower layer.
Short hand for send(msg, lowerGateOut);
You have to take care of encapsulation We recommend that you use a pair of functions called encapsMsg/decapsMsg.
Definition at line 108 of file BaseLayer.cc.
References PassedMessage::LOWER_DATA, lowerGateOut, PassedMessage::OUTGOING, and recordPacket().
Referenced by CSMAMacLayer::handleLowerControl(), BaseNetwLayer::handleUpperMsg(), BaseMacLayer::handleUpperMsg(), Mac80211::sendACKframe(), TestApplLayer::sendBroadcast(), Mac80211::sendBROADCASTframe(), Mac80211::sendCTSframe(), Mac80211::sendDATAframe(), and Mac80211::sendRTSframe().
{
    recordPacket(PassedMessage::OUTGOING,PassedMessage::LOWER_DATA,msg);
    send(msg, lowerGateOut);
}
void BaseLayer::sendUp (cMessage * msg) [protected]
Sends a message to the upper layer.
Short hand for send(msg, upperGateOut); You have to take care of decapsulation and deletion of superflous frames. We recommend that you use a pair of functions decapsMsg/encapsMsg.
Definition at line 113 of file BaseLayer.cc.
References PassedMessage::OUTGOING, recordPacket(), PassedMessage::UPPER_DATA, and upperGateOut.
Referenced by Mac80211::handleBroadcastMsg(), Mac80211::handleDATAframe(), CSMAMacLayer::handleLowerMsg(), BaseNetwLayer::handleLowerMsg(), and BaseMacLayer::handleLowerMsg().
{
    recordPacket(PassedMessage::OUTGOING,PassedMessage::UPPER_DATA,msg);
    send(msg, upperGateOut);
}
Member Data Documentation
int BaseLayer::catPassedMsg [protected]
Definition at line 56 of file BaseLayer.h.
Referenced by initialize(), and recordPacket().
bool BaseLayer::doStats [protected]
Definition at line 55 of file BaseLayer.h.
Referenced by initialize(), recordPacket(), and ~BaseLayer().
int BaseLayer::hostId [protected]
The hosts id.
Reimplemented from BaseModule.
Definition at line 58 of file BaseLayer.h.
Referenced by initialize(), and recordPacket().
int BaseLayer::lowerControlIn [protected]
Definition at line 50 of file BaseLayer.h.
Referenced by handleMessage(), and initialize().
int BaseLayer::lowerControlOut [protected]
Definition at line 51 of file BaseLayer.h.
Referenced by initialize(), and sendControlDown().
int BaseLayer::lowerGateIn [protected]
Definition at line 46 of file BaseLayer.h.
Referenced by handleMessage(), and initialize().
int BaseLayer::lowerGateOut [protected]
Definition at line 47 of file BaseLayer.h.
Referenced by initialize(), BaseApplLayer::sendDelayedDown(), and sendDown().
PassedMessage* BaseLayer::passedMsg [protected]
Definition at line 57 of file BaseLayer.h.
Referenced by initialize(), recordPacket(), and ~BaseLayer().
int BaseLayer::upperControlIn [protected]
Definition at line 48 of file BaseLayer.h.
Referenced by handleMessage(), and initialize().
int BaseLayer::upperControlOut [protected]
Definition at line 49 of file BaseLayer.h.
Referenced by initialize(), and sendControlUp().
int BaseLayer::upperGateIn [protected]
gate id
Definition at line 44 of file BaseLayer.h.
Referenced by handleMessage(), and initialize().
int BaseLayer::upperGateOut [protected]
Definition at line 45 of file BaseLayer.h.
Referenced by initialize(), and sendUp().
The documentation for this class was generated from the following files:
base/modules/BaseLayer.h
base/modules/BaseLayer.cc