MiXiM: ChannelState Class Reference
ChannelState Class Reference
[decider - decider modules]
Provides information about the current state of the channel:.
#include <ChannelState.h>
Public Member Functions
ChannelState (bool isIdle=false, double rssi=0.0)
Creates and initializes a new ChannelState with the passed state.
bool isIdle ()
Returns true if the channel is considered idle, meaning depends on the used decider.
double getRSSI ()
Returns the current RSSI value of the channel.
std::string info () const
Protected Attributes
bool idle
defines if the channel is currently idle
double rssi
the current RSSI value of the channel
Detailed Description
Provides information about the current state of the channel:.
idle/busy - is the physical currently receiving something? RSSI - the currently received signal strength indicator.
Definition at line 14 of file ChannelState.h.
Constructor & Destructor Documentation
ChannelState::ChannelState (bool isIdle = false, double rssi = 0.0) [inline]
Creates and initializes a new ChannelState with the passed state.
isIdle - defines if the channel is currently idle rssi - the current RSSI value of the channel
Definition at line 31 of file ChannelState.h.
                                                       :
    idle(isIdle), rssi(rssi) {}
Member Function Documentation
double ChannelState::getRSSI ()
Returns the current RSSI value of the channel.
Definition at line 8 of file ChannelState.cc.
References rssi.
{
  return rssi;
}
std::string ChannelState::info () const [inline]
Definition at line 45 of file ChannelState.h.
References idle, and rssi.
Referenced by Mac80211::beginNewCycle().
{
    std::stringstream os;
    if (idle) {
      os << "[idle with rssi of ";
    } else {
      os << "[busy with rssi of ";
    }
    os << rssi << "]";
    return os.str();
  }
bool ChannelState::isIdle ()
Returns true if the channel is considered idle, meaning depends on the used decider.
Definition at line 3 of file ChannelState.cc.
References idle.
Referenced by Mac80211::beginNewCycle(), and CSMAMacLayer::handleSelfMsg().
{
  return idle;
}
Member Data Documentation
bool ChannelState::idle [protected]
defines if the channel is currently idle
Definition at line 18 of file ChannelState.h.
Referenced by info(), and isIdle().
double ChannelState::rssi [protected]
the current RSSI value of the channel
Definition at line 21 of file ChannelState.h.
Referenced by getRSSI(), and info().
The documentation for this class was generated from the following files:
base/phyLayer/ChannelState.h
base/phyLayer/ChannelState.cc