MiXiM: BaseConnectionManager Class Reference
BaseConnectionManager Class Reference
[connectionManager - channel and connection related classes]
Module to control the channel and handle all connection related stuff.
#include <BaseConnectionManager.h>
Inherited by ConnectionManager.
Classes
class CoordSet
Represents an minimalistic (hash)set of GridCoords. It is a workaround because c++ doesn't come with an hash set.
class GridCoord
Represents a position inside a grid.
Public Member Functions
virtual ~BaseConnectionManager ()
virtual int numInitStages () const
virtual void initialize (int stage)
Reads init parameters and calculates a maximal interference distance.
bool registerNic (cModule *nic, ChannelAccess *chAccess, const Coord *nicPos)
Registers a nic to have its connections managed by ConnectionManager.
void updateNicPos (int nicID, const Coord *newPos)
Updates the position information of a registered nic.
const NicEntry::GateList & getGateList (int nicID)
Returns the ingates of all nics in range.
const cGate * getOutGateTo (const NicEntry *nic, const NicEntry *targetNic)
Returns the ingate of the with id==targetID, or 0 if not in range.
Protected Types
typedef std::map< int, NicEntry * > NicEntries
typedef std::vector< NicEntries > RowVector
typedef std::vector< RowVector > NicMatrix
typedef std::vector< NicMatrix > NicCube
Protected Member Functions
virtual double calcInterfDist ()=0
Calculate interference distance This method has to be overridden by any derived class.
virtual void registerNicExt (int nicID)
Called by "registerNic()" after the nic has been registered. That means that the NicEntry for the nic has already been created and added to nics map.
virtual void updateConnections (int nicID, const Coord *oldPos, const Coord *newPos)
Updates the connections of the nic with "nicID".
Protected Attributes
NicEntries nics
bool coreDebug
Set debugging for the basic module.
bool sendDirect
Does the ConnectionManager use sendDirect or not?
const Coord * playgroundSize
Stores the size of the playground.
double maxInterferenceDistance
the biggest interference distance in the network.
double maxDistSquared
Square of maxInterferenceDistance cache a value that is often used.
bool useTorus
Stores the useTorus flag of the WorldUtility.
NicCube nicGrid
Registry of all nics.
double findDistance
Distance that helps to find a node under a certain position.
GridCoord gridDim
The size of the grid.
Private Member Functions
void updateNicConnections (NicEntries &nmap, NicEntry *nic)
Manages the connections of a registered nic.
void checkGrid (GridCoord &oldCell, GridCoord &newCell, int id)
Check connections of a nic in the grid.
GridCoord getCellForCoordinate (const Coord &c)
Calculates the corresponding cell of a coordinate.
NicEntries & getCellEntries (GridCoord &cell)
Returns the NicEntries of the cell with specified coordinate.
int wrapIfTorus (int value, int max)
void fillUnionWithNeighbors (CoordSet &gridUnion, GridCoord cell)
Adds every direct Neighbor of a GridCoord to a union of coords.
Detailed Description
Module to control the channel and handle all connection related stuff.
The central module that coordinates the connections between all nodes, and handles dynamic gate creation. BasicConnectionManager therefore periodically communicates with the ChannelAccess modules
You may not instantiate BasicConnectionManager! Use ConnectionManager instead.
Author:
Steffen Sroka, Daniel Willkomm, Karl Wessel
See also:
ChannelAccess
Definition at line 23 of file BaseConnectionManager.h.
Member Typedef Documentation
typedef std::vector<NicMatrix> BaseConnectionManager::NicCube [protected]
Definition at line 227 of file BaseConnectionManager.h.
typedef std::map<int, NicEntry*> BaseConnectionManager::NicEntries [protected]
Definition at line 201 of file BaseConnectionManager.h.
typedef std::vector<RowVector> BaseConnectionManager::NicMatrix [protected]
Definition at line 226 of file BaseConnectionManager.h.
typedef std::vector<NicEntries> BaseConnectionManager::RowVector [protected]
Definition at line 225 of file BaseConnectionManager.h.
Constructor & Destructor Documentation
BaseConnectionManager::~BaseConnectionManager () [virtual]
Definition at line 312 of file BaseConnectionManager.cc.
References nics.
{
  for (NicEntries::iterator ne = nics.begin(); ne != nics.end(); ne++)
  {
    delete ne->second;
  }
}
Member Function Documentation
virtual double BaseConnectionManager::calcInterfDist () [protected, pure virtual]
Calculate interference distance This method has to be overridden by any derived class.
Implemented in ConnectionManager, and UnitDisk.
Referenced by initialize().
void BaseConnectionManager::checkGrid (BaseConnectionManager::GridCoord & oldCell, BaseConnectionManager::GridCoord & newCell, int id) [private]
Check connections of a nic in the grid.
Definition at line 129 of file BaseConnectionManager.cc.
References BaseConnectionManager::BaseConnectionManager::CoordSet::add(), ccEV, fillUnionWithNeighbors(), getCellEntries(), gridDim, BaseConnectionManager::BaseConnectionManager::GridCoord::info(), BaseConnectionManager::BaseConnectionManager::CoordSet::next(), updateNicConnections(), BaseConnectionManager::BaseConnectionManager::GridCoord::x, BaseConnectionManager::BaseConnectionManager::GridCoord::y, and BaseConnectionManager::BaseConnectionManager::GridCoord::z.
Referenced by updateConnections().
{
    // structure to find union of grid squares
    CoordSet gridUnion(74);
    // find nic at old position
    NicEntries& oldCellEntries = getCellEntries(oldCell);
    NicEntries::iterator it = oldCellEntries.find(id);
    NicEntry *nic = it->second;
    // move nic to a new position in matrix
    if(oldCell != newCell) {
      oldCellEntries.erase(it);
      getCellEntries(newCell)[id] = nic;
    }
  if((gridDim.x == 1) && (gridDim.y == 1) && (gridDim.z == 1)) {
    gridUnion.add(oldCell);
    } else {
    //add grid around oldPos
    fillUnionWithNeighbors(gridUnion, oldCell);
        if(oldCell != newCell) {
            //add grid around newPos
            fillUnionWithNeighbors(gridUnion, newCell);
        }
    }
    GridCoord* c = gridUnion.next();
    while(c != 0) {
    ccEV << "Update cons in [" << c->info() << "]" << endl;
    updateNicConnections(getCellEntries(*c), nic);
    c = gridUnion.next();
    }
}
void BaseConnectionManager::fillUnionWithNeighbors (CoordSet & gridUnion, GridCoord cell) [private]
Adds every direct Neighbor of a GridCoord to a union of coords.
Definition at line 189 of file BaseConnectionManager.cc.
References BaseConnectionManager::BaseConnectionManager::CoordSet::add(), gridDim, BaseConnectionManager::BaseConnectionManager::GridCoord::use2D, wrapIfTorus(), BaseConnectionManager::BaseConnectionManager::GridCoord::x, BaseConnectionManager::BaseConnectionManager::GridCoord::y, and BaseConnectionManager::BaseConnectionManager::GridCoord::z.
Referenced by checkGrid().
{
  for(int iz = (int)cell.z - 1; iz <= (int)cell.z + 1; iz++) {
    if(iz != cell.z && cell.use2D) {
      continue;
    }
    int cz = wrapIfTorus(iz, gridDim.z);
    if(cz == -1) {
      continue;
    }
    for(int ix = (int)cell.x - 1; ix <= (int)cell.x + 1; ix++) {
      int cx = wrapIfTorus(ix, gridDim.x);
      if(cx == -1) {
        continue;
      }
      for(int iy = (int)cell.y - 1; iy <= (int)cell.y + 1; iy++) {
        int cy = wrapIfTorus(iy, gridDim.y);
        if(cy != -1) {
          if(cell.use2D) {
            gridUnion.add(GridCoord(cx, cy));
          } else {
            gridUnion.add(GridCoord(cx, cy, cz));
          }
        }
      }
    }
  }
}
BaseConnectionManager::NicEntries & BaseConnectionManager::getCellEntries (BaseConnectionManager::GridCoord & cell) [private]
Returns the NicEntries of the cell with specified coordinate.
Definition at line 112 of file BaseConnectionManager.cc.
References nicGrid, BaseConnectionManager::BaseConnectionManager::GridCoord::x, BaseConnectionManager::BaseConnectionManager::GridCoord::y, and BaseConnectionManager::BaseConnectionManager::GridCoord::z.
Referenced by checkGrid(), and registerNicExt().
{
    return nicGrid[cell.x][cell.y][cell.z];
}
BaseConnectionManager::GridCoord BaseConnectionManager::getCellForCoordinate (const Coord & c) [private]
Calculates the corresponding cell of a coordinate.
Definition at line 100 of file BaseConnectionManager.cc.
References findDistance.
Referenced by registerNicExt(), and updateConnections().
{
    return GridCoord(c, findDistance);
}
const NicEntry::GateList & BaseConnectionManager::getGateList (int nicID)
Returns the ingates of all nics in range.
Definition at line 302 of file BaseConnectionManager.cc.
References nics.
Referenced by ChannelAccess::sendToChannel().
{
  return nics[nicID]->getGateList();
}
const cGate * BaseConnectionManager::getOutGateTo (const NicEntry * nic, const NicEntry * targetNic)
Returns the ingate of the with id==targetID, or 0 if not in range.
Definition at line 307 of file BaseConnectionManager.cc.
References NicEntry::nicId, and nics.
{
    return nics[nic->nicId]->getOutGateTo(targetNic);
}
void BaseConnectionManager::initialize (int stage) [virtual]
Reads init parameters and calculates a maximal interference distance.
Reimplemented in UnitDisk.
Definition at line 16 of file BaseConnectionManager.cc.
References calcInterfDist(), ccEV, coreDebug, EPSILON, findDistance, BaseWorldUtility::getPgs(), Coord::getX(), Coord::getY(), Coord::getZ(), gridDim, FWMath::max(), maxDistSquared, maxInterferenceDistance, nicGrid, playgroundSize, sendDirect, BaseWorldUtility::useTorus(), useTorus, BaseConnectionManager::BaseConnectionManager::GridCoord::x, BaseConnectionManager::BaseConnectionManager::GridCoord::y, and BaseConnectionManager::BaseConnectionManager::GridCoord::z.
{
  //BaseModule::initialize(stage);
  if (stage == 0)
  {
    if(hasPar("coreDebug"))
      coreDebug = par("coreDebug").boolValue();
    else
      coreDebug = false;
  }
  else if (stage == 1)
  {
    ccEV <<"initializing BaseConnectionManager\n";
    BaseWorldUtility* world = FindModule<BaseWorldUtility*>::findGlobalModule();
    assert(world != 0);
    playgroundSize = world->getPgs();
    useTorus = world->useTorus();
    if(hasPar("sendDirect"))
      sendDirect = par("sendDirect").boolValue();
    else
      sendDirect = false;
    maxInterferenceDistance = calcInterfDist();
    maxDistSquared = maxInterferenceDistance * maxInterferenceDistance;
    //----initialize node grid-----
    //step 1 - calculate dimension of grid
    //one cell should have the size of maxInterferenceDistance
    Coord dim((*playgroundSize) / maxInterferenceDistance + Coord(1.0, 1.0, 1.0));
    gridDim = GridCoord(dim);
    //A grid smaller or equal to 3x3 whould mean that every cell has every other cell as direct
    //neighbor (if our playground is a torus, even if not the most of the cells are direct
    //neighbors of each other. So we reduce the grid size to 1x1.
    if((gridDim.x <= 3) && (gridDim.y <= 3) && (gridDim.z <= 3))
    {
      gridDim.x = 1;
      gridDim.y = 1;
      gridDim.z = 1;
    }
    //step 2 - initialize the matrix which represents our grid
    NicEntries entries;
    RowVector row;
    NicMatrix matrix;
    for (int i = 0; i < gridDim.z; ++i) {
      row.push_back(entries);         //copy empty NicEntries to RowVector
    }
    for (int i = 0; i < gridDim.y; ++i) { //fill the ColVector with copies of
      matrix.push_back(row);          //the RowVector.
    }
    for (int i = 0; i < gridDim.x; ++i) { //fill the grid with copies of
      nicGrid.push_back(matrix);        //the matrix.
    }
    ccEV << " using " << gridDim.x << "x" <<
               gridDim.y << "x" <<
               gridDim.z << " grid" << endl;
    //step 3 -  calculate the factor which maps the coordinate of a node
    //      to the grid cell
    if (gridDim.x == 1 &&                       //if we use a 1x1 grid
      gridDim.y == 1 &&                       //every coordinate is
      gridDim.z == 1) {                       //mapped to (1,1, 1)
      findDistance = FWMath::max(playgroundSize->getX(),        //so the factor is the
                     FWMath::max(playgroundSize->getY(),  //largest number a
                           playgroundSize->getZ())) //coordinate can get (+1)
               + 1.0;
    } else {
      findDistance = ceil(maxInterferenceDistance);   //otherwise the factor is our
      if(findDistance == maxInterferenceDistance)     //maxInterferenceDistance
        findDistance += EPSILON;                  //plus a small epsilon
    }
    ccEV << "findDistance is " << findDistance << endl;
  }
}
virtual int BaseConnectionManager::numInitStages () const [inline, virtual]
Definition at line 323 of file BaseConnectionManager.h.
{
    return 2;
  }
bool BaseConnectionManager::registerNic (cModule * nic, ChannelAccess * chAccess, const Coord * nicPos)
Registers a nic to have its connections managed by ConnectionManager.
If you want to do your own stuff at the registration of a nic see "registerNicExt()".
Definition at line 258 of file BaseConnectionManager.cc.
References ccEV, NicEntry::chAccess, coreDebug, NicEntry::hostId, NicEntry::nicId, NicEntry::nicPtr, nics, NicEntry::pos, registerNicExt(), sendDirect, and updateConnections().
Referenced by ChannelAccess::receiveBBItem().
{
  assert(nic != 0);
  int nicID = nic->getId();
  ccEV << " registering nic #" << nicID << endl;
  // create new NicEntry
  NicEntry *nicEntry;
  if(sendDirect)
    nicEntry = new NicEntryDirect(coreDebug);
  else
    nicEntry = new NicEntryDebug(coreDebug);
  // fill nicEntry
  nicEntry->nicPtr = nic;
  nicEntry->nicId = nicID;
  nicEntry->hostId = nic->getParentModule()->getId();
  nicEntry->pos = nicPos;
  nicEntry->chAccess = chAccess;
  // add to map
  nics[nicID] = nicEntry;
  registerNicExt(nicID);
  updateConnections(nicID, nicPos, nicPos);
  return sendDirect;
}
void BaseConnectionManager::registerNicExt (int nicID) [protected, virtual]
Called by "registerNic()" after the nic has been registered. That means that the NicEntry for the nic has already been created and added to nics map.
You better know what you are doing if you want to override this method. Most time you won't need to.
See ConnectionManager::registerNicExt() for an example.
Parameters:
nicID - the id of the NicEntry
Definition at line 116 of file BaseConnectionManager.cc.
References ccEV, getCellEntries(), getCellForCoordinate(), BaseConnectionManager::BaseConnectionManager::GridCoord::info(), nics, and NicEntry::pos.
Referenced by registerNic().
{
  NicEntry* nicEntry = nics[nicID];
  GridCoord cell = getCellForCoordinate(nicEntry->pos);
  ccEV <<" registering (ext) nic at loc " << cell.info() << std::endl;
  // add to matrix
  NicEntries& cellEntries = getCellEntries(cell);
    cellEntries[nicID] = nicEntry;
}
void BaseConnectionManager::updateConnections (int nicID, const Coord * oldPos, const Coord * newPos) [protected, virtual]
Updates the connections of the nic with "nicID".
This method is called by "updateNicPos()" after the new Position is stored in the corresponding nic.
Most time you won't need to override this method.
Parameters:
nicID the id of the NicEntry
oldPos the old position of the nic
newPos the new position of the nic
Definition at line 104 of file BaseConnectionManager.cc.
References checkGrid(), and getCellForCoordinate().
Referenced by registerNic(), and updateNicPos().
{
  GridCoord oldCell = getCellForCoordinate(*oldPos);
    GridCoord newCell = getCellForCoordinate(*newPos);
  checkGrid(oldCell, newCell, nicID );
}
void BaseConnectionManager::updateNicConnections (NicEntries & nmap, NicEntry * nic) [private]
Manages the connections of a registered nic.
Definition at line 217 of file BaseConnectionManager.cc.
References ccEV, NicEntry::connectTo(), NicEntry::disconnectFrom(), NicEntry::isConnected(), maxDistSquared, NicEntry::nicId, playgroundSize, NicEntry::pos, Coord::sqrdist(), Coord::sqrTorusDist(), and useTorus.
Referenced by checkGrid().
{
    int id = nic->nicId;
    for(NicEntries::iterator i = nmap.begin(); i != nmap.end(); ++i)
    {
    NicEntry* nic_i = i->second;
        // no recursive connections
        if ( nic_i->nicId == id ) continue;
    double distance;
        if(useTorus)
        {
          distance = nic->pos.sqrTorusDist(nic_i->pos, playgroundSize);
        } else {
          distance = nic->pos.sqrdist(nic_i->pos);
        }
        bool inRange = (distance <= maxDistSquared);
        bool connected = nic->isConnected(nic_i);
        if ( inRange && !connected ){
            // nodes within communication range: connect
            // nodes within communication range && not yet connected
            ccEV << "nic #" << id << " and #" << nic_i->nicId << " are in range" << endl;
            nic->connectTo( nic_i );
            nic_i->connectTo( nic );
        }
        else if ( !inRange && connected ){
            // out of range: disconnect
            // out of range, and still connected
            ccEV << "nic #" << id << " and #" << nic_i->nicId << " are NOT in range" << endl;
            nic->disconnectFrom( nic_i );
            nic_i->disconnectFrom( nic );
        }
    }
}
void BaseConnectionManager::updateNicPos (int nicID, const Coord * newPos)
Updates the position information of a registered nic.
Definition at line 290 of file BaseConnectionManager.cc.
References nics, NicEntry::pos, and updateConnections().
Referenced by ChannelAccess::receiveBBItem().
{
  NicEntry* nicEntry = nics[nicID];
  if(nicEntry == 0)
    error("No nic with this ID is registered with this ConnectionManager.");
    Coord oldPos = nicEntry->pos;
    nicEntry->pos = newPos;
  updateConnections(nicID, &oldPos, newPos);
}
int BaseConnectionManager::wrapIfTorus (int value, int max) [private]
If the value is outside of its bounds (zero and max) this function returns -1 if useTorus is false and the wrapped value if useTorus is true. Otherwise its just returns the value unchanged.
Definition at line 171 of file BaseConnectionManager.cc.
References useTorus.
Referenced by fillUnionWithNeighbors().
{
  if(value < 0) {
    if(useTorus) {
      return max + value;
    } else {
      return -1;
    }
  } else if(value >= max) {
    if(useTorus) {
      return value - max;
    } else {
      return -1;
    }
  } else {
    return value;
  }
}
Member Data Documentation
bool BaseConnectionManager::coreDebug [protected]
Set debugging for the basic module.
Definition at line 206 of file BaseConnectionManager.h.
Referenced by initialize(), and registerNic().
double BaseConnectionManager::findDistance [protected]
Distance that helps to find a node under a certain position.
Can be larger then
See also:
maxInterferenceDistance to allow nodes to be placed into the same square if the playground is too small for the grid speedup to work.
Definition at line 245 of file BaseConnectionManager.h.
Referenced by getCellForCoordinate(), and initialize().
GridCoord BaseConnectionManager::gridDim [protected]
The size of the grid.
Definition at line 248 of file BaseConnectionManager.h.
Referenced by checkGrid(), fillUnionWithNeighbors(), and initialize().
double BaseConnectionManager::maxDistSquared [protected]
Square of maxInterferenceDistance cache a value that is often used.
Definition at line 219 of file BaseConnectionManager.h.
Referenced by initialize(), and updateNicConnections().
double BaseConnectionManager::maxInterferenceDistance [protected]
the biggest interference distance in the network.
Definition at line 215 of file BaseConnectionManager.h.
Referenced by initialize().
NicCube BaseConnectionManager::nicGrid [protected]
Registry of all nics.
This matrix keeps all nics according to their position. It allows to restrict the position update to a subset of all nics.
Definition at line 235 of file BaseConnectionManager.h.
Referenced by getCellEntries(), and initialize().
NicEntries BaseConnectionManager::nics [protected]
Definition at line 203 of file BaseConnectionManager.h.
Referenced by getGateList(), getOutGateTo(), registerNic(), registerNicExt(), updateNicPos(), and ~BaseConnectionManager().
const Coord* BaseConnectionManager::playgroundSize [protected]
Stores the size of the playground.
Definition at line 212 of file BaseConnectionManager.h.
Referenced by initialize(), and updateNicConnections().
bool BaseConnectionManager::sendDirect [protected]
Does the ConnectionManager use sendDirect or not?
Definition at line 209 of file BaseConnectionManager.h.
Referenced by initialize(), and registerNic().
bool BaseConnectionManager::useTorus [protected]
Stores the useTorus flag of the WorldUtility.
Definition at line 222 of file BaseConnectionManager.h.
Referenced by initialize(), updateNicConnections(), and wrapIfTorus().
The documentation for this class was generated from the following files:
base/connectionManager/BaseConnectionManager.h
base/connectionManager/BaseConnectionManager.cc