MiXiM: BaseModule Class Reference
BaseModule Class Reference
[baseModules - base module classes of MiXiM]
Base class for all simple modules of a host that want to have access to the BaseUtility module.
#include <BaseModule.h>
Inherits ImNotifiable.
Inherited by BaseArp, BaseBattery, BatteryAccess, BatteryStats, RepeatTimerCore, SimpleMacLayer, SimpleNetwLayer, and TimerCore.
Public Member Functions
BaseModule ()
virtual void initialize (int)
Basic initialization for all modules.
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void)
Function to get the logging name of the host.
cModule * getNode ()
Get a reference to the local node module.
virtual void receiveBBItem (int category, const BBItem *details, int scopeModuleId)
Called by the Blackboard whenever a change of a category occurs to which we have subscribed. Redefined from ImNotifiable. In this base class just handle the host state switching and some debug notifications.
Protected Member Functions
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule * findHost (void)
Function to get a pointer to the host module.
std::string getLogName (int)
Function to get the logging name of id.
Protected Attributes
BaseUtility * utility
Cached pointer to the utility module.
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state. If not explicitly set this module has to capture changes in the host state.
int hostStateCat
Stores the category of the HostState.
int hostId
The hosts id.
Detailed Description
Base class for all simple modules of a host that want to have access to the BaseUtility module.
BaseModule listens for HostState changes broadcasted over BaseUtility and calls its own "handleHostState()" method. This method raises an error if the host state changes to something else than ACTIVE. Therefore that a sub-classing module can be used in a simulation where the host state can change it has to override that method which forces the author to make sure the module reacts well to host state changes. Alternatively one can also set a "notAffectedByHostState" parameter of the module to true.
The base module additionally provides a function findHost which returns a pointer to the host module and a function hostIndex to return the index of the host module. The latter one correspondes to the index shown in tkenv and comes in very handy for testing and debugging using tkenv. It is used e.g. in all the 'print' macros used for debugging.
There will never be a stand-alone BaseModule module.
Note: most modules wont derive from BaseModule directly but from its sub class "BatteryAccess" which extends BaseModule by several methods for accessing the battery module.
See also:
BaseUtility
BatteryAccess
Author:
Steffen Sroka
Andreas Koepke
Definition at line 78 of file BaseModule.h.
Constructor & Destructor Documentation
BaseModule::BaseModule ()
Definition at line 25 of file BaseModule.cc.
                      :
  cSimpleModule(),
  utility(NULL)
{}
Member Function Documentation
cModule * BaseModule::findHost (void) [protected]
Function to get a pointer to the host module.
Definition at line 86 of file BaseModule.cc.
Referenced by getNode(), SimpleBattery::initialize(), BatteryStats::initialize(), SimpleMacLayer::initialize(), SamplePhyLayer::initialize(), initialize(), BaseMobility::initialize(), BaseLayer::initialize(), ChannelAccess::initialize(), PhyLayer::initializeDecider80211(), PhyLayerBattery::initializeDecider80211Battery(), PhyLayer::initializeSNRThresholdDecider(), logName(), and BatteryAccess::registerWithBattery().
{
   return FindModule<>::findHost(this);
}
std::string BaseModule::getLogName (int id) [protected]
Function to get the logging name of id.
This function returns the logging name of the module with the specified id. It can be used for logging messages to simplify debugging in TKEnv.
Only supports ids from simple module derived from the BaseModule or the nic compound module id.
Parameters:
id Id of the module for the desired logging name
Returns:
logging name of module id or NULL if not found
See also:
logName
Definition at line 104 of file BaseModule.cc.
References logName().
{
    BaseModule *mod;
    std::string lname;
    mod = check_and_cast<BaseModule *>(simulation.getModule(id));
    if (mod->isSimple()) {
        lname = mod->logName();
    }
    else if(mod->getSubmodule("phy")) {
        lname = check_and_cast<BaseModule *>(mod->getSubmodule("phy"))->logName();
    }
    return lname;
};
cModule* BaseModule::getNode () [inline]
Get a reference to the local node module.
Definition at line 164 of file BaseModule.h.
References findHost().
Referenced by SimpleNetwLayer::broadcastHelloWorld(), SimpleNetwLayer::handleHelloWorld(), SimpleNetwLayer::handleIncomingJabber(), FrameTimerGenerator::init(), and SimpleNetwLayer::jabberToSomeone().
                       {
      return findHost();
    };
void BaseModule::handleHostState (const HostState & state) [protected, virtual]
Called whenever the hosts state changes.
Default implementation of this method throws an error whenever the host state changes and the "notAffectedbyHostState" variable is not explicitly set. This is because every module of a host has to make sure to react well to changes in the host state. Or it has to explicitly set its parameter "notAffectedbyHostState" to true.
Reimplemented in BurstApplLayerBattery, PhyLayerBattery, and SimpleBattery.
Definition at line 66 of file BaseModule.cc.
References HostState::ACTIVE, HostState::get(), and notAffectedByHostState.
Referenced by receiveBBItem().
{
  if(notAffectedByHostState)
    return;
  if(state.get() != HostState::ACTIVE) {
    error("Hosts state changed to something else than active which"
        " is not handled by this module. Either handle this state"
        " correctly or if this module really isn't affected by the"
        " hosts state set the parameter \"notAffectedByHostState\""
        " of this module to true.");
  }
}
void BaseModule::initialize (int stage) [virtual]
Basic initialization for all modules.
Subscription to Blackboard should be in stage==0, and firing notifications in stage==1 or later.
NOTE: You have to call this in the initialize() function of the inherited class!
Reimplemented in ChannelAccess, BaseApplLayer, BaseArp, BaseLayer, BaseMacLayer, BaseMobility, BaseNetwLayer, TestApplLayer, BasePhyLayer, SamplePhyLayer, SimpleMacLayer, SimpleNetwLayer, BurstApplLayer, BurstApplLayerBattery, CSMAMacLayer, Mac80211, ANSimMobility, BonnMotionMobility, CircleMobility, ConstSpeedMobility, LinearMobility, MassMobility, RectangleMobility, TractorMobility, TurtleMobility, PhyLayerBattery, BatteryStats, and SimpleBattery.
Definition at line 37 of file BaseModule.cc.
References debug, findHost(), hostId, hostStateCat, notAffectedByHostState, BaseUtility::subscribe(), and utility.
{
    if (stage == 0) {
      notAffectedByHostState =  hasPar("notAffectedByHostState")
                 && par("notAffectedByHostState").boolValue();
        hasPar("debug") ? debug = par("debug").boolValue() : debug = false;
        utility = FindModule<BaseUtility*>::findSubModule(findHost());
        if(!utility) {
          error("No BaseUtility module found!");
        }
        hostId = findHost()->getId();
        /* host failure notification */
    HostState hs;
    hostStateCat = utility->subscribe(this, &hs, hostId);
    }
}
std::string BaseModule::logName (void)
Function to get the logging name of the host.
The logging name is the ned module name of the host (unless the host ned variable loggingName is specified). It can be used for logging messages to simplify debugging in TKEnv.
Definition at line 119 of file BaseModule.cc.
References findHost().
Referenced by getLogName().
{
        std::ostringstream ost;
  if (hasPar("logName")) // let modules override
  {
    ost << par("logName").stringValue();
  }
  else
  {
    cModule *parent = findHost();
    parent->hasPar("logName") ?
      ost << parent->par("logName").stringValue() : ost << parent->getName();
    ost << "[" << parent->getIndex() << "]";
  }
  return ost.str();
}
virtual int BaseModule::numInitStages () const [inline, virtual]
Divide initialization into two stages.
In the first stage (stage==0), modules subscribe to notification categories at Blackboard. The first notifications (e.g. about the initial values of some variables such as RadioState) should take place earliest in the second stage (stage==1), when everyone interested in them has already subscribed.
Definition at line 148 of file BaseModule.h.
{
      return 2;
    }
void BaseModule::receiveBBItem (int category, const BBItem * details, int scopeModuleId) [virtual]
Called by the Blackboard whenever a change of a category occurs to which we have subscribed. Redefined from ImNotifiable. In this base class just handle the host state switching and some debug notifications.
Implements ImNotifiable.
Reimplemented in ChannelAccess, and BatteryStats.
Definition at line 57 of file BaseModule.cc.
References handleHostState(), and hostStateCat.
{
  Enter_Method_Silent();
  if (category == hostStateCat) {
    handleHostState(*(HostState*)details);
  }
}
void BaseModule::switchHostState (HostState::States state) [protected]
Switches the host to the passed state.
This is a convenience method for publishing the host state to BaseUtility.
If the hosts state is switched to anything else than "ACTIVE" every module of the host has to handle this explicitly (see method "handleHostState()")!
Definition at line 80 of file BaseModule.cc.
References hostId, hostStateCat, BaseUtility::publishBBItem(), and utility.
{
  HostState hostState(state);
  utility->publishBBItem(hostStateCat, &hostState, hostId);
}
Member Data Documentation
bool BaseModule::debug [protected]
Debug switch for all other modules.
Definition at line 84 of file BaseModule.h.
Referenced by BaseArp::getMacAddr(), and initialize().
int BaseModule::hostId [protected]
The hosts id.
Reimplemented in BaseLayer, and BaseMobility.
Definition at line 97 of file BaseModule.h.
Referenced by initialize(), and switchHostState().
int BaseModule::hostStateCat [protected]
Stores the category of the HostState.
Reimplemented in SimpleBattery.
Definition at line 94 of file BaseModule.h.
Referenced by initialize(), receiveBBItem(), and switchHostState().
bool BaseModule::notAffectedByHostState [protected]
Stores if this module is affected by changes in the hosts state. If not explicitly set this module has to capture changes in the host state.
Definition at line 91 of file BaseModule.h.
Referenced by handleHostState(), and initialize().
BaseUtility* BaseModule::utility [protected]
Cached pointer to the utility module.
Definition at line 81 of file BaseModule.h.
Referenced by SimpleBattery::deductAndCheck(), PhyLayerBattery::handleAirFrame(), SimpleBattery::handleMessage(), PhyLayerBattery::handleUpperMessage(), SimpleBattery::initialize(), BatteryStats::initialize(), initialize(), BaseMobility::initialize(), BaseLayer::initialize(), ChannelAccess::initialize(), BaseLayer::recordPacket(), switchHostState(), and BaseMobility::updatePosition().
The documentation for this class was generated from the following files:
base/modules/BaseModule.h
base/modules/BaseModule.cc