MiXiM: ConstDelayedMapping Class Reference
ConstDelayedMapping Class Reference
[mappingDetails - mostly internal mapping classes]
Moves another ConstMapping in its time dimension.
#include <MappingUtils.h>
Inherits BaseDelayedMapping< ConstMapping >.
Public Member Functions
ConstDelayedMapping (ConstMapping *mapping, simtime_t delay)
virtual ~ConstDelayedMapping ()
virtual ConstMapping * constClone () const
returns a deep copy of this mapping instance.
Detailed Description
Moves another ConstMapping in its time dimension.
See propagation delay effect of the signal for an example how to use this mapping.
Author:
Karl Wessel
Definition at line 2195 of file MappingUtils.h.
Constructor & Destructor Documentation
ConstDelayedMapping::ConstDelayedMapping (ConstMapping * mapping, simtime_t delay) [inline]
Definition at line 2197 of file MappingUtils.h.
Referenced by constClone().
                                                             :
    BaseDelayedMapping<ConstMapping>(mapping, delay) {}
virtual ConstDelayedMapping::~ConstDelayedMapping () [inline, virtual]
Definition at line 2200 of file MappingUtils.h.
{}
Member Function Documentation
virtual ConstMapping* ConstDelayedMapping::constClone () const [inline, virtual]
returns a deep copy of this mapping instance.
Implements ConstMapping.
Definition at line 2202 of file MappingUtils.h.
References ConstMapping::constClone(), ConstDelayedMapping(), BaseDelayedMapping< ConstMapping >::delay, and BaseDelayedMapping< ConstMapping >::mapping.
{
    return new ConstDelayedMapping(mapping->constClone(), delay);
  }
The documentation for this class was generated from the following file:
base/phyLayer/MappingUtils.h