MiXiM: BatteryState Class Reference
BatteryState Class Reference
[BaseUtility - blackboard related stuff, Power consumption - Classes using/defining power consumption]
residual capacity of battery
#include <BatteryState.h>
Inherits BBItem.
Public Member Functions
BatteryState (double n=-1)
double getRel () const
residual capacity of battery (relative to nominal capacity)
double getAbs () const
residual capacity of battery (in mW-s)
void set (double s)
std::string info () const
Protected Attributes
double nominal
nominal battery capacity in mW-s (mA-s at nominal voltage)
double absolute
remaining battery capacity in mW-s
Private Member Functions
BBITEM_METAINFO (BBItem)
Detailed Description
residual capacity of battery
BatteryState is passed to BatteryStats and should not be used by non-statistics modules. Value may be read as absolute or relative (to nominal) capacity.
Definition at line 31 of file BatteryState.h.
Constructor & Destructor Documentation
BatteryState::BatteryState (double n = -1) [inline]
Definition at line 42 of file BatteryState.h.
                            : BBItem(), nominal(n) {
  };
Member Function Documentation
BatteryState::BBITEM_METAINFO (BBItem) [private]
double BatteryState::getAbs () const [inline]
residual capacity of battery (in mW-s)
Definition at line 51 of file BatteryState.h.
References absolute.
Referenced by SimpleBattery::deductAndCheck(), SimpleBattery::estimateResidualAbs(), and SimpleBattery::estimateResidualRelative().
{
    return absolute;
  }
double BatteryState::getRel () const [inline]
residual capacity of battery (relative to nominal capacity)
Definition at line 46 of file BatteryState.h.
References absolute, and nominal.
{
    return absolute/nominal;
  }
std::string BatteryState::info () const [inline]
Definition at line 59 of file BatteryState.h.
References absolute, and nominal.
{
    std::ostringstream ost;
    ost << " battery at "<<  (absolute/nominal) * 100 <<"%";
    return ost.str();
  }
void BatteryState::set (double s) [inline]
Definition at line 55 of file BatteryState.h.
References absolute.
Referenced by SimpleBattery::deductAndCheck(), and SimpleBattery::initialize().
                     {
    absolute = s;
  }
Member Data Documentation
double BatteryState::absolute [protected]
remaining battery capacity in mW-s
Definition at line 39 of file BatteryState.h.
Referenced by getAbs(), getRel(), info(), and set().
double BatteryState::nominal [protected]
nominal battery capacity in mW-s (mA-s at nominal voltage)
Definition at line 37 of file BatteryState.h.
Referenced by getRel(), and info().
The documentation for this class was generated from the following file:
modules/power/battery/BatteryState.h