MiXiM: InterpolateableMap< Key, V, Interpolator > Class Template Reference
InterpolateableMap< Key, V, Interpolator > Class Template Reference
[mappingDetails - mostly internal mapping classes]
Represents a std::map which is able to interpolate.
#include <Interpolation.h>
Public Types
typedef std::map< Key, V > map_type
typedef map_type::const_iterator const_iterator
typedef map_type::iterator iterator
typedef map_type::value_type value_type
typedef
InterpolateableIterator< Key,
V, map_type, Interpolator > intpl_iterator
typedef
ConstInterpolateableIterator
< Key, V, const map_type,
typename
map_type::const_iterator,
Interpolator > const_intpl_iterator
typedef Interpolated< V > interpolated
Public Member Functions
InterpolateableMap ()
InterpolateableMap (V oorv)
void setOutOfRangeVal (V oorv)
interpolated getIntplValue (const Key &pos) const
const_intpl_iterator findIntpl (const Key &pos) const
const_intpl_iterator beginIntpl () const
intpl_iterator findIntpl (const Key &pos)
intpl_iterator beginIntpl ()
Protected Attributes
Interpolator interpolate
Detailed Description
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>>
class InterpolateableMap< Key, V, Interpolator >
Represents a std::map which is able to interpolate.
Returns interpolated values if accessed at position without keys.
Used to represent Mappings
Author:
Karl Wessel
See also:
Mapping
Definition at line 560 of file Interpolation.h.
Member Typedef Documentation
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> typedef ConstInterpolateableIterator<Key, V, const map_type, typename map_type::const_iterator, Interpolator> InterpolateableMap< Key, V, Interpolator >::const_intpl_iterator
Definition at line 569 of file Interpolation.h.
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> typedef map_type::const_iterator InterpolateableMap< Key, V, Interpolator >::const_iterator
Definition at line 563 of file Interpolation.h.
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> typedef Interpolated<V> InterpolateableMap< Key, V, Interpolator >::interpolated
Definition at line 570 of file Interpolation.h.
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> typedef InterpolateableIterator<Key, V, map_type, Interpolator> InterpolateableMap< Key, V, Interpolator >::intpl_iterator
Definition at line 566 of file Interpolation.h.
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> typedef map_type::iterator InterpolateableMap< Key, V, Interpolator >::iterator
Definition at line 564 of file Interpolation.h.
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> typedef std::map<Key, V> InterpolateableMap< Key, V, Interpolator >::map_type
Definition at line 562 of file Interpolation.h.
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> typedef map_type::value_type InterpolateableMap< Key, V, Interpolator >::value_type
Definition at line 565 of file Interpolation.h.
Constructor & Destructor Documentation
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> InterpolateableMap< Key, V, Interpolator >::InterpolateableMap () [inline]
Definition at line 577 of file Interpolation.h.
{}
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> InterpolateableMap< Key, V, Interpolator >::InterpolateableMap (V oorv) [inline]
Definition at line 579 of file Interpolation.h.
                            :
    interpolate(oorv) {}
Member Function Documentation
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> intpl_iterator InterpolateableMap< Key, V, Interpolator >::beginIntpl () [inline]
Definition at line 621 of file Interpolation.h.
{
    intpl_iterator it(*this, interpolate);
    return it;
  }
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> const_intpl_iterator InterpolateableMap< Key, V, Interpolator >::beginIntpl () const [inline]
Definition at line 607 of file Interpolation.h.
Referenced by TimeMapping< Interpolator >::createIterator().
{
    const_intpl_iterator it(this->begin(), this->end, interpolate);
    return it;
  }
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> intpl_iterator InterpolateableMap< Key, V, Interpolator >::findIntpl (const Key & pos) [inline]
Definition at line 613 of file Interpolation.h.
{
    intpl_iterator it(*this, interpolate);
    it.jumpTo(pos);
    return it;
  }
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> const_intpl_iterator InterpolateableMap< Key, V, Interpolator >::findIntpl (const Key & pos) const [inline]
Definition at line 599 of file Interpolation.h.
Referenced by TimeMapping< Interpolator >::createIterator().
{
    const_intpl_iterator it(this->begin(), this->end(), interpolate);
    it.jumpTo(pos);
    return it;
  }
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> interpolated InterpolateableMap< Key, V, Interpolator >::getIntplValue (const Key & pos) const [inline]
Definition at line 586 of file Interpolation.h.
Referenced by TimeMapping< Interpolator >::getValue().
{
    //if(this->empty())
    //  return interpolated(V(), true);
    const_iterator it = this->upper_bound(pos);
    //if(it != this->end() && it->first == pos)
    //  return interpolated(it->second, false);
    return interpolate(this->begin(), this->end(), pos, it);
  }
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> void InterpolateableMap< Key, V, Interpolator >::setOutOfRangeVal (V oorv) [inline]
Definition at line 582 of file Interpolation.h.
{
    interpolate.setOutOfRangeVal(oorv);
  }
Member Data Documentation
template<class Key, class V, class Interpolator = NextSmaller<Key, V, typename std::map<Key, V>::value_type, typename std::map<Key, V>::const_iterator>> Interpolator InterpolateableMap< Key, V, Interpolator >::interpolate [protected]
Definition at line 574 of file Interpolation.h.
Referenced by InterpolateableMap< double, Mapping *, Linear< double, Mapping *, std::map< double, Mapping * >::value_type, std::map< double, Mapping * >::const_iterator > >::beginIntpl(), InterpolateableMap< double, Mapping *, Linear< double, Mapping *, std::map< double, Mapping * >::value_type, std::map< double, Mapping * >::const_iterator > >::findIntpl(), InterpolateableMap< double, Mapping *, Linear< double, Mapping *, std::map< double, Mapping * >::value_type, std::map< double, Mapping * >::const_iterator > >::getIntplValue(), and InterpolateableMap< double, Mapping *, Linear< double, Mapping *, std::map< double, Mapping * >::value_type, std::map< double, Mapping * >::const_iterator > >::setOutOfRangeVal().
The documentation for this class was generated from the following file:
base/phyLayer/Interpolation.h