MiXiM: ConstMappingIterator Class Reference
ConstMappingIterator Class Reference
[mapping - classes representing mathematical mappings]
Defines an const iterator for a ConstMapping which is able to iterate over the Mapping.
#include <MappingBase.h>
Inherited by BaseFilteredIterator< ConstMappingIterator >, MappingIterator, RSAMConstMappingIterator, and SimpleConstMappingIterator.
Public Member Functions
virtual ~ConstMappingIterator ()
virtual const Argument & getNextPosition () const =0
Returns the position the next call to "next()" of this Iterator would iterate to.
virtual void jumpTo (const Argument &pos)=0
Lets the iterator point to the passed position.
virtual void jumpToBegin ()=0
Lets the iterator point to the begin of the mapping.
virtual void iterateTo (const Argument &pos)=0
Iterates to the specified position. This method should be used if the new position is near the current position. Furthermore the new position has to be compared bigger than the old position.
virtual void next ()=0
Iterates to the next position of the Mapping.
virtual bool inRange () const =0
Returns true if the current position of the iterator is in range of the function.
virtual bool hasNext () const =0
Returns true if the iterator has a next value it can iterate to on a call to "next()".
virtual const Argument & getPosition () const =0
Returns the current position of the iterator.
virtual double getValue () const =0
Returns the value of the Mapping at the current position.
Detailed Description
Defines an const iterator for a ConstMapping which is able to iterate over the Mapping.
Iterators provide a fast way to iterate over every "entry" or important position of a Mapping. They also provide constant complexity for accessing the Mapping at the position of the Iterator.
Every implementation of an mapping-Iterator provides the same ordering when iterating over a Mapping. This is that, if the iterator is increased, the position of the entry it points to has to be also "increased". Which means that the new position has to be compared bigger than the previous position (see class Argument for comparison of positions).
"Const" means that you can not change the values of the underlying Mapping with this iterator.
Author:
Karl Wessel
Definition at line 505 of file MappingBase.h.
Constructor & Destructor Documentation
virtual ConstMappingIterator::~ConstMappingIterator () [inline, virtual]
Definition at line 507 of file MappingBase.h.
{}
Member Function Documentation
virtual const Argument& ConstMappingIterator::getNextPosition () const [pure virtual]
Returns the position the next call to "next()" of this Iterator would iterate to.
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, BaseFilteredIterator< MappingIterator >, BaseFilteredIterator< ConstMappingIterator >, and MultiDimMappingIterator< Linear >.
Referenced by SNRThresholdDecider::checkIfAboveThreshold(), MappingUtils::findMax(), MappingUtils::findMin(), ConstMappingIteratorWrapper::getNextPosition(), and MappingUtils::iterateToNext().
virtual const Argument& ConstMappingIterator::getPosition () const [pure virtual]
Returns the current position of the iterator.
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, BaseFilteredIterator< MappingIterator >, BaseFilteredIterator< ConstMappingIterator >, and MultiDimMappingIterator< Linear >.
Referenced by MappingUtils::applyElementWiseOperator(), SNRThresholdDecider::checkIfAboveThreshold(), MappingUtils::createCompatibleMapping(), FilledUpMapping::FilledUpMapping(), MappingUtils::findMax(), MappingUtils::findMin(), ConstMappingIteratorWrapper::getPosition(), LinearIntplMappingIterator::getPosition(), MappingUtils::iterateToNext(), LinearIntplMappingIterator::LinearIntplMappingIterator(), ConstMapping::print(), ThresholdDecider::printMapping(), and MultiDimMappingIterator< Linear >::updateNextPosition().
virtual double ConstMappingIterator::getValue () const [pure virtual]
Returns the value of the Mapping at the current position.
The complexity of this method should be constant for every implementation.
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, BaseFilteredIterator< MappingIterator >, BaseFilteredIterator< ConstMappingIterator >, and MultiDimMappingIterator< Linear >.
Referenced by MappingUtils::applyElementWiseOperator(), SNRThresholdDecider::checkIfAboveThreshold(), Decider80211::checkIfSignalOk(), FilledUpMapping::FilledUpMapping(), MappingUtils::findMax(), MappingUtils::findMin(), ConstMappingIteratorWrapper::getValue(), LinearIntplMappingIterator::getValue(), ThresholdDecider::handleSignalOver(), and ConstMapping::print().
virtual bool ConstMappingIterator::hasNext () const [pure virtual]
Returns true if the iterator has a next value it can iterate to on a call to "next()".
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, BaseFilteredIterator< MappingIterator >, BaseFilteredIterator< ConstMappingIterator >, and MultiDimMappingIterator< Linear >.
Referenced by SNRThresholdDecider::checkIfAboveThreshold(), MappingUtils::createCompatibleMapping(), FilledUpMapping::FilledUpMapping(), MappingUtils::findMax(), MappingUtils::findMin(), ThresholdDecider::handleSignalOver(), ConstMappingIteratorWrapper::hasNext(), MappingUtils::iterateToNext(), ConstMapping::print(), and ThresholdDecider::printMapping().
virtual bool ConstMappingIterator::inRange () const [pure virtual]
Returns true if the current position of the iterator is in range of the function.
This method should be used as end-condition when iterating over the function with the "next()" method.
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, BaseFilteredIterator< MappingIterator >, BaseFilteredIterator< ConstMappingIterator >, and MultiDimMappingIterator< Linear >.
Referenced by MappingUtils::applyElementWiseOperator(), MappingUtils::createCompatibleMapping(), FilledUpMapping::FilledUpMapping(), MappingUtils::findMax(), MappingUtils::findMin(), ThresholdDecider::handleSignalOver(), ConstMappingIteratorWrapper::inRange(), ConstMapping::print(), and ThresholdDecider::printMapping().
virtual void ConstMappingIterator::iterateTo (const Argument & pos) [pure virtual]
Iterates to the specified position. This method should be used if the new position is near the current position. Furthermore the new position has to be compared bigger than the old position.
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, BaseFilteredIterator< MappingIterator >, BaseFilteredIterator< ConstMappingIterator >, and MultiDimMappingIterator< Linear >.
Referenced by MappingUtils::applyElementWiseOperator(), SNRThresholdDecider::checkIfAboveThreshold(), MappingUtils::findMax(), MappingUtils::findMin(), ConstMappingIteratorWrapper::iterateTo(), LinearIntplMappingIterator::iterateTo(), and MappingUtils::iterateToNext().
virtual void ConstMappingIterator::jumpTo (const Argument & pos) [pure virtual]
Lets the iterator point to the passed position.
The passed new position can be at arbitrary places.
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, BaseFilteredIterator< MappingIterator >, BaseFilteredIterator< ConstMappingIterator >, and MultiDimMappingIterator< Linear >.
Referenced by MappingUtils::applyElementWiseOperator(), ConstMappingIteratorWrapper::jumpTo(), and LinearIntplMappingIterator::jumpTo().
virtual void ConstMappingIterator::jumpToBegin () [pure virtual]
Lets the iterator point to the begin of the mapping.
The beginning of the mapping depends on the implementation. With an implementation based on a number of key-entries, this could be the key entry with the smallest position (see class Argument for ordering of positions).
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, BaseFilteredIterator< MappingIterator >, BaseFilteredIterator< ConstMappingIterator >, and MultiDimMappingIterator< Linear >.
Referenced by ConstMappingIteratorWrapper::jumpToBegin().
virtual void ConstMappingIterator::next () [pure virtual]
Iterates to the next position of the Mapping.
The next position depends on the implementation of the Mapping. With an implementation based on a number of key-entries this probably would be the next bigger key-entry.
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, BaseFilteredIterator< MappingIterator >, BaseFilteredIterator< ConstMappingIterator >, and MultiDimMappingIterator< Linear >.
Referenced by SNRThresholdDecider::checkIfAboveThreshold(), Decider80211::checkIfSignalOk(), MappingUtils::createCompatibleMapping(), FilledUpMapping::FilledUpMapping(), MappingUtils::findMax(), MappingUtils::findMin(), ThresholdDecider::handleSignalOver(), MappingUtils::iterateToNext(), ConstMappingIteratorWrapper::next(), ConstMapping::print(), and ThresholdDecider::printMapping().
The documentation for this class was generated from the following file:
base/phyLayer/MappingBase.h