MiXiM: FilledUpMapping Class Reference
FilledUpMapping Class Reference
[mappingDetails - mostly internal mapping classes]
Takes a source ConstMapping with a domain A and a set of KeyEntries for a domain B and creates a clone of the source mapping with the domain B and the KeyEntries passed.
#include <MappingUtils.h>
Inherits MultiDimMapping< Linear >.
Public Types
typedef std::set< double > KeySet
typedef std::map< Dimension,
KeySet > KeyMap
Public Member Functions
FilledUpMapping (ConstMapping *source, const DimensionSet &dims, const KeyMap *keys)
virtual ~FilledUpMapping ()
virtual void appendValue (const Argument &pos, double value)
Appends the passed value at the passed position to the mapping. This method assumes that the passed position is after the last key entry of the mapping.
virtual MappingIterator * createIterator ()
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change the value the iterator points to.
virtual MappingIterator * createIterator (const Argument &pos)
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change the value the iterator points to.
Protected Member Functions
void fillRefIfNecessary ()
FilledUpMapping (const DimensionSet &myDims, Dimension myDim, const KeyMap *keys, InterpolationMethod intpl=STEPS)
Mapping * createSubSignal () const
Internal helper method which creates a new sub-mapping for this MultiDimMapping instance.
Protected Attributes
Mapping * fillRef
const KeyMap * keys
Detailed Description
Takes a source ConstMapping with a domain A and a set of KeyEntries for a domain B and creates a clone of the source mapping with the domain B and the KeyEntries passed.
This class is used by "applyElementWiseOperator()"-method to be able to handle cases where the second mappings domain is a real subset of the first mappings domain (meaning the first mappings domain has the same dimensions as the seconds domain and at least one further dimension).
Author:
Karl Wessel
Definition at line 1628 of file MappingUtils.h.
Member Typedef Documentation
typedef std::map<Dimension, KeySet > FilledUpMapping::KeyMap
Definition at line 1632 of file MappingUtils.h.
typedef std::set<double> FilledUpMapping::KeySet
Definition at line 1631 of file MappingUtils.h.
Constructor & Destructor Documentation
FilledUpMapping::FilledUpMapping (const DimensionSet & myDims, Dimension myDim, const KeyMap * keys, InterpolationMethod intpl = STEPS) [inline, protected]
Definition at line 1654 of file MappingUtils.h.
References fillRefIfNecessary().
Referenced by createSubSignal().
                                                                                                                     :
    MultiDimMapping<Linear>(myDims, myDim, intpl), fillRef(0), keys(keys)
  {
    fillRefIfNecessary();
  }
FilledUpMapping::FilledUpMapping (ConstMapping * source, const DimensionSet & dims, const KeyMap * keys) [inline]
Definition at line 1669 of file MappingUtils.h.
References appendValue(), ConstMapping::createConstIterator(), fillRefIfNecessary(), ConstMappingIterator::getPosition(), ConstMappingIterator::getValue(), ConstMappingIterator::hasNext(), ConstMappingIterator::inRange(), and ConstMappingIterator::next().
                                                                                     :
    MultiDimMapping<Linear>(dims), fillRef(0), keys(keys)
  {
    ConstMappingIterator* it = source->createConstIterator();
    if(it->inRange())
    {
      fillRefIfNecessary();
      while(it->inRange()){
        appendValue(it->getPosition(), it->getValue());
        if(!it->hasNext())
          break;
        it->next();
      }
    }
    delete it;
    keys = 0;
  }
virtual FilledUpMapping::~FilledUpMapping () [inline, virtual]
Definition at line 1693 of file MappingUtils.h.
References MultiDimMapping< Linear >::entries, and fillRef.
{
    if(fillRef != 0){
      delete fillRef;
      entries.clear();
    }
  }
Member Function Documentation
virtual void FilledUpMapping::appendValue (const Argument & pos, double value) [inline, virtual]
Appends the passed value at the passed position to the mapping. This method assumes that the passed position is after the last key entry of the mapping.
Depending on the implementation of the underlying method this method could be faster or at least as fast as the "setValue()"-method.
Implementations of the Mapping interface can override this method if appending values to the end of the mapping could be implemented faster than the "setValue()" method. Otherwise this method just calls the "setValue()"-method implementation.
Reimplemented from Mapping.
Definition at line 1700 of file MappingUtils.h.
References Mapping::appendValue(), createSubSignal(), MultiDimMapping< Linear >::entries, fillRef, Argument::getArgValue(), keys, and MultiDimMapping< Linear >::myDimension.
Referenced by FilledUpMapping().
{
    assert(keys != 0);
    if(fillRef != 0)
    {
      fillRef->appendValue(pos, value);
    }
    else
    {
      double argVal = pos.getArgValue(myDimension);
      SubFunctionMap::iterator posIt = entries.lower_bound(argVal);
      if(posIt == entries.end() || posIt->first != argVal) {
        Mapping* subF = createSubSignal();
        posIt = entries.insert(posIt, SubFunctionMap::value_type(argVal, subF));
      }
      posIt->second->appendValue(pos, value);
    }
  }
virtual MappingIterator* FilledUpMapping::createIterator (const Argument & pos) [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change the value the iterator points to.
The caller of this method has to delete the Iterator if not needed anymore.
Reimplemented from MultiDimMapping< Linear >.
Definition at line 1727 of file MappingUtils.h.
{
    return new FilledUpMappingIterator(*this, pos);
  }
virtual MappingIterator* FilledUpMapping::createIterator () [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change the value the iterator points to.
The caller of this method has to delete the Iterator if not needed anymore.
Reimplemented from MultiDimMapping< Linear >.
Definition at line 1723 of file MappingUtils.h.
{
    return new FilledUpMappingIterator(*this);
  }
Mapping* FilledUpMapping::createSubSignal () const [inline, protected]
Internal helper method which creates a new sub-mapping for this MultiDimMapping instance.
Reimplemented from MultiDimMapping< Linear >.
Definition at line 1660 of file MappingUtils.h.
References ConstMapping::dimensions, FilledUpMapping(), keys, Mapping::LINEAR, MultiDimMapping< Linear >::myDimension, and Dimension::time.
Referenced by appendValue(), and fillRefIfNecessary().
{
    DimensionSet::const_iterator it = dimensions.find(myDimension);
    Dimension nextDim = *(--it);
    if(nextDim == Dimension::time)
      return new TimeMapping<Linear>();
    else
      return new FilledUpMapping(dimensions, nextDim, keys, LINEAR);
  }
void FilledUpMapping::fillRefIfNecessary () [inline, protected]
Definition at line 1639 of file MappingUtils.h.
References createSubSignal(), MultiDimMapping< Linear >::entries, fillRef, keys, and MultiDimMapping< Linear >::myDimension.
Referenced by FilledUpMapping().
{
    KeyMap::const_iterator it = keys->find(myDimension);
    if(it == keys->end())
      return;
    fillRef = createSubSignal();
    for (KeySet::const_iterator keyIt = it->second.begin();
       keyIt != it->second.end(); ++keyIt)
    {
      entries.insert(entries.end(), SubFunctionMap::value_type(*keyIt, fillRef));
    }
  }
Member Data Documentation
Mapping* FilledUpMapping::fillRef [protected]
Definition at line 1634 of file MappingUtils.h.
Referenced by appendValue(), fillRefIfNecessary(), and ~FilledUpMapping().
const KeyMap* FilledUpMapping::keys [protected]
Definition at line 1635 of file MappingUtils.h.
Referenced by appendValue(), createSubSignal(), and fillRefIfNecessary().
The documentation for this class was generated from the following file:
base/phyLayer/MappingUtils.h