MiXiM: MacToPhyInterface Class Reference
MacToPhyInterface Class Reference
[macLayer - MAC layer modules, phyLayer - physical layer modules]
Defines the methods provided by the phy to the mac layer.
#include <MacToPhyInterface.h>
Inherited by BasePhyLayer.
Public Types
enum BasePhyMessageKinds {
TX_OVER = 22000, RADIO_SWITCHING_OVER, CHANNEL_SENSE_REQUEST, AIR_FRAME,
LAST_BASE_PHY_KIND
}
Public Member Functions
virtual ~MacToPhyInterface ()
virtual int getRadioState ()=0
Returns the current state the radio is in. See RadioState for possible values.
virtual simtime_t setRadioState (int rs)=0
Tells the BasePhyLayer to switch to the specified radio state.
virtual ChannelState getChannelState ()=0
Returns the current state of the channel. See ChannelState for details.
Detailed Description
Defines the methods provided by the phy to the mac layer.
Definition at line 17 of file MacToPhyInterface.h.
Member Enumeration Documentation
enum MacToPhyInterface::BasePhyMessageKinds
Enumerator:
TX_OVER Indicates the end of a send transmission.
RADIO_SWITCHING_OVER Indicates the end of a radio switch.
CHANNEL_SENSE_REQUEST Channel sense control message between Mac and Phy.
AIR_FRAME AirFrame kind
LAST_BASE_PHY_KIND Stores the id on which classes extending BasePhy should continue their own kinds.
Definition at line 20 of file MacToPhyInterface.h.
{
    TX_OVER = 22000,
    RADIO_SWITCHING_OVER,
    CHANNEL_SENSE_REQUEST,
    AIR_FRAME,
    LAST_BASE_PHY_KIND,
  };
Constructor & Destructor Documentation
virtual MacToPhyInterface::~MacToPhyInterface () [inline, virtual]
Definition at line 36 of file MacToPhyInterface.h.
{}
Member Function Documentation
virtual ChannelState MacToPhyInterface::getChannelState () [pure virtual]
Returns the current state of the channel. See ChannelState for details.
Implemented in BasePhyLayer.
Referenced by Mac80211::beginNewCycle(), and CSMAMacLayer::handleSelfMsg().
virtual int MacToPhyInterface::getRadioState () [pure virtual]
Returns the current state the radio is in. See RadioState for possible values.
This method is mainly used by the mac layer.
Implemented in BasePhyLayer.
Referenced by Mac80211::handleLowerControl(), CSMAMacLayer::handleLowerControl(), Mac80211::handleLowerMsg(), SimpleMacLayer::handleMessage(), CSMAMacLayer::handleSelfMsg(), and CSMAMacLayer::scheduleBackoff().
virtual simtime_t MacToPhyInterface::setRadioState (int rs) [pure virtual]
Tells the BasePhyLayer to switch to the specified radio state.
The switching process can take some time depending on the specified switching times in the ned file. The return value is the time needed to switch to the specified state, or smaller zero if the radio could not be switched (propably because it is already switching.
Implemented in BasePhyLayer.
Referenced by Mac80211::handleEndContentionTimer(), Mac80211::handleEndSifsTimer(), Mac80211::handleLowerControl(), CSMAMacLayer::handleLowerControl(), SimpleMacLayer::handleMacPkt(), CSMAMacLayer::handleSelfMsg(), SimpleMacLayer::handleTXOver(), and SimpleMacLayer::initialize().
The documentation for this class was generated from the following file:
base/phyLayer/MacToPhyInterface.h