MiXiM: BaseUtility Class Reference
BaseUtility Class Reference
[BaseUtility - blackboard related stuff, baseModules - base module classes of MiXiM]
Provides a blackboard like information distribution.
#include <BaseUtility.h>
Inherits ImNotifiable.
Classes
class Subscriber
Public Member Functions
void handleMessage (cMessage *msg)
This modules should only receive self-messages.
virtual void initialize (int)
Initializes mobility model parameters.
const Coord * getPos ()
Delete dynamically allocated objects.
const HostState & getHostState ()
Get the current HostState.
virtual void receiveBBItem (int category, const BBItem *details, int scopeModuleId)
virtual ~BaseUtility ()
virtual int numInitStages () const
Methods for consumers of change notifications
int subscribe (ImNotifiable *client, const BBItem *category, int scopeModuleId=-1)
int subscribe (ImNotifiable *client, int category, int scopeModuleId=-1)
void unsubscribe (ImNotifiable *client, int category)
Methods for producers of change notifications
void publishBBItem (int category, const BBItem *details, int scopeModuleId)
int getCategory (const BBItem *details)
Protected Types
typedef std::vector< Subscriber > SubscriberVector
typedef std::vector
< SubscriberVector > ClientVector
typedef std::vector< const char * > CategoryDescriptions
typedef std::vector< int > ParentVector
typedef ClientVector::iterator ClientVectorIter
typedef
CategoryDescriptions::iterator DescriptionsIter
typedef ParentVector::iterator ParentVectorIter
Protected Member Functions
cModule * findHost (void)
Function to get a pointer to the host module.
const char * categoryName (int category)
int findAndCreateDescription (bool *isNewEntry, const BBItem *category)
void fillParentVector (const BBItem *category, int cat)
Protected Attributes
ClientVector clientVector
CategoryDescriptions categoryDescriptions
ParentVector parentVector
int nextCategory
int catMove
BBItem category number of Move.
int catHostState
BBItem category number of HostState.
HostState hostState
The hosts current state.
Private Attributes
bool coreDebug
Coord pos
Friends
std::ostream & operator<< (std::ostream &, const SubscriberVector &)
Detailed Description
Provides a blackboard like information distribution.
This file has been merged from BaseUtility.h and Blackboard.h in order to bring Blackboard's functionality to BaseUtility.
Blackboard's comments have been copied since they describe the migrated functionality. In protocol simulations, one often has to evaluate the performance of a protocol. This implies that not only the protocol has to be developed, but also the code used for the performance evaluation. Often, this leads to ugly implementations: real protocol code is mixed with debug and performance evaluation code. This mix becomes annoying if the code is made public to the community.
Another, somewhat similar, problem appears if programmers want to implement new protocols that integrate information from other protocol layers. Usually, researchers have to reimplement at least parts of the protocol tp expose the necessary information -- making it less useful for other researchers as this usually increases the coupling of the protocols.
One way around both problems is a black board. On the black board, protocols publish their state and possible state changes. It is now possible to separate performance monitors from the protocol code. Also, cross-layer information exchange also boils down to publishing and subscribing information -- without introducing tight coupling. The only commonly known entity is the blackboard.
The interaction with the blackboard is simple:
publisher -publish(BBItem)-> Blackboard -notify(BBItem)--> subscriber
The publisher can be anything that knows how to call a Blackboard and how to construct a proper BBItem. It remains the logical owner of the published item. The BB neither stores it, nor keeps any reference to it.
The subscriber must implement the ImNotifiable interface. It can keep a copy of the published item (cache it), but it should not keep a reference to it. Otherwise, things become really messy. (Some code written for older versions of the BB speaks for itself).
See also:
ImNotifiable
Author:
Andras Varga
Andreas Koepke
Definition at line 73 of file BaseUtility.h.
Member Typedef Documentation
typedef std::vector<const char* > BaseUtility::CategoryDescriptions [protected]
Definition at line 103 of file BaseUtility.h.
typedef std::vector<SubscriberVector> BaseUtility::ClientVector [protected]
Definition at line 101 of file BaseUtility.h.
typedef ClientVector::iterator BaseUtility::ClientVectorIter [protected]
Definition at line 107 of file BaseUtility.h.
typedef CategoryDescriptions::iterator BaseUtility::DescriptionsIter [protected]
Definition at line 108 of file BaseUtility.h.
typedef std::vector<int> BaseUtility::ParentVector [protected]
Definition at line 105 of file BaseUtility.h.
typedef ParentVector::iterator BaseUtility::ParentVectorIter [protected]
Definition at line 109 of file BaseUtility.h.
typedef std::vector<Subscriber> BaseUtility::SubscriberVector [protected]
Definition at line 100 of file BaseUtility.h.
Constructor & Destructor Documentation
BaseUtility::~BaseUtility () [virtual]
Definition at line 43 of file BaseUtility.cc.
{
}
Member Function Documentation
const char * BaseUtility::categoryName (int category) [protected]
find the description of a category
Definition at line 116 of file BaseUtility.cc.
References categoryDescriptions.
Referenced by publishBBItem(), subscribe(), and unsubscribe().
{
    if(categoryDescriptions.size() < static_cast<unsigned>(category)) {
        error("BaseUtility::categoryName called with unknown category (%i)", category);
    }
    return categoryDescriptions[category];
}
void BaseUtility::fillParentVector (const BBItem * category, int cat) [protected]
traverse inheritance diagramm and make sure that children of category are also delivered to modules that susbcribed to one of its parent classes.
Definition at line 154 of file BaseUtility.cc.
References findAndCreateDescription(), BBItem::parentObject(), and parentVector.
Referenced by getCategory(), and subscribe().
{
    bool isNewEntry = true;
    int it;
    BBItem *parentObject;
    BBItem base;
    parentObject = category->parentObject();
    if(typeid(*parentObject) != typeid(base)) {
        it = findAndCreateDescription(&isNewEntry, parentObject);
        parentVector[cat] = it;
        fillParentVector(parentObject, it);
    }
    delete parentObject;
}
int BaseUtility::findAndCreateDescription (bool * isNewEntry, const BBItem * category) [protected]
find or create a category, returns iterator in map and sets isNewEntry to true if the entry was created new.
Definition at line 124 of file BaseUtility.cc.
References categoryDescriptions, clientVector, nextCategory, and parentVector.
Referenced by fillParentVector(), getCategory(), and subscribe().
{
    CategoryDescriptions::size_type it;
    std::string desc = category->getClassName();
    std::string cName;
    for(it = 0; it < categoryDescriptions.size(); ++it)
    {
        cName = categoryDescriptions[it];
        if(cName == desc) {
            (*isNewEntry) = false;
            break;
        }
    }
    if(it == categoryDescriptions.size()) {
        (*isNewEntry) = true;
        categoryDescriptions.push_back(category->getClassName());
        it = categoryDescriptions.size() - 1;
        clientVector.push_back(SubscriberVector());
        if(it != clientVector.size()-1)
            error("BaseUtility::findAndCreateDescription SubscriberVector creation failed");
        parentVector.push_back(-1);
        if(it != parentVector.size()-1)
            error("BaseUtility::findAndCreateDescription ParentVector creation failed");
        nextCategory = categoryDescriptions.size();
    }
    return static_cast<int>(it);
}
cModule * BaseUtility::findHost (void) [protected]
Function to get a pointer to the host module.
Definition at line 74 of file BaseUtility.cc.
Referenced by initialize().
{
  return FindModule<>::findHost(this);
}
int BaseUtility::getCategory (const BBItem * details)
Get the category from the BB -- if you don't want to subscribe but rather publish
Definition at line 265 of file BaseUtility.cc.
References coreDebug, fillParentVector(), and findAndCreateDescription().
Referenced by SimpleBattery::initialize(), BaseMobility::initialize(), and BaseLayer::initialize().
{
    if(coreDebug) {
        Enter_Method("getCategory(%s)", details?details->getClassName():"n/a");
    } else {
        Enter_Method_Silent();
    }
    int category = -1;
    bool isNewEntry;
    if(details) {
        category = findAndCreateDescription(&isNewEntry, details);
        if(isNewEntry) fillParentVector(details, category);
    } else {
        error("BaseUtility::getCategory called without category item");
    }
    return category;
}
const HostState& BaseUtility::getHostState () [inline]
Get the current HostState.
Definition at line 163 of file BaseUtility.h.
References hostState.
Referenced by PhyLayerBattery::handleAirFrame(), and PhyLayerBattery::handleUpperMessage().
{ return hostState; }
const Coord* BaseUtility::getPos () [inline]
Delete dynamically allocated objects.
Get current position
Definition at line 160 of file BaseUtility.h.
References pos.
{return &pos;}
void BaseUtility::handleMessage (cMessage * msg)
This modules should only receive self-messages.
Definition at line 79 of file BaseUtility.cc.
{
  error("This module does not handle any messages yet");
}
void BaseUtility::initialize (int stage) [virtual]
Initializes mobility model parameters.
Definition at line 49 of file BaseUtility.cc.
References HostState::ACTIVE, categoryDescriptions, catHostState, catMove, clientVector, coreDebug, findHost(), hostState, nextCategory, parentVector, HostState::set(), and subscribe().
{
  //BaseModule::initialize(stage);
  if (stage == 0) {
    hasPar("coreDebug") ? coreDebug = par("coreDebug").boolValue() : coreDebug = false;
//BB start
    WATCH_VECTOR(clientVector);
      WATCH_VECTOR(categoryDescriptions);
      clientVector.clear();
      categoryDescriptions.clear();
      parentVector.clear();
      nextCategory = 0;
//BB end
        // subscribe to position changes
        Move moveBBItem;
        catMove = subscribe(this, &moveBBItem, findHost()->getId());
        catHostState = subscribe(this, &hostState, findHost()->getId());
        hostState.set(HostState::ACTIVE);
  }
}
virtual int BaseUtility::numInitStages () const [inline, virtual]
Definition at line 241 of file BaseUtility.h.
{
    return 2;
  }
void BaseUtility::publishBBItem (int category, const BBItem * details, int scopeModuleId)
Tells Blackboard that a change of the given category has taken place. The optional details object (
See also:
BBItem) may carry more specific information about the change (e.g. exact location, specific attribute that changed, old value, new value, etc).
This function is very central once you start working with the blackboard. You should heed the following advices:
Publish in stage 1 of initialize after everbody was able to subscribe.
This function should be the last thing you call in a method. There is a chance that a certain race condition occurs, as in the following case, for simplicity the module is subscribed to the value that it publishes: -- Module::myMethod: lock module; publishBBItem; unlock module -- Module::receiveBBItem: if module not locked, do something Since receiveBBItem is called from within publishBBItem, the module will always be locked and the code in receiveBBItem is never executed.
Definition at line 241 of file BaseUtility.cc.
References categoryName(), clientVector, coreDebug, and parentVector.
Referenced by SimpleBattery::deductAndCheck(), SimpleBattery::handleMessage(), SimpleBattery::initialize(), BaseLayer::recordPacket(), BaseModule::switchHostState(), and BaseMobility::updatePosition().
{
    if(coreDebug) {
        Enter_Method("publish(%s, %s, %i)", categoryName(category),
                     details?details->info().c_str() : "n/a", scopeModuleId);
    } else {
        Enter_Method_Silent();
    }
    int pCat;
    if(clientVector.size() > 0) {
        SubscriberVector::const_iterator j;
        for (j=clientVector[category].begin(); j!=clientVector[category].end(); ++j)
        {
            if(((*j).scopeModuleId == -1) || ((*j).scopeModuleId == scopeModuleId))
            {
                (*j).client->receiveBBItem(category, details, scopeModuleId);
            }
        }
        pCat = parentVector[category];
        if(pCat >= 0) publishBBItem(pCat, details, scopeModuleId);
    }
}
void BaseUtility::receiveBBItem (int category, const BBItem * details, int scopeModuleId) [virtual]
We want to receive Moves and HostStates from BaseUtility to synchronize hostPosition and -state.
BaseUtility subscribes itself to position and host state changes to synchronize the hostPosition and -state.
Implements ImNotifiable.
Definition at line 95 of file BaseUtility.cc.
References catHostState, catMove, coreEV, hostState, HostState::info(), Move::info(), pos, and Move::startPos.
{
    //BaseModule::receiveBBItem(category, details, scopeModuleId);
    if(category == catMove)
    {
        const Move* m = static_cast<const Move*>(details);
        pos = m->startPos;
        coreEV << "new HostMove: " << m->info() << endl;
    }
    else if(category == catHostState)
    {
      const HostState* state = static_cast<const HostState*>(details);
    hostState = *state;
    coreEV << "new HostState: " << hostState.info() << endl;
    }
}
int BaseUtility::subscribe (ImNotifiable * client, int category, int scopeModuleId = -1)
Subscribe to changes of a specific category. This time using the numeric id. This implies that you have previously called subscribe with the apprpriate category class.
Both subscribe functions subscribe also to children of this category class.
Subscribe in stage 0 of initialize -- this way you get all publishes that happen at stage 1.
Definition at line 174 of file BaseUtility.cc.
References categoryName(), clientVector, and coreDebug.
{
    if(coreDebug) {
        Enter_Method("subscribe(%s, %i)", categoryName(category), scopeModuleId);
    } else {
        Enter_Method_Silent();
    }
    // find or create entry for this category
    SubscriberVector& clients = clientVector[category];
    SubscriberVector::const_iterator it;
    for(it = clients.begin(); it != clients.end(); ++it) {
        if((*it).client == client) {
            std::string cname("unkown");
            cModule *cm = dynamic_cast<cModule *>(client);
            if(cm) cname = cm->getFullPath();
            error("BaseUtility::subscribe called twice for item %s, by client %s. \nThis probably means that a class from which you derived yours has \nalready subscribed to this item. This may result in conflicts, please check.\n ", categoryName(category), cname.c_str());
            break;
        }
    }
    // add client if not already there
    if (it == clients.end()) {
        clients.push_back(Subscriber(client, scopeModuleId));
    }
    return category;
}
int BaseUtility::subscribe (ImNotifiable * client, const BBItem * category, int scopeModuleId = -1)
Subscribe to changes of a specific category. The category is defined by the BBItem class to which this object belongs. Returns the id of this category.
Both subscribe functions subscribe also to children of this category class.
Definition at line 201 of file BaseUtility.cc.
References coreDebug, fillParentVector(), and findAndCreateDescription().
Referenced by BatteryStats::initialize(), initialize(), BaseModule::initialize(), and ChannelAccess::initialize().
{
    if(coreDebug) {
        Enter_Method("subscribe(%s, %i)", category?category->getClassName() : "n/a",
                     scopeModuleId);
    } else {
        Enter_Method_Silent();
    }
    CategoryDescriptions::size_type it = 0;
    bool isNewEntry;
    if(category) {
        it = findAndCreateDescription(&isNewEntry, category);
        if(isNewEntry) fillParentVector(category, static_cast<int>(it));
        subscribe(client, static_cast<int>(it), scopeModuleId);
    }
    else {
        error("BaseUtility::subscribe called without category item");
    }
    return static_cast<int>(it);
}
void BaseUtility::unsubscribe (ImNotifiable * client, int category)
Unsubscribe from notifications
Definition at line 223 of file BaseUtility.cc.
References categoryName(), clientVector, and coreDebug.
{
    if(coreDebug) {
        Enter_Method("unsubscribe(%s)", categoryName(category));
    } else {
        Enter_Method_Silent();
    }
    // find (or create) entry for this category
    SubscriberVector& clients = clientVector[category];
    // remove client if there
    SubscriberVector::iterator it;
    for(it = clients.begin(); it != clients.end(); ++it) {
        if((*it).client == client) clients.erase(it);
        break;
    }
}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const SubscriberVector & v) [friend]
Definition at line 15 of file BaseUtility.cc.
{
    os << v.size() << " client(s) ";
    BaseUtility::SubscriberVector::const_iterator it;
    for (it = v.begin(); it != v.end(); ++it)
    {
        os << (it == v.begin() ? ": " : ", ");
        if (dynamic_cast<cModule*>((*it).client))
        {
            cModule *mod = dynamic_cast<cModule*>((*it).client);
            os << "mod (" << mod->getClassName() << ") " << mod->getFullName() << " id=" << mod->getId();
        }
        else if (dynamic_cast<cObject*>((*it).client))
        {
            cObject *obj = dynamic_cast<cObject*>((*it).client);
            os << "a " << obj->getClassName();
        }
        else
        {
            os << "a " << opp_typename(typeid((*it).client));
        }
        os << " scope: " << (*it).scopeModuleId;
    }
    return os;
}
Member Data Documentation
CategoryDescriptions BaseUtility::categoryDescriptions [protected]
Definition at line 112 of file BaseUtility.h.
Referenced by categoryName(), findAndCreateDescription(), and initialize().
int BaseUtility::catHostState [protected]
BBItem category number of HostState.
Definition at line 124 of file BaseUtility.h.
Referenced by initialize(), and receiveBBItem().
int BaseUtility::catMove [protected]
BBItem category number of Move.
Definition at line 121 of file BaseUtility.h.
Referenced by initialize(), and receiveBBItem().
ClientVector BaseUtility::clientVector [protected]
Definition at line 111 of file BaseUtility.h.
Referenced by findAndCreateDescription(), initialize(), publishBBItem(), subscribe(), and unsubscribe().
bool BaseUtility::coreDebug [private]
Definition at line 77 of file BaseUtility.h.
Referenced by getCategory(), initialize(), publishBBItem(), subscribe(), and unsubscribe().
HostState BaseUtility::hostState [protected]
The hosts current state.
Definition at line 127 of file BaseUtility.h.
Referenced by getHostState(), initialize(), and receiveBBItem().
int BaseUtility::nextCategory [protected]
Definition at line 115 of file BaseUtility.h.
Referenced by findAndCreateDescription(), and initialize().
ParentVector BaseUtility::parentVector [protected]
Definition at line 113 of file BaseUtility.h.
Referenced by fillParentVector(), findAndCreateDescription(), initialize(), and publishBBItem().
Coord BaseUtility::pos [private]
The position of the Host. This coordinate is synchronized with BaseMobility.
Definition at line 83 of file BaseUtility.h.
Referenced by getPos(), and receiveBBItem().
The documentation for this class was generated from the following files:
base/modules/BaseUtility.h
base/modules/BaseUtility.cc