MiXiM: Mapping Class Reference
Mapping Class Reference
[mapping - classes representing mathematical mappings]
Represents a changeable mapping (mathematical function) from at least time to double.
#include <MappingBase.h>
Inherits ConstMapping.
Inherited by BaseDelayedMapping< Mapping >, ConstMappingWrapper, LinearIntplMapping, MultiDimMapping< Interpolator >, MultiDimMapping< Linear >, and TimeMapping< Interpolator >.
Public Types
enum InterpolationMethod { STEPS, NEAREST, LINEAR }
Public Member Functions
Mapping (const DimensionSet &dims)
Initializes the Mapping with the passed DimensionSet as domain.
Mapping ()
Initializes the Mapping with the time dimension as domain.
virtual ~Mapping ()
virtual void setValue (const Argument &pos, double value)=0
Changes the value of the Mapping at the specified position.
virtual void appendValue (const Argument &pos, double value)
Appends the passed value at the passed position to the mapping. This method assumes that the passed position is after the last key entry of the mapping.
virtual MappingIterator * createIterator ()=0
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change it.
virtual MappingIterator * createIterator (const Argument &pos)=0
Returns a pointer of a new Iterator which is able to iterate over the function and can change it.
virtual ConstMappingIterator * createConstIterator ()
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
virtual ConstMappingIterator * createConstIterator (const Argument &pos)
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
virtual Mapping * clone () const =0
Returns a deep copy of this Mapping.
virtual ConstMapping * constClone () const
Returns a deep const copy of this mapping by using the according "clone()"-implementation.
Detailed Description
Represents a changeable mapping (mathematical function) from at least time to double.
This class extends the ConstMapping interface with write access.
See ConstMapping for details.
Author:
Karl Wessel
Definition at line 835 of file MappingBase.h.
Member Enumeration Documentation
enum Mapping::InterpolationMethod
Enumerator:
STEPS interpolates with next lower entry
NEAREST interpolates with nearest entry
LINEAR interpolates linear with next lower and next upper entry constant before the first and after the last entry
Definition at line 837 of file MappingBase.h.
{
    STEPS,
    NEAREST,
    LINEAR
  };
Constructor & Destructor Documentation
Mapping::Mapping (const DimensionSet & dims) [inline]
Initializes the Mapping with the passed DimensionSet as domain.
The passed DimensionSet has to contain the time dimension!
Definition at line 856 of file MappingBase.h.
                                   :
    ConstMapping(dims) {}
Mapping::Mapping () [inline]
Initializes the Mapping with the time dimension as domain.
Definition at line 862 of file MappingBase.h.
           :
      ConstMapping() {}
virtual Mapping::~Mapping () [inline, virtual]
Definition at line 865 of file MappingBase.h.
{}
Member Function Documentation
virtual void Mapping::appendValue (const Argument & pos, double value) [inline, virtual]
Appends the passed value at the passed position to the mapping. This method assumes that the passed position is after the last key entry of the mapping.
Depending on the implementation of the underlying method this method could be faster or at least as fast as the "setValue()"-method.
Implementations of the Mapping interface can override this method if appending values to the end of the mapping could be implemented faster than the "setValue()" method. Otherwise this method just calls the "setValue()"-method implementation.
Reimplemented in FilledUpMapping.
Definition at line 888 of file MappingBase.h.
References setValue().
Referenced by FilledUpMapping::appendValue(), and LogNormalShadowing::filterSignal().
{
    setValue(pos, value);
  }
virtual Mapping* Mapping::clone () const [pure virtual]
Returns a deep copy of this Mapping.
Implemented in TimeMapping< Interpolator >, LinearIntplMapping, ConstMappingWrapper, MultiDimMapping< Interpolator >, DelayedMapping, and MultiDimMapping< Linear >.
Referenced by DelayedMapping::clone(), constClone(), Signal::operator=(), and Signal::Signal().
virtual ConstMapping* Mapping::constClone () const [inline, virtual]
Returns a deep const copy of this mapping by using the according "clone()"-implementation.
Implements ConstMapping.
Reimplemented in ConstMappingWrapper.
Definition at line 937 of file MappingBase.h.
References clone().
{ return clone(); }
virtual ConstMappingIterator* Mapping::createConstIterator (const Argument & pos) [inline, virtual]
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
Override this method if your ConstIterator differs from the normal iterator.
Implements ConstMapping.
Reimplemented in ConstMappingWrapper, and BaseDelayedMapping< Mapping >.
Definition at line 922 of file MappingBase.h.
References createIterator().
{
    return createIterator(pos);
  }
virtual ConstMappingIterator* Mapping::createConstIterator () [inline, virtual]
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
Override this method if your ConstIterator differs from the normal iterator.
Implements ConstMapping.
Reimplemented in ConstMappingWrapper, and BaseDelayedMapping< Mapping >.
Definition at line 912 of file MappingBase.h.
References createIterator().
Referenced by SNRThresholdDecider::checkIfAboveThreshold(), and Decider80211::checkIfSignalOk().
{
    return createIterator();
  }
virtual MappingIterator* Mapping::createIterator (const Argument & pos) [pure virtual]
Returns a pointer of a new Iterator which is able to iterate over the function and can change it.
The iterator starts at the passed position.
Implemented in TimeMapping< Interpolator >, LinearIntplMapping, ConstMappingWrapper, MultiDimMapping< Interpolator >, FilledUpMapping, DelayedMapping, and MultiDimMapping< Linear >.
virtual MappingIterator* Mapping::createIterator () [pure virtual]
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change it.
Implemented in TimeMapping< Interpolator >, LinearIntplMapping, ConstMappingWrapper, MultiDimMapping< Interpolator >, FilledUpMapping, DelayedMapping, and MultiDimMapping< Linear >.
Referenced by MappingUtils::applyElementWiseOperator(), createConstIterator(), and DelayedMapping::createIterator().
virtual void Mapping::setValue (const Argument & pos, double value) [pure virtual]
Changes the value of the Mapping at the specified position.
The complexity of this method depends on the implementation.
Implemented in TimeMapping< Interpolator >, LinearIntplMapping, ConstMappingWrapper, MultiDimMapping< Interpolator >, DelayedMapping, and MultiDimMapping< Linear >.
Referenced by appendValue(), BaseMacLayer::createConstantMapping(), SimpleMacLayer::createMapping(), Mac80211::createSignal(), BaseMacLayer::createSingleFrequencyMapping(), RandomFrequencyOnlyModel::filterSignal(), RandomFreqTimeModel::filterSignal(), and DelayedMapping::setValue().
The documentation for this class was generated from the following file:
base/phyLayer/MappingBase.h