MiXiM: ConstMappingWrapper Class Reference
ConstMappingWrapper Class Reference
[mappingDetails - mostly internal mapping classes]
Wraps an ConstMapping into a Mapping interface.
#include <MappingUtils.h>
Inherits Mapping.
Public Member Functions
ConstMappingWrapper (ConstMapping *m)
virtual void setValue (const Argument &pos, double value)
Changes the value of the Mapping at the specified position.
virtual MappingIterator * createIterator ()
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change it.
virtual MappingIterator * createIterator (const Argument &pos)
Returns a pointer of a new Iterator which is able to iterate over the function and can change it.
virtual double getValue (const Argument &pos) const
Returns the value of this Mapping at the position specified by the passed Argument.
virtual ConstMappingIterator * createConstIterator ()
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
virtual ConstMappingIterator * createConstIterator (const Argument &pos)
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
virtual ConstMapping * constClone () const
Returns a deep const copy of this mapping by using the according "clone()"-implementation.
virtual Mapping * clone () const
Returns a deep copy of this Mapping.
Protected Attributes
ConstMapping * mapping
Detailed Description
Wraps an ConstMapping into a Mapping interface.
Assumes that "setValue()" of the Mapping interface will never be called.
Author:
Karl Wessel
Definition at line 869 of file MappingUtils.h.
Constructor & Destructor Documentation
ConstMappingWrapper::ConstMappingWrapper (ConstMapping * m) [inline]
Definition at line 874 of file MappingUtils.h.
Referenced by clone().
                                      :
    Mapping(m->getDimensionSet()), mapping(m) {}
Member Function Documentation
virtual Mapping* ConstMappingWrapper::clone () const [inline, virtual]
Returns a deep copy of this Mapping.
Implements Mapping.
Definition at line 899 of file MappingUtils.h.
References ConstMapping::constClone(), ConstMappingWrapper(), and mapping.
{
    return new ConstMappingWrapper(mapping->constClone());
  }
virtual ConstMapping* ConstMappingWrapper::constClone () const [inline, virtual]
Returns a deep const copy of this mapping by using the according "clone()"-implementation.
Reimplemented from Mapping.
Definition at line 897 of file MappingUtils.h.
References ConstMapping::constClone(), and mapping.
{ return mapping->constClone(); }
virtual ConstMappingIterator* ConstMappingWrapper::createConstIterator (const Argument & pos) [inline, virtual]
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
Override this method if your ConstIterator differs from the normal iterator.
Reimplemented from Mapping.
Definition at line 893 of file MappingUtils.h.
References ConstMapping::createConstIterator(), and mapping.
{
    return mapping->createConstIterator(pos);
  }
virtual ConstMappingIterator* ConstMappingWrapper::createConstIterator () [inline, virtual]
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
Override this method if your ConstIterator differs from the normal iterator.
Reimplemented from Mapping.
Definition at line 889 of file MappingUtils.h.
References ConstMapping::createConstIterator(), and mapping.
{
    return mapping->createConstIterator();
  }
virtual MappingIterator* ConstMappingWrapper::createIterator (const Argument & pos) [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the function and can change it.
The iterator starts at the passed position.
Implements Mapping.
Definition at line 883 of file MappingUtils.h.
References ConstMapping::createConstIterator(), and mapping.
{
    return new ConstMappingIteratorWrapper(mapping->createConstIterator(pos));
  }
virtual MappingIterator* ConstMappingWrapper::createIterator () [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change it.
Implements Mapping.
Definition at line 879 of file MappingUtils.h.
References ConstMapping::createConstIterator(), and mapping.
{
    return new ConstMappingIteratorWrapper(mapping->createConstIterator());
  }
virtual double ConstMappingWrapper::getValue (const Argument & pos) const [inline, virtual]
Returns the value of this Mapping at the position specified by the passed Argument.
The complexity of this method depends on the actual implementation.
Implements ConstMapping.
Definition at line 887 of file MappingUtils.h.
References ConstMapping::getValue(), and mapping.
{ return mapping->getValue(pos); }
virtual void ConstMappingWrapper::setValue (const Argument & pos, double value) [inline, virtual]
Changes the value of the Mapping at the specified position.
The complexity of this method depends on the implementation.
Implements Mapping.
Definition at line 877 of file MappingUtils.h.
{ assert(false); }
Member Data Documentation
ConstMapping* ConstMappingWrapper::mapping [protected]
Definition at line 871 of file MappingUtils.h.
Referenced by clone(), constClone(), createConstIterator(), createIterator(), and getValue().
The documentation for this class was generated from the following file:
base/phyLayer/MappingUtils.h