MiXiM: FrameTimerGenerator Class Reference
FrameTimerGenerator Class Reference
#include <FrameTimerGenerator.h>
Public Member Functions
~FrameTimerGenerator ()
virtual void init (FrameTimer *parent)
void setFrameTimer (unsigned int index, double period)
unsigned int setFrameTimer (double period)
void cancelFrameTimer (unsigned int index)
Protected Member Functions
void nextFrame (unsigned int index)
virtual void handleMessage (cMessage *msg)
Protected Attributes
FrameTimer * ft
GlobalTime * gt
std::map< unsigned int,
cMessage * > * timers
std::map< unsigned int, double > * frames
Detailed Description
Definition at line 16 of file FrameTimerGenerator.h.
Constructor & Destructor Documentation
FrameTimerGenerator::~FrameTimerGenerator ()
Definition at line 83 of file FrameTimerGenerator.cc.
References cancelFrameTimer(), frames, and timers.
{
  for (std::map<unsigned int,cMessage*>::const_iterator p=timers->begin();p!=timers->end();p++)
  {
    cancelFrameTimer(p->second->getKind());
    delete p->second;
  }
  delete timers;
  delete  frames;
}
Member Function Documentation
void FrameTimerGenerator::cancelFrameTimer (unsigned int index)
Definition at line 69 of file FrameTimerGenerator.cc.
References frames, and timers.
Referenced by FrameTimer::cancelFrameTimer(), setFrameTimer(), and ~FrameTimerGenerator().
{
  assert(frames->find(index)!=frames->end());
  if ((*timers)[index]->isScheduled())
    cancelEvent((*timers)[index]);
  (*frames)[index] = 0;
}
void FrameTimerGenerator::handleMessage (cMessage * msg) [protected, virtual]
Definition at line 77 of file FrameTimerGenerator.cc.
References ft, FrameTimer::handleFrameTimer(), and nextFrame().
{
  ft->handleFrameTimer(msg->getKind());
  nextFrame(msg->getKind());
}
void FrameTimerGenerator::init (FrameTimer * parent) [virtual]
Definition at line 7 of file FrameTimerGenerator.cc.
References frames, ft, BaseModule::getNode(), gt, FrameTimer::owner, and timers.
Referenced by FrameTimer::init().
{
  Enter_Method_Silent();
  char * lookupname;
  ft = parent;
  if (parent->owner->hasPar("GlobalTime"))
    lookupname = strdup(parent->owner->par("GlobalTime"));
  else
    lookupname = strdup("GlobalTime");
  gt = dynamic_cast<GlobalTime*>(parent->owner->getNode()->getSubmodule(lookupname));
  if (gt == NULL)
    gt = dynamic_cast<GlobalTime*>(cModuleType::get(lookupname)->createScheduleInit(lookupname,parent->owner->getNode()));
  free(lookupname);
  frames = new std::map<unsigned int,double>;
  timers = new std::map<unsigned int, cMessage*>;
}
void FrameTimerGenerator::nextFrame (unsigned int index) [protected]
Definition at line 26 of file FrameTimerGenerator.cc.
References GlobalTime::currentGlobalTime(), frames, gt, and timers.
Referenced by handleMessage(), and setFrameTimer().
{
  simtime_t now = gt->currentGlobalTime();
  if ((*frames)[index] == 0)
    return;
  assert(frames->find(index)!=frames->end());
  simtime_t count = floor(now/(*frames)[index]);
  ev <<"scheduling at "<<count<<"," <<((count+1)*(*frames)[index])<<endl;
  scheduleAt((count+1)*(*frames)[index],(*timers)[index]);
}
unsigned int FrameTimerGenerator::setFrameTimer (double period)
Definition at line 37 of file FrameTimerGenerator.cc.
References setFrameTimer(), and timers.
{
  unsigned int key = timers->size();
  while (timers->find(key)!=timers->end())
    key++;
  setFrameTimer(key,period);
  return key;
}
void FrameTimerGenerator::setFrameTimer (unsigned int index, double period)
Definition at line 46 of file FrameTimerGenerator.cc.
References cancelFrameTimer(), nextFrame(), and timers.
Referenced by setFrameTimer(), and FrameTimer::setFrameTimer().
{
  Enter_Method_Silent();
  cMessage *timer;
  assert(period>0);
  if (timers->find(index)==timers->end())
  {
    char buffer[255];
    sprintf(buffer,"frame timer %d",index);
    timer = new cMessage();
    timer->setKind(index);
    timer->setName(buffer);
    (*timers)[index] = timer;
  }
  else
  {
    timer = (*timers)[index];
    cancelFrameTimer(index);
  }
  (*frames)[index] = period;
  nextFrame(index);
}
Member Data Documentation
std::map<unsigned int,double>* FrameTimerGenerator::frames [protected]
Definition at line 22 of file FrameTimerGenerator.h.
Referenced by cancelFrameTimer(), init(), nextFrame(), and ~FrameTimerGenerator().
FrameTimer* FrameTimerGenerator::ft [protected]
Definition at line 19 of file FrameTimerGenerator.h.
Referenced by handleMessage(), and init().
GlobalTime* FrameTimerGenerator::gt [protected]
Definition at line 20 of file FrameTimerGenerator.h.
Referenced by init(), and nextFrame().
std::map<unsigned int,cMessage *>* FrameTimerGenerator::timers [protected]
Definition at line 21 of file FrameTimerGenerator.h.
Referenced by cancelFrameTimer(), init(), nextFrame(), setFrameTimer(), and ~FrameTimerGenerator().
The documentation for this class was generated from the following files:
base/timers/FrameTimerGenerator.h
base/timers/FrameTimerGenerator.cc