MiXiM: ConcatConstMapping< Operator > Class Template Reference
ConcatConstMapping< Operator > Class Template Reference
[mappingDetails - mostly internal mapping classes]
Defines it values by concatenating one or more Mappings to a reference Mapping.
#include <MappingUtils.h>
Inherits ConstMapping.
Public Member Functions
template<class Iterator >
ConcatConstMapping (ConstMapping *refMapping, Iterator first, Iterator last, Operator op=Operator())
Initializes with the passed reference Mapping, the operator and the Mappings defined by the passed iterator.
ConcatConstMapping (ConstMapping *refMapping, ConstMapping *other, Operator op=Operator())
Initializes with the passed reference Mapping, the operator and another Mapping to concatenate.
void addMapping (ConstMapping *m)
Adds another Mapping to the list of Mappings to concatenate.
virtual double getValue (const Argument &pos) const
Returns the value of this Mapping at the position specified by the passed Argument.
Mapping * createConcatenatedMapping ()
Returns the concatenated Mapping.
virtual ConstMappingIterator * createConstIterator ()
Returns a pointer of a new Iterator which is able to iterate over this Mapping.
virtual ConstMappingIterator * createConstIterator (const Argument &pos)
Returns a pointer of a new Iterator which is able to iterate over the function. The iterator starts at the passed position.
virtual ConstMapping * constClone () const
returns a deep copy of this mapping instance.
ConstMapping * getRefMapping ()
Returns the pointer to the reference mapping.
Protected Types
typedef std::pair< Dimension,
Argument::const_iterator > DimIteratorPair
typedef std::list< ConstMapping * > MappingSet
Protected Attributes
MappingSet mappings
ConstMapping * refMapping
Operator op
Detailed Description
template<class Operator>
class ConcatConstMapping< Operator >
Defines it values by concatenating one or more Mappings to a reference Mapping.
Author:
Karl Wessel
Definition at line 1950 of file MappingUtils.h.
Member Typedef Documentation
template<class Operator > typedef std::pair<Dimension, Argument::const_iterator> ConcatConstMapping< Operator >::DimIteratorPair [protected]
Definition at line 1952 of file MappingUtils.h.
template<class Operator > typedef std::list<ConstMapping*> ConcatConstMapping< Operator >::MappingSet [protected]
Definition at line 1953 of file MappingUtils.h.
Constructor & Destructor Documentation
template<class Operator > template<class Iterator > ConcatConstMapping< Operator >::ConcatConstMapping (ConstMapping * refMapping, Iterator first, Iterator last, Operator op = Operator()) [inline]
Initializes with the passed reference Mapping, the operator and the Mappings defined by the passed iterator.
Definition at line 1964 of file MappingUtils.h.
References ConcatConstMapping< Operator >::mappings.
Referenced by ConcatConstMapping< Operator >::constClone().
                                      :
    ConstMapping(refMapping->getDimensionSet()),
    refMapping(refMapping), op(op)
  {
    while(first != last){
      mappings.push_back(*first);
      ++first;
    }
  }
template<class Operator > ConcatConstMapping< Operator >::ConcatConstMapping (ConstMapping * refMapping, ConstMapping * other, Operator op = Operator()) [inline]
Initializes with the passed reference Mapping, the operator and another Mapping to concatenate.
Definition at line 1980 of file MappingUtils.h.
References ConcatConstMapping< Operator >::mappings.
                                      :
    ConstMapping(refMapping->getDimensionSet()),
    refMapping(refMapping), op(op)
  {
    mappings.push_back(other);
  }
Member Function Documentation
template<class Operator > void ConcatConstMapping< Operator >::addMapping (ConstMapping * m) [inline]
Adds another Mapping to the list of Mappings to concatenate.
Definition at line 1992 of file MappingUtils.h.
References ConcatConstMapping< Operator >::mappings.
Referenced by Signal::addAttenuation().
{
    mappings.push_back(m);
  }
template<class Operator > virtual ConstMapping* ConcatConstMapping< Operator >::constClone () const [inline, virtual]
returns a deep copy of this mapping instance.
Implements ConstMapping.
Definition at line 2034 of file MappingUtils.h.
References ConcatConstMapping< Operator >::ConcatConstMapping().
{
    return new ConcatConstMapping(*this);
  }
template<class Operator > Mapping* ConcatConstMapping< Operator >::createConcatenatedMapping () [inline]
Returns the concatenated Mapping.
Definition at line 2012 of file MappingUtils.h.
References MappingUtils::applyElementWiseOperator(), ConcatConstMapping< Operator >::mappings, and ConcatConstMapping< Operator >::op.
Referenced by ConcatConstMapping< Operator >::createConstIterator().
{
    MappingSet::const_iterator it = mappings.begin();
    Mapping* result = MappingUtils::applyElementWiseOperator(*refMapping, **it, op);
    while(++it != mappings.end()){
      Mapping* buf = result;
      result = MappingUtils::applyElementWiseOperator(*buf, **it, op);
      delete buf;
    }
    return result;
  }
template<class Operator > virtual ConstMappingIterator* ConcatConstMapping< Operator >::createConstIterator (const Argument & pos) [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the function. The iterator starts at the passed position.
See class ConstIterator for details.
Implements ConstMapping.
Definition at line 2030 of file MappingUtils.h.
References ConcatConstMapping< Operator >::createConcatenatedMapping().
{
    return new ConcatConstMappingIterator(createConcatenatedMapping(), pos);
  }
template<class Operator > virtual ConstMappingIterator* ConcatConstMapping< Operator >::createConstIterator () [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over this Mapping.
See class ConstIterator for details.
Implements ConstMapping.
Definition at line 2026 of file MappingUtils.h.
References ConcatConstMapping< Operator >::createConcatenatedMapping().
{
    return new ConcatConstMappingIterator(createConcatenatedMapping());
  }
template<class Operator > ConstMapping* ConcatConstMapping< Operator >::getRefMapping () [inline]
Returns the pointer to the reference mapping.
Definition at line 2041 of file MappingUtils.h.
Referenced by Signal::markRcvPowerOutdated(), and Signal::~Signal().
{
    return refMapping;
  }
template<class Operator > virtual double ConcatConstMapping< Operator >::getValue (const Argument & pos) const [inline, virtual]
Returns the value of this Mapping at the position specified by the passed Argument.
The complexity of this method depends on the actual implementation.
Implements ConstMapping.
Definition at line 1996 of file MappingUtils.h.
References ConstMapping::getValue(), ConcatConstMapping< Operator >::mappings, and ConcatConstMapping< Operator >::op.
{
    MappingSet::const_iterator it = mappings.begin();
    double res = refMapping->getValue(pos);
    for (MappingSet::const_iterator it = mappings.begin();
       it != mappings.end(); ++it)
    {
      res = op(res, (*it)->getValue(pos));
    }
    return res;
  }
Member Data Documentation
template<class Operator > MappingSet ConcatConstMapping< Operator >::mappings [protected]
Definition at line 1954 of file MappingUtils.h.
Referenced by ConcatConstMapping< Operator >::addMapping(), ConcatConstMapping< Operator >::ConcatConstMapping(), ConcatConstMapping< Operator >::createConcatenatedMapping(), and ConcatConstMapping< Operator >::getValue().
template<class Operator > Operator ConcatConstMapping< Operator >::op [protected]
Definition at line 1956 of file MappingUtils.h.
Referenced by ConcatConstMapping< Operator >::createConcatenatedMapping(), and ConcatConstMapping< Operator >::getValue().
template<class Operator > ConstMapping* ConcatConstMapping< Operator >::refMapping [protected]
Definition at line 1955 of file MappingUtils.h.
The documentation for this class was generated from the following file:
base/phyLayer/MappingUtils.h