MiXiM: SimpleNetwLayer Class Reference
SimpleNetwLayer Class Reference
[CSMAMac example - Classes from the CSMAMac example]
This is an implementation of a simple network layer which provides only some simple routing (next hop) and message forwarding (only switches).
#include <SimpleNetwLayer.h>
Inherits BaseModule.
Public Member Functions
virtual void initialize (int stage)
Basic initialization for all modules.
virtual void handleMessage (cMessage *msg)
Protected Types
enum NetwPktKind { HELLO_WORLD = 4200, JABBER, START_TO_JABBER }
typedef std::map< int, int > RoutingTable
Protected Member Functions
void scheduleJabbering ()
void broadcastHelloWorld ()
void sendDown (cPacket *pkt)
void forwardPacket (NetwPkt *pkt, int nextHop)
void handleHelloWorld (NetwPkt *pkt)
void jabberToSomeone ()
void handleIncomingJabber (NetwPkt *pkt)
Protected Attributes
bool isSwitch
simtime_t boredTime
time after when the module gets bored and starts jabbering.
int maxTtl
int ip
int dataIn
int dataOut
cMessage * startJabberTimer
unsigned long runningSeqNumber
RoutingTable routingTable
Detailed Description
This is an implementation of a simple network layer which provides only some simple routing (next hop) and message forwarding (only switches).
This network layer isn't a real network layer its only purpose is to provide some message sending for the CSMA-Mac layer.
At first there is a small "saying hello"-phase where the several network layers saying hello to each other and creating their routing table.
After that phase the non-switch instances start to babbling randomly to other instances without caring if they here them. The switch instances does only provide packet forwarding from there on.
The several instanceses can bable directly to each other or over a switch instance.
Definition at line 39 of file SimpleNetwLayer.h.
Member Typedef Documentation
typedef std::map<int, int> SimpleNetwLayer::RoutingTable [protected]
Definition at line 57 of file SimpleNetwLayer.h.
Member Enumeration Documentation
enum SimpleNetwLayer::NetwPktKind [protected]
Enumerator:
HELLO_WORLD
JABBER
START_TO_JABBER
Definition at line 61 of file SimpleNetwLayer.h.
                  {
    HELLO_WORLD = 4200,
    JABBER,
    START_TO_JABBER
  };
Member Function Documentation
void SimpleNetwLayer::broadcastHelloWorld () [inline, protected]
Definition at line 77 of file SimpleNetwLayer.h.
References BaseModule::getNode(), HELLO_WORLD, ip, L2BROADCAST, L3BROADCAST, maxTtl, runningSeqNumber, and sendDown().
Referenced by initialize().
{
    assert(!ev.isDisabled());
    ev << "Broadcasting hello world.\n";
    NetwPkt* helloWorld = new NetwPkt("helloWorld", HELLO_WORLD);
    helloWorld->setDestAddr(L3BROADCAST);
    helloWorld->setSrcAddr(ip);
    helloWorld->setSeqNum(runningSeqNumber++);
    helloWorld->setTtl(maxTtl);
    MacControlInfo* cInfo = new MacControlInfo(L2BROADCAST);
    helloWorld->setControlInfo(cInfo);
    getNode()->bubble("Hello World!");
    sendDown(helloWorld);
  }
void SimpleNetwLayer::forwardPacket (NetwPkt * pkt, int nextHop) [inline, protected]
Definition at line 100 of file SimpleNetwLayer.h.
References sendDown().
Referenced by handleHelloWorld(), and handleIncomingJabber().
{
    NetwPkt* fwd = new NetwPkt(pkt->getName(), pkt->getKind());
    fwd->setDestAddr(pkt->getDestAddr());
    fwd->setSrcAddr(pkt->getSrcAddr());
    fwd->setSeqNum(pkt->getSeqNum());
    fwd->setTtl(pkt->getTtl() - 1);
    MacControlInfo* cInfo = new MacControlInfo(nextHop);
    fwd->setControlInfo(cInfo);
    sendDown(fwd);
  }
void SimpleNetwLayer::handleHelloWorld (NetwPkt * pkt) [inline, protected]
Definition at line 115 of file SimpleNetwLayer.h.
References forwardPacket(), MacControlInfo::getNextHopMac(), BaseModule::getNode(), ip, isSwitch, L2BROADCAST, routingTable, and scheduleJabbering().
Referenced by handleMessage().
{
    //who said hello?
    int srcIP = pkt->getSrcAddr();
    //we already know ourself...
    if (srcIP == ip){
      delete pkt;
      return;
    }
    //do we already know him?
    if(routingTable.count(srcIP) == 0){
      //if not add him with the mac address of the previous hop
      MacControlInfo* cInfo = static_cast<MacControlInfo*>(pkt->getControlInfo());
      int prevHop = cInfo->getNextHopMac();
      routingTable[srcIP] = prevHop;
      char buff[255];
      sprintf(buff, "Got hello from %d", srcIP);
      getNode()->bubble(buff);
      ev << buff << endl;
    }
    //if we are a switch and the time to live of the packet
    //hasn't exceeded yet forward it
    if(isSwitch){
      if(pkt->getTtl() > 0) {
        forwardPacket(pkt, L2BROADCAST);
        char buff[255];
        sprintf(buff, "%d said hello!", srcIP);
        getNode()->bubble(buff);
        ev << buff << endl;
      }
    } else {
      //otherwise reset the bored timer after when we will start jabbering
      scheduleJabbering();
    }
    delete pkt;
  }
void SimpleNetwLayer::handleIncomingJabber (NetwPkt * pkt) [inline, protected]
Definition at line 191 of file SimpleNetwLayer.h.
References forwardPacket(), BaseModule::getNode(), ip, isSwitch, and routingTable.
Referenced by handleMessage().
{
    if(isSwitch) {
      if(pkt->getDestAddr() != ip){
        assert(pkt->getTtl() > 0);
        assert(routingTable.count(pkt->getDestAddr()) > 0);
        int nextHop = routingTable[pkt->getDestAddr()];
        char buff[255];
        sprintf(buff, "%d babbles with %d", pkt->getSrcAddr(), pkt->getDestAddr());
        getNode()->bubble(buff);
        ev << buff << endl;
        forwardPacket(pkt, nextHop);
      } else {
        char buff[255];
        sprintf(buff, "%d babbles with me. But I'm a serious switch, I do not babble...", pkt->getSrcAddr());
        getNode()->bubble(buff);
        ev << buff << endl;
      }
    } else {
      assert(pkt->getDestAddr() == ip);
      char buff[255];
      sprintf(buff, "Got babbling from %d", pkt->getSrcAddr());
      getNode()->bubble(buff);
      ev << buff << endl;
    }
    delete pkt;
  }
virtual void SimpleNetwLayer::handleMessage (cMessage * msg) [inline, virtual]
Definition at line 244 of file SimpleNetwLayer.h.
References handleHelloWorld(), handleIncomingJabber(), HELLO_WORLD, JABBER, jabberToSomeone(), and START_TO_JABBER.
{
    switch(msg->getKind()){
    case HELLO_WORLD:
      handleHelloWorld(static_cast<NetwPkt*>(msg));
      break;
    case START_TO_JABBER:
      jabberToSomeone();
      break;
    case JABBER:
      handleIncomingJabber(static_cast<NetwPkt*>(msg));
      break;
    default:
      error("unknown packet type");
      break;
    }
  }
virtual void SimpleNetwLayer::initialize (int stage) [inline, virtual]
Basic initialization for all modules.
Subscription to Blackboard should be in stage==0, and firing notifications in stage==1 or later.
NOTE: You have to call this in the initialize() function of the inherited class!
Reimplemented from BaseModule.
Definition at line 224 of file SimpleNetwLayer.h.
References boredTime, broadcastHelloWorld(), dataIn, dataOut, ip, isSwitch, maxTtl, START_TO_JABBER, and startJabberTimer.
{
    if(stage == 0){
      dataOut = findGate("lowerGateOut");
      dataIn = findGate("lowerGateIn");
      isSwitch = par("isSwitch").boolValue();
      if(isSwitch)
        getParentModule()->getParentModule()->getDisplayString().setTagArg("i",0,"device/accesspoint");
      ip = par("ip").longValue();
      maxTtl = par("maxTtl").longValue();
      boredTime = par("boredTime").doubleValue();
    } else if(stage == 1) {
      startJabberTimer = new cMessage("jabber!", START_TO_JABBER);
      broadcastHelloWorld();
    }
  }
void SimpleNetwLayer::jabberToSomeone () [inline, protected]
Definition at line 159 of file SimpleNetwLayer.h.
References BaseModule::getNode(), ip, isSwitch, JABBER, maxTtl, routingTable, runningSeqNumber, scheduleJabbering(), and sendDown().
Referenced by handleMessage().
{
    assert(!isSwitch);
    assert(routingTable.size() > 0);
    int target = intrand(routingTable.size());
    RoutingTable::const_iterator it = routingTable.begin();
    for(int i = 0; i < target; ++i)
      ++it;
    ev << "Jabbering - Routingtablesize:" << routingTable.size() << "  target:" << target << "  dest:" << it->first << endl;
    NetwPkt* jabber = new NetwPkt("jabber", JABBER);
    jabber->setDestAddr(it->first);
    jabber->setSrcAddr(ip);
    jabber->setSeqNum(runningSeqNumber++);
    jabber->setTtl(maxTtl);
    MacControlInfo* cInfo = new MacControlInfo(it->second);
    jabber->setControlInfo(cInfo);
    char buff[255];
    sprintf(buff, "Babbling with %d", it->first);
    getNode()->bubble(buff);
    ev << buff << endl;
    sendDown(jabber);
    scheduleJabbering();
  }
void SimpleNetwLayer::scheduleJabbering () [inline, protected]
Definition at line 69 of file SimpleNetwLayer.h.
References boredTime, and startJabberTimer.
Referenced by handleHelloWorld(), and jabberToSomeone().
{
    if(startJabberTimer->isScheduled()){
      cancelEvent(startJabberTimer);
    }
    scheduleAt(simTime() + boredTime, startJabberTimer);
  }
void SimpleNetwLayer::sendDown (cPacket * pkt) [inline, protected]
Definition at line 96 of file SimpleNetwLayer.h.
References dataOut.
Referenced by broadcastHelloWorld(), forwardPacket(), and jabberToSomeone().
{
    send(pkt, dataOut);
  }
Member Data Documentation
simtime_t SimpleNetwLayer::boredTime [protected]
time after when the module gets bored and starts jabbering.
Definition at line 44 of file SimpleNetwLayer.h.
Referenced by initialize(), and scheduleJabbering().
int SimpleNetwLayer::dataIn [protected]
Definition at line 50 of file SimpleNetwLayer.h.
Referenced by initialize().
int SimpleNetwLayer::dataOut [protected]
Definition at line 51 of file SimpleNetwLayer.h.
Referenced by initialize(), and sendDown().
int SimpleNetwLayer::ip [protected]
Definition at line 48 of file SimpleNetwLayer.h.
Referenced by broadcastHelloWorld(), handleHelloWorld(), handleIncomingJabber(), initialize(), and jabberToSomeone().
bool SimpleNetwLayer::isSwitch [protected]
Definition at line 42 of file SimpleNetwLayer.h.
Referenced by handleHelloWorld(), handleIncomingJabber(), initialize(), and jabberToSomeone().
int SimpleNetwLayer::maxTtl [protected]
Definition at line 46 of file SimpleNetwLayer.h.
Referenced by broadcastHelloWorld(), initialize(), and jabberToSomeone().
RoutingTable SimpleNetwLayer::routingTable [protected]
Definition at line 59 of file SimpleNetwLayer.h.
Referenced by handleHelloWorld(), handleIncomingJabber(), and jabberToSomeone().
unsigned long SimpleNetwLayer::runningSeqNumber [protected]
Definition at line 55 of file SimpleNetwLayer.h.
Referenced by broadcastHelloWorld(), and jabberToSomeone().
cMessage* SimpleNetwLayer::startJabberTimer [protected]
Definition at line 53 of file SimpleNetwLayer.h.
Referenced by initialize(), and scheduleJabbering().
The documentation for this class was generated from the following file:
examples/CSMAMac/SimpleNetwLayer.h