MiXiM: ThresholdDecider Class Reference
ThresholdDecider Class Reference
[AnalogueModels example - Classes from the AnalogueModels example]
A simple Decider implementation which only checks for a received signal if the receiving power is above a certain value.
#include <ThresholdDecider.h>
Inherits Decider.
Public Member Functions
ThresholdDecider (DeciderToPhyInterface *phy, int myIndex, double threshold)
virtual simtime_t processSignal (AirFrame *frame)
this method is called by the BasePhylayer whenever it gets a AirFrame (from another phy or self scheduled).
virtual ChannelState getChannelState ()
A function that returns information about the channel state.
virtual simtime_t handleChannelSenseRequest (ChannelSenseRequest *)
This function is called by the PhyLayer to hand over a ChannelSenseRequest.
Protected Types
enum { FIRST, HEADER_OVER, SIGNAL_OVER }
Protected Member Functions
simtime_t handleNewSignal (Signal *s)
handles Signals passed the first time.
simtime_t handleHeaderOver (std::map< Signal *, int >::iterator &it)
handles the Signal when passed after after end of the header.
simtime_t handleSignalOver (std::map< Signal *, int >::iterator &it, AirFrame *frame)
handles the signal when passed at the end of the signal.
void log (std::string msg)
double toDecibel (double v)
template<class T >
std::string toString (T v, unsigned int length)
std::string toString (simtime_t v, unsigned int length)
void printMapping (ConstMapping *m)
Quick and ugly printing of a two dimensional mapping.
Protected Attributes
int myIndex
double threshold
std::map< Signal *, int > currentSignals
stores the currently receiving signals together with their current state.
Detailed Description
A simple Decider implementation which only checks for a received signal if the receiving power is above a certain value.
Note: This implementation is only meant to be as a quick and ugly Decider to demonstrate the usage of the AnalogueModels. You should not take it as template for a real Decider.
Definition at line 21 of file ThresholdDecider.h.
Member Enumeration Documentation
anonymous enum [protected]
Enumerator:
FIRST
HEADER_OVER
SIGNAL_OVER
Definition at line 31 of file ThresholdDecider.h.
       {
    FIRST,
    HEADER_OVER,
    SIGNAL_OVER
  };
Constructor & Destructor Documentation
ThresholdDecider::ThresholdDecider (DeciderToPhyInterface * phy, int myIndex, double threshold) [inline]
Definition at line 246 of file ThresholdDecider.h.
                                                                             :
    Decider(phy), myIndex(myIndex), threshold(threshold) {}
Member Function Documentation
virtual ChannelState ThresholdDecider::getChannelState () [inline, virtual]
A function that returns information about the channel state.
It is an alternative for the MACLayer in order to obtain information immediately (in contrast to sending a ChannelSenseRequest, i.e. sending a cMessage over the OMNeT-control-channel)
Reimplemented from Decider.
Definition at line 282 of file ThresholdDecider.h.
{
    return ChannelState(false, 0);
  }
virtual simtime_t ThresholdDecider::handleChannelSenseRequest (ChannelSenseRequest * request) [inline, virtual]
This function is called by the PhyLayer to hand over a ChannelSenseRequest.
The MACLayer is able to send a ChannelSenseRequest to the PhyLayer that calls this function with it and is returned a time point when to re-call this function with the specific ChannelSenseRequest.
The Decider puts the result (ChannelState) to the ChannelSenseRequest and "answers" by calling the "sendControlMsg"-function on the DeciderToPhyInterface, i.e. telling the PhyLayer to send it back.
Reimplemented from Decider.
Definition at line 285 of file ThresholdDecider.h.
{
    return -1;
  }
simtime_t ThresholdDecider::handleHeaderOver (std::map< Signal *, int >::iterator & it) [inline, protected]
handles the Signal when passed after after end of the header.
Definition at line 54 of file ThresholdDecider.h.
References log(), and SIGNAL_OVER.
Referenced by processSignal().
{
    log("Second receive of a signal from Phy - Deciding if packet should be received - Let's try to receive it.");
    //we don't really do something after the header, so we only update the next state
    it->second = SIGNAL_OVER;
    return it->first->getSignalStart() + it->first->getSignalLength();
  }
simtime_t ThresholdDecider::handleNewSignal (Signal * s) [inline, protected]
handles Signals passed the first time.
Definition at line 42 of file ThresholdDecider.h.
References currentSignals, Signal::getSignalLength(), Signal::getSignalStart(), HEADER_OVER, and log().
Referenced by processSignal().
{
    //set the state the signal will be in the next time we get it
    currentSignals[s] = HEADER_OVER;
    log("First processing of this signal. Scheduling it to end of header to decide if Signal should be received.");
    //we say that the length of the header is at 10% of the length of the signal
    return s->getSignalStart() + 0.10 * s->getSignalLength();
  }
simtime_t ThresholdDecider::handleSignalOver (std::map< Signal *, int >::iterator & it, AirFrame * frame) [inline, protected]
handles the signal when passed at the end of the signal.
Definition at line 64 of file ThresholdDecider.h.
References currentSignals, ConstMappingIterator::getValue(), ConstMappingIterator::hasNext(), ConstMappingIterator::inRange(), log(), MappingUtils::multiply(), ConstMappingIterator::next(), Decider::phy, printMapping(), DeciderToPhyInterface::sendUp(), threshold, and toDecibel().
Referenced by processSignal().
{
    log("Last receive of signal from Phy - Deciding if the packet could be received correctly...");
    //get the receiving power from the signal (calculated at each call of
    //this method
    //Mapping* receivingPower = it->first->getReceivingPower();
    //------print the mappings----------------------
    ev << "Sending power mapping: " << endl;
    printMapping(it->first->getTransmissionPower());
    ConstMapping* receivingPower;
    simtime_t delay = it->first->getPropagationDelay();
    if(delay == 0)
      receivingPower = it->first->getTransmissionPower()->constClone();
    else
      receivingPower = new ConstDelayedMapping(it->first->getTransmissionPower(), delay);
    std::list<ConstMapping*> attList = it->first->getAttenuation();
    int count = 1;
    for(std::list<ConstMapping*>::const_iterator aIt = attList.begin();
      aIt != attList.end(); ++aIt){
      ev << endl;
      ev << " multiplied with Attenuation " << count;
      switch(count){
      case 1:
        ev << "(Radiostate)";
        break;
      case 2:
        ev << "(Pathloss)";
        break;
      case 3:
        ev << "(Random time and freq attenuation)";
        break;
      case 4:
        ev << "(Random freq only attenuation)";
        break;
      }
      ev << ":" << endl;
      printMapping(*aIt);
      ++count;
      ConstMapping* tmp = MappingUtils::multiply(*receivingPower, **aIt, 0.0);
      delete receivingPower;
      receivingPower = tmp;
      ev << endl;
      ev << " result:" << endl;
      printMapping(receivingPower);
    }
    ev << endl;
    ev << "Receiving power calculated.\n";
    ev << "Signal receiving power. (Should be same as above)\n";
    printMapping(it->first->getReceivingPower());
    ev << endl;
    ev << "Threshold is " << toDecibel(threshold) << "dbm" << endl;
    //----------------------------------------------
    bool toWeak = false;
    //iterate over receiving power mapping and chekc if every value is bigger
    //then the threshold
    ConstMappingIterator* mIt = receivingPower->createConstIterator();
    while(mIt->inRange()){
      if(mIt->getValue() < threshold){
        // print receiving power if too weak
        ev << "receiving power: " << mIt->getValue() << endl;
        toWeak = true;
        break;
      }
      if(!mIt->hasNext())
        break;
      mIt->next();
    }
    delete mIt;
    delete receivingPower;
    if(toWeak){
      log("...signal is to weak -> discard.");
    } else {
      log("...strong enough -> forwarding it to Mac layer.");
      phy->sendUp(frame, new DeciderResult(true));
    }
    currentSignals.erase(it);
    return -1;
  }
void ThresholdDecider::log (std::string msg) [inline, protected]
Definition at line 163 of file ThresholdDecider.h.
References myIndex.
Referenced by handleHeaderOver(), handleNewSignal(), and handleSignalOver().
{
    ev << "[Host " << myIndex << "] - PhyLayer(Decider): " << msg << endl;
  }
void ThresholdDecider::printMapping (ConstMapping * m) [inline, protected]
Quick and ugly printing of a two dimensional mapping.
Definition at line 190 of file ThresholdDecider.h.
References ConstMapping::createConstIterator(), Argument::getArgValue(), ConstMappingIterator::getPosition(), Argument::getTime(), ConstMapping::getValue(), ConstMappingIterator::hasNext(), ConstMappingIterator::inRange(), ConstMappingIterator::next(), Argument::setArgValue(), Argument::setTime(), toDecibel(), and toString().
Referenced by handleSignalOver().
{
    Dimension frequency("frequency");
    //const DimensionSet& dims = m->getDimensionSet();
    std::set<simtime_t> timeEntries;
    std::set<double> freqEntries;
    std::map<double, std::set<simtime_t> > entries;
    ConstMappingIterator* it = m->createConstIterator();
    while(it->inRange()){
      entries[it->getPosition().getArgValue(frequency)].insert(it->getPosition().getTime());
      timeEntries.insert(it->getPosition().getTime());
      freqEntries.insert(it->getPosition().getArgValue(frequency));
      if(!it->hasNext())
        break;
      it->next();
    }
    delete it;
    ev << "------+---------------------------------------------------------" << endl;
    ev << "f\\t   | ";
    for(std::set<simtime_t>::const_iterator tIt = timeEntries.begin();
      tIt != timeEntries.end(); ++tIt){
      ev << toString(*tIt * 1000, 6) << " ";
    }
    ev << endl;
    ev << "------+---------------------------------------------------------" << endl;
    Argument pos;
    for(std::set<double>::const_iterator fIt = freqEntries.begin();
      fIt != freqEntries.end(); ++fIt){
      ev << toString(*fIt, 5) << " | ";
      pos.setArgValue(frequency, *fIt);
      std::map<double, std::set<simtime_t> >::iterator tmpIt = entries.find(*fIt);
      for(std::set<simtime_t>::const_iterator tIt = timeEntries.begin();
        tIt != timeEntries.end(); ++tIt){
        if(tmpIt != entries.end() && tmpIt->second.find(*tIt) != tmpIt->second.end()){
          pos.setTime(*tIt);
          ev << toString(toDecibel(m->getValue(pos)), 6) << " ";
        } else {
          ev << "       ";
        }
      }
      ev << endl;
    }
    ev << "------+---------------------------------------------------------" << endl;
  }
virtual simtime_t ThresholdDecider::processSignal (AirFrame * frame) [inline, virtual]
this method is called by the BasePhylayer whenever it gets a AirFrame (from another phy or self scheduled).
Reimplemented from Decider.
Definition at line 253 of file ThresholdDecider.h.
References currentSignals, handleHeaderOver(), handleNewSignal(), handleSignalOver(), HEADER_OVER, and SIGNAL_OVER.
{
    Signal* s = &frame->getSignal();
    //Check if we already know this signal...
    std::map<Signal*, int>::iterator it = currentSignals.find(s);
    //if not, we handle it as a new signal
    if(it == currentSignals.end()) {
      return handleNewSignal(s);
    //otherwise handle it depending on the state it currently is in
    } else {
      switch(it->second) {
      case HEADER_OVER:
        return handleHeaderOver(it);
      case SIGNAL_OVER:
        return handleSignalOver(it, frame);
      default:
        break;
      }
    }
    //we should never get here!
    assert(false);
    return 0;
  }
double ThresholdDecider::toDecibel (double v) [inline, protected]
Definition at line 167 of file ThresholdDecider.h.
Referenced by handleSignalOver(), and printMapping().
{
    return 10.0 * log10(v);
  }
std::string ThresholdDecider::toString (simtime_t v, unsigned int length) [inline, protected]
Definition at line 183 of file ThresholdDecider.h.
References toString().
{
    return toString(SIMTIME_DBL(v), length);
  }
template<class T > std::string ThresholdDecider::toString (T v, unsigned int length) [inline, protected]
Definition at line 172 of file ThresholdDecider.h.
Referenced by printMapping(), and toString().
{
    char* tmp = new char[255];
    sprintf(tmp, "%.2f", v);
    std::string result(tmp);
    delete[] tmp;
    while(result.length() < length)
      result += " ";
    return result;
  }
Member Data Documentation
std::map<Signal*, int> ThresholdDecider::currentSignals [protected]
stores the currently receiving signals together with their current state.
Definition at line 29 of file ThresholdDecider.h.
Referenced by handleNewSignal(), handleSignalOver(), and processSignal().
int ThresholdDecider::myIndex [protected]
Definition at line 23 of file ThresholdDecider.h.
Referenced by log().
double ThresholdDecider::threshold [protected]
Definition at line 25 of file ThresholdDecider.h.
Referenced by handleSignalOver().
The documentation for this class was generated from the following file:
examples/analogueModels/ThresholdDecider.h