MiXiM: NicEntryDebug Class Reference
NicEntryDebug Class Reference
[connectionManager - channel and connection related classes]
NicEntry is used by ConnectionManager to store the necessary information for each nic.
#include <NicEntryDebug.h>
Inherits NicEntry.
Public Member Functions
NicEntryDebug (bool debug)
Constructor, initializes all members.
virtual ~NicEntryDebug ()
Destructor -- needs to be there...
virtual void connectTo (NicEntry *)
Connect two nics.
virtual void disconnectFrom (NicEntry *)
Disconnect two nics.
Protected Member Functions
cGate * requestInGate (void)
Returns a free in gate of the nic.
cGate * requestOutGate (void)
Returns a free out gate of the nic.
Protected Attributes
int inCnt
Number of in gates allocated for the nic so far.
int outCnt
Number of out gates allocated for the nic so far.
std::vector< cGate * > freeInGates
In Gates that were once used but are not connected now.
std::vector< cGate * > freeOutGates
Out Gates that were once used but are not connected now.
Detailed Description
NicEntry is used by ConnectionManager to store the necessary information for each nic.
Author:
Daniel Willkomm
See also:
ConnectionManager, NicEntry
Definition at line 38 of file NicEntryDebug.h.
Constructor & Destructor Documentation
NicEntryDebug::NicEntryDebug (bool debug) [inline]
Constructor, initializes all members.
Definition at line 63 of file NicEntryDebug.h.
: NicEntry(debug), inCnt(0), outCnt(0) {};
virtual NicEntryDebug::~NicEntryDebug () [inline, virtual]
Destructor -- needs to be there...
Definition at line 69 of file NicEntryDebug.h.
{}
Member Function Documentation
void NicEntryDebug::connectTo (NicEntry * other) [virtual]
Connect two nics.
Establish unidirectional connection with other nic
Parameters:
other reference to remote nic (other NicEntry)
This function acquires an in gate at the remote nic and an out gate at this nic, connects the two and updates the freeInGate, freeOutGate and outConns data sets.
It handles compound modules correctly, provided that the physical module is called "phy" or "snrEval" respectively in the .ned files.
Implements NicEntry.
Definition at line 43 of file NicEntryDebug.cc.
References nicEV, NicEntry::nicId, NicEntry::outConns, requestInGate(), and requestOutGate().
{
  nicEV<<"connecting nic #"<<nicId<< " and #"<<other->nicId<<endl;
  NicEntryDebug* otherNic = (NicEntryDebug*) other;
  cGate *localoutgate = requestOutGate();
  localoutgate->connectTo(otherNic->requestInGate());
  outConns[other] = localoutgate->getPathStartGate();
}
void NicEntryDebug::disconnectFrom (NicEntry * other) [virtual]
Disconnect two nics.
Release unidirectional connection with other nic
Parameters:
other reference to remote nic (other NicEntry)
Implements NicEntry.
Definition at line 58 of file NicEntryDebug.cc.
References freeInGates, freeOutGates, nicEV, NicEntry::nicId, and NicEntry::outConns.
{
  nicEV<<"disconnecting nic #"<<nicId<< " and #"<<other->nicId<<endl;
  NicEntryDebug* otherNic = (NicEntryDebug*) other;
  //search the connection in the outConns list
  GateList::iterator p = outConns.find(other);
  //no need to check whether entry is valid; is already check by ConnectionManager isConnected
  //get the hostGate
  //order is phyGate->nicGate->hostGate
  cGate* hostGate = p->second->getNextGate()->getNextGate();
  // release local out gate
  freeOutGates.push_back(hostGate);
  // release remote in gate
  otherNic->freeInGates.push_back(hostGate->getNextGate());
  //reset gates
  //hostGate->getNextGate()->connectTo(0);
  hostGate->disconnect();
  //delete the connection
  outConns.erase(p);
}
cGate * NicEntryDebug::requestInGate (void) [protected]
Returns a free in gate of the nic.
This checks the list of free in gates, if one is available it is returned. Otherwise, a new in gate is added to the nic. This function handles the interaction with snrEval / phy and nic corectly, provided that the phy name is "snrEval or "phy" respectively in the .ned files.
Definition at line 91 of file NicEntryDebug.cc.
References freeInGates, inCnt, NicEntry::nicId, and NicEntry::nicPtr.
Referenced by connectTo().
{
  // gate of the host
  cGate *hostGate;
  if (!freeInGates.empty()) {
    hostGate = freeInGates.back();
    freeInGates.pop_back();
  } else {
    char gateName[20];
    // we will have one more in gate
    ++inCnt;
    //get a unique name for the gate (composed of the nic module id and a counter)
    sprintf(gateName, "in%d-%d", nicId, inCnt);
    // create a new gate for the host module
    nicPtr->getParentModule()->addGate(gateName, cGate::INPUT);
    hostGate = nicPtr->getParentModule()->gate(gateName);
    // gate of the nic
    cGate *nicGate;
    // create a new gate for the nic module
    nicPtr->addGate(gateName, cGate::INPUT);
    nicGate = nicPtr->gate(gateName);
    // connect the hist gate with the nic gate
    hostGate->connectTo(nicGate);
    // pointer to the phy module
    ChannelAccess* phyModule;
    // gate of the phy module
    cGate *phyGate;
    // to avoid unnecessary dynamic_casting we check for a "phy"-named submodule first
    if ((phyModule = static_cast<ChannelAccess *> (nicPtr->getSubmodule("phy"))) == NULL)
      phyModule = FindModule<ChannelAccess*>::findSubModule(nicPtr);
    // create a new gate for the phy module
    phyModule->addGate(gateName, cGate::INPUT);
    phyGate = phyModule->gate(gateName);
    // connect the nic gate (the gate of the compound module) to
    // a "real" gate -- the gate of the phy module
    nicGate->connectTo(phyGate);
  }
  return hostGate;
}
cGate * NicEntryDebug::requestOutGate (void) [protected]
Returns a free out gate of the nic.
returns a free out gate. If none is available it is created. See NicEntry::requestInGate for a detailed description
Definition at line 146 of file NicEntryDebug.cc.
References freeOutGates, NicEntry::nicId, NicEntry::nicPtr, and outCnt.
Referenced by connectTo().
{
  // gate of the host
  cGate *hostGate;
  if (!freeOutGates.empty()) {
    hostGate = freeOutGates.back();
    freeOutGates.pop_back();
  } else {
    char gateName[20];
    // we will have one more out gate
    ++outCnt;
    //get a unique name for the gate (composed of the nic module id and a counter)
    sprintf(gateName, "out%d-%d", nicId, outCnt);
    // create a new gate for the host module
    nicPtr->getParentModule()->addGate(gateName, cGate::OUTPUT);
    hostGate = nicPtr->getParentModule()->gate(gateName);
    // gate of the nic
    cGate *nicGate;
    // create a new gate for the nic module
    nicPtr->addGate(gateName, cGate::OUTPUT);
    nicGate = nicPtr->gate(gateName);
    // connect the hist gate with the nic gate
    nicGate->connectTo(hostGate);
    // pointer to the phy module
    ChannelAccess* phyModule;
    // gate of the phy module
    cGate *phyGate;
    // to avoid unnecessary dynamic_casting we check for a "phy"-named submodule first
    if ((phyModule = static_cast<ChannelAccess *> (nicPtr->getSubmodule("phy"))) == NULL)
      phyModule = FindModule<ChannelAccess*>::findSubModule(nicPtr);
    assert(phyModule != 0);
    // create a new gate for the phy module
    phyModule->addGate(gateName, cGate::OUTPUT);
    phyGate = phyModule->gate(gateName);
    // connect the nic gate (the gate of the compound module) to
    // a "real" gate -- the gate of the phy module
    phyGate->connectTo(nicGate);
  }
  return hostGate;
}
Member Data Documentation
std::vector<cGate* > NicEntryDebug::freeInGates [protected]
In Gates that were once used but are not connected now.
Definition at line 48 of file NicEntryDebug.h.
Referenced by disconnectFrom(), and requestInGate().
std::vector<cGate* > NicEntryDebug::freeOutGates [protected]
Out Gates that were once used but are not connected now.
Definition at line 51 of file NicEntryDebug.h.
Referenced by disconnectFrom(), and requestOutGate().
int NicEntryDebug::inCnt [protected]
Number of in gates allocated for the nic so far.
Definition at line 42 of file NicEntryDebug.h.
Referenced by requestInGate().
int NicEntryDebug::outCnt [protected]
Number of out gates allocated for the nic so far.
Definition at line 45 of file NicEntryDebug.h.
Referenced by requestOutGate().
The documentation for this class was generated from the following files:
base/connectionManager/NicEntryDebug.h
base/connectionManager/NicEntryDebug.cc