MiXiM: TurtleMobility Class Reference
TurtleMobility Class Reference
[mobility - modules handling the mobility of the hosts]
LOGO-style movement model, with the script coming from XML. See NED file for more info.
#include <TurtleMobility.h>
Inherits LineSegmentsMobilityBase.
Public Member Functions
virtual void initialize (int)
Initializes mobility model parameters.
virtual void setTargetPosition ()
Overridden from LineSegmentsMobilityBase. Invokes resumeScript().
virtual void fixIfHostGetsOutside ()
Overridden from LineSegmentsMobilityBase.
Protected Member Functions
void resumeScript ()
Process next statements from script.
void executeStatement (cXMLElement *nextStatement)
Execute the given statement.
double getValue (const char *s)
Parse attrs in the script -- accepts things like "uniform(10,50) as well.
void gotoNextStatement ()
Advance nextStatement pointer.
Protected Attributes
cXMLElement * turtleScript
cXMLElement * nextStatement
double angle
BorderPolicy borderPolicy
std::stack< long > loopVars
Detailed Description
LOGO-style movement model, with the script coming from XML. See NED file for more info.
Author:
Andras Varga
Definition at line 33 of file TurtleMobility.h.
Member Function Documentation
void TurtleMobility::executeStatement (cXMLElement * nextStatement) [protected]
Execute the given statement.
Definition at line 110 of file TurtleMobility.cc.
References angle, borderPolicy, Coord::distance(), getValue(), Coord::getX(), Coord::getY(), loopVars, BaseMobility::move, BaseMobility::PLACERANDOMLY, BaseMobility::RAISEERROR, BaseMobility::REFLECT, Coord::setX(), Coord::setY(), Move::speed, Move::startPos, LineSegmentsMobilityBase::targetPos, LineSegmentsMobilityBase::targetTime, and BaseMobility::WRAP.
Referenced by resumeScript().
{
    const char *tag = stmt->getTagName();
    EV << "doing <" << tag << ">\n";
    if (!strcmp(tag,"repeat"))
    {
        const char *nAttr = stmt->getAttribute("n");
        long n = -1;  // infinity -- that's the default
        if (nAttr)
        {
            n = (long) getValue(nAttr);
            if (n<0)
                error("<repeat>: negative repeat count at %s", stmt->getSourceLocation());
        }
        loopVars.push(n);
    }
    else if (!strcmp(tag,"set"))
    {
        const char *speedAttr = stmt->getAttribute("speed");
        const char *angleAttr = stmt->getAttribute("angle");
        const char *xAttr = stmt->getAttribute("x");
        const char *yAttr = stmt->getAttribute("y");
        const char *bpAttr = stmt->getAttribute("borderPolicy");
        if (speedAttr)
            move.speed = getValue(speedAttr);
        if (angleAttr)
            angle = getValue(angleAttr);
        if (xAttr)
            targetPos.setX(getValue(xAttr));
        if (yAttr)
            targetPos.setY(getValue(yAttr));
        if (move.speed<=0)
            error("<set>: speed is negative or zero at %s", stmt->getSourceLocation());
        if (bpAttr)
        {
            if (!strcmp(bpAttr,"reflect"))
                borderPolicy = REFLECT;
            else if (!strcmp(bpAttr,"wrap"))
                borderPolicy = WRAP;
            else if (!strcmp(bpAttr,"placerandomly"))
                borderPolicy = PLACERANDOMLY;
            else if (!strcmp(bpAttr,"error"))
                borderPolicy = RAISEERROR;
            else
                error("<set>: value for attribute borderPolicy is invalid, should be "
                      "'reflect', 'wrap', 'placerandomly' or 'error' at %s",
                      stmt->getSourceLocation());
        }
    }
    else if (!strcmp(tag,"forward"))
    {
        const char *dAttr = stmt->getAttribute("d");
        const char *tAttr = stmt->getAttribute("t");
        if (!dAttr && !tAttr)
            error("<forward>: must have at least attribute 't' or 'd' (or both) at %s", stmt->getSourceLocation());
        double d, t;
        if (tAttr && dAttr)
        {
            // cover distance d in time t (current speed is ignored)
            d = getValue(dAttr);
            t = getValue(tAttr);
        }
        else if (dAttr)
        {
            // travel distance d at current speed
            d = getValue(dAttr);
            t = d / move.speed;
        }
        else // tAttr only
        {
            // travel for time t at current speed
            t = getValue(tAttr);
            d = move.speed * t;
        }
        if (t<0)
            error("<forward>: time (attribute t) is negative at %s", stmt->getSourceLocation());
        if (d<0)
            error("<forward>: distance (attribute d) is negative at %s", stmt->getSourceLocation());
        // FIXME handle zeros properly...
        targetPos.setX(targetPos.getX() + d * cos(PI * angle / 180));
        targetPos.setY(targetPos.getY() + d * sin(PI * angle / 180));
        targetTime += t;
    }
    else if (!strcmp(tag,"turn"))
    {
        const char *angleAttr = stmt->getAttribute("angle");
        if (!angleAttr)
            error("<turn>: required attribute 'angle' missing at %s", stmt->getSourceLocation());
        angle += getValue(angleAttr);
    }
    else if (!strcmp(tag,"wait"))
    {
        const char *tAttr = stmt->getAttribute("t");
        if (!tAttr)
            error("<wait>: required attribute 't' missing at %s", stmt->getSourceLocation());
        simtime_t t = getValue(tAttr);
        if (t<0)
            error("<wait>: time (attribute t) is negative (%s) at %s", SIMTIME_STR(t), stmt->getSourceLocation());
        targetTime += t;  // targetPos is unchanged
    }
    else if (!strcmp(tag,"moveto"))
    {
        const char *xAttr = stmt->getAttribute("x");
        const char *yAttr = stmt->getAttribute("y");
        const char *tAttr = stmt->getAttribute("t");
        if (xAttr)
            targetPos.setX(getValue(xAttr));
        if (yAttr)
            targetPos.setY(getValue(yAttr));
        // travel to targetPos at current speed, or get there in time t (ignoring current speed then)
        simtime_t t = tAttr ? getValue(tAttr) : move.startPos.distance(targetPos)/move.speed;
        if (t<0)
            error("<wait>: time (attribute t) is negative at %s", stmt->getSourceLocation());
        targetTime += t;
    }
    else if (!strcmp(tag,"moveby"))
    {
        const char *xAttr = stmt->getAttribute("x");
        const char *yAttr = stmt->getAttribute("y");
        const char *tAttr = stmt->getAttribute("t");
        if (xAttr)
            targetPos.setX(targetPos.getX() + getValue(xAttr));
        if (yAttr)
            targetPos.setY(targetPos.getY() + getValue(yAttr));
        // travel to targetPos at current speed, or get there in time t (ignoring current speed then)
        simtime_t t = tAttr ? getValue(tAttr) : move.startPos.distance(targetPos)/move.speed;
        if (t<0)
            error("<wait>: time (attribute t) is negative at %s", stmt->getSourceLocation());
        targetTime += t;
    }
}
void TurtleMobility::fixIfHostGetsOutside () [virtual]
Overridden from LineSegmentsMobilityBase.
Reimplemented from BaseMobility.
Definition at line 75 of file TurtleMobility.cc.
References angle, borderPolicy, BaseMobility::handleIfOutside(), Coord::info(), LineSegmentsMobilityBase::stepSize, LineSegmentsMobilityBase::stepTarget, and LineSegmentsMobilityBase::targetPos.
{
    EV << "stepTarget: " << stepTarget.info() << " targetPos: " << targetPos.info() << " stepSize: " << stepSize.info()
       << " angle: " << angle << endl;
    if( handleIfOutside(borderPolicy, stepTarget, targetPos, stepSize, angle) ){
  EV << "stepTarget: " << stepTarget.info() << " targetPos: " << targetPos.info() << " stepSize: " << stepSize.info()
     << " angle: " << angle << endl;
    }
}
double TurtleMobility::getValue (const char * s) [protected]
Parse attrs in the script -- accepts things like "uniform(10,50) as well.
Definition at line 248 of file TurtleMobility.cc.
References nextStatement, BaseMobility::playgroundSizeX(), and BaseMobility::playgroundSizeY().
Referenced by executeStatement().
{
    // first, textually replace $MAXX and $MAXY with their actual values
    std::string str;
    if (strchr(s,'$'))
    {
        char strMaxX[32], strMaxY[32];
        sprintf(strMaxX, "%g", playgroundSizeX()-1);
        sprintf(strMaxY, "%g", playgroundSizeY()-1);
        str = s;
        std::string::size_type pos;
        while ((pos = str.find("$MAXX")) != std::string::npos)
            str.replace(pos, sizeof("$MAXX")-1, strMaxX);
        while ((pos = str.find("$MAXY")) != std::string::npos)
            str.replace(pos, sizeof("$MAXY")-1, strMaxY);
        s = str.c_str();
    }
    // then use cMsgPar to evaluate the string
    cMsgPar tmp;
    if (!tmp.parse(s,'?'))
        error("wrong value '%s' around %s", s, nextStatement->getSourceLocation());
    return tmp.doubleValue();
}
void TurtleMobility::gotoNextStatement () [protected]
Advance nextStatement pointer.
Definition at line 274 of file TurtleMobility.cc.
References loopVars, nextStatement, and turtleScript.
Referenced by resumeScript().
{
    // "statement either doesn't have a child, or it's a <repeat> and loop count is already pushed on the stack"
    ASSERT(!nextStatement->getFirstChild() || (!strcmp(nextStatement->getTagName(),"repeat") && !loopVars.empty()));
    if (nextStatement->getFirstChild() && (loopVars.top()!=0 || (loopVars.pop(),false)))   // !=0: positive or -1
    {
        // statement must be a <repeat> if it has children; repeat count>0 must be
        // on the stack; let's start doing the body.
        nextStatement = nextStatement->getFirstChild();
    }
    else if (!nextStatement->getNextSibling())
    {
        // no sibling -- either end of <repeat> body, or end of script
        ASSERT(nextStatement->getParentNode()==turtleScript ? loopVars.empty() : !loopVars.empty());
        if (!loopVars.empty())
        {
            // decrement and check loop counter
            if (loopVars.top()!=-1)  // -1 means infinity
                loopVars.top()--;
            if (loopVars.top()!=0)  // positive or -1
            {
                // go to beginning of <repeat> block again
                nextStatement = nextStatement->getParentNode()->getFirstChild();
            }
            else
            {
                // end of loop -- locate next statement after the <repeat>
                nextStatement = nextStatement->getParentNode();
                gotoNextStatement();
            }
        }
        else
        {
            // end of script
            nextStatement = NULL;
        }
    }
    else
    {
        // go to next statement (must exist -- see "if" above)
        nextStatement = nextStatement->getNextSibling();
    }
}
void TurtleMobility::initialize (int stage) [virtual]
Initializes mobility model parameters.
Reads the parameters. If the host is not stationary it calculates a random position and schedules a timer to trigger the first movement
Reimplemented from BaseMobility.
Definition at line 31 of file TurtleMobility.cc.
References angle, borderPolicy, BaseMobility::move, nextStatement, BaseMobility::REFLECT, Move::speed, Move::startPos, LineSegmentsMobilityBase::stepTarget, LineSegmentsMobilityBase::targetPos, LineSegmentsMobilityBase::targetTime, and turtleScript.
{
    LineSegmentsMobilityBase::initialize(stage);
    EV << "initializing TurtleMobility stage " << stage << endl;
    if(stage == 0)
    {
        turtleScript = par("turtleScript");
        nextStatement = turtleScript->getFirstChild();
        move.speed = 1;
        angle = 0;
        borderPolicy = REFLECT;
        // a dirty trick to extract starting position out of the script
        // (start doing it, but then rewind to the beginning)
  // does not really work
  // we need to  set the startPos initially for which there is no option in
  // turtlemobility
  // -> always starting with random position... (Daniel)
        //resumeScript();
        //nextStatement = turtleScript->getFirstChild();
        //while (!loopVars.empty()) loopVars.pop();
        WATCH(move.speed);
        WATCH(angle);
        WATCH(borderPolicy);
    }
    else if(stage == 1){
  targetPos = move.startPos;
  stepTarget = move.startPos;
  targetTime = simTime();
    }
}
void TurtleMobility::resumeScript () [protected]
Process next statements from script.
Will set a new targetTime and targetPos
Definition at line 91 of file TurtleMobility.cc.
References executeStatement(), gotoNextStatement(), BaseMobility::move, nextStatement, Move::speed, and LineSegmentsMobilityBase::targetTime.
Referenced by setTargetPosition().
{
    if (!nextStatement)
    {
  move.speed = 0;
  EV << "no statement found -> not moving!\n";
        return;
    }
    simtime_t now = targetTime;
    // interpret statement
    while (nextStatement && targetTime==now)
    {
        executeStatement(nextStatement);
        gotoNextStatement();
    }
}
void TurtleMobility::setTargetPosition () [virtual]
Overridden from LineSegmentsMobilityBase. Invokes resumeScript().
Implements LineSegmentsMobilityBase.
Definition at line 68 of file TurtleMobility.cc.
References BaseMobility::move, resumeScript(), and Move::startTime.
{
    resumeScript();
    move.startTime = simTime();
}
Member Data Documentation
double TurtleMobility::angle [protected]
Definition at line 41 of file TurtleMobility.h.
Referenced by executeStatement(), fixIfHostGetsOutside(), and initialize().
BorderPolicy TurtleMobility::borderPolicy [protected]
Definition at line 42 of file TurtleMobility.h.
Referenced by executeStatement(), fixIfHostGetsOutside(), and initialize().
std::stack<long> TurtleMobility::loopVars [protected]
Definition at line 43 of file TurtleMobility.h.
Referenced by executeStatement(), and gotoNextStatement().
cXMLElement* TurtleMobility::nextStatement [protected]
Definition at line 40 of file TurtleMobility.h.
Referenced by getValue(), gotoNextStatement(), initialize(), and resumeScript().
cXMLElement* TurtleMobility::turtleScript [protected]
Definition at line 37 of file TurtleMobility.h.
Referenced by gotoNextStatement(), and initialize().
The documentation for this class was generated from the following files:
modules/mobility/TurtleMobility.h
modules/mobility/TurtleMobility.cc