MiXiM: base/phyLayer/MappingUtils.cc File Reference
MappingUtils.cc File Reference
#include "MappingUtils.h"
Functions
Mapping * operator* (ConstMapping &f1, ConstMapping &f2)
Mapping * operator/ (ConstMapping &f1, ConstMapping &f2)
Mapping * operator+ (ConstMapping &f1, ConstMapping &f2)
Mapping * operator- (ConstMapping &f1, ConstMapping &f2)
Function Documentation
Mapping* operator* (ConstMapping & f1, ConstMapping & f2)
Definition at line 202 of file MappingUtils.cc.
References MappingUtils::multiply().
{
  return MappingUtils::multiply(f1, f2);
}
Mapping* operator+ (ConstMapping & f1, ConstMapping & f2)
Definition at line 210 of file MappingUtils.cc.
References MappingUtils::add().
{
  return MappingUtils::add(f1, f2);
}
Mapping* operator- (ConstMapping & f1, ConstMapping & f2)
Definition at line 214 of file MappingUtils.cc.
References MappingUtils::subtract().
{
  return MappingUtils::subtract(f1, f2);
}
Mapping* operator/ (ConstMapping & f1, ConstMapping & f2)
Definition at line 206 of file MappingUtils.cc.
References MappingUtils::divide().
{
  return MappingUtils::divide(f1, f2);
}