MiXiM: Radio Class Reference
Radio Class Reference
[phyLayer - physical layer modules]
The class that represents the Radio as a state machine.
#include <PhyUtils.h>
Public Types
enum RadioState {
RX = 0, TX, SLEEP, SWITCHING,
NUM_RADIO_STATES
}
The state of the radio of the nic.
Public Member Functions
Radio (int initialState=RX, double minAtt=1.0, double maxAtt=0.0)
Default constructor for instances of class Radio.
virtual ~Radio ()
Destructor for the Radio class.
simtime_t switchTo (int newState, simtime_t now)
A function called by the Physical Layer to start the switching process to a new RadioState.
void setSwitchTime (int from, int to, simtime_t time)
function called by PhyLayer in order to make an entry in the switch times matrix, i.e. set the time for switching from one state to another
int getCurrentState () const
void endSwitch (simtime_t now)
called by PhyLayer when duration-time for the current switching process is up
RadioStateAnalogueModel * getAnalogueModel ()
Returns a pointer to the RadioStateAnalogueModel.
void cleanAnalogueModelUntil (simtime_t t)
discards information in the RadioStateAnalogueModel before given time-point
Protected Member Functions
virtual void makeRSAMEntry (simtime_t time, int state)
responsible for making entries to the RSAM
virtual double mapStateToAtt (int state)
maps RadioState to attenuation, the Radios receiving characteristic
Protected Attributes
int state
int nextState
const int numRadioStates
simtime_t ** swTimes
const double minAtt
const double maxAtt
RadioStateAnalogueModel rsam
Detailed Description
The class that represents the Radio as a state machine.
The Radio creates and updates its corresponding RadioStateAnalogueModel, that is a filter representing the radios attenuation to a Signal depending on the RadioState over time.
For this basic version we assume a minimal attenuation when the Radio is in state RX, and a maximum attenuation otherwise.
Definition at line 235 of file PhyUtils.h.
Member Enumeration Documentation
enum Radio::RadioState
The state of the radio of the nic.
PLEASE INSERT NEW RADIOSTATES !!!BEFORE!!! NUM_RADIO_STATES
Enumerator:
RX
TX
SLEEP
SWITCHING
NUM_RADIO_STATES
Definition at line 243 of file PhyUtils.h.
                  {
    /* receiving state*/
    RX = 0,
    /* transmiting state*/
    TX,
    /* sleeping*/
    SLEEP,
    /* switching between two states*/
    SWITCHING,
    /* New entries from here... */
    /* ... to here. */
    /*
     * NOTE: THIS IS NO REAL RADIOSTATE, JUST A COUNTER FOR THE NUMBER OF RADIOSTATES
     * IT ALWAYS NEEDS TO BE THE LAST ENTRY IN THIS ENUM!
     */
    NUM_RADIO_STATES
  };
Constructor & Destructor Documentation
Radio::Radio (int initialState = RX, double minAtt = 1.0, double maxAtt = 0.0) [inline]
Default constructor for instances of class Radio.
Definition at line 296 of file PhyUtils.h.
References numRadioStates, and swTimes.
    : state(initialState), nextState(initialState), numRadioStates(NUM_RADIO_STATES),
    minAtt(minAtt), maxAtt(maxAtt), rsam(mapStateToAtt(initialState))
  {
    // allocate memory for one dimension
    swTimes = new simtime_t* [numRadioStates];
    // go through the first dimension and
    for (int i = 0; i < numRadioStates; i++)
    {
      // allocate memory for the second dimension
      swTimes[i] = new simtime_t[numRadioStates];
    }
    // initialize all matrix entries to 0.0
    for (int i = 0; i < numRadioStates; i++)
    {
      for (int j = 0; j < numRadioStates; j++)
      {
        swTimes[i][j] = 0;
      }
    }
  }
virtual Radio::~Radio () [inline, virtual]
Destructor for the Radio class.
Definition at line 325 of file PhyUtils.h.
References numRadioStates, and swTimes.
  {
    // delete all allocated memory for the switching times matrix
    for (int i = 0; i < numRadioStates; i++)
    {
      delete[] swTimes[i];
    }
    delete[] swTimes;
    swTimes = 0;
  }
Member Function Documentation
void Radio::cleanAnalogueModelUntil (simtime_t t) [inline]
discards information in the RadioStateAnalogueModel before given time-point
Definition at line 451 of file PhyUtils.h.
References RadioStateAnalogueModel::cleanUpUntil(), and rsam.
Referenced by BasePhyLayer::handleAirFrameEndReceive().
  {
    rsam.cleanUpUntil(t);
  }
void Radio::endSwitch (simtime_t now) [inline]
called by PhyLayer when duration-time for the current switching process is up
Radio checks whether it is in switching state (pre-condition) and switches to the target state
The actual simtime must be passed, to create properly RSAMEntry
Definition at line 422 of file PhyUtils.h.
References makeRSAMEntry(), nextState, state, and SWITCHING.
Referenced by BasePhyLayer::finishRadioSwitching().
  {
    // make sure we are currently switching
    assert(state == SWITCHING);
    // set the current state finally to the next state
    state = nextState;
    // make entry to RSAM
    makeRSAMEntry(now, state);
    return;
  }
RadioStateAnalogueModel* Radio::getAnalogueModel () [inline]
Returns a pointer to the RadioStateAnalogueModel.
This method is intended to be used by the PhyLayer to obtain a pointer to the corresponding RSAM to this Radio
Definition at line 442 of file PhyUtils.h.
References rsam.
Referenced by BasePhyLayer::getAnalogueModelFromName(), and BasePhyLayer::~BasePhyLayer().
  {
    return (&rsam);
  }
int Radio::getCurrentState () const [inline]
Returns the state the Radio is currently in
Definition at line 404 of file PhyUtils.h.
References state.
Referenced by BasePhyLayer::getRadioState(), and BasePhyLayer::handleUpperMessage().
  {
    return state;
  }
virtual void Radio::makeRSAMEntry (simtime_t time, int state) [inline, protected, virtual]
responsible for making entries to the RSAM
Definition at line 461 of file PhyUtils.h.
References mapStateToAtt(), rsam, and RadioStateAnalogueModel::writeRecvEntry().
Referenced by endSwitch(), and switchTo().
  {
    rsam.writeRecvEntry(time, mapStateToAtt(state));
  }
virtual double Radio::mapStateToAtt (int state) [inline, protected, virtual]
maps RadioState to attenuation, the Radios receiving characteristic
Definition at line 470 of file PhyUtils.h.
References maxAtt, minAtt, and RX.
Referenced by makeRSAMEntry().
  {
    if (state == RX)
    {
      return minAtt;
    } else
    {
      return maxAtt;
    }
  }
void Radio::setSwitchTime (int from, int to, simtime_t time) [inline]
function called by PhyLayer in order to make an entry in the switch times matrix, i.e. set the time for switching from one state to another
Definition at line 385 of file PhyUtils.h.
References numRadioStates, SWITCHING, and swTimes.
Referenced by BasePhyLayer::initialize().
  {
    // assert parameters are in valid range
    assert(time >= 0.0);
    assert(0 <= from && from < numRadioStates);
    assert(0 <= to && to < numRadioStates);
    // it shall not be possible to set times to/from SWITCHING
    assert(from != SWITCHING && to != SWITCHING);
    swTimes[from][to] = time;
    return;
  }
simtime_t Radio::switchTo (int newState, simtime_t now) [inline]
A function called by the Physical Layer to start the switching process to a new RadioState.
Returns:
-1: Error code if the Radio is currently switching else: switching time from the current RadioState to the new RadioState
The actual simtime must be passed, to create properly RSAMEntry
Definition at line 349 of file PhyUtils.h.
References makeRSAMEntry(), nextState, numRadioStates, state, SWITCHING, and swTimes.
Referenced by BasePhyLayer::setRadioState().
  {
    // state to switch to must be in a valid range, i.e. 0 <= newState < numRadioStates
    assert(0 <= newState && newState < numRadioStates);
    // state to switch to must not be SWITCHING
    assert(newState != SWITCHING);
    // return error value if newState is the same as the current state
    // if (newState == state) return -1;
    // return error value if Radio is currently switching
    if (state == SWITCHING) return -1;
    /* REGULAR CASE */
    // set the nextState to the newState and the current state to SWITCHING
    nextState = newState;
    int lastState = state;
    state = SWITCHING;
    // make entry to RSAM
    makeRSAMEntry(now, state);
    // return matching entry from the switch times matrix
    return swTimes[lastState][nextState];
  }
Member Data Documentation
const double Radio::maxAtt [protected]
Definition at line 283 of file PhyUtils.h.
Referenced by mapStateToAtt().
const double Radio::minAtt [protected]
Constants to store the minimum and maximum attenuation for a Radio instance
Definition at line 282 of file PhyUtils.h.
Referenced by mapStateToAtt().
int Radio::nextState [protected]
Definition at line 270 of file PhyUtils.h.
Referenced by endSwitch(), and switchTo().
const int Radio::numRadioStates [protected]
Array for storing switchtimes between states
Definition at line 276 of file PhyUtils.h.
Referenced by Radio(), setSwitchTime(), switchTo(), and ~Radio().
RadioStateAnalogueModel Radio::rsam [protected]
The corresponding RadioStateAnalogueModel, depends on the characteristics of the radio
Definition at line 289 of file PhyUtils.h.
Referenced by cleanAnalogueModelUntil(), getAnalogueModel(), and makeRSAMEntry().
int Radio::state [protected]
The current state the radio is in
Definition at line 269 of file PhyUtils.h.
Referenced by endSwitch(), getCurrentState(), and switchTo().
simtime_t** Radio::swTimes [protected]
Definition at line 277 of file PhyUtils.h.
Referenced by Radio(), setSwitchTime(), switchTo(), and ~Radio().
The documentation for this class was generated from the following file:
base/phyLayer/PhyUtils.h