MiXiM: RepeatTimerCore Class Reference
RepeatTimerCore Class Reference
#include <RepeatTimerCore.h>
Inherits BaseModule.
Classes
struct TInfo
Public Member Functions
typedef void() cleanup (void *data)
~RepeatTimerCore ()
void init (RepeatTimer *t)
void setRepeatTimer (unsigned int index, double when, int repeats=1)
unsigned int setRepeatTimer (double when, int repeats=1)
void cancelRepeatTimer (unsigned int index)
void resetRepeatTimer (unsigned int index)
void resetAllRepeatTimers (void)
bool timerExists (unsigned int index)
float remainingRepeatTimer (unsigned int index)
void setContextPointer (unsigned int index, void *data)
void * contextPointer (unsigned int index)
void setContextDestructor (unsigned int index, cleanup *)
void allocateRepeatTimers (unsigned int count)
void deleteRepeatTimer (unsigned int index)
Protected Member Functions
void checkExists (unsigned int index)
virtual void handleMessage (cMessage *msg)
Handle self messages.
Protected Attributes
RepeatTimer * timer
std::map< unsigned int, TInfo > * timer_map
Detailed Description
Definition at line 9 of file RepeatTimerCore.h.
Constructor & Destructor Documentation
RepeatTimerCore::~RepeatTimerCore ()
Definition at line 86 of file RepeatTimerCore.cc.
References checkExists(), contextPointer(), timer, and timer_map.
{
  for (std::map<unsigned int,TInfo>::const_iterator p=timer_map->begin();p!=timer_map->end();p++) {
    unsigned int index = p->second.timer->getKind();
    checkExists(index);
    if ((*timer_map)[index].timer->isScheduled()) {
      if ((*timer_map)[index].destructor!=NULL)
        (*timer_map)[index].destructor(contextPointer(index));
      cancelEvent((*timer_map)[index].timer);
    }
    delete p->second.timer;
  }
  delete timer_map;
}
Member Function Documentation
void RepeatTimerCore::allocateRepeatTimers (unsigned int count)
Definition at line 113 of file RepeatTimerCore.cc.
References timer, and timer_map.
Referenced by RepeatTimer::allocateRepeatTimers().
{
  Enter_Method_Silent();
  for (unsigned int i=0;i<count;i++) {
    cMessage *timer;
    if (timer_map->find(i)==timer_map->end()) {
      timer = new cMessage("timer");
      timer->setKind(i);
      (*timer_map)[i].timer = timer;
    }
  }
}
void RepeatTimerCore::cancelRepeatTimer (unsigned int index)
Cancel an existing timer set by setRepeatTimer() If the timer has not been set, or has already fires, this does nothing Must call init() before using.
Parameters:
index RepeatTimer to cancel. Must be between 0 and the value given to init()
Definition at line 63 of file RepeatTimerCore.cc.
References checkExists(), timer, and timer_map.
Referenced by RepeatTimer::cancelRepeatTimer(), and deleteRepeatTimer().
{
  Enter_Method_Silent();
  checkExists(index);
  if ((*timer_map)[index].timer->isScheduled())
    cancelEvent((*timer_map)[index].timer);
}
void RepeatTimerCore::checkExists (unsigned int index) [protected]
Definition at line 8 of file RepeatTimerCore.cc.
References timer_map.
Referenced by cancelRepeatTimer(), contextPointer(), deleteRepeatTimer(), remainingRepeatTimer(), resetRepeatTimer(), setContextDestructor(), setContextPointer(), and ~RepeatTimerCore().
{
  if (timer_map->find(index)==timer_map->end())
    error(" timer index %u doesn't exist", index);
}
typedef void() RepeatTimerCore::cleanup (void * data)
void * RepeatTimerCore::contextPointer (unsigned int index)
Retreive a "context pointer" refering to some piece of opaque useful data
Parameters:
index RepeatTimer number
Returns:
Opaque pointer from
Definition at line 107 of file RepeatTimerCore.cc.
References checkExists(), and timer_map.
Referenced by RepeatTimer::contextPointer(), deleteRepeatTimer(), and ~RepeatTimerCore().
{
  checkExists(index);
  return (*timer_map)[index].timer->getContextPointer();
}
void RepeatTimerCore::deleteRepeatTimer (unsigned int index)
Definition at line 126 of file RepeatTimerCore.cc.
References cancelRepeatTimer(), checkExists(), contextPointer(), and timer_map.
Referenced by RepeatTimer::deleteRepeatTimer().
{
  checkExists(index);
  cancelRepeatTimer(index);
  if ((*timer_map)[index].destructor)
    (*timer_map)[index].destructor(contextPointer(index));
  delete timer_map->find(index)->second.timer;
  timer_map->erase(timer_map->find(index));
}
void RepeatTimerCore::handleMessage (cMessage * msg) [protected, virtual]
Handle self messages.
Definition at line 14 of file RepeatTimerCore.cc.
References RepeatTimer::handleRepeatTimer(), timer, and timer_map.
{
  assert(msg->isSelfMessage());
  unsigned int index = msg->getKind();
  (*timer_map)[index].count --;
  if ((*timer_map)[index].count > 0) {
    cMessage *timer = (*timer_map)[index].timer;
    double when = (*timer_map)[index].when;
    scheduleAt(simTime() + when, timer);
  }
  //simulation.setContextModule(timer->owner);
  timer->handleRepeatTimer(msg->getKind());
}
void RepeatTimerCore::init (RepeatTimer * t)
Definition at line 28 of file RepeatTimerCore.cc.
References timer, and timer_map.
Referenced by RepeatTimer::init().
{
  timer = owner;
  timer_map = new std::map<unsigned int,TInfo>();
}
float RepeatTimerCore::remainingRepeatTimer (unsigned int index)
Fires on expiration of a timer. Fires after a call to setRepeatTimer(). Subclasses should override this.
Parameters:
index RepeatTimer number that fired. Will be between 0 and the value given to init()
Definition at line 71 of file RepeatTimerCore.cc.
References checkExists(), timer, and timer_map.
Referenced by RepeatTimer::remainingRepeatTimer().
{
  checkExists(index);
  if ((*timer_map)[index].timer->isScheduled())
    return SIMTIME_DBL((*timer_map)[index].timer->getArrivalTime()-simTime());
  else
    return -1;
}
void RepeatTimerCore::resetAllRepeatTimers (void)
Definition at line 148 of file RepeatTimerCore.cc.
References resetRepeatTimer(), and timer_map.
Referenced by RepeatTimer::resetAllRepeatTimers().
{
  std::map <unsigned int, TInfo>::const_iterator p;
  for (p = timer_map->begin(); p != timer_map->end(); p++) {
    resetRepeatTimer(p->second.timer->getKind());
  }
}
void RepeatTimerCore::resetRepeatTimer (unsigned int index)
Definition at line 136 of file RepeatTimerCore.cc.
References checkExists(), and timer.
Referenced by resetAllRepeatTimers(), and RepeatTimer::resetRepeatTimer().
{
  Enter_Method_Silent();
  checkExists(index);
  (*timer_map)[index].count = (*timer_map)[index].repeats;
  cMessage *timer = (*timer_map)[index].timer;
  if (timer->isScheduled())
    cancelEvent(timer);
  double when = (*timer_map)[index].when;
  scheduleAt(simTime() + when, timer);
}
void RepeatTimerCore::setContextDestructor (unsigned int index, cleanup * c)
Provide a destructor function for a "context pointer" such that we can do complete cleanup even if there are still timers remaining at the end of a simulation. Called on end of sim for still scheduled timers.
Parameters:
index RepeatTimer number
Definition at line 80 of file RepeatTimerCore.cc.
References checkExists().
Referenced by RepeatTimer::setContextDestructor().
{
  checkExists(index);
  (*timer_map)[index].destructor = c;
}
void RepeatTimerCore::setContextPointer (unsigned int index, void * data)
Set a "context pointer" refering to some piece of opaque useful data
Parameters:
index RepeatTimer number
data Opaque pointer. Never free'd or dereferenced
Definition at line 101 of file RepeatTimerCore.cc.
References checkExists().
Referenced by RepeatTimer::setContextPointer().
{
  checkExists(index);
  (*timer_map)[index].timer->setContextPointer(data);
}
unsigned int RepeatTimerCore::setRepeatTimer (double when, int repeats = 1)
Set a timer to fire at a point in the future. Auto-generates a timer id that's guaranteed not to have been used by anyone else. If the timer with that id has already been set then this discards the old information.
Parameters:
when Time in seconds in the future to fire the timer
Returns:
RepeatTimer id
Definition at line 34 of file RepeatTimerCore.cc.
References setRepeatTimer(), and timer_map.
{
  unsigned int key = timer_map->size();
  while (timer_map->find(key)!=timer_map->end())
    key++;
  setRepeatTimer(key,when,repeats);
  return key;
}
void RepeatTimerCore::setRepeatTimer (unsigned int index, double when, int repeats = 1)
Set a timer to fire at a point in the future. If the timer with that id has already been set then this discards the old information.
Parameters:
index RepeatTimer number to set.
when Time in seconds in the future to fire the timer
Definition at line 43 of file RepeatTimerCore.cc.
References timer, and timer_map.
Referenced by setRepeatTimer(), and RepeatTimer::setRepeatTimer().
{
  Enter_Method_Silent();
  cMessage *timer;
  if (timer_map->find(index)==timer_map->end()) {
    timer = new cMessage("timer");
    timer->setKind(index);
    (*timer_map)[index].timer = timer;
    (*timer_map)[index].destructor = NULL;
  } else {
    timer = (*timer_map)[index].timer;
    if (timer->isScheduled())
      cancelEvent(timer);
  }
  (*timer_map)[index].count = (*timer_map)[index].repeats = repeats;
  (*timer_map)[index].when = when;
  scheduleAt(simTime() + when, timer);
}
bool RepeatTimerCore::timerExists (unsigned int index)
Definition at line 156 of file RepeatTimerCore.cc.
References timer_map.
Referenced by RepeatTimer::timerExists().
{
  return timer_map->find(index) != timer_map->end();
}
Member Data Documentation
RepeatTimer* RepeatTimerCore::timer [protected]
Definition at line 21 of file RepeatTimerCore.h.
Referenced by allocateRepeatTimers(), cancelRepeatTimer(), handleMessage(), init(), remainingRepeatTimer(), resetRepeatTimer(), setRepeatTimer(), and ~RepeatTimerCore().
std::map<unsigned int, TInfo>* RepeatTimerCore::timer_map [protected]
Definition at line 23 of file RepeatTimerCore.h.
Referenced by allocateRepeatTimers(), cancelRepeatTimer(), checkExists(), contextPointer(), deleteRepeatTimer(), handleMessage(), init(), remainingRepeatTimer(), resetAllRepeatTimers(), setRepeatTimer(), timerExists(), and ~RepeatTimerCore().
The documentation for this class was generated from the following files:
base/timers/RepeatTimerCore.h
base/timers/RepeatTimerCore.cc