MiXiM: TimerCore Class Reference
TimerCore Class Reference
#include <TimerCore.h>
Inherits BaseModule.
Public Member Functions
typedef void() cleanup (void *data)
~TimerCore ()
void init (Timer *t)
void setTimer (unsigned int index, simtime_t when)
unsigned int setTimer (simtime_t when)
void cancelTimer (unsigned int index)
float remainingTimer (unsigned int index)
void setContextPointer (unsigned int index, void *data)
void * contextPointer (unsigned int index)
void setContextDestructor (unsigned int index, cleanup *)
void allocateTimers (unsigned int count)
void deleteTimer (unsigned int index)
Protected Member Functions
void checkExists (unsigned int index)
virtual void handleMessage (cMessage *msg)
Handle self messages.
Protected Attributes
Timer * timer
std::map< unsigned int,
cMessage * > * timers
std::map< unsigned int,
cleanup * > * destructors
Detailed Description
Definition at line 9 of file TimerCore.h.
Constructor & Destructor Documentation
TimerCore::~TimerCore ()
Definition at line 81 of file TimerCore.cc.
References checkExists(), contextPointer(), destructors, and timers.
{
  for (std::map<unsigned int,cMessage*>::const_iterator p=timers->begin();p!=timers->end();p++)
  {
    unsigned int index = p->second->getKind();
    checkExists(index);
    if ((*timers)[index]->isScheduled())
    {
      if ((*destructors)[index]!=NULL)
        (*destructors)[index](contextPointer(index));
      cancelEvent((*timers)[index]);
    }
    delete p->second;
  }
  delete timers;
  delete destructors;
}
Member Function Documentation
void TimerCore::allocateTimers (unsigned int count)
Definition at line 123 of file TimerCore.cc.
References timer, and timers.
Referenced by Timer::allocateTimers().
{
  Enter_Method_Silent();
  for (unsigned int i=0;i<count;i++)
  {
    cMessage *timer;
    if (timers->find(i)==timers->end())
    {
      timer = new cMessage("timer");
      timer->setKind(i);
      (*timers)[i] = timer;
    }
  }
}
void TimerCore::cancelTimer (unsigned int index)
Cancel an existing timer set by setTimer() If the timer has not been set, or has already fires, this does nothing Must call initTimers() before using.
Parameters:
index Timer to cancel. Must be between 0 and the value given to initTimers()
Definition at line 58 of file TimerCore.cc.
References checkExists(), and timers.
Referenced by Timer::cancelTimer(), and deleteTimer().
{
  Enter_Method_Silent();
  checkExists(index);
  if ((*timers)[index]->isScheduled())
    cancelEvent((*timers)[index]);
}
void TimerCore::checkExists (unsigned int index) [protected]
Definition at line 8 of file TimerCore.cc.
References timers.
Referenced by cancelTimer(), contextPointer(), remainingTimer(), setContextDestructor(), setContextPointer(), and ~TimerCore().
{
  if (timers->find(index)==timers->end())
    error(" timer index %u doesn't exist", index);
}
typedef void() TimerCore::cleanup (void * data)
void * TimerCore::contextPointer (unsigned int index)
Retreive a "context pointer" refering to some piece of opaque useful data
Parameters:
index Timer number
Returns:
Opaque pointer from
Definition at line 113 of file TimerCore.cc.
References checkExists(), and timers.
Referenced by Timer::contextPointer(), and ~TimerCore().
{
  checkExists(index);
  return (*timers)[index]->getContextPointer();
}
void TimerCore::deleteTimer (unsigned int index)
Definition at line 142 of file TimerCore.cc.
References cancelTimer(), and timers.
Referenced by Timer::deleteTimer().
{
  if (timers->find(index)!=timers->end())
  {
    cancelTimer(index);
    delete timers->find(index)->second;
    timers->erase(timers->find(index));
  }
}
void TimerCore::handleMessage (cMessage * msg) [protected, virtual]
Handle self messages.
Definition at line 14 of file TimerCore.cc.
References Timer::handleTimer(), and timer.
{
  assert(msg->isSelfMessage());
  //simulation.setContextModule(timer->owner);
  timer->handleTimer(msg->getKind());
}
void TimerCore::init (Timer * t)
Definition at line 21 of file TimerCore.cc.
References destructors, timer, and timers.
Referenced by Timer::init().
{
  timer = owner;
  timers = new std::map<unsigned int,cMessage *>();
  destructors = new std::map<unsigned int,cleanup *>();
}
float TimerCore::remainingTimer (unsigned int index)
Fires on expiration of a timer. Fires after a call to setTimer(). Subclasses should override this.
Parameters:
index Timer number that fired. Will be between 0 and the value given to initTimers()
Definition at line 66 of file TimerCore.cc.
References checkExists(), and timers.
Referenced by Timer::remainingTimer().
{
  checkExists(index);
  if ((*timers)[index]->isScheduled())
    return SIMTIME_DBL((*timers)[index]->getArrivalTime()-simTime());
  else
    return -1;
}
void TimerCore::setContextDestructor (unsigned int index, cleanup * c)
Provide a destructor function for a "context pointer" such that we can do complete cleanup even if there are still timers remaining at the end of a simulation. Called on end of sim for still scheduled timers.
Parameters:
index Timer number
Definition at line 75 of file TimerCore.cc.
References checkExists().
Referenced by Timer::setContextDestructor().
{
  checkExists(index);
  (*destructors)[index] = c;
}
void TimerCore::setContextPointer (unsigned int index, void * data)
Set a "context pointer" refering to some piece of opaque useful data
Parameters:
index Timer number
data Opaque pointer. Never free'd or dereferenced
Definition at line 103 of file TimerCore.cc.
References checkExists().
Referenced by Timer::setContextPointer().
{
  checkExists(index);
  (*timers)[index]->setContextPointer(data);
}
unsigned int TimerCore::setTimer (simtime_t when)
Set a timer to fire at a point in the future. Auto-generates a timer id that's guaranteed not to have been used by anyone else. If the timer with that id has already been set then this discards the old information.
Parameters:
when Time in seconds in the future to fire the timer
Returns:
Timer id
Definition at line 28 of file TimerCore.cc.
References setTimer(), and timers.
{
  unsigned int key = timers->size();
  while (timers->find(key)!=timers->end())
    key++;
  setTimer(key,when);
  return key;
}
void TimerCore::setTimer (unsigned int index, simtime_t when)
Set a timer to fire at a point in the future. If the timer with that id has already been set then this discards the old information.
Parameters:
index Timer number to set.
when Time in seconds in the future to fire the timer
Definition at line 37 of file TimerCore.cc.
References timer, and timers.
Referenced by setTimer(), and Timer::setTimer().
{
  Enter_Method_Silent();
  cMessage *timer;
  if (timers->find(index)==timers->end())
  {
    timer = new cMessage("timer");
    timer->setKind(index);
    (*timers)[index] = timer;
    (*destructors)[index] = NULL;
  }
  else
  {
    timer = (*timers)[index];
    if (timer->isScheduled())
      cancelEvent(timer);
  }
  scheduleAt(simTime() + when, timer);
}
Member Data Documentation
std::map<unsigned int, cleanup*>* TimerCore::destructors [protected]
Definition at line 18 of file TimerCore.h.
Referenced by init(), and ~TimerCore().
Timer* TimerCore::timer [protected]
Definition at line 15 of file TimerCore.h.
Referenced by allocateTimers(), handleMessage(), init(), and setTimer().
std::map<unsigned int, cMessage *>* TimerCore::timers [protected]
Definition at line 17 of file TimerCore.h.
Referenced by allocateTimers(), cancelTimer(), checkExists(), contextPointer(), deleteTimer(), init(), remainingTimer(), setTimer(), and ~TimerCore().
The documentation for this class was generated from the following files:
base/timers/TimerCore.h
base/timers/TimerCore.cc