MiXiM: PhyLayer Class Reference
PhyLayer Class Reference
[phyLayer - physical layer modules]
Provides initialisation for several AnalogueModels and Deciders from modules directory.
#include <PhyLayer.h>
Inherits BasePhyLayer.
Inherited by PhyLayerBattery, and SamplePhyLayer.
Protected Member Functions
virtual AnalogueModel * getAnalogueModelFromName (std::string name, ParameterMap &params)
Creates and returns an instance of the AnalogueModel with the specified name.
AnalogueModel * initializeSimplePathlossModel (ParameterMap &params)
Creates and initializes a SimplePathlossModel with the passed parameter values.
AnalogueModel * initializeLogNormalShadowing (ParameterMap &params)
Creates and initializes a LogNormalShadowing with the passed parameter values.
AnalogueModel * initializeJakesFading (ParameterMap &params)
Creates and initializes a JakesFading with the passed parameter values.
virtual Decider * getDeciderFromName (std::string name, ParameterMap &params)
Creates and returns an instance of the Decider with the specified name.
virtual Decider * initializeDecider80211 (ParameterMap &params)
Initializes a new Decider80211 from the passed parameter map.
virtual Decider * initializeSNRThresholdDecider (ParameterMap &params)
Initializes a new SNRThresholdDecider from the passed parameter map.
Detailed Description
Provides initialisation for several AnalogueModels and Deciders from modules directory.
Knows the following AnalogueModels:
SimplePathlossModel
LogNormalShadowing
JakesFading
Knows the following Deciders
Decider80211
SNRThresholdDecider
Definition at line 28 of file PhyLayer.h.
Member Function Documentation
AnalogueModel * PhyLayer::getAnalogueModelFromName (std::string name, ParameterMap & params) [protected, virtual]
Creates and returns an instance of the AnalogueModel with the specified name.
Is able to initialize the following AnalogueModels:
Reimplemented from BasePhyLayer.
Reimplemented in SamplePhyLayer.
Definition at line 17 of file PhyLayer.cc.
References initializeJakesFading(), initializeLogNormalShadowing(), and initializeSimplePathlossModel().
{
  if (name == "SimplePathlossModel")
  {
    return initializeSimplePathlossModel(params);
  }
  else if (name == "LogNormalShadowing")
  {
    return initializeLogNormalShadowing(params);
  }
  else if (name == "JakesFading")
  {
    return initializeJakesFading(params);
  }
  return BasePhyLayer::getAnalogueModelFromName(name, params);
}
Decider * PhyLayer::getDeciderFromName (std::string name, ParameterMap & params) [protected, virtual]
Creates and returns an instance of the Decider with the specified name.
Is able to initialize the following Deciders:
Decider80211
SNRThresholdDecider
Reimplemented from BasePhyLayer.
Reimplemented in SamplePhyLayer, and PhyLayerBattery.
Definition at line 136 of file PhyLayer.cc.
References initializeDecider80211(), and initializeSNRThresholdDecider().
{
  if(name == "Decider80211") {
    return initializeDecider80211(params);
  }
  else if(name == "SNRThresholdDecider"){
    return initializeSNRThresholdDecider(params);
  }
  return BasePhyLayer::getDeciderFromName(name, params);
}
Decider * PhyLayer::initializeDecider80211 (ParameterMap & params) [protected, virtual]
Initializes a new Decider80211 from the passed parameter map.
Definition at line 147 of file PhyLayer.cc.
References ChannelAccess::coreDebug, BaseModule::findHost(), and BasePhyLayer::sensitivity.
Referenced by getDeciderFromName().
{
  double threshold = params["threshold"];
  double centerFreq = params["centerFrequency"];
  return new Decider80211(this, threshold, sensitivity, centerFreq, findHost()->getIndex(), coreDebug);
}
AnalogueModel * PhyLayer::initializeJakesFading (ParameterMap & params) [protected]
Creates and initializes a JakesFading with the passed parameter values.
Definition at line 42 of file PhyLayer.cc.
References ChannelAccess::cc, and ChannelAccess::move.
Referenced by getAnalogueModelFromName().
{
  int fadingPaths = params["fadingPaths"].longValue();
  simtime_t delayRMS = params["delayRMS"].doubleValue();
  simtime_t interval = params["interval"].doubleValue();
  double carrierFrequency = 2.412e+9;
  if(params.count("carrierFrequency") > 0) {
    carrierFrequency = params["carrierFrequency"];
  }
  else {
    if (cc->hasPar("carrierFrequency")) {
      carrierFrequency = cc->par("carrierFrequency").doubleValue();
    }
  }
  return new JakesFading(fadingPaths, delayRMS, &move, carrierFrequency, interval);
}
AnalogueModel * PhyLayer::initializeLogNormalShadowing (ParameterMap & params) [protected]
Creates and initializes a LogNormalShadowing with the passed parameter values.
Definition at line 34 of file PhyLayer.cc.
Referenced by getAnalogueModelFromName().
{
  double mean = params["mean"].doubleValue();
  double stdDev = params["stdDev"].doubleValue();
  simtime_t interval = params["interval"].doubleValue();
  return new LogNormalShadowing(mean, stdDev, interval);
}
AnalogueModel * PhyLayer::initializeSimplePathlossModel (ParameterMap & params) [protected]
Creates and initializes a SimplePathlossModel with the passed parameter values.
Definition at line 60 of file PhyLayer.cc.
References ChannelAccess::cc, ChannelAccess::coreDebug, coreEV, BaseWorldUtility::getPgs(), ChannelAccess::move, BaseWorldUtility::useTorus(), and BasePhyLayer::world.
Referenced by getAnalogueModelFromName().
{
  // init with default value
  double alpha = 3.5;
  double carrierFrequency = 2.412e+9;
  bool useTorus = world->useTorus();
  const Coord& playgroundSize = *(world->getPgs());
  // get alpha-coefficient from config
  ParameterMap::iterator it = params.find("alpha");
  if ( it != params.end() ) // parameter alpha has been specified in config.xml
  {
    // set alpha
    alpha = it->second.doubleValue();
    coreEV << "createPathLossModel(): alpha set from config.xml to " << alpha << endl;
    // check whether alpha is not smaller than specified in ConnectionManager
    if(cc->hasPar("alpha") && alpha < cc->par("alpha").doubleValue())
    {
          // throw error
      opp_error("TestPhyLayer::createPathLossModel(): alpha can't be smaller than specified in \
                 ConnectionManager. Please adjust your config.xml file accordingly");
    }
  }
  else // alpha has not been specified in config.xml
  {
    if (cc->hasPar("alpha")) // parameter alpha has been specified in ConnectionManager
    {
      // set alpha according to ConnectionManager
      alpha = cc->par("alpha").doubleValue();
      coreEV << "createPathLossModel(): alpha set from ConnectionManager to " << alpha << endl;
    }
    else // alpha has not been specified in ConnectionManager
    {
      // keep alpha at default value
      coreEV << "createPathLossModel(): alpha set from default value to " << alpha << endl;
    }
  }
  // get carrierFrequency from config
  it = params.find("carrierFrequency");
  if ( it != params.end() ) // parameter carrierFrequency has been specified in config.xml
  {
    // set carrierFrequency
    carrierFrequency = it->second.doubleValue();
    coreEV << "createPathLossModel(): carrierFrequency set from config.xml to " << carrierFrequency << endl;
    // check whether carrierFrequency is not smaller than specified in ConnectionManager
    if(cc->hasPar("carrierFrequency") && carrierFrequency < cc->par("carrierFrequency").doubleValue())
    {
      // throw error
      opp_error("TestPhyLayer::createPathLossModel(): carrierFrequency can't be smaller than specified in \
                 ConnectionManager. Please adjust your config.xml file accordingly");
    }
  }
  else // carrierFrequency has not been specified in config.xml
  {
    if (cc->hasPar("carrierFrequency")) // parameter carrierFrequency has been specified in ConnectionManager
    {
      // set carrierFrequency according to ConnectionManager
      carrierFrequency = cc->par("carrierFrequency").doubleValue();
      coreEV << "createPathLossModel(): carrierFrequency set from ConnectionManager to " << carrierFrequency << endl;
    }
    else // carrierFrequency has not been specified in ConnectionManager
    {
      // keep carrierFrequency at default value
      coreEV << "createPathLossModel(): carrierFrequency set from default value to " << carrierFrequency << endl;
    }
  }
  return new SimplePathlossModel(alpha, carrierFrequency, &move, useTorus, playgroundSize, coreDebug);
}
Decider * PhyLayer::initializeSNRThresholdDecider (ParameterMap & params) [protected, virtual]
Initializes a new SNRThresholdDecider from the passed parameter map.
Definition at line 153 of file PhyLayer.cc.
References ChannelAccess::coreDebug, BaseModule::findHost(), and BasePhyLayer::sensitivity.
Referenced by getDeciderFromName().
{
  double threshold = params["threshold"];
  return new SNRThresholdDecider(this, threshold, sensitivity, findHost()->getIndex(), coreDebug);
}
The documentation for this class was generated from the following files:
modules/phy/PhyLayer.h
modules/phy/PhyLayer.cc