MiXiM: RSAMMapping Class Reference
RSAMMapping Class Reference
[phyLayer - physical layer modules]
This class represents the corresponding mapping to a RadioStateAnalogueModel (RSAM).
#include <PhyUtils.h>
Inherits ConstMapping.
Public Member Functions
RSAMMapping (const RadioStateAnalogueModel *rsam, simtime_t signalStart, simtime_t signalEnd)
Constructor taking a pointer to the corresponding RSAM.
virtual ~RSAMMapping ()
virtual double getValue (const Argument &pos) const
Returns the value of this Function at position specified by the passed Argument. Zero-time-switches are ignored here, i.e. in case of multiple entries at the same time-point, the last one is significant.
virtual ConstMappingIterator * createConstIterator ()
Returns a pointer of a new Iterator which is able to iterate over the function.
virtual ConstMappingIterator * createConstIterator (const Argument &pos)
Returns a pointer of a new Iterator which is able to iterate over the function. The iterator starts at the passed position.
virtual ConstMapping * constClone () const
returns a deep copy of this mapping instance.
Protected Attributes
const RadioStateAnalogueModel * rsam
simtime_t signalStart
simtime_t signalEnd
Detailed Description
This class represents the corresponding mapping to a RadioStateAnalogueModel (RSAM).
Since RSAM is modified dynamically over time, RSAMMapping doesn't store the information itself, but interacts with its RSAM to obtain information about the mapping.
The relation to RSAM is very tight. RSAM creates an appropriate RSAMMapping by passing a self-pointer to the constructor call.
class RSAMMapping is a friend of class RadioStateAnalogueModel
Definition at line 746 of file PhyUtils.h.
Constructor & Destructor Documentation
RSAMMapping::RSAMMapping (const RadioStateAnalogueModel * rsam, simtime_t signalStart, simtime_t signalEnd) [inline]
Constructor taking a pointer to the corresponding RSAM.
Definition at line 759 of file PhyUtils.h.
Referenced by constClone().
                             :
    ConstMapping(),
    rsam(rsam),
    signalStart(signalStart),
    signalEnd(signalEnd)
  {
    assert(rsam);
    assert( !(signalStart < rsam->radioIsReceiving.front().getTime()) );
  }
virtual RSAMMapping::~RSAMMapping () [inline, virtual]
Definition at line 771 of file PhyUtils.h.
{}
Member Function Documentation
virtual ConstMapping* RSAMMapping::constClone () const [inline, virtual]
returns a deep copy of this mapping instance.
Implements ConstMapping.
Definition at line 828 of file PhyUtils.h.
References RSAMMapping().
  {
    return new RSAMMapping(*this);
  }
virtual ConstMappingIterator* RSAMMapping::createConstIterator (const Argument & pos) [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the function. The iterator starts at the passed position.
Implements ConstMapping.
Definition at line 818 of file PhyUtils.h.
References RSAMConstMappingIterator::jumpTo(), rsam, signalEnd, and signalStart.
  {
    RSAMConstMappingIterator* rsamCMI
      = new RSAMConstMappingIterator(rsam, signalStart, signalEnd);
    rsamCMI->jumpTo(pos);
    return rsamCMI;
  }
virtual ConstMappingIterator* RSAMMapping::createConstIterator () [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the function.
Implements ConstMapping.
Definition at line 808 of file PhyUtils.h.
References rsam, signalEnd, and signalStart.
  {
    return new RSAMConstMappingIterator(rsam, signalStart, signalEnd);
  }
virtual double RSAMMapping::getValue (const Argument & pos) const [inline, virtual]
Returns the value of this Function at position specified by the passed Argument. Zero-time-switches are ignored here, i.e. in case of multiple entries at the same time-point, the last one is significant.
In this case we have a function: simtime_t -> attenuation
Implements ConstMapping.
Definition at line 782 of file PhyUtils.h.
References Argument::getTime(), RadioStateAnalogueModel::radioIsReceiving, and rsam.
  {
    // extract the time-component from the argument
    simtime_t t = pos.getTime();
    // assert that t is not before the first timepoint in the RSAM
    // and receiving list is not empty
    assert( !(rsam->radioIsReceiving.empty()) &&
        !(t < rsam->radioIsReceiving.front().getTime()) );
    /* receiving list contains at least one entry */
    // set an iterator to the first entry with timepoint > t
    std::list<RadioStateAnalogueModel::ListEntry>::const_iterator it;
    it = upper_bound(rsam->radioIsReceiving.begin(), rsam->radioIsReceiving.end(), t);
    // REGULAR CASE: it points to an element that has a predecessor
    it--; // go back one entry, this one is significant!
    return it->getValue();
  }
Member Data Documentation
const RadioStateAnalogueModel* RSAMMapping::rsam [protected]
Definition at line 750 of file PhyUtils.h.
Referenced by createConstIterator(), and getValue().
simtime_t RSAMMapping::signalEnd [protected]
Definition at line 752 of file PhyUtils.h.
Referenced by createConstIterator().
simtime_t RSAMMapping::signalStart [protected]
Definition at line 751 of file PhyUtils.h.
Referenced by createConstIterator().
The documentation for this class was generated from the following file:
base/phyLayer/PhyUtils.h