MiXiM: base/phyLayer/MappingUtils.h File Reference
MappingUtils.h File Reference
#include "MappingBase.h"
Classes
class BaseFilteredIterator< Base >
This iterator takes another ConstMappingIterator and does just pipe every method to the passed ConstMappingIterator.
class FilteredMappingIterator
Non-Const version of the BaseFilteredIterator. Meant to be used for MappingIterator instances.
class TimeMappingIterator< Interpolator >
Provides an implementation of the MappingIterator- Interface which is able to iterate over TimeMappings.
class TimeMapping< Interpolator >
Implements the Mapping-interface with an InterpolateableMap from simtime_t to double between which values can be interpolated to represent a Mapping with only time as domain.
class LinearIntplMappingIterator
Helper-class for the MultiDimMapping which provides an Iterator which linear interpolates between two other Mapping iterators. Or in other words, it provides an Iterator for an linear interpolated Mapping.
class LinearIntplMapping
Helper class which represents a linear interpolation between two other mappings.
class Interpolated< Mapping * >
Helper class (-specialization) for multiDimMapping which is used by an InterpolateableMap as return value of the "getValue()" - method.
class Linear< double, Mapping *, std::map< double, Mapping * >::value_type, std::map< double, Mapping * >::const_iterator >
Specialization of the Linear-template which provides LinearInterpolation for pointer two Mappings. Used by MultiDimMapping.
class ConstantSimpleConstMapping
Represents a constant mathematical mapping (f(x) = c).
class ConstMappingIteratorWrapper
Wraps an ConstMappingIterator into a MappingIterator interface.
class ConstMappingWrapper
Wraps an ConstMapping into a Mapping interface.
class MultiDimMappingIterator< Interpolator >
Implementation of the MappingIterator-interface which is able to iterate over every value in a MultiDimMapping.
class MultiDimMapping< Interpolator >
Implementation of the Mapping-interface which is able to represent arbitrary dimensional instances of Mappings by using a tree-like structure of sub-mappings, each representing the values for one of the dimensions.
class FilledUpMappingIterator
MappingIterator implementation for FilledUpMappings.
class FilledUpMapping
Takes a source ConstMapping with a domain A and a set of KeyEntries for a domain B and creates a clone of the source mapping with the domain B and the KeyEntries passed.
class MappingUtils
Provides several utility methods for Mappings.
class ConcatConstMappingIterator
Deletes its ConstMapping when this iterator is deleted.
class ConcatConstMapping< Operator >
Defines it values by concatenating one or more Mappings to a reference Mapping.
class BaseDelayedIterator< Base, Iterator >
Common base for a Const- and NonConst-Iterator for a DelayedMapping.
class BaseDelayedMapping< Base >
Common base for Const- and NonConst-DelayedMapping.
class ConstDelayedMapping
Moves another ConstMapping in its time dimension.
class DelayedMapping
Moves another Mapping in its time dimension.
Typedefs
typedef BaseFilteredIterator
< ConstMappingIterator > FilteredConstMappingIterator
Const version of the BaseFilteredIterator. Meant to be used for ConstMappingIterator instances.
typedef BaseDelayedIterator
< FilteredConstMappingIterator,
ConstMappingIterator > ConstDelayedMappingIterator
ConstIterator for a ConstDelayedMapping.
typedef BaseDelayedIterator
< FilteredMappingIterator,
MappingIterator > DelayedMappingIterator
Iterator for a DelayedMapping.
Functions
Mapping * operator* (ConstMapping &f1, ConstMapping &f2)
Mapping * operator/ (ConstMapping &f1, ConstMapping &f2)
Mapping * operator+ (ConstMapping &f1, ConstMapping &f2)
Mapping * operator- (ConstMapping &f1, ConstMapping &f2)
Function Documentation
Mapping* operator* (ConstMapping & f1, ConstMapping & f2)
Definition at line 202 of file MappingUtils.cc.
References MappingUtils::multiply().
{
  return MappingUtils::multiply(f1, f2);
}
Mapping* operator+ (ConstMapping & f1, ConstMapping & f2)
Definition at line 210 of file MappingUtils.cc.
References MappingUtils::add().
{
  return MappingUtils::add(f1, f2);
}
Mapping* operator- (ConstMapping & f1, ConstMapping & f2)
Definition at line 214 of file MappingUtils.cc.
References MappingUtils::subtract().
{
  return MappingUtils::subtract(f1, f2);
}
Mapping* operator/ (ConstMapping & f1, ConstMapping & f2)
Definition at line 206 of file MappingUtils.cc.
References MappingUtils::divide().
{
  return MappingUtils::divide(f1, f2);
}