MiXiM: SimplePathlossConstMapping Class Reference
SimplePathlossConstMapping Class Reference
[analogueModels - AnalogueModel implementations, mapping - classes representing mathematical mappings]
Mapping that represents a Pathloss-function.
#include <SimplePathlossModel.h>
Inherits SimpleConstMapping.
Public Member Functions
SimplePathlossConstMapping (const DimensionSet &dimensions, SimplePathlossModel *model, const double distFactor)
initializes the PathlossMapping for the passed dimensions, its model and the distance factor for the signal to attenuate.
virtual double getValue (const Argument &pos) const
Calculates attenuation from the distance factor and the current positions frequency (or the models carrier frequency if we are using using signals without frequency domain.
ConstMapping * constClone () const
creates a clone of this mapping. This method has to be implemented by every subclass. But most time the implementation will look like the implementation of this method (except of the class name).
Protected Attributes
const double distFactor
SimplePathlossModel * model
bool hasFrequency
Detailed Description
Mapping that represents a Pathloss-function.
SimplePathlossConstMapping is subclassed from SimpleConstMapping for convenience. In this simple pathloss implementation, we assume one attenuation value being constant over the signals duration.
Definition at line 22 of file SimplePathlossModel.h.
Constructor & Destructor Documentation
SimplePathlossConstMapping::SimplePathlossConstMapping (const DimensionSet & dimensions, SimplePathlossModel * model, const double distFactor)
initializes the PathlossMapping for the passed dimensions, its model and the distance factor for the signal to attenuate.
Definition at line 5 of file SimplePathlossModel.cc.
Referenced by constClone().
                                                      :
  SimpleConstMapping(dimensions),
  distFactor(distFactor),
  model(model),
  hasFrequency(dimensions.hasDimension(Dimension::frequency_static()))
{
}
Member Function Documentation
ConstMapping* SimplePathlossConstMapping::constClone () const [inline, virtual]
creates a clone of this mapping. This method has to be implemented by every subclass. But most time the implementation will look like the implementation of this method (except of the class name).
Implements SimpleConstMapping.
Definition at line 51 of file SimplePathlossModel.h.
References SimplePathlossConstMapping().
  {
    return new SimplePathlossConstMapping(*this);
  }
double SimplePathlossConstMapping::getValue (const Argument & pos) const [virtual]
Calculates attenuation from the distance factor and the current positions frequency (or the models carrier frequency if we are using using signals without frequency domain.
Implements SimpleConstMapping.
Definition at line 15 of file SimplePathlossModel.cc.
References SimplePathlossModel::carrierFrequency, distFactor, Dimension::frequency, Argument::getArgValue(), Argument::hasArgVal(), hasFrequency, model, and BaseWorldUtility::speedOfLight.
{
  double freq = model->carrierFrequency;
  if(hasFrequency) {
    assert(pos.hasArgVal(Dimension::frequency));
    freq = pos.getArgValue(Dimension::frequency);
  }
  double wavelength = BaseWorldUtility::speedOfLight / freq;
  return (wavelength * wavelength) * distFactor;
}
Member Data Documentation
const double SimplePathlossConstMapping::distFactor [protected]
Definition at line 26 of file SimplePathlossModel.h.
Referenced by getValue().
bool SimplePathlossConstMapping::hasFrequency [protected]
Definition at line 28 of file SimplePathlossModel.h.
Referenced by getValue().
SimplePathlossModel* SimplePathlossConstMapping::model [protected]
Definition at line 27 of file SimplePathlossModel.h.
Referenced by getValue().
The documentation for this class was generated from the following files:
modules/analogueModel/SimplePathlossModel.h
modules/analogueModel/SimplePathlossModel.cc