MiXiM: Signal Class Reference
Signal Class Reference
[phyLayer - physical layer modules]
The signal class stores the physical representation of the signal of an AirFrame.
#include <Signal_.h>
Public Types
typedef ConcatConstMapping
< std::multiplies< double > > MultipliedMapping
typedef std::list< ConstMapping * > ConstMappingList
Public Member Functions
Signal (simtime_t start=-1.0, simtime_t length=-1.0)
Initializes a signal with the specified start and length.
Signal (const Signal &o)
Overwrites the copy constructor to make sure that the mappings are cloned correct.
const Signal & operator= (const Signal &o)
Overwrites the copy operator to make sure that the mappings are cloned correct.
~Signal ()
Delete the functions of this signal.
simtime_t getSignalStart () const
Returns the point in time when the receiving of the Signal started.
Move getMove () const
Returns the movement of the sending host.
void setMove (Move &move)
Sets the movement of the sending host.
simtime_t getSignalLength () const
Returns the length of the signal transmission.
simtime_t getPropagationDelay () const
Returns the propagation delay of the signal.
void setPropagationDelay (simtime_t delay)
Sets the propagation delay of the signal.
void setTransmissionPower (ConstMapping *power)
Sets the function representing the transmission power of the signal.
void setBitrate (Mapping *bitrate)
Sets the function representing the bitrate of the signal.
void addAttenuation (ConstMapping *att)
Adds a function representing an attenuation of the signal.
ConstMapping * getTransmissionPower ()
Returns the function representing the transmission power of the signal.
const ConstMapping * getTransmissionPower () const
Returns the function representing the transmission power of the signal.
Mapping * getBitrate ()
Returns the function representing the bitrate of the signal.
const ConstMappingList & getAttenuation () const
Returns a list of functions representing the attenuations of the signal.
MultipliedMapping * getReceivingPower ()
Calculates and returns the receiving power of this Signal. Ownership of the returned mapping belongs to this class.
Protected Member Functions
void markRcvPowerOutdated ()
Protected Attributes
simtime_t signalStart
The start of the signal transmission.
simtime_t signalLength
The length of the signal transmission.
simtime_t propDelay
The propagation delay of the transmission.
Move senderMovement
The movement of the sending host.
ConstMapping * power
Stores the function which describes the power of the signal.
Mapping * bitrate
Stores the function which describes the bitrate of the signal.
Mapping * txBitrate
If propagation delay is not zero this stores the undelayed bitrate.
ConstMappingList attenuations
Stores the functions describing the attenuations of the signal.
MultipliedMapping * rcvPower
Detailed Description
The signal class stores the physical representation of the signal of an AirFrame.
This includes start, duration and propagation delay of the signal, the sender hosts move pattern as well as Mappings which represent the transmission power, bitrate, attenuations caused by effects of the channel on the signal during its transmission and the receiving power.
The Signal is created at the senders MAC layer which has to define the TX-power- and the bitrate Mapping. The sender hosts move pattern as well as start and duration is added at the senders physical layer. Attenuation Mappings are added to the Signal by the AnalogueModels of the receivers physical layer. The RX-power Mapping is calculated on demand by multiplying the TX-power Mapping with every attenuation Mapping of the signal.
Definition at line 30 of file Signal_.h.
Member Typedef Documentation
typedef std::list<ConstMapping*> Signal::ConstMappingList
Definition at line 33 of file Signal_.h.
typedef ConcatConstMapping<std::multiplies<double> > Signal::MultipliedMapping
Definition at line 32 of file Signal_.h.
Constructor & Destructor Documentation
Signal::Signal (simtime_t start = -1.0, simtime_t length = -1.0)
Initializes a signal with the specified start and length.
Definition at line 3 of file Signal.cc.
                                               :
  signalStart(start), signalLength(length),
  propDelay(0),
  power(0), bitrate(0),
  txBitrate(0),
  rcvPower(0)
{}
Signal::Signal (const Signal & o)
Overwrites the copy constructor to make sure that the mappings are cloned correct.
Definition at line 11 of file Signal.cc.
References attenuations, bitrate, Mapping::clone(), ConstMapping::constClone(), power, and txBitrate.
                              :
  signalStart(o.signalStart), signalLength(o.signalLength),
  propDelay(o.propDelay),
  senderMovement(o.senderMovement),
  power(0), bitrate(0),
  txBitrate(0),
  rcvPower(0)
{
  if (o.power) {
    power = o.power->constClone();
  }
  if (o.bitrate) {
    bitrate = o.bitrate->clone();
  }
  if (o.txBitrate) {
    txBitrate = o.txBitrate->clone();
  }
  for(ConstMappingList::const_iterator it = o.attenuations.begin();
    it != o.attenuations.end(); it++){
    attenuations.push_back((*it)->constClone());
  }
}
Signal::~Signal ()
Delete the functions of this signal.
Definition at line 84 of file Signal.cc.
References attenuations, bitrate, ConcatConstMapping< Operator >::getRefMapping(), power, propDelay, rcvPower, and txBitrate.
{
  if(rcvPower){
    if(propDelay != 0){
      assert(rcvPower->getRefMapping() != power);
      delete rcvPower->getRefMapping();
    }
    delete rcvPower;
  }
  if(power)
    delete power;
  if(bitrate)
    delete bitrate;
  if(txBitrate)
    delete txBitrate;
  for(ConstMappingList::iterator it = attenuations.begin();
    it != attenuations.end(); it++) {
    delete *it;
  }
}
Member Function Documentation
void Signal::addAttenuation (ConstMapping * att) [inline]
Adds a function representing an attenuation of the signal.
The ownership of the passed pointer goes to the signal.
Definition at line 150 of file Signal_.h.
References ConcatConstMapping< Operator >::addMapping(), attenuations, and rcvPower.
Referenced by SimplePathlossModel::filterSignal(), LogNormalShadowing::filterSignal(), JakesFading::filterSignal(), RandomFrequencyOnlyModel::filterSignal(), RandomFreqTimeModel::filterSignal(), and RadioStateAnalogueModel::filterSignal().
{
    attenuations.push_back(att);
    if(rcvPower)
      rcvPower->addMapping(att);
  }
const ConstMappingList& Signal::getAttenuation () const [inline]
Returns a list of functions representing the attenuations of the signal.
Definition at line 191 of file Signal_.h.
References attenuations.
{
    return attenuations;
  }
Mapping* Signal::getBitrate () [inline]
Returns the function representing the bitrate of the signal.
Definition at line 183 of file Signal_.h.
References bitrate.
Referenced by Decider80211::checkIfSignalOk().
{
    return bitrate;
  }
Move Signal::getMove () const
Returns the movement of the sending host.
Definition at line 161 of file Signal.cc.
References senderMovement.
Referenced by SimplePathlossModel::filterSignal(), and JakesFading::filterSignal().
{
  return senderMovement;
}
simtime_t Signal::getPropagationDelay () const
Returns the propagation delay of the signal.
Definition at line 119 of file Signal.cc.
References propDelay.
{
  return propDelay;
}
MultipliedMapping* Signal::getReceivingPower () [inline]
Calculates and returns the receiving power of this Signal. Ownership of the returned mapping belongs to this class.
The receiving power is calculated by multiplying the transmission power with the attenuation of every receiving phys AnalogueModel.
Definition at line 202 of file Signal_.h.
References attenuations, power, propDelay, and rcvPower.
Referenced by BaseDecider::calculateRSSIMapping(), BaseDecider::calculateSnrMapping(), Decider80211::processNewSignal(), and BaseDecider::processNewSignal().
{
    if(!rcvPower)
    {
      ConstMapping* tmp = power;
      if(propDelay != 0) {
        tmp = new ConstDelayedMapping(power, propDelay);
      }
      rcvPower = new MultipliedMapping(tmp,
                        attenuations.begin(),
                        attenuations.end());
    }
    return rcvPower;
  }
simtime_t Signal::getSignalLength () const
Returns the length of the signal transmission.
Definition at line 115 of file Signal.cc.
References signalLength.
Referenced by BaseDecider::calculateRSSIMapping(), BaseDecider::calculateSnrMapping(), Decider80211::checkIfSignalOk(), BasePhyLayer::encapsMsg(), SimplePathlossModel::filterSignal(), LogNormalShadowing::filterSignal(), JakesFading::filterSignal(), RandomFreqTimeModel::filterSignal(), RadioStateAnalogueModel::filterSignal(), BasePhyLayer::handleAirFrameReceiving(), ThresholdDecider::handleNewSignal(), Decider80211::processNewSignal(), BaseDecider::processNewSignal(), and SNRThresholdDecider::processSignalEnd().
{
  return signalLength;
}
simtime_t Signal::getSignalStart () const
Returns the point in time when the receiving of the Signal started.
Already includes the propagation delay.
Definition at line 111 of file Signal.cc.
References propDelay, and signalStart.
Referenced by BaseDecider::calculateRSSIMapping(), BaseDecider::calculateSnrMapping(), Decider80211::checkIfSignalOk(), SimplePathlossModel::filterSignal(), LogNormalShadowing::filterSignal(), JakesFading::filterSignal(), RandomFrequencyOnlyModel::filterSignal(), RandomFreqTimeModel::filterSignal(), RadioStateAnalogueModel::filterSignal(), BasePhyLayer::handleAirFrameReceiving(), BasePhyLayer::handleAirFrameStartReceive(), ThresholdDecider::handleNewSignal(), Decider80211::processNewSignal(), BaseDecider::processNewSignal(), and SNRThresholdDecider::processSignalEnd().
{
  return signalStart + propDelay;
}
const ConstMapping* Signal::getTransmissionPower () const [inline]
Returns the function representing the transmission power of the signal.
Be aware that the transmission power mapping is not yet affected by the propagation delay!
Definition at line 175 of file Signal_.h.
References power.
{
    return power;
  }
ConstMapping* Signal::getTransmissionPower () [inline]
Returns the function representing the transmission power of the signal.
Be aware that the transmission power mapping is not yet affected by the propagation delay!
Definition at line 164 of file Signal_.h.
References power.
Referenced by SimplePathlossModel::filterSignal().
{
    return power;
  }
void Signal::markRcvPowerOutdated () [inline, protected]
Definition at line 62 of file Signal_.h.
References ConcatConstMapping< Operator >::getRefMapping(), power, propDelay, and rcvPower.
Referenced by operator=(), setPropagationDelay(), and setTransmissionPower().
{
    if(rcvPower){
      if(propDelay != 0) {
        assert(rcvPower->getRefMapping() != power);
        delete rcvPower->getRefMapping();
      }
      delete rcvPower;
      rcvPower = 0;
    }
  }
const Signal & Signal::operator= (const Signal & o)
Overwrites the copy operator to make sure that the mappings are cloned correct.
Definition at line 37 of file Signal.cc.
References attenuations, bitrate, Mapping::clone(), ConstMapping::constClone(), markRcvPowerOutdated(), power, propDelay, senderMovement, signalLength, signalStart, and txBitrate.
{
  signalStart = o.signalStart;
  signalLength = o.signalLength;
  propDelay = o.propDelay;
  senderMovement = o.senderMovement;
  markRcvPowerOutdated();
  if(power){
    delete power;
    power = 0;
  }
  if(bitrate){
    delete bitrate;
    bitrate = 0;
  }
  if(txBitrate){
    delete txBitrate;
    txBitrate = 0;
  }
  if(o.power)
    power = o.power->constClone();
  if(o.bitrate)
    bitrate = o.bitrate->clone();
  if(o.txBitrate)
    txBitrate = o.txBitrate->clone();
  for(ConstMappingList::const_iterator it = attenuations.begin();
    it != attenuations.end(); it++){
    delete(*it);
  }
  attenuations.clear();
  for(ConstMappingList::const_iterator it = o.attenuations.begin();
    it != o.attenuations.end(); it++){
    attenuations.push_back((*it)->constClone());
  }
  return *this;
}
void Signal::setBitrate (Mapping * bitrate)
Sets the function representing the bitrate of the signal.
The ownership of the passed pointer goes to the signal.
Definition at line 147 of file Signal.cc.
References txBitrate.
Referenced by SimpleMacLayer::createMacPkt(), Mac80211::createSignal(), and BaseMacLayer::createSignal().
{
  assert(!txBitrate);
  if(this->bitrate)
    delete this->bitrate;
  this->bitrate = bitrate;
}
void Signal::setMove (Move & move)
Sets the movement of the sending host.
Definition at line 157 of file Signal.cc.
References senderMovement.
Referenced by BasePhyLayer::encapsMsg().
{
  senderMovement = move;
}
void Signal::setPropagationDelay (simtime_t delay)
Sets the propagation delay of the signal.
This should be only set by the sending physical layer.
Definition at line 123 of file Signal.cc.
References bitrate, markRcvPowerOutdated(), propDelay, and txBitrate.
Referenced by BasePhyLayer::handleAirFrameStartReceive().
{
  assert(propDelay == 0);
  assert(!txBitrate);
  markRcvPowerOutdated();
  propDelay = delay;
  if(bitrate) {
    txBitrate = bitrate;
    bitrate = new DelayedMapping(txBitrate, propDelay);
  }
}
void Signal::setTransmissionPower (ConstMapping * power)
Sets the function representing the transmission power of the signal.
The ownership of the passed pointer goes to the signal.
Definition at line 137 of file Signal.cc.
References markRcvPowerOutdated().
Referenced by SimpleMacLayer::createMacPkt(), Mac80211::createSignal(), and BaseMacLayer::createSignal().
{
  if(this->power){
    markRcvPowerOutdated();
    delete this->power;
  }
  this->power = power;
}
Member Data Documentation
ConstMappingList Signal::attenuations [protected]
Stores the functions describing the attenuations of the signal.
Definition at line 57 of file Signal_.h.
Referenced by addAttenuation(), getAttenuation(), getReceivingPower(), operator=(), Signal(), and ~Signal().
Mapping* Signal::bitrate [protected]
Stores the function which describes the bitrate of the signal.
Definition at line 51 of file Signal_.h.
Referenced by getBitrate(), operator=(), setPropagationDelay(), Signal(), and ~Signal().
ConstMapping* Signal::power [protected]
Stores the function which describes the power of the signal.
Definition at line 48 of file Signal_.h.
Referenced by getReceivingPower(), getTransmissionPower(), markRcvPowerOutdated(), operator=(), Signal(), and ~Signal().
simtime_t Signal::propDelay [protected]
The propagation delay of the transmission.
Definition at line 42 of file Signal_.h.
Referenced by getPropagationDelay(), getReceivingPower(), getSignalStart(), markRcvPowerOutdated(), operator=(), setPropagationDelay(), and ~Signal().
MultipliedMapping* Signal::rcvPower [protected]
Definition at line 59 of file Signal_.h.
Referenced by addAttenuation(), getReceivingPower(), markRcvPowerOutdated(), and ~Signal().
Move Signal::senderMovement [protected]
The movement of the sending host.
Definition at line 45 of file Signal_.h.
Referenced by getMove(), operator=(), and setMove().
simtime_t Signal::signalLength [protected]
The length of the signal transmission.
Definition at line 40 of file Signal_.h.
Referenced by getSignalLength(), and operator=().
simtime_t Signal::signalStart [protected]
The start of the signal transmission.
Definition at line 38 of file Signal_.h.
Referenced by getSignalStart(), and operator=().
Mapping* Signal::txBitrate [protected]
If propagation delay is not zero this stores the undelayed bitrate.
Definition at line 54 of file Signal_.h.
Referenced by operator=(), setBitrate(), setPropagationDelay(), Signal(), and ~Signal().
The documentation for this class was generated from the following files:
base/phyLayer/Signal_.h
base/phyLayer/Signal.cc