MiXiM: PhyToMacControlInfo Class Reference
PhyToMacControlInfo Class Reference
[phyLayer - physical layer modules, macLayer - MAC layer modules]
Controlinfo for packets which are send from Physical layer to the MAC layer.
#include <PhyToMacControlInfo.h>
Public Member Functions
PhyToMacControlInfo (DeciderResult *result)
Initializes the PhyToMacControlInfo with the passed DeciderResult.
~PhyToMacControlInfo ()
Clean up the DeciderResult.
const DeciderResult * getDeciderResult () const
Returns the result of the evaluation of the Decider.
Protected Attributes
DeciderResult * result
Detailed Description
Controlinfo for packets which are send from Physical layer to the MAC layer.
The ControlInfo contains the the DeciderResult of the Decider.
Definition at line 15 of file PhyToMacControlInfo.h.
Constructor & Destructor Documentation
PhyToMacControlInfo::PhyToMacControlInfo (DeciderResult * result) [inline]
Initializes the PhyToMacControlInfo with the passed DeciderResult.
NOTE: PhyToMacControlInfo takes ownership of the passed DeciderResult!
Definition at line 26 of file PhyToMacControlInfo.h.
                                            :
    result(result) {}
PhyToMacControlInfo::~PhyToMacControlInfo () [inline]
Clean up the DeciderResult.
Definition at line 32 of file PhyToMacControlInfo.h.
References result.
{
    if(result)
      delete result;
  }
Member Function Documentation
const DeciderResult* PhyToMacControlInfo::getDeciderResult () const [inline]
Returns the result of the evaluation of the Decider.
Definition at line 40 of file PhyToMacControlInfo.h.
References result.
Referenced by Mac80211::sendACKframe(), Mac80211::sendCTSframe(), and Mac80211::sendDATAframe().
{
    return result;
  }
Member Data Documentation
DeciderResult* PhyToMacControlInfo::result [protected]
The result of the decider evaluation.
Definition at line 18 of file PhyToMacControlInfo.h.
Referenced by getDeciderResult(), and ~PhyToMacControlInfo().
The documentation for this class was generated from the following file:
base/phyLayer/PhyToMacControlInfo.h