MiXiM: SimpleMacLayer Class Reference
SimpleMacLayer Class Reference
[AnalogueModels example - Classes from the AnalogueModels example]
A simple Mac layer implementation which only shows how to create Signals, send them to Phy and receive the from the Phy layer.
#include <SimpleMacLayer.h>
Inherits BaseModule.
Public Member Functions
virtual void initialize (int stage)
Basic initialization for all modules.
virtual void handleMessage (cMessage *msg)
Protected Types
enum { TEST_MACPKT = 12121 }
Protected Member Functions
Mapping * createMapping (simtime_t time, simtime_t length, double freqFrom, double freqTo, double value)
Creates a Mapping with the passed value at the passed position in freqency and time.
void handleMacPkt (MacPkt *pkt)
void handleTXOver ()
void broadCastPacket ()
Sends the answer packet.
void sendDown (MacPkt *pkt)
MacPkt * createMacPkt (simtime_t length)
Creates the answer packet.
void log (std::string msg)
Protected Attributes
MacToPhyInterface * phy
Pointer to the phy module of this host.
int dataOut
Omnet gates.
int dataIn
int myIndex
int nextReceiver
The index of the host the next packet should be send to.
DimensionSet dimensions
The dimensions for the signal this mac layer works with (frequency and time).
Detailed Description
A simple Mac layer implementation which only shows how to create Signals, send them to Phy and receive the from the Phy layer.
This Mac layer just sends an answer packet every time it receives a packet. Since both hosts do that in this simulation, it will only terminate if one packet gets lost (couldn't be received by the phy layer correctly).
Definition at line 21 of file SimpleMacLayer.h.
Member Enumeration Documentation
anonymous enum [protected]
Enumerator:
TEST_MACPKT Used as Message kind to identify MacPackets.
Definition at line 35 of file SimpleMacLayer.h.
       {
    TEST_MACPKT = 12121
  };
Member Function Documentation
void SimpleMacLayer::broadCastPacket () [protected]
Sends the answer packet.
Definition at line 94 of file SimpleMacLayer.cc.
References createMacPkt(), log(), and sendDown().
Referenced by handleMessage().
{
  //create the answer packet of length 64kByte / 11kByte/sec
  MacPkt* pkt = createMacPkt(64.0 / 11000.0);
  log("Sending broadcast packet to phy layer.");
  //pass it to the phy layer
  sendDown(pkt);
}
MacPkt * SimpleMacLayer::createMacPkt (simtime_t length) [protected]
Creates the answer packet.
Definition at line 134 of file SimpleMacLayer.cc.
References createMapping(), nextReceiver, Signal::setBitrate(), Signal::setTransmissionPower(), and TEST_MACPKT.
Referenced by broadCastPacket().
{
  //create signal with start at current simtime and passed length
  Signal* s = new Signal(simTime(), length);
  //create and set tx power mapping
  Mapping* txPower = createMapping(simTime(), length, 2.412, 2.472, 50.0);
  s->setTransmissionPower(txPower);
  //create and set bitrate mapping
  Mapping* bitrate = createMapping(simTime(), length, 2.412, 2.472, 54.0);
  s->setBitrate(bitrate);
  //create and initialize control info
  MacToPhyControlInfo* ctrl = new MacToPhyControlInfo(s);
  MacPkt* res = new MacPkt();
  res->setControlInfo(ctrl);
  res->setKind(TEST_MACPKT);
  res->setDestAddr(nextReceiver);
  return res;
}
Mapping * SimpleMacLayer::createMapping (simtime_t time, simtime_t length, double freqFrom, double freqTo, double value) [protected]
Creates a Mapping with the passed value at the passed position in freqency and time.
Definition at line 107 of file SimpleMacLayer.cc.
References dimensions, Mapping::LINEAR, Argument::setArgValue(), Argument::setTime(), and Mapping::setValue().
Referenced by createMacPkt().
{
  //create mapping for frequency and time
  Mapping* m = MappingUtils::createMapping(0.0, dimensions, Mapping::LINEAR);
  //set position Argument
  Argument pos(dimensions, time);
  pos.setArgValue(Dimension("frequency"), freqFrom);
  //set mapping at position
  m->setValue(pos, value);
  pos.setTime(time + length);
  //set mapping at position
  m->setValue(pos, value);
  pos.setArgValue(Dimension("frequency"), freqTo);
  //set mapping at position
  m->setValue(pos, value);
  pos.setTime(time);
  //set mapping at position
  m->setValue(pos, value);
  return m;
}
void SimpleMacLayer::handleMacPkt (MacPkt * pkt) [protected]
Definition at line 71 of file SimpleMacLayer.cc.
References log(), myIndex, nextReceiver, phy, MacToPhyInterface::setRadioState(), and Radio::TX.
Referenced by handleMessage().
{
  //if we got a Mac packet check if it was for us or not.
  if(pkt->getDestAddr() == myIndex){
    log("Received MacPkt for me - broadcasting answer (but first change to TX mode)");
    if(myIndex == 0)
      nextReceiver = 1;
    else
      nextReceiver = 0;
    //if the destination of the packet was us, send an answer packet->switch to sending mode
    phy->setRadioState(Radio::TX);
  }else
    log("Received MacPkt - but not for me.");
  delete pkt;
}
void SimpleMacLayer::handleMessage (cMessage * msg) [virtual]
Definition at line 38 of file SimpleMacLayer.cc.
References broadCastPacket(), MacToPhyInterface::getRadioState(), handleMacPkt(), handleTXOver(), log(), phy, MacToPhyInterface::RADIO_SWITCHING_OVER, TEST_MACPKT, Radio::TX, and MacToPhyInterface::TX_OVER.
{
  //what to do if the radio has switched
  if(msg->getKind() == MacToPhyInterface::RADIO_SWITCHING_OVER) {
    log("...switching radio done.");
    switch(phy->getRadioState()) {
    case Radio::TX:     //if we switched to TX mode we probably wanted to send
      broadCastPacket();  //an answer packet
      break;
    default:
      break;
    }
    delete msg;
  //forward MacPackets and TX_OVER to their own handling routine
  } else if (msg->getKind() == TEST_MACPKT) {
    handleMacPkt(static_cast<MacPkt*>(msg));
  } else if(msg->getKind() == MacToPhyInterface::TX_OVER) {
    handleTXOver();
    delete msg;
  }
}
void SimpleMacLayer::handleTXOver () [protected]
Definition at line 63 of file SimpleMacLayer.cc.
References log(), phy, Radio::RX, and MacToPhyInterface::setRadioState().
Referenced by handleMessage().
{
  //the TX_Over message is sent by the phy to us to indicate that
  //the sending process is over. SO we will switch back to receiving
  //mode after that.
  log("Transmission over signal from PhyLayer received. Changing back to RX");
  phy->setRadioState(Radio::RX);
}
void SimpleMacLayer::initialize (int stage) [virtual]
Basic initialization for all modules.
Subscription to Blackboard should be in stage==0, and firing notifications in stage==1 or later.
NOTE: You have to call this in the initialize() function of the inherited class!
Reimplemented from BaseModule.
Definition at line 9 of file SimpleMacLayer.cc.
References DimensionSet::addDimension(), dataIn, dataOut, dimensions, BaseModule::findHost(), Dimension::frequency, log(), myIndex, nextReceiver, phy, Radio::RX, MacToPhyInterface::setRadioState(), Dimension::time, and Radio::TX.
{
  BaseModule::initialize(stage);
  if(stage == 0) {
    myIndex = findHost()->getIndex();
    dimensions.addDimension(Dimension::time);
    dimensions.addDimension(Dimension::frequency);
    dataOut = findGate("lowerGateOut");
    dataIn = findGate("lowerGateIn");
    phy = FindModule<MacToPhyInterface*>::findSubModule(this->getParentModule());
  } else if(stage == 1) {
    if(myIndex == 0){ //host with index 0 start with sending packets
      log("Switching radio to TX...");
      nextReceiver = 1;
      phy->setRadioState(Radio::TX); //to be able to send packets it has to switch to TX mode
    }else{ //every other host start in receiving mode
      log("Switching radio to RX...");
      phy->setRadioState(Radio::RX);
    }
    //switching the radio can take some time,
    //we will get a "RADIO_SWITCHING_OVER" message as soon as the radio has switched.
  }
}
void SimpleMacLayer::log (std::string msg) [protected]
Definition at line 90 of file SimpleMacLayer.cc.
References myIndex.
Referenced by broadCastPacket(), handleMacPkt(), handleMessage(), handleTXOver(), and initialize().
{
  ev << "[Host " << myIndex << "] - MacLayer: " << msg << endl;
}
void SimpleMacLayer::sendDown (MacPkt * pkt) [protected]
Definition at line 103 of file SimpleMacLayer.cc.
References dataOut.
Referenced by broadCastPacket().
{
  send(pkt, dataOut);
}
Member Data Documentation
int SimpleMacLayer::dataIn [protected]
Definition at line 28 of file SimpleMacLayer.h.
Referenced by initialize().
int SimpleMacLayer::dataOut [protected]
Omnet gates.
Definition at line 27 of file SimpleMacLayer.h.
Referenced by initialize(), and sendDown().
DimensionSet SimpleMacLayer::dimensions [protected]
The dimensions for the signal this mac layer works with (frequency and time).
Definition at line 41 of file SimpleMacLayer.h.
Referenced by createMapping(), and initialize().
int SimpleMacLayer::myIndex [protected]
Definition at line 30 of file SimpleMacLayer.h.
Referenced by handleMacPkt(), initialize(), and log().
int SimpleMacLayer::nextReceiver [protected]
The index of the host the next packet should be send to.
Definition at line 33 of file SimpleMacLayer.h.
Referenced by createMacPkt(), handleMacPkt(), and initialize().
MacToPhyInterface* SimpleMacLayer::phy [protected]
Pointer to the phy module of this host.
Definition at line 24 of file SimpleMacLayer.h.
Referenced by handleMacPkt(), handleMessage(), handleTXOver(), and initialize().
The documentation for this class was generated from the following files:
examples/analogueModels/SimpleMacLayer.h
examples/analogueModels/SimpleMacLayer.cc