MiXiM: PhyLayerBattery Class Reference
PhyLayerBattery Class Reference
[Power consumption - Classes using/defining power consumption, decider - decider modules]
Extends PhyLayer by adding power consumption for tx, rx and idle.
#include <PhyLayerBattery.h>
Inherits PhyLayer.
Public Member Functions
virtual void initialize (int stage)
OMNeT++ initialization function. Read simple parameters. Read and parse xml file for decider and analogue models configuration.
virtual void handleUpperMessage (cMessage *msg)
Checks the hosts state and draws txCurrent from battery.
virtual void handleAirFrame (cMessage *msg)
Checks if the the host state is on and prevents reception of AirFrames if not.
virtual void handleSelfMessage (cMessage *msg)
Catches TX over messages to set current power consumption back for idle mode.
virtual void handleHostState (const HostState &state)
Provides ability to draw power for the Decider.
Protected Types
enum Activities { SLEEP_ACCT = 0, IDLE_ACCT = 1, RX_ACCT = 2, TX_ACCT = 3 }
Defines the power consuming activities (accounts) of the NIC. Should be the same as defined in the decider.
Protected Member Functions
virtual Decider * getDeciderFromName (std::string name, ParameterMap &params)
Creates and returns an instance of the Decider with the specified name.
virtual Decider * initializeDecider80211Battery (ParameterMap &params)
Initializes a new Decider80211Battery from the passed parameter map.
Protected Attributes
int numActivities
Number of power consuming activities (accounts).
double sleepCurrent
The different currents in mA.
double idleCurrent
double rxCurrent
double txCurrent
Detailed Description
Extends PhyLayer by adding power consumption for tx, rx and idle.
Does two things, first before sending messages to the channel or receiving messages from the channel it checks the hosts current state. If the host is not able to send or the receive (e.g. no power) the messages are dropped. Draws tx current from battery during transmissions (starting on reception of message from upper layer until reception of TX_OVER message). And idle current any time else. Does also provide battery access to the Decider by implementing DeciderToPhyInterfaces "drawCurrent()"-method.
Defines initialization for "Decider80211Battery".
Definition at line 41 of file PhyLayerBattery.h.
Member Enumeration Documentation
enum PhyLayerBattery::Activities [protected]
Defines the power consuming activities (accounts) of the NIC. Should be the same as defined in the decider.
Enumerator:
SLEEP_ACCT
IDLE_ACCT
RX_ACCT
TX_ACCT
Definition at line 53 of file PhyLayerBattery.h.
                  {
    SLEEP_ACCT=0,
    IDLE_ACCT=1,
    RX_ACCT=2,
    TX_ACCT=3
  };
Member Function Documentation
Decider * PhyLayerBattery::getDeciderFromName (std::string name, ParameterMap & params) [protected, virtual]
Creates and returns an instance of the Decider with the specified name.
Is able to initialize the following Deciders:
Decider80211
Decider80211Battery
SNRThresholdDecider
Reimplemented from PhyLayer.
Definition at line 42 of file PhyLayerBattery.cc.
References initializeDecider80211Battery().
{
  if(name == "Decider80211Battery") {
    return initializeDecider80211Battery(params);
  }
  return PhyLayer::getDeciderFromName(name, params);
}
void PhyLayerBattery::handleAirFrame (cMessage * msg) [virtual]
Checks if the the host state is on and prevents reception of AirFrames if not.
Calls the base classes overriden method for normal handling.
Reimplemented from BasePhyLayer.
Definition at line 86 of file PhyLayerBattery.cc.
References HostState::FAILED, HostState::get(), BaseUtility::getHostState(), and BaseModule::utility.
{
  if (utility->getHostState().get() == HostState::FAILED) {
    EV<< "host has FAILED, dropping msg " << msg->getName() << endl;
    delete msg;
    return;
  }
  PhyLayer::handleAirFrame(msg);
}
void PhyLayerBattery::handleHostState (const HostState & state) [virtual]
Provides ability to draw power for the Decider.
Method is defined in "DeciderToPhyInterface". Captures changes in host state. Note: Does not yet cancel any ongoing transmissions if the state changes to off.
Reimplemented from BaseModule.
Definition at line 96 of file PhyLayerBattery.cc.
References HostState::FAILED, and HostState::get().
{
  // handles only battery consumption
  HostState::States hostState = state.get();
  switch (hostState) {
  case HostState::FAILED:
    EV<< "t = " << simTime() << " host state FAILED" << endl;
    // it would be good to create a radioState OFF, as well
    break;
  default:
    break;
  }
}
void PhyLayerBattery::handleSelfMessage (cMessage * msg) [virtual]
Catches TX over messages to set current power consumption back for idle mode.
Calls the base classes overriden method for normal handling.
Reimplemented from BasePhyLayer.
Definition at line 79 of file PhyLayerBattery.cc.
References BasePhyLayer::drawCurrent(), IDLE_ACCT, idleCurrent, and MacToPhyInterface::TX_OVER.
{
  if(msg->getKind() == TX_OVER) {
    drawCurrent(idleCurrent, IDLE_ACCT);
  }
  PhyLayer::handleSelfMessage(msg);
}
void PhyLayerBattery::handleUpperMessage (cMessage * msg) [virtual]
Checks the hosts state and draws txCurrent from battery.
Prevents sending of AirFrames if the hosts state is not on. Sets current power consumption for TX mode. Calls the base classes overriden method for normal handling.
Reimplemented from BasePhyLayer.
Definition at line 67 of file PhyLayerBattery.cc.
References BasePhyLayer::drawCurrent(), HostState::FAILED, HostState::get(), BaseUtility::getHostState(), TX_ACCT, txCurrent, and BaseModule::utility.
{
  if (utility->getHostState().get() == HostState::FAILED) {
    EV<< "host has FAILED, dropping msg " << msg->getName() << endl;
    delete msg;
    return;
  }
  PhyLayer::handleUpperMessage(msg);
  drawCurrent(txCurrent, TX_ACCT);
}
void PhyLayerBattery::initialize (int stage) [virtual]
OMNeT++ initialization function. Read simple parameters. Read and parse xml file for decider and analogue models configuration.
Reimplemented from BasePhyLayer.
Definition at line 20 of file PhyLayerBattery.cc.
References BasePhyLayer::drawCurrent(), IDLE_ACCT, idleCurrent, numActivities, BatteryAccess::registerWithBattery(), rxCurrent, sleepCurrent, and txCurrent.
{
  PhyLayer::initialize(stage);
  if (stage == 0) {
    numActivities = hasPar("numActivities") ? par("numActivities").longValue() : 4;
    /* parameters belong to the NIC, not just snrEval
     *
     * if/when variable transmit power is supported, txCurrent
     * should be specified as an xml table of available transmit
     * power levels and corresponding txCurrent */
    sleepCurrent = idleCurrent = rxCurrent = txCurrent = 0;
    sleepCurrent = getParentModule()->par( "sleepCurrent" );
    idleCurrent = getParentModule()->par( "idleCurrent" );
    rxCurrent = getParentModule()->par( "rxCurrent" );
    txCurrent = getParentModule()->par( "txCurrent" );
  } else {
    registerWithBattery("80211Nic", numActivities);
    drawCurrent(idleCurrent, IDLE_ACCT);
  }
}
Decider * PhyLayerBattery::initializeDecider80211Battery (ParameterMap & params) [protected, virtual]
Initializes a new Decider80211Battery from the passed parameter map.
Definition at line 50 of file PhyLayerBattery.cc.
References ChannelAccess::coreDebug, BaseModule::findHost(), idleCurrent, rxCurrent, and BasePhyLayer::sensitivity.
Referenced by getDeciderFromName().
{
  double threshold = params["threshold"];
  double centerFreq = params["centerFrequency"];
  return new Decider80211Battery(this,
                   threshold,
                   sensitivity,
                   centerFreq,
                   rxCurrent,
                   idleCurrent,
                   findHost()->getIndex(),
                   coreDebug);
}
Member Data Documentation
double PhyLayerBattery::idleCurrent [protected]
Definition at line 47 of file PhyLayerBattery.h.
Referenced by handleSelfMessage(), initialize(), and initializeDecider80211Battery().
int PhyLayerBattery::numActivities [protected]
Number of power consuming activities (accounts).
Definition at line 44 of file PhyLayerBattery.h.
Referenced by initialize().
double PhyLayerBattery::rxCurrent [protected]
Definition at line 47 of file PhyLayerBattery.h.
Referenced by initialize(), and initializeDecider80211Battery().
double PhyLayerBattery::sleepCurrent [protected]
The different currents in mA.
Definition at line 47 of file PhyLayerBattery.h.
Referenced by initialize().
double PhyLayerBattery::txCurrent [protected]
Definition at line 47 of file PhyLayerBattery.h.
Referenced by handleUpperMessage(), and initialize().
The documentation for this class was generated from the following files:
modules/phy/PhyLayerBattery.h
modules/phy/PhyLayerBattery.cc