MiXiM: RSAMConstMappingIterator Class Reference
RSAMConstMappingIterator Class Reference
[phyLayer - physical layer modules]
ConstMapingIterator implementation for a RSAM.
#include <PhyUtils.h>
Inherits ConstMappingIterator.
Public Member Functions
RSAMConstMappingIterator (const RadioStateAnalogueModel *rsam, simtime_t signalStart, simtime_t signalEnd)
virtual ~RSAMConstMappingIterator ()
virtual void jumpTo (const Argument &pos)
Lets the iterator point to the passed position.
virtual void setNextPosition ()
virtual void jumpToBegin ()
Lets the iterator point to the begin of the function.
virtual void iterateTo (const Argument &pos)
Iterates to the specified position. This method should be used if the new position is near the current position.
virtual void next ()
Iterates to the next position of the function.
virtual bool inRange () const
Returns true if the current position of the iterator is in range of the function.
virtual bool hasNext () const
Returns true if the iterator has a next value inside its range.
virtual const Argument & getPosition () const
Returns the current position of the iterator.
virtual const Argument & getNextPosition () const
Returns the position the next call to "next()" of this Iterator would iterate to.
virtual double getValue () const
Returns the value of the function at the current position.
virtual void iterateToOverZeroSwitches (simtime_t t)
Iterates to valid entry for timepoint t over all zero-time switches starting from the current position of iterator it.
Protected Types
typedef std::list
< RadioStateAnalogueModel::ListEntry > CurrList
Protected Attributes
const RadioStateAnalogueModel * rsam
CurrList::const_iterator it
Argument position
Argument nextPosition
simtime_t signalStart
simtime_t signalEnd
Detailed Description
ConstMapingIterator implementation for a RSAM.
Definition at line 492 of file PhyUtils.h.
Member Typedef Documentation
typedef std::list<RadioStateAnalogueModel::ListEntry> RSAMConstMappingIterator::CurrList [protected]
Definition at line 498 of file PhyUtils.h.
Constructor & Destructor Documentation
RSAMConstMappingIterator::RSAMConstMappingIterator (const RadioStateAnalogueModel * rsam, simtime_t signalStart, simtime_t signalEnd) [inline]
Definition at line 511 of file PhyUtils.h.
References jumpToBegin().
                                     :
    rsam(rsam),
    signalStart(signalStart),
    signalEnd(signalEnd)
  {
    assert(rsam);
    assert( !(signalStart < rsam->radioIsReceiving.front().getTime()) );
    jumpToBegin();
  }
virtual RSAMConstMappingIterator::~RSAMConstMappingIterator () [inline, virtual]
Definition at line 525 of file PhyUtils.h.
{}
Member Function Documentation
virtual const Argument& RSAMConstMappingIterator::getNextPosition () const [inline, virtual]
Returns the position the next call to "next()" of this Iterator would iterate to.
Implements ConstMappingIterator.
Definition at line 694 of file PhyUtils.h.
References nextPosition.
  {
    return nextPosition;
  }
virtual const Argument& RSAMConstMappingIterator::getPosition () const [inline, virtual]
Returns the current position of the iterator.
Implements ConstMappingIterator.
Definition at line 689 of file PhyUtils.h.
References position.
  {
    return position;
  }
virtual double RSAMConstMappingIterator::getValue () const [inline, virtual]
Returns the value of the function at the current position.
Implements ConstMappingIterator.
Definition at line 703 of file PhyUtils.h.
References it.
  {
    return it->getValue();
  }
virtual bool RSAMConstMappingIterator::hasNext () const [inline, virtual]
Returns true if the iterator has a next value inside its range.
Implements ConstMappingIterator.
Definition at line 672 of file PhyUtils.h.
References Argument::getTime(), it, position, RadioStateAnalogueModel::radioIsReceiving, rsam, signalEnd, and signalStart.
Referenced by setNextPosition().
  {
    assert( !(rsam->radioIsReceiving.empty()) );
    CurrList::const_iterator it2 = it;
    if (it2 != rsam->radioIsReceiving.end())
    {
      it2++;
    }
    return  position.getTime() < signalStart
        || (it2 != rsam->radioIsReceiving.end() && it2->getTime() <= signalEnd);
  }
virtual bool RSAMConstMappingIterator::inRange () const [inline, virtual]
Returns true if the current position of the iterator is in range of the function.
This method should be used as end-condition when iterating over the function with the "next()" method.
Implements ConstMappingIterator.
Definition at line 657 of file PhyUtils.h.
References Argument::getTime(), position, RadioStateAnalogueModel::radioIsReceiving, rsam, signalEnd, and signalStart.
  {
    simtime_t t = position.getTime();
    simtime_t lastEntryTime = std::max(rsam->radioIsReceiving.back().getTime(), signalStart);
    return  signalStart <= t
        && t <= signalEnd
        && t <= lastEntryTime;
  }
virtual void RSAMConstMappingIterator::iterateTo (const Argument & pos) [inline, virtual]
Iterates to the specified position. This method should be used if the new position is near the current position.
Implements ConstMappingIterator.
Definition at line 611 of file PhyUtils.h.
References Argument::getTime(), iterateToOverZeroSwitches(), position, RadioStateAnalogueModel::radioIsReceiving, rsam, setNextPosition(), and Argument::setTime().
Referenced by next().
  {
    // extract the time component from the passed Argument
    simtime_t t = pos.getTime();
    // ERROR CASE: iterating to a position before (time) the beginning of the mapping is forbidden
    assert( !(rsam->radioIsReceiving.empty()) &&
        !(t < rsam->radioIsReceiving.front().getTime()) );
    assert( !(t < position.getTime()) );
    // REGULAR CASES:
    // t >= position.getTime();
    // we are already exactly there
    if( t == position.getTime() )
      return;
    // we iterate there going over all zero time switches
    iterateToOverZeroSwitches(t);
    // update current position
    position.setTime(t);
    setNextPosition();
  }
virtual void RSAMConstMappingIterator::iterateToOverZeroSwitches (simtime_t t) [inline, virtual]
Iterates to valid entry for timepoint t over all zero-time switches starting from the current position of iterator it.
Definition at line 714 of file PhyUtils.h.
References it, RadioStateAnalogueModel::radioIsReceiving, and rsam.
Referenced by iterateTo().
  {
    if( it != rsam->radioIsReceiving.end() && !(t < it->getTime()) )
    {
      // and go over (ignore) all zero-time-switches, to the next greater entry (time)
      while( it != rsam->radioIsReceiving.end() && !(t < it->getTime()) )
        it++;
      // go back one step, here the iterator 'it' is placed right
      it--;
    }
  }
virtual void RSAMConstMappingIterator::jumpTo (const Argument & pos) [inline, virtual]
Lets the iterator point to the passed position.
The passed new position can be at arbitary places, jumping explicitly before signalStart is allowed.
Implements ConstMappingIterator.
Definition at line 533 of file PhyUtils.h.
References Argument::getTime(), it, position, RadioStateAnalogueModel::radioIsReceiving, rsam, setNextPosition(), and Argument::setTime().
Referenced by RSAMMapping::createConstIterator(), and jumpToBegin().
  {
    // extract the time-component from the argument
    simtime_t t = pos.getTime();
    assert( !(rsam->radioIsReceiving.empty()) &&
        !(t < rsam->radioIsReceiving.front().getTime()) );
    // current position is already correct
    if( t == position.getTime() )
      return;
    // this automatically goes over all zero time switches
    it = upper_bound(rsam->radioIsReceiving.begin(), rsam->radioIsReceiving.end(), t);
    --it;
    position.setTime(t);
    setNextPosition();
  }
virtual void RSAMConstMappingIterator::jumpToBegin () [inline, virtual]
Lets the iterator point to the begin of the function.
The beginning of the function depends on the implementation.
Implements ConstMappingIterator.
Definition at line 590 of file PhyUtils.h.
References jumpTo(), and signalStart.
Referenced by RSAMConstMappingIterator().
  {
    jumpTo(signalStart);
    /*
    it = rsam->radioIsReceiving.begin();
    simtime_t t = it->getTime();
    assert( !(signalStart < t) );
    iterateToOverZeroSwitches(signalStart);
    position.setTime(signalStart);
    setNextPosition();
    */
  }
virtual void RSAMConstMappingIterator::next () [inline, virtual]
Iterates to the next position of the function.
The next position depends on the implementation of the Function.
Implements ConstMappingIterator.
Definition at line 645 of file PhyUtils.h.
References iterateTo(), and nextPosition.
  {
    iterateTo(nextPosition);
  }
virtual void RSAMConstMappingIterator::setNextPosition () [inline, virtual]
Helper function that sets member nextPosition. Presumes that iterator it and member position are set correctly.
This function does not care for zero time switches! This must be done before!
Might be helpful if position of iterator it has not been set by upper_bound before (it has not just been standing on the "nextPosition").
Definition at line 563 of file PhyUtils.h.
References Argument::getTime(), hasNext(), it, nextPosition, position, Argument::setTime(), and signalStart.
Referenced by iterateTo(), and jumpTo().
  {
    if (hasNext()) // iterator it does not stand on last entry and next entry is before signal end
    {
      if(position.getTime() < signalStart) //signal start is our first key entry
      {
        nextPosition.setTime(signalStart);
      } else
      {
        CurrList::const_iterator it2 = it;
        it2++;
        nextPosition.setTime(it2->getTime());
      }
    } else // iterator it stands on last entry or next entry whould be behind signal end
    {
      nextPosition.setTime(position.getTime() + 1);
    }
  }
Member Data Documentation
CurrList::const_iterator RSAMConstMappingIterator::it [protected]
Definition at line 499 of file PhyUtils.h.
Referenced by getValue(), hasNext(), iterateToOverZeroSwitches(), jumpTo(), and setNextPosition().
Argument RSAMConstMappingIterator::nextPosition [protected]
Definition at line 502 of file PhyUtils.h.
Referenced by getNextPosition(), next(), and setNextPosition().
Argument RSAMConstMappingIterator::position [protected]
Definition at line 501 of file PhyUtils.h.
Referenced by getPosition(), hasNext(), inRange(), iterateTo(), jumpTo(), and setNextPosition().
const RadioStateAnalogueModel* RSAMConstMappingIterator::rsam [protected]
Definition at line 496 of file PhyUtils.h.
Referenced by hasNext(), inRange(), iterateTo(), iterateToOverZeroSwitches(), and jumpTo().
simtime_t RSAMConstMappingIterator::signalEnd [protected]
Definition at line 505 of file PhyUtils.h.
Referenced by hasNext(), and inRange().
simtime_t RSAMConstMappingIterator::signalStart [protected]
Definition at line 504 of file PhyUtils.h.
Referenced by hasNext(), inRange(), jumpToBegin(), and setNextPosition().
The documentation for this class was generated from the following file:
base/phyLayer/PhyUtils.h