MiXiM: RepeatTimer Class Reference
RepeatTimer Class Reference
#include <RepeatTimer.h>
Public Member Functions
virtual ~RepeatTimer ()
void setRepeatTimer (unsigned int index, double period, int repeats=1)
unsigned int setRepeatTimer (double period, int repeats=1)
void cancelRepeatTimer (unsigned int index)
void resetRepeatTimer (unsigned int index)
void resetAllRepeatTimers (void)
bool timerExists (unsigned int index)
float remainingRepeatTimer (unsigned int index)
void setContextPointer (unsigned int index, void *data)
void * contextPointer (unsigned int index)
void setContextDestructor (unsigned int index, void(*func)(void *data))
void allocateRepeatTimers (unsigned int count)
void deleteRepeatTimer (unsigned int index)
virtual void init (BaseModule *parent)
virtual void handleRepeatTimer (unsigned int index)
Protected Attributes
RepeatTimerCore * core
BaseModule * owner
Friends
class RepeatTimerCore
Detailed Description
Definition at line 12 of file RepeatTimer.h.
Constructor & Destructor Documentation
virtual RepeatTimer::~RepeatTimer () [inline, virtual]
Definition at line 18 of file RepeatTimer.h.
References core.
{
    delete core;
  }
Member Function Documentation
void RepeatTimer::allocateRepeatTimers (unsigned int count) [inline]
Definition at line 52 of file RepeatTimer.h.
References RepeatTimerCore::allocateRepeatTimers(), and core.
{
    core->allocateRepeatTimers(count);
  }
void RepeatTimer::cancelRepeatTimer (unsigned int index) [inline]
Definition at line 27 of file RepeatTimer.h.
References RepeatTimerCore::cancelRepeatTimer(), and core.
{
    core->cancelRepeatTimer(index);
  }
void* RepeatTimer::contextPointer (unsigned int index) [inline]
Definition at line 46 of file RepeatTimer.h.
References RepeatTimerCore::contextPointer(), and core.
{
    return core->contextPointer(index);
  }
void RepeatTimer::deleteRepeatTimer (unsigned int index) [inline]
Definition at line 55 of file RepeatTimer.h.
References core, and RepeatTimerCore::deleteRepeatTimer().
{
    core->deleteRepeatTimer(index);
  }
virtual void RepeatTimer::handleRepeatTimer (unsigned int index) [inline, virtual]
Definition at line 60 of file RepeatTimer.h.
Referenced by RepeatTimerCore::handleMessage().
{}
void RepeatTimer::init (BaseModule * parent) [virtual]
Definition at line 3 of file RepeatTimer.cc.
References core, RepeatTimerCore::init(), and owner.
{
  owner = parent;
  core = dynamic_cast < RepeatTimerCore * >
      (cModuleType::get("RepeatTimerCore")->
       createScheduleInit("generator", owner));
  core->init(this);
}
float RepeatTimer::remainingRepeatTimer (unsigned int index) [inline]
Definition at line 40 of file RepeatTimer.h.
References core, and RepeatTimerCore::remainingRepeatTimer().
{
    return core->remainingRepeatTimer(index);
  }
void RepeatTimer::resetAllRepeatTimers (void) [inline]
Definition at line 33 of file RepeatTimer.h.
References core, and RepeatTimerCore::resetAllRepeatTimers().
{
    core->resetAllRepeatTimers();
  }
void RepeatTimer::resetRepeatTimer (unsigned int index) [inline]
Definition at line 30 of file RepeatTimer.h.
References core, and RepeatTimerCore::resetRepeatTimer().
{
    core->resetRepeatTimer(index);
  }
void RepeatTimer::setContextDestructor (unsigned int index, void(*)(void *data) func) [inline]
Definition at line 49 of file RepeatTimer.h.
References core, and RepeatTimerCore::setContextDestructor().
{
    core->setContextDestructor(index,func);
  }
void RepeatTimer::setContextPointer (unsigned int index, void * data) [inline]
Definition at line 43 of file RepeatTimer.h.
References core, and RepeatTimerCore::setContextPointer().
{
    core->setContextPointer(index,data);
  }
unsigned int RepeatTimer::setRepeatTimer (double period, int repeats = 1) [inline]
Definition at line 24 of file RepeatTimer.h.
References core, and RepeatTimerCore::setRepeatTimer().
{
    return core->setRepeatTimer(period, repeats);
  }
void RepeatTimer::setRepeatTimer (unsigned int index, double period, int repeats = 1) [inline]
Definition at line 21 of file RepeatTimer.h.
References core, and RepeatTimerCore::setRepeatTimer().
{
    core->setRepeatTimer(index, period, repeats);
  }
bool RepeatTimer::timerExists (unsigned int index) [inline]
Definition at line 36 of file RepeatTimer.h.
References core, and RepeatTimerCore::timerExists().
{
    return core->timerExists(index);
  }
Friends And Related Function Documentation
friend class RepeatTimerCore [friend]
Definition at line 13 of file RepeatTimer.h.
Member Data Documentation
RepeatTimerCore* RepeatTimer::core [protected]
Definition at line 15 of file RepeatTimer.h.
Referenced by allocateRepeatTimers(), cancelRepeatTimer(), contextPointer(), deleteRepeatTimer(), init(), remainingRepeatTimer(), resetAllRepeatTimers(), resetRepeatTimer(), setContextDestructor(), setContextPointer(), setRepeatTimer(), timerExists(), and ~RepeatTimer().
BaseModule* RepeatTimer::owner [protected]
Definition at line 16 of file RepeatTimer.h.
Referenced by init().
The documentation for this class was generated from the following files:
base/timers/RepeatTimer.h
base/timers/RepeatTimer.cc