MiXiM: SimplePathlossModel Class Reference
SimplePathlossModel Class Reference
[analogueModels - AnalogueModel implementations]
Basic implementation of a SimplePathlossModel that uses SimplePathlossConstMapping (that is subclassed from SimpleConstMapping) as attenuation-Mapping.
#include <SimplePathlossModel.h>
Inherits AnalogueModel.
Public Member Functions
SimplePathlossModel (double alpha, double carrierFrequency, const Move *myMove, bool useTorus, const Coord &playgroundSize, bool debug)
Initializes the analogue model. myMove and playgroundSize need to be valid as long as this instance exists.
virtual void filterSignal (Signal &s)
Filters a specified Signal by adding an attenuation over time to the Signal.
virtual double calcPathloss (const Coord &myPos, const Coord &sendersPos)
Method to calculate the attenuation value for pathloss.
Protected Attributes
double pathLossAlphaHalf
Path loss coefficient.
double carrierFrequency
carrier frequency needed for calculation
const Move & myMove
stores my Move pattern
const bool useTorus
const Coord & playgroundSize
bool debug
Whether debug messages should be displayed.
Friends
class SimplePathlossConstMapping
Detailed Description
Basic implementation of a SimplePathlossModel that uses SimplePathlossConstMapping (that is subclassed from SimpleConstMapping) as attenuation-Mapping.
Definition at line 65 of file SimplePathlossModel.h.
Constructor & Destructor Documentation
SimplePathlossModel::SimplePathlossModel (double alpha, double carrierFrequency, const Move * myMove, bool useTorus, const Coord & playgroundSize, bool debug) [inline]
Initializes the analogue model. myMove and playgroundSize need to be valid as long as this instance exists.
The constructor needs some specific knowledge in order to create its mapping properly:
1. the coefficient alpha (specified e.g. in config.xml and passed in constructor call) 2. the carrier frequency 3. a pointer to the hosts move pattern 4. information about the playground the host is moving in
Definition at line 101 of file SimplePathlossModel.h.
                                                                 :
    pathLossAlphaHalf(alpha * 0.5),
    carrierFrequency(carrierFrequency),
    myMove(*myMove),
    useTorus(useTorus),
    playgroundSize(playgroundSize),
    debug(debug)
  {
  }
Member Function Documentation
double SimplePathlossModel::calcPathloss (const Coord & myPos, const Coord & sendersPos) [virtual]
Method to calculate the attenuation value for pathloss.
Functionality is similar to pathloss-calculation in BasicSnrEval from Mobility-frame work.
Definition at line 69 of file SimplePathlossModel.cc.
References carrierFrequency, debugEV, M_PI, pathLossAlphaHalf, playgroundSize, BaseWorldUtility::speedOfLight, Coord::sqrdist(), Coord::sqrTorusDist(), and useTorus.
{
  /*
   * maybe we can reuse an already calculated value for the square-distance
   * at this point.
   *
   */
  double sqrdistance = 0.0;
  if (useTorus)
  {
    sqrdistance = myPos.sqrTorusDist(sendersPos, playgroundSize);
  } else
  {
    sqrdistance = myPos.sqrdist(sendersPos);
  }
  debugEV << "sqrdistance is: " << sqrdistance << endl;
  double attenuation = 1.0;
  // wavelength in metres
  double wavelength = (BaseWorldUtility::speedOfLight/carrierFrequency);
  debugEV << "wavelength is: " << wavelength << endl;
  if (sqrdistance > 1.0)
  {
    attenuation = (wavelength * wavelength) / (16.0 * M_PI * M_PI)
            * (pow(sqrdistance, -1.0*pathLossAlphaHalf));
  }
  debugEV << "attenuation is: " << attenuation << endl;
  return attenuation;
}
void SimplePathlossModel::filterSignal (Signal & s) [virtual]
Filters a specified Signal by adding an attenuation over time to the Signal.
Get start of the signal
claim the Move pattern of the sender from the Signal
Calculate the distance factor
Implements AnalogueModel.
Definition at line 28 of file SimplePathlossModel.cc.
References Signal::addAttenuation(), carrierFrequency, debugEV, Dimension::frequency, ConstMapping::getDimensionSet(), Signal::getMove(), Move::getPositionAt(), Signal::getSignalLength(), Signal::getSignalStart(), Signal::getTransmissionPower(), DimensionSet::hasDimension(), M_PI, myMove, pathLossAlphaHalf, playgroundSize, SimplePathlossConstMapping, BaseWorldUtility::speedOfLight, Coord::sqrdist(), Coord::sqrTorusDist(), DimensionSet::timeDomain, DimensionSet::timeFreqDomain, and useTorus.
{
  simtime_t sStart = s.getSignalStart();
  simtime_t sEnd = s.getSignalLength() + sStart;
  Coord sendersPos = s.getMove().getPositionAt(sStart);
  Coord myPos = myMove.getPositionAt(sStart);
  double sqrDistance = useTorus ? myPos.sqrTorusDist(sendersPos, playgroundSize)
                  : myPos.sqrdist(sendersPos);
  debugEV << "sqrdistance is: " << sqrDistance << endl;
  if(sqrDistance <= 1.0) {
    //attenuation is negligible
    return;
  }
  // wavelength in metres
  double wavelength = (BaseWorldUtility::speedOfLight/carrierFrequency);
  debugEV << "wavelength is: " << wavelength << endl;
  double distFactor = pow(sqrDistance, -pathLossAlphaHalf) / (16.0 * M_PI * M_PI);
  debugEV << "distance factor is: " << distFactor << endl;
  bool hasFrequency = s.getTransmissionPower()->getDimensionSet().hasDimension(Dimension::frequency);
  const DimensionSet& domain = hasFrequency ? DimensionSet::timeFreqDomain : DimensionSet::timeDomain;
  SimplePathlossConstMapping* attMapping = new SimplePathlossConstMapping(
                          domain,
                          this,
                          distFactor);
  /* at last add the created attenuation mapping to the signal */
  s.addAttenuation(attMapping);
}
Friends And Related Function Documentation
friend class SimplePathlossConstMapping [friend]
Definition at line 68 of file SimplePathlossModel.h.
Referenced by filterSignal().
Member Data Documentation
double SimplePathlossModel::carrierFrequency [protected]
carrier frequency needed for calculation
Definition at line 74 of file SimplePathlossModel.h.
Referenced by calcPathloss(), filterSignal(), and SimplePathlossConstMapping::getValue().
bool SimplePathlossModel::debug [protected]
Whether debug messages should be displayed.
Definition at line 84 of file SimplePathlossModel.h.
const Move& SimplePathlossModel::myMove [protected]
stores my Move pattern
Definition at line 77 of file SimplePathlossModel.h.
Referenced by filterSignal().
double SimplePathlossModel::pathLossAlphaHalf [protected]
Path loss coefficient.
Definition at line 71 of file SimplePathlossModel.h.
Referenced by calcPathloss(), and filterSignal().
const Coord& SimplePathlossModel::playgroundSize [protected]
Definition at line 81 of file SimplePathlossModel.h.
Referenced by calcPathloss(), and filterSignal().
const bool SimplePathlossModel::useTorus [protected]
Information needed about the playground
Definition at line 80 of file SimplePathlossModel.h.
Referenced by calcPathloss(), and filterSignal().
The documentation for this class was generated from the following files:
modules/analogueModel/SimplePathlossModel.h
modules/analogueModel/SimplePathlossModel.cc