MiXiM: SimpleConstMapping Class Reference
SimpleConstMapping Class Reference
[mapping - classes representing mathematical mappings]
Abstract subclass of ConstMapping which can be used as base for any ConstMapping implementation with read access of constant complexity.
#include <MappingBase.h>
Inherits ConstMapping.
Inherited by ConstantSimpleConstMapping, JakesFadingMapping, and SimplePathlossConstMapping.
Public Member Functions
virtual ConstMappingIterator * createConstIterator ()
Returns a pointer of a new Iterator which is able to iterate over the Mapping.
virtual ConstMappingIterator * createConstIterator (const Argument &pos)
Returns a pointer of a new Iterator which is able to iterate over the Mapping. The iterator starts at the passed position.
SimpleConstMapping (const DimensionSet &dims)
Initializes a not yet iterateable SimpleConstmapping with the passed DimensionSet as domain.
SimpleConstMapping (const DimensionSet &dims, const Argument &key)
Fully initializes this mapping with the passed position as key entry.
SimpleConstMapping (const DimensionSet &dims, const Argument &key1, const Argument &key2)
Fully initializes this mapping with the passed two positions as key entries.
SimpleConstMapping (const DimensionSet &dims, const Argument &min, const Argument &max, const Argument &interval)
Fully initializes this mapping with the key entries defined by the passed min, max and interval values.
void initializeArguments (const Argument &key)
Initializes the key entry set with the passed position as entry.
void initializeArguments (const Argument &key1, const Argument &key2)
Initializes the key entry set with the passed two positions as entries.
void initializeArguments (const Argument &min, const Argument &max, const Argument &interval)
Initializes the key entry set with the passed min, max and interval-Arguments.
virtual double getValue (const Argument &pos) const =0
Returns the value of the mapping at the passed position.
ConstMapping * constClone () const =0
creates a clone of this mapping.
Protected Types
typedef std::set< Argument > KeyEntrySet
Protected Member Functions
void createKeyEntries (const Argument &from, const Argument &to, const Argument &step, Argument &pos)
Utility method to fill add range of key entries in the time dimension to the key entry set.
void createKeyEntries (const Argument &from, const Argument &to, const Argument &step, DimensionSet::const_iterator curDim, Argument &pos)
Utility method to fill add range of key entries in the passed dimension (and recursively its sub dimensions) to the key entry set.
Protected Attributes
KeyEntrySet keyEntries
A set of Arguments defining the "points of interest" an iterator should iterate over.
Detailed Description
Abstract subclass of ConstMapping which can be used as base for any ConstMapping implementation with read access of constant complexity.
Any subclass only has to implement the "getValue()" and the "clone()"-method.
The subclass has to define the "points of interest" an iterator should iterate over. This should be done either at construction time or later by calling the "initializeArguments()"-method.
The SimpleConstMapping class provides Iterator creation by using the SimpleConstMappingIterator which assumes that the underlying ConstMappings getValue()-method is fast enough to be called on every iteration step (which means constant complexity).
Author:
Karl Wessel
Definition at line 1135 of file MappingBase.h.
Member Typedef Documentation
typedef std::set<Argument> SimpleConstMapping::KeyEntrySet [protected]
Definition at line 1137 of file MappingBase.h.
Constructor & Destructor Documentation
SimpleConstMapping::SimpleConstMapping (const DimensionSet & dims) [inline]
Initializes a not yet iterateable SimpleConstmapping with the passed DimensionSet as domain.
Definition at line 1184 of file MappingBase.h.
                                              :
    ConstMapping(dims) {}
SimpleConstMapping::SimpleConstMapping (const DimensionSet & dims, const Argument & key) [inline]
Fully initializes this mapping with the passed position as key entry.
A SimpleConstMapping initialized by this constructor is able to return a valid ConstIterator.
Definition at line 1194 of file MappingBase.h.
References initializeArguments().
                                 :
    ConstMapping(dims){
    initializeArguments(key);
  }
SimpleConstMapping::SimpleConstMapping (const DimensionSet & dims, const Argument & key1, const Argument & key2) [inline]
Fully initializes this mapping with the passed two positions as key entries.
A SimpleConstMapping initialized by this constructor is able to return a valid ConstIterator.
Definition at line 1208 of file MappingBase.h.
References initializeArguments().
                                                        :
    ConstMapping(dims){
    initializeArguments(key1, key2);
  }
SimpleConstMapping::SimpleConstMapping (const DimensionSet & dims, const Argument & min, const Argument & max, const Argument & interval) [inline]
Fully initializes this mapping with the key entries defined by the passed min, max and interval values.
A SimpleConstMapping initialized by this constructor is able to return a valid ConstIterator.
Definition at line 1222 of file MappingBase.h.
References initializeArguments().
                                                                                :
    ConstMapping(dims){
    initializeArguments(min, max, interval);
  }
Member Function Documentation
ConstMapping* SimpleConstMapping::constClone () const [pure virtual]
creates a clone of this mapping.
This method has to be implemented by every subclass.
Implements ConstMapping.
Implemented in ConstantSimpleConstMapping, JakesFadingMapping, and SimplePathlossConstMapping.
virtual ConstMappingIterator* SimpleConstMapping::createConstIterator (const Argument & pos) [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the Mapping. The iterator starts at the passed position.
This method asserts that the mapping had been fully initialized.
Implements ConstMapping.
Definition at line 1175 of file MappingBase.h.
References keyEntries.
{
    return new SimpleConstMappingIterator(this, &keyEntries, pos);
  }
virtual ConstMappingIterator* SimpleConstMapping::createConstIterator () [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the Mapping.
This method asserts that the mapping had been fully initialized.
Implements ConstMapping.
Definition at line 1165 of file MappingBase.h.
References keyEntries.
{
    return new SimpleConstMappingIterator(this, &keyEntries);
  }
void SimpleConstMapping::createKeyEntries (const Argument & from, const Argument & to, const Argument & step, DimensionSet::const_iterator curDim, Argument & pos) [protected]
Utility method to fill add range of key entries in the passed dimension (and recursively its sub dimensions) to the key entry set.
Definition at line 413 of file MappingBase.cc.
References createKeyEntries(), Argument::getArgValue(), and Argument::setArgValue().
{
  //get the dimension to iterate over
  Dimension d = *curDim;
  //increase iterator to next dimension (means curDim now stores the next dimension)
  --curDim;
  bool nextIsTime = (*curDim == Dimension::time);
  //get our iteration borders and steps
  double fromD = from.getArgValue(d);
  double toD = to.getArgValue(d);
  double stepD = step.getArgValue(d);
  //iterate over interval without the last entry
  for(double i = fromD; (i - toD) < -0.0001; i += stepD){
    pos.setArgValue(d, i); //update position
    //call iteration over sub dimension
    if(nextIsTime){
      createKeyEntries(from, to, step, pos);
    } else {
      createKeyEntries(from, to, step, curDim, pos);
    }
  }
  //makes sure that the end of the interval has its own key entry
  pos.setArgValue(d, toD);
  if(nextIsTime){
    createKeyEntries(from, to, step, pos);
  } else {
    createKeyEntries(from, to, step, curDim, pos);
  }
}
void SimpleConstMapping::createKeyEntries (const Argument & from, const Argument & to, const Argument & step, Argument & pos) [protected]
Utility method to fill add range of key entries in the time dimension to the key entry set.
Definition at line 394 of file MappingBase.cc.
References Argument::getTime(), keyEntries, and Argument::setTime().
Referenced by createKeyEntries(), and initializeArguments().
{
  //get iteration borders and steps
  simtime_t fromT = from.getTime();
  simtime_t toT = to.getTime();
  simtime_t stepT = step.getTime();
  //iterate over interval without the end of the interval
  for(simtime_t t = fromT; t < toT; t += stepT){
    //create key entry at current position
    pos.setTime(t);
    keyEntries.insert(pos);
  }
  //makes sure that the end of the interval becomes it own key entry
  pos.setTime(toT);
  keyEntries.insert(pos);
}
virtual double SimpleConstMapping::getValue (const Argument & pos) const [pure virtual]
Returns the value of the mapping at the passed position.
This method has to be implemented by every subclass and should only have constant complexity.
Implements ConstMapping.
Implemented in ConstantSimpleConstMapping, JakesFadingMapping, and SimplePathlossConstMapping.
void SimpleConstMapping::initializeArguments (const Argument & min, const Argument & max, const Argument & interval)
Initializes the key entry set with the passed min, max and interval-Arguments.
After a call to this method this SimpleConstMapping is able to return a valid ConstIterator.
Definition at line 448 of file MappingBase.cc.
References createKeyEntries(), ConstMapping::dimensions, and keyEntries.
{
  keyEntries.clear();
  DimensionSet::const_iterator dimIt = dimensions.end();
  --dimIt;
  Argument pos = min;
  if(*dimIt == Dimension::time)
    createKeyEntries(min, max, interval, pos);
  else
    createKeyEntries(min, max, interval, dimIt, pos);
}
void SimpleConstMapping::initializeArguments (const Argument & key1, const Argument & key2) [inline]
Initializes the key entry set with the passed two positions as entries.
Convenience method for simple mappings.
Definition at line 1246 of file MappingBase.h.
References keyEntries.
{
    keyEntries.clear();
    keyEntries.insert(key1);
    keyEntries.insert(key2);
  }
void SimpleConstMapping::initializeArguments (const Argument & key) [inline]
Initializes the key entry set with the passed position as entry.
Convenience method for simple mappings.
Definition at line 1235 of file MappingBase.h.
References keyEntries.
Referenced by BasePhyLayer::getThermalNoise(), and SimpleConstMapping().
{
    keyEntries.clear();
    keyEntries.insert(key);
  }
Member Data Documentation
KeyEntrySet SimpleConstMapping::keyEntries [protected]
A set of Arguments defining the "points of interest" an iterator should iterate over.
Definition at line 1141 of file MappingBase.h.
Referenced by createConstIterator(), createKeyEntries(), and initializeArguments().
The documentation for this class was generated from the following files:
base/phyLayer/MappingBase.h
base/phyLayer/MappingBase.cc